apiVersion: ENC[AES256_GCM,data:D4o=,iv:kfhENS80quGXTlhLo+qq+ShJPG9e0PeINtMBAU2fH64=,tag:19C8158uQAvyTB8lpN81nQ==,type:str]
kind: ENC[AES256_GCM,data:Kgkmvu7V,iv:/NDJA/AQWPc1Xsh7e6ibY035t2Es3aL0/oORlq3qnoM=,tag:GBINv9IsZw+SgY+q+Lx1mA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dUPnzcc+Xu+W5EH8tyk6fVg7JIw=,iv:L2y6CUoCLlvuJh/+G6H1zKYNMiVW5BLT4vaQJiXkG1U=,tag:D1eA+fPYrrZpaXxflYeqkg==,type:str]
    namespace: ENC[AES256_GCM,data:QP1qkb0Txnw=,iv:gFdqueTF1kWtQlUG6lG2/I/Qt+vzVMMrs/OcvLlVKlU=,tag:RyqK9v7rVd2RAsxq3wpCjw==,type:str]
type: ENC[AES256_GCM,data:miX9zugT,iv:MewqCt9OQuppn5bRMSwtddgcRDWHVkAzcfFfWkUZrk0=,tag:aXONOONEFo6k1mO7U1Egow==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:1p/4Gia8lcWKe2b23pVnR/eC0ZNSwF0jbb2eWFT3BEjVzGDJ7eFpqKq2wrJNCsE3ffNCdl7DfBjw6tuYufGkQxDqyjb9kow=,iv:VOPzxzCp10PP7w3daKoHkeTxhanXO7I47Y4Hgr6feWk=,tag:Pv3gKGbKUm2/rUo34B4s6g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:D0JixMMa1BjYlQ==,iv:doci3Gd4sb9xuD5G8tXN1joA90sJtXiDFSwkbCDc2E0=,tag:a+NF511udKlBpKuHE2nelA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3g6+i/2MVFIKEg==,iv:0XOgZ9h15knPDm9JBwHLja3D5sbUHq0+BClnv3a8uqs=,tag:Lj3nHUmmvQHICIQtizq4xg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EVG4rXQ+zdq7kQ==,iv:ukYfrdqiEf5PZv+a5GKaYPzO65RBcb22R6xScAC5p1I=,tag:UGI8GGADTR3/Qdyk6Q9JRg==,type:str]
sops:
    lastmodified: "2026-08-10T17:40:00Z"
    mac: ENC[AES256_GCM,data:pWYEjuKuI90wCRRr4K4FUf7aT98w2tdUqQMmMy4IK7pfmn10d87NaqEMjDRQVe62mge4g5Y7Rh4IYRqpXt4TmczM3bsVLMubLjv81lkCs/m0pEis8MgTnU1GchB5v6I1rA17sMZAC1Sd7d5jNyJ+pfJBA0lFkHgX0nqj0XlNg8U=,iv:UYQ+edh1Nhefg/idd+HNcqlquhKTByqNM0U4nYviTBM=,tag:CUVvOsz/WtB8m/joeLM00Q==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAtvaj1GjRBbuMNQQGvtibYm4wNihXaUmyg2lKATFbS7lS
            W3OiYQi2t84A1PEcyuI+PrUYyzKDSyUg7ppEonZ61FUQWyWphDO595yHtH9ywBmA
            wgf4wfMi1dWEAYQd9dj8eiVT5CrGSrmpbcp4JHes+9a/IUxgnusjIrrHqiMewFlc
            ES0Q8b5alHZrSTZGGJnZZzYdXk0vLV+RL+/ebWSe8gAMEDfla5wetMu4V1ntjD7s
            jc3Fz/UqT5MgOERyoyxMD6wygxGxcQnX1Ac4NNHxokZWnGR4ZcyI+3oNeumvcFRk
            2gh4oL3LRRd3Fd8WkmW6LRR36DdMUJrWfCWsqVCdxFXwebionj/gnBsoSvDhek6x
            L/dHY+YX+Ly00bpijqKNqyKHwFRGFzrQf1qup2jUAASpFXrvqsxHOa2++86uHR3x
            bCWauPWuAvjzth+IlmdPTfR369CE6PPQWzRNklFu45iBGj8jRnNTPnCijW4sMV+K
            L0E9iKCk0DEop9PCJJudvPNZXCqIX2waBgyuasktH+KFBR4QoO1Qu2vl3sC9QLxy
            v3mdVU4EFsdfURtn5DL7NMPosM7/FCaYG6f9OvwCSA/W9JcQAhJ5YH+EGeQqhKcu
            h91/4YunDu5kQ+SIvgz0HDiIBeJZwjp0EUIct3i6GREqIfIlz/WqOc48lBieeZ3U
            aAEJAhBZETqb99dxGArmNauMlKUu3FmzVP7484v5KVylPDM9BWXgPETZGTfCjfKe
            lUgEZ+yd0dYbB1pwPXXCWLugGt8p0pSVQyMDho+I5fCxATV6SyCzVGclPOdsVueX
            qpY7zMG1lKah
            =D2TD
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
