apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archiveteam-warrior

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - deployment-telegram.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: warrior-item-log
    files:
      - item-log.py
