apiVersion: v1
kind: Service
metadata:
  name: aldo-ssh
  namespace: vms
  labels:
    app: aldo-vm
spec:
  type: ClusterIP
  selector:
    kubevirt.io/vm: aldo
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
