apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: aldo
  namespace: vms
  labels:
    app: aldo-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: aldo
        app: aldo-vm
    spec:
      architecture: amd64
      nodeSelector:
        kubernetes.io/hostname: talos-ramhaus
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: 16Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - name: ssh
                  port: 22
                  protocol: TCP
          networkInterfaceMultiqueue: true
        machine:
          type: q35
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: aldo-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: aldo-cloud-init
