apiVersion: ENC[AES256_GCM,data:PsY=,iv:gPckjkgC8C9xo/ZgnXUISL5anCnCFriHvhgGMgSoOnk=,tag:ezlsEOAsKZU462dB1fOIPw==,type:str]
kind: ENC[AES256_GCM,data:XKUA5XCu,iv:zH1FZp+/q3B9WIn+3JyG3tTXAUgfwqan5TzDiSA920U=,tag:ZwUFYKCXmUkKgXGnYcbqjg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3KEGXSmFDtDqUV+C4rEBO8wecmkM8u5xDK8SH1ey,iv:F47j+x4W/Ij4jlGrjwYvyDZNDthlH0XyaW98yjFp5q8=,tag:Rt8PmF71Y4yWVwE+mM3fUA==,type:str]
type: ENC[AES256_GCM,data:LFfviaaHyXefuyhfc2kTq+tdpJTQ8v0l,iv:+PWqYGBVwz4SiMjv+6kCI6A0caF7zrIhHa+0fZD/CFk=,tag:eObLgpGoOU6ANxuZV6Dxmg==,type:str]
stringData:
    #ENC[AES256_GCM,data:YxBrwWX08whmSoMzBHT2JxgoQQlNqy8RmD5+dje1Xb4PWK2nYVKViPUgJ3/rMLAWcX1Ku4M91q7GypL2xpaP,iv:dWiykXG7PiT/ZihERVhlSRhoBE89eiQyCnYDrfAT+XQ=,tag:OiyWFZldV8uzs3fGA2hinA==,type:comment]
    username: ENC[AES256_GCM,data:lCb3B7mJ4xpt,iv:ic7MlEzvuddF7F2MVHBdklOUJe6z4Fm6Dm4bWNjgrrM=,tag:QjEk0awrJytqu01EGDyDkA==,type:str]
    password: ENC[AES256_GCM,data:g55BUSsDdRXN6CkTKMlagkU=,iv:x0zTLeEz0DFp6oVGzaWXTvsjLGwlcUpctJc0TKrToCM=,tag:P77yoo4VXbIrND56nCoLvw==,type:str]
sops:
    lastmodified: "2025-12-22T02:44:37Z"
    mac: ENC[AES256_GCM,data:Flt51uy3OFURSzHmD/ACDYarYWwEsUdsmeEDJHKYOG0UuyKEBylOJUwF8lWOdje6K51Ivp3U1uT6lFgZoHC1YhURlVCVN54hoRwcqREyEiIYM2KJ1301p3N1ruCsm7oYO9chTIj7qdMLZMtuNSKobGVJ1u3uEyFWE9YoodbuA2w=,iv:2kYWxfuB3GUf3zf14dywWBHR6601e6TperADRrslYuM=,tag:XO4MwQ0bTnkghbnJR9NsJA==,type:str]
    pgp:
        - created_at: "2025-12-22T02:40:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ/+LgwFKbpSZBSjr1wWIeytYUXLmWazMIt790ehxy9jNWNk
            ypKUGBEPBk+j9MN6WQdxOdjnntszAZHjM7Y4zEaUirxzQZNftKBV9FklfdPcYkv6
            BeN4nnklL7titq5D/6wcaGIHUKeqLP8I/I3Zc70Sldpb/HCQRpdXGVvEEOiAYaB1
            yNNQhmcgGKLIHv8AgzP8ATYskyqEy2nGlF4LE1v/DWx6cWIxTsfiMbD1cAorLss/
            UWJktTUwZqWR/ADKyArwf5aqywoD1Jj2vK8dFTtooqfKpcwQKioZw3UfPjQkxx+m
            yLV/ZP39FXdyPhgSu14kO1NaRls1oE7ExlsaIMWA3TVOqmcW5kGZZmcQfAyfqyCh
            dsPxe718GVzsUmQkTTbp6ZRei78xAGI7EW1LgSZPf/68njLzAiA7uk/gXxZbcToL
            X3OS1EcgPqkEiL2gP9KUXSTsgJDxuKYrw52TrvTUXdEs+FOIpjTkp3Xs7fPgbJHx
            4O0/Zc1GVugeYKbfonlDZDEvksOF5B7+8MQ/QcjKaph4BJQd0gG6PVpx9xBONImK
            a7mhOO6S3jEdtrxwpSs+jp7QliVWcQagnUU23pUxi4LAP81Db+9sn8V7H9pR+kxY
            7ZXQGBkqxFCNVC+c8ibeqq0p+coftEVKZaHvjqjKOZI/MfBbo2PsmJydFU0WwznS
            XgHUKYahzvEyCtYgTfUvRSqmal4MEnJV2dXXDEEq8TaNjny5ndWccPzntco64dKs
            ZSBYwBjq9IRyBKGkjB3R94WwxpDQRCBulofbsMEHmTR97x+AbHk/6c+9wq9XCSg=
            =nDeF
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.11.0
