apiVersion: ENC[AES256_GCM,data:OcE=,iv:2mts67x5F0JBE/FzoJlaVVk9qN7rLZUscbFsO4sx65M=,tag:WPbsvPa3m4lZmRvnouVKWQ==,type:str]
kind: ENC[AES256_GCM,data:LBn79XZY,iv:+ruUpqfCi5UN6pU70ZsS2C84H6aL8/4rXQ2wXe1MxVA=,tag:gvRpoZtqrynETive8Reyng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PzvJpHxVGl6nNk9AiIPUeM8=,iv:hOh6j7cOLxMU3mYyYZSJeY6BPjNKnF2qC3W6/pXcX2I=,tag:samMeJ9SY5lRNZwix21JeA==,type:str]
type: ENC[AES256_GCM,data:1LyVyzea,iv:k/Fj7wHtlRggVRR3iOfsijGI63OdjoSSe7D5Hl/c/9c=,tag:yGF55o+ZQKSx9sgP+8q4bg==,type:str]
stringData:
    #ENC[AES256_GCM,data:Z0A9ZEVIGBcnCLN1ZlTwvCilrJjOXyCC/yB5ruhcSjdFgpmneQIxMG71fNhp,iv:dDqgVa2mFtQQA7eTuoiZWeOst2mzLAEDFK33go0qjfo=,tag:Y2zGjkxuwPeLSvepx10/Mw==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:OViU8OVffjwCwlwoew44KOHb1QxaXPO2UpSFxTzqC8SWYgCsd6ABy2FjpS3dvYVq1idYQBCa1S6EBBi8UChGWMdYv+06C/ze/IKl61ZpFfI=,iv:qY7yOrGwaON0RS07+B/n7GndWNJiVnXBk4l4PMjjkA4=,tag:Q2EdYFusHrvSA+BRKEWgJA==,type:str]
    #ENC[AES256_GCM,data:YVCWoN/mB0y4DoBjYce6nwPN7/s2UnluBJmhYtsm6VJPFDCx+wH3fgzPdj1f8wn2+ivvvnok44T/UKC8KO9O9g==,iv:r4tdzRuVJo0Zb9TN5UBWJlCSJpQa3X9Zk8x/yuFnhyE=,tag:gzgOfY+hAfTEFAnE4zbeqg==,type:comment]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:nC7gMgiAlTekEBgPnIIEDew=,iv:g2qFkp3R3ma7WkJJf1AdGGXRPZW6izAxMoHdcijJ1S4=,tag:v7iT3cKZOXiBN1hvkEEGpA==,type:str]
    #ENC[AES256_GCM,data:MQ6zvAlBHuk6rSystycKL+eaHUOn6g==,iv:lXTNopbs9ZPdSlv0H/9Z2fUOG4Z8bujsLwZjzp2aH8o=,tag:zgboOTfVXGOanDZqMuRg+w==,type:comment]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:FCLLtPGr7uIYGPkBs1m77kwoIL23,iv:v4+aZDW6dSsI7SPTcvPdRtwbGRhZPPLWY916K8haRfc=,tag:LMAaKVGym0iZHgkbe2UfTg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:YOzmkUJ5tM3PW8xH,iv:aJjmKLbeTjlYsd7Sy3FoUjYps9CRnHqZL+JEFxKYTYY=,tag:JJpdNJoVfuocEYDpnjm7fg==,type:str]
sops:
    lastmodified: "2025-12-22T02:47:46Z"
    mac: ENC[AES256_GCM,data:uh8jctERDLCffyXLQeFLgXbGF7TsPknTm39HG+oQCkj1NcmxplYOF0BfF6WpK91Gp1dBp+DoIrkWXWHTuL/SDcU8U3JoF2SfNWVGUQv+gynxwZrCwb9z0UpRvQX+8oAaV/cVN/ZpJoKvcVeufr2ND9ID3kX//gunfu+I4VW1HJo=,iv:9vk5FryxIfTkYc+L4ndUETCv27jhzqJWOAplWzK5RDY=,tag:It5ymSwgeTFPt1N4x9Hnvg==,type:str]
    pgp:
        - created_at: "2025-12-22T02:40:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ/+IqgL84MY7OfZoOvgVuLGBMH9jCxWet19JiKtd7UtDsE7
            A1TT8KHKB9HOqHYs8CECI7kLIqbGS6ERhaBTE1+rpKRZP/aKpEhWRBMSzSPu43lk
            qXzD8Pigra16bSN78fcxd+kVmqHeKLpmwLULMNK1DcDstpTE7fdk/HlcBiLK7QpG
            KdDgDf04epnYWR9vlLBAZdt2K7cY1xh2IBTmpAnokCa+iY5oSv5r3EPTAt57GlGk
            eL+vGN2Vb12SXSqLj8YiDIo9hDj7GjAqJHCNF/I9xR6gUAduXyD/SzueQPTzxNvP
            Ae60xjYpObwFDJiWNE8XU+Q/fQ9FQ9NOOJrejIvh/0qUpAgZbEYWU+Ni5+p9Cz63
            DFTr73yUVEnBc/FK1u7crZ+qNn0MCoEWo2IyrozbAIX7QV+cFouanITZ79APW4u1
            KK3WYHuK4YsqouBZfrzHPuZRGz7IHUiKG8IgHw5Vg25OK1YdYXflNhuYYUX0LU63
            lbwNU+asY+f/BLPjb22enI/O+707vZdD7iK+em9qFfsrUOiL0SW4lhBtz+AmwNLl
            gFkp+EbVxRTB5HNCzjqwama/wBgwl7WZsKiSnEyVcBaUnbj5oLv8/vTCDRVo+TWb
            /2y+M9acF7gVFP1xa+Hqo2eMVpTVa9+X1iu2D7ivs1w/CqAg+4Iu24B2enRleHrS
            XAFWNDjY6Lz7SGKV84Y8OuMdL2NsukZf43hOAnNwXtFnANJiEdwd6pOpInspAWqL
            T46Zxl40KvICV8Ep+wzNvn6gKKuDI/A3KoTcxq4ozMS/FVceQwHKorTGzT7E
            =mjr8
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.11.0
