apiVersion: ENC[AES256_GCM,data:xVM=,iv:b+T1S4c6SU+BoT0sMmhavFEwP75QYBgWdY/Bog97lpY=,tag:eOxyqPrE7xrMb8+dwOPEOg==,type:str]
kind: ENC[AES256_GCM,data:jW0xFRNs,iv:F/jWD5Bp5TZ8ZA2OL4hQobqvOgSKa9HZe7PpNdHMFqI=,tag:IfVyAlsZec/9fwfBI/0jhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1N9DIxB2h3Yu+pOP39I/mca2Nh5YeQ==,iv:PiiXppmA17xYbzysRjck6FHbzlV/fGVzR6orgNjWdyw=,tag:9SH2ClnrPERmeMrtDg3+Bg==,type:str]
type: ENC[AES256_GCM,data:sSqJ/kmR,iv:DnyD0LfB0+RL29ov6IB46iqrig2COgqZerRO21H4FFY=,tag:hGy7z8T6ri/h5onBrI7VJg==,type:str]
stringData:
    CLOUDFLARE_ACCESS_CLIENT_ID: ENC[AES256_GCM,data:gA0+Bk9rDZ2ejYMwN/YwT9ZLyedchs1jpZsvj1zSPAERai9Ijh/s1A==,iv:Egi9G6n1ASdWBH/N3flHOJ3BjYJXSQuFTvRWN46rNQc=,tag:zoZI9HtQijfK+JueWoZRKw==,type:str]
    CLOUDFLARE_ACCESS_CLIENT_SECRET: ENC[AES256_GCM,data:Wz+kU/v7W0KFvICPaDobbe9/K/ee6EnY64N9liiuI6lyM/rBMineQA1+HEk97pduOj+ixmzeKvTII2zuFy6eJZ+sVZ42jyG0hPOy3OcuAiUaMyoDRoM=,iv:nOpIo3TeEpjc+QfybTh/anXonyGKaHQZs2ZSXfmbrJA=,tag:xOjpmPL+PF+wm6/QyiufKQ==,type:str]
sops:
    lastmodified: "2026-09-19T01:02:30Z"
    mac: ENC[AES256_GCM,data:DDnoW6lbqYSMC8eH8Z5M2gOstZpcPUr+YurYSqaBDHM2x4c8MlMhV4E+piB7eEGWuDTbbRI+TV/0Lm3SThDpHFq3beky4luzWcNQ+UTd+DqqEsWIjd3J2HNt81G5KwDl7wu0Fv4IV6d8WSJ+dSEQImgb+ia7ZWgLFyp7mp8x8H8=,iv:THSYHA0DBUy0gQj1q6YZeyQ4uWBzdtv/JNAg2gliySE=,tag:uMn9FCkqoOXMzyHlqIXCnA==,type:str]
    pgp:
        - created_at: "2026-09-19T01:02:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/+JcTn420uTcz2s8c+mlpkUl+i5dSJSiN7lk8rO21J9xmX
            uRim1H+lLtxi+YdPjRp1b4KSX5IcOYLY0hpJUYNgH6rNvwrFdxj1PnvDSPmrhGOY
            L+lrQd6QAIpx/T1Y54Q2/46N41aFdjcV661mZMYpBYGZn6BHl+xuOo+ZdITm1r3l
            MsfL5cqXMxz0zTh5C5uTmdIqsSnWw3ffLe3ceQIBJ3kaEoowbux46PgQkNVKcp2B
            XRcVVbqefVRKceGxdk5fHI+ZRdVuso/EkM36rdHAa15V/+TrFhqHYb92+9SaAZFl
            Imrk0KgcHFoeogoB+I+q7HVI2I0UKQy2Eil7Rqy0o0bQxX2rc3T+xZ27d73aBI2C
            +t9brr0nKpLn+4PhYdVYP3SB/kE8cKZ0r+Ba3XSduf0C4++OHQv4hkox5eNSh1fn
            BMHkSOHGx2K8KymgPiCrqwvphDTblzfiPsd7r4TGGW4biUVurkdIoSFa5zi8c/82
            eqECrbwBQuSD4jcMAeBg2Px8vwLVSIwnGGcwmRXbWL9C7SjHQhHaxt87O5xwJVIp
            Eja//7/rhNxs9bzUow539ExpdypzpwCL8n1dbCg2ydSEkv0Z7rZAbbarKi2PJgs1
            xy1q/A5Yai8qecPh9UpZY1IJgU7ky9w3XItSvkBHQuNqpbHU0B8OPS0Dv7db+3PU
            aAEJAhAM4f/ODR91l4mIDwANVYI+NetTFV4YiCEQB19IBwm2FZVpPlZedPlRf+im
            Q8tdX2ESjyAg78DQsSJZBdOS2iikFgQLDA3vsf6VePpl3KZthyTYvN1nIdUeWFDk
            VgYfA+9WfkuI
            =/2tn
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
