apiVersion: ENC[AES256_GCM,data:eCI=,iv:yvQBwIhpzqxdpnoBKivkpMTR6LlomflSw6VvPbGoCyw=,tag:Fi/EfZVWCeP0IAIfr0obSA==,type:str]
kind: ENC[AES256_GCM,data:/+m7bigt,iv:3faGaiX0VGmd8fd/I6xyPf/AdOjAEnFK5aYtjsienSw=,tag:YqA3YZyoLUErroQDI1IRLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KKHclhk2SrJFKMA=,iv:V4zDNqF6iJMZVxY7FSJOc0vFqT7qR+z0zDr3SBK3CQU=,tag:rPg4iOuuHQOfJlUvulUkCQ==,type:str]
    namespace: ENC[AES256_GCM,data:QPRA4tNxui/t,iv:JqWZZsQGlgK/XxgDFGqR3zSvCS6IeufVSYZ4TXE6XUA=,tag:qR9b4L1Rl/UyHYUp8Tr/OA==,type:str]
type: ENC[AES256_GCM,data:eDiuZJKf,iv:h/MndcnRbtlxg76FFEjHS2uuveigiLlnxAi1wnGkvZ8=,tag:R+LFGevnsAVJUmd3+B2jkw==,type:str]
stringData:
    MEALIE_OIDC_CLIENT_ID: ENC[AES256_GCM,data:J0Aqet9R3qq3gC5KMXht+C9NHa+TGYXR/JWVPEXpMlkyfp0+6NkRjw==,iv:IJKlY2/pTqwgr69etjwTTPUeUMfb1b4pUasC1d1/mOE=,tag:UyWKbjMdtAVN6amYnOnD+A==,type:str]
    MEALIE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:yPeHedxwjEPGawos/J+FAtVh0VyoZpTamUeRS8fzfQj8nb+9zU8bKrYNKmKRTET9BOx+fJfNrf5H8e4RxSOCh7tj62pgF+TqZrz7pRrzWE/vwsDYNF+ncaZzkghaKAz+,iv:8pDzbgxwQ1EU6WBgYXTjXkLDLOsjxk9k/6WKK8+WnB4=,tag:fgtW0zjSuGN+u3sd/LTCLA==,type:str]
sops:
    lastmodified: "2026-10-08T17:03:18Z"
    mac: ENC[AES256_GCM,data:VYx4WCKZAStGI0HMSHzO/5i2DAZlWyxfQZLFV/1DE4wULzsr5XAdGuSGGUpkhjrWhFoAGYnoDMs280zvqt6Nm7aVTYewvwHtcK9odHFFIWBVqGv6ONWD40cuVVHNqwwwnSllIRBVM8vuuBfT/0P45JK1KVHcoKtKGDqUXkQ4Bfs=,iv:gOLfpVHidqN2GctDZytNDcgd8/FeO5CCwXzG8s+2/cQ=,tag:tq6Unqh3Q1uznQBbaLctwg==,type:str]
    pgp:
        - created_at: "2026-10-08T17:03:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAoQY2K5LTpCEtUknKRFA5kimMgCBMVPxhnVJGkpgJQ2eN
            qhN23zu6eUx7l5opXr7eoKCW2zAcgelZL/7N8jydmzu8JJ1WbSGrAL8b1eERyAR4
            gnumuU3t0hPY7K98SUGIYztpkeFmeLgA1TEXi75Fl+hQBNOqf37laG0vibwZBn7L
            D9WiGAiFv1t8eJ00QY+1xB/PTeC0IXyEx977Pl6Uiw/BafOK4DPXo4tbTuKWLAFs
            dga1qXRJaZ8h16216kN/PlZg++VsMD2t+Ett7hQaFb+tqhlSLr0sUc9wjdoO4+hW
            mYvIx/q6MhbQcKXHjbauiFHF0Vuoq2rG56ZwLt4mV1Pw4ZZLc3ERE1I+wiSBYM7q
            w9qVTe3ye6I1hGuqisJORttZtkJBlWP6dd2MUAByE0M2Qp+XntMQ9K5A66Ac09bF
            XbF6GiSOn7Gd8pvLQt/zUZ0f049cimtrj8xnYPZ7FxP8UKrNtQWQJ070Sd38WKNz
            GNtDiVFL5vm+8ZcptKaqHnJvd7Mw9JiKLo6izObxXyFkia5O7BWDVTBkgBPpqpoS
            sIpCpKu1U2toTczAa/NN5uI2dsZGSA4DO4JTnqLB7uCdLzMJyaUCpmtGiQ/v6zWK
            DNp9U+hK3VeAHRBQQ8z3ny9vgv4WiJsUr6qHgKafDk5629ZfnRO93n3iaWjfBA7U
            aAEJAhDg6yH9wJRTDDENMhGE+qKidvq8a7i5Hh7ML8DVwG6Gng/3IDxBIaZQlzD8
            J7HDbjVQMKKCWkSln7wGF4DObqtVJFH1c5i8Gab0VIM9J9bmNJbFQkV7zILbGtfP
            H4hYZYBT/COD
            =jjOZ
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
