apiVersion: v1
kind: Namespace
metadata:
  name: windscribe
  labels:
    # Privileged required for VPN container NET_ADMIN capability
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged