apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: windscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        imagePullPolicy: Always
        env:
        - name: DNS_ADDRESS
          value: "10.96.0.10"  # Using actual cluster DNS instead of 10.255.255.1
        - name: TZ
          value: America/Chicago
        - name: VPN_SERVICE_PROVIDER
          value: windscribe
        - name: VPN_TYPE
          value: openvpn
        - name: SERVER_REGIONS
          value: "US Central"
        - name: WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL
          value: "14s"
        - name: WIREGUARD_MTU
          value: "1410"
        - name: HEALTH_VPN_DURATION_INITIAL
          value: "10s"
        - name: HEALTH_VPN_DURATION_ADDITION
          value: "5s"
        envFrom:
        - secretRef:
            name: windscribe-openvpn-creds
        ports:
        - containerPort: 9091
          protocol: TCP
        - containerPort: 8888
          name: http-proxy
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File