apiVersion: ENC[AES256_GCM,data:5s0=,iv:KwmM9/snT4W9RXIwo1aBB9KApRuf0AHkzMX7NgAvFFk=,tag:aCzjFirjxJaieJNcIUA6ug==,type:str]
kind: ENC[AES256_GCM,data:uuNFpyzQ,iv:TEDVpqz4gKWEXAJmrMpUqd1Ln+AVMu+mszBJtsltNSY=,tag:XzsRVblcKEtx9nFPtCTYFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FWZqdRGR+OCTp0YpvdUyne0+gdpvPAxnhw==,iv:CQKfIInJqFEZYXUZtg3GPawa1/tLg5Y0+O4K2xCDhEI=,tag:VgwlJLRbCwhvJpRhWjUJoA==,type:str]
    namespace: ENC[AES256_GCM,data:Wdjbmnk=,iv:jZwQrpkHM+mmnsRTt2v2SEUyujZZyR7c6LrEmTP06BA=,tag:7exJSkFW6GIzu6/GUQrJ6A==,type:str]
type: ENC[AES256_GCM,data:vR5bte4L,iv:IU960+6ewqlzLLXlD4/F4R0wMTC4u0FKG6XSOgK8YRs=,tag:8RH7OXx06AJEiR1MvNBbCQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:x2WjHOD+DBCPVF7g7NKM3b+v6OQkFUeSmCuDPX5sXp7N4loNMjnw+UF83KrK0iXgAw7mvU4rak5lpThqN8Z6LPBnl4Hsy8f0oIdmLA==,iv:8Svjcwh3l+1WwmsHvGicSi9epWnJ4hqKMmTXyP+wixE=,tag:mzePfaeCXotCO2ms8X3P8Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:gJI6W6ggbdqZrA==,iv:UY2C2aDWYCGDDjyfSZNBhg5K2nKkdiLv4c0dLO0o6/I=,tag:X+A3R6MfB5PFikJ2KmuA/Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PXhkkacky7IFBQ==,iv:CBkURAw43B7pLYEdKAt+dSH9KYzUqnWgLTISicixrWQ=,tag:Orru51soJHSlr8JKxL+6wg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wxSdTo+AK0HXPw==,iv:FHksz/3A3iFoVAqGQxg302RzUl0QJxtGfCuAzmVoLko=,tag:9mchvHjdQCMToMe/6maa7w==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:Kre+VDigh+SaGivpDkXwVkJSGUBYHo0ViqSW7d6hWxH3zKbdbVMFfZyHxdqwLsVSxbzKk5W9p/NrtXKgTgfZWBzIS1k1zj7LbyOWnMfI0vnZ58PoFY4wTVdxlLajJCKhXcaulJB+sRqOvn6x0ImJUjsEZchvjZrJ6NjZUWfCgwY=,iv:l3sjhEY9fqBpQ60Ncor/zfyhAkXpf5mgNec+r6PCs6M=,tag:u83Eb4PoEaDeM/bI6LJBHw==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/8DHq47nRTlFJT2nGgTo2JCcnR1uEOwxy2kCKIbPiF0MOe
            p21ekIxsjEGBrsacNtzldF3YtzDO9ntR7peK/Cp2tn5ceiqe4eBQZJG9KzUb+DCV
            lctj5oiHy+zAsPCO4kbnNDaPvvA2Bh41Ee1Cmd6YOya2W0XFH/jeaiBfZ3/eWD6I
            cWMqu5aa+bvonhb/95d8EVRWac1oFARpK/SD7ALmLhOlqE1GsDW98IKpzNzliF4V
            OQ/2jv9vK4qheH45ELptRc+BBM5UPdoxOvObAYe8T/wIFJaXxkiygNENm9ai6oj/
            xzqDp5yHCBYB//XwdUFPC5Z6HAZ1vMWq6W1abTFqHOEdSsLKYcYA3sUMz4SlqMFp
            a5jZTQqUnBKvqeJe439GcF+QfuSsbkMarv5QZbXXOPOdI8J80IBJBsEKIli/XmVS
            +EA/tXxw51UGu4PdwVzOhJfm9VV+iBqVKvFNet0mSqUkU5fESWsE983gUrWp912R
            qG84aVOjW+AnJSgwTpL/tvODu1FTScgoFEndYGMWeevh6PN+uMW34ODH1ckCNO6I
            4EMkBs59WqIfJS1mynEo/+NMKiErfVNCSI8LSQRFhrt+oq+8WO2BAPxjME0qb+mL
            Ju7iipFeOlSFYenUykyuErRa3bb5WMnC+JCt+x86/D6TrEgtOSvqd5xgB0/IsdTU
            ZgEJAhArlIiAHpER0dt59FZKUzI6gICPetI/Yf94YYBP6oZpkw7fueu19yknX7ue
            7kNIZQaVxAQyKMwpr7rPcOLHpu20U1V6U1+RtciTg+NvH/p4UxAqfMFSkc3FS6GZ
            2S6c8rcTjg==
            =o10s
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
