apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p2pool

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - cronjob.yaml
  - service.yaml
  - servicemonitor.yaml
  - vmrule.yaml

generators:
  - secrets-generator.yaml

configMapGenerator:
  - name: p2pool-json-exporter
    files:
      - json-exporter.yml
