apiVersion: ENC[AES256_GCM,data:GY4=,iv:YM+jEV36rqWzfBeLEVhUdauhfty9YKJXuPmtQhgJ1RQ=,tag:t9b5a/zWyoAJFa6eUjwiRg==,type:str]
kind: ENC[AES256_GCM,data:zO7F8SbU,iv:jbSvQZjn4cTmr4q0Ajk0IeLJZnMVjPfWYWsB8uLutvU=,tag:u0HlcWjDketFzxOjPErfLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iFIFIaANyA/tptVhaAz2/85A+/J3/MvC,iv:PmqiDjuAQsG09W8JYoeMdCcDUFq5Znq9nlx37NzR4AA=,tag:zE6tlM1E7y1AwqGwkJQj6g==,type:str]
    namespace: ENC[AES256_GCM,data:98oY0H21ITuqSQsSKKO50A==,iv:tjo4fvB27AGtECkKDQZrkc6B5j8ObOf/K0ZTj3uNTAE=,tag:+WKsaC9wYOswnI1MTV72/w==,type:str]
type: ENC[AES256_GCM,data:xz+Usu+G,iv:gjaB8ia5iIJ/ggktV4Dc+9i4ROMLG6l54zIUfcIdJOg=,tag:+PpOQzA3iCIBQoHGqxKnug==,type:str]
stringData:
    jelly: ENC[AES256_GCM,data:Wxk+LrhPlIBI/aaP0TDtY3USk4F0mUbKPPKdtP8iPgfFaZUwBYfZ577/pEg=,iv:jCh72ghfVKXIIX62fWQYYDWfn5JpSL4z9tAtPIubHQQ=,tag:bmLqRsaSWblKfgdDG9a1vw==,type:str]
    monero: ENC[AES256_GCM,data:D3L85G1rx46j+9URFfM0Ev5/LRxnifBfR4+eY6qu3rHH7GzyCrGMxDB0WAI=,iv:yjT34AWadWh5RWKdrqe7lbMaEL/PGyUgm2JCHlkX6VU=,tag:I5CKitk/0p+4DFPREMPXCg==,type:str]
    snowflake: ENC[AES256_GCM,data:2E8A11cgg2fEm1iw860PdUXV06EkKIGBAkedjG8nWV82rHJzlGmGXZrts8M=,iv:nXDsKz9YAfyya/NVbcO4rcCiDQutYHeZ6dDl/RFI25c=,tag:bRwHl1BFAjLypUfnG4uT+g==,type:str]
    signal: ENC[AES256_GCM,data:QjLkKor3Gz/fs8+JiwD65uY2ugxbtPylBcR/YU1TVLMWVxA+uXb2dG+RRc0=,iv:QOpzayf7FbvrECW8P7VV29h+K4iN9/g6cnno+QNzOeg=,tag:cMlim4knCWiVefJWUkYzYw==,type:str]
sops:
    lastmodified: "2026-09-15T17:00:50Z"
    mac: ENC[AES256_GCM,data:0Y7WYWtsrNwwAWpwPsqxBASWnRZtssWY3+fNzmjm3T8ny/1y4uVcjW4Nwmm0yPQuTiohF09LsSI9hX5o73r2fzsm1BrQUUGk2WNIQ2G5WwxSYxoRo+RQGsTfG0S1h3UkJVwoA+Yp8DsOe0myRvyyg6Xw5y3QSZft+MQsBCdOayo=,iv:0jGHpq5nCYVI/TtADdXYzhcdSpsb8FHWooU1YlCoC90=,tag:nyGl0bYk21qlH4Mg+86Z3w==,type:str]
    pgp:
        - created_at: "2026-09-14T19:35:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//dTh3B3GMOzlSNINIM4kHOZ+qvtKv9HGXWh/DTpsvYyl0
            sp6SHbbWTo6V7zWh7cOTk7t9hGfZRaLXAtoZurKZsV6nQou+WTKAcmpSfSWq+61x
            RTAtYDrmZt6dhVRzDNunCfXulXb9nfKGE8a/rGui6pRog2mqsK8HgAWL5WgP1hm1
            weStAt8ION2uyXLY99uo94bJ9mVrXeuXR9SyksqixV3BPP+KgKdRN+q4Cs2kxVYs
            pWVxhQuC/QGzLRKdytILbm0lQZ9wFUqIwEL0pd7HfJqL406NvU7LcELoxALjV3Ej
            2nc/QkmR/+oLIHw6wYZfHsSDLfM5kn36mqmIJfZSUt3ek8I8ew2zmBXURn85DLgI
            rWXbcF1Lo84avodryBAa8Jm+CFTaGsIt6fGA6uWWQ7RYA4tWCwHn6RhTVZcN92NQ
            z9XhVtsQuLp/hmuQD9fkXHiJtbUVtSRHcGdeVtJ0S9bswwRDrFIip1cfKntb2Ufd
            qvV0X2rJ9Y/bo1PxzG3CeHbnTQoRBkox4QpD7mETp3QiogkyPx/raS+pov/9q9ye
            Jm7nVlH+Gf7/uAb6HzXpdDp8DnHEDVPMuY7wV6+XZbkNDrPt5Rtgp9X9BRPDC5Va
            u8AArsXcNXAT5+8InVDb9zwVcdh9dsE6IZe9im7HU+U4LnBZxK6SpBUm9pQ8FmLU
            ZgEJAhDIU4S4a2weqQa0IxaAvISbgQ49x3cNHXiJ/Q+YpB1I+xikZhcv1O2pB2V+
            nHBgCAZC1OOA9jqm2KoLYo+nBShVtSUVCr37uTTiFMqg0t+e2uFx+CsWcc8w8Gy5
            IeO7sFSLSQ==
            =GFKZ
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
