---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/cluster-services/democratic-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-csi
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-cloudflare
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/cluster-services/external-dns-cloudflare
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-opnsense
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/cluster-services/external-dns-opnsense
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/cluster-services/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/cluster-services/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/cluster-services/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/cluster-services/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true