apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SuperCoolAlan/homelab-manifests.git
    targetRevision: HEAD
    path: talos/twingate
  destination:
    server: https://kubernetes.default.svc
    namespace: twingate
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true