apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helm

helmCharts:
  - name: cloudflare-tunnel
    namespace: cloudflare
    releasename: cloudflared
    valuesFile: myvalues.yaml

# Commented out - secret is managed separately due to SOPS encryption
# generators:
#   - secrets-generator.yaml

