apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-apps
  namespace: media-v2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: media-apps-secret-manager
  namespace: media-v2
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: media-apps-secret-manager
  namespace: media-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: media-apps-secret-manager
subjects:
- kind: ServiceAccount
  name: media-apps
  namespace: media-v2