apiVersion: batch/v1
kind: Job
metadata:
  name: bazarr-setup
  namespace: media-v2
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        env:
        - name: BAZARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: bazarr-api-key
        - name: SONARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: sonarr-api-key
        - name: RADARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: radarr-api-key
        args:
        - -c
        - |
          set -e
          echo "Waiting for Bazarr to be ready..."
          until curl -f http://bazarr:6767/api/system/health -H "X-Api-Key: $BAZARR_API_KEY"; do
            echo "Bazarr not ready yet, waiting..."
            sleep 5
          done
          echo "Bazarr is ready!"
          
          # Configure Sonarr connection
          echo "Configuring Sonarr connection..."
          curl -X POST http://bazarr:6767/api/system/settings \
            -H "X-Api-Key: $BAZARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"sonarr\": {
                \"use_sonarr\": true,
                \"ip\": \"sonarr\",
                \"port\": 8989,
                \"base_url\": \"\",
                \"ssl\": false,
                \"apikey\": \"$SONARR_API_KEY\",
                \"full_update\": \"Daily\",
                \"full_update_day\": 6,
                \"full_update_hour\": 4,
                \"only_monitored\": false,
                \"series_sync\": 15,
                \"episodes_sync\": 15,
                \"excluded_tags\": [],
                \"excluded_series_types\": []
              }
            }"
          
          # Configure Radarr connection
          echo "Configuring Radarr connection..."
          curl -X POST http://bazarr:6767/api/system/settings \
            -H "X-Api-Key: $BAZARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"radarr\": {
                \"use_radarr\": true,
                \"ip\": \"radarr\",
                \"port\": 7878,
                \"base_url\": \"\",
                \"ssl\": false,
                \"apikey\": \"$RADARR_API_KEY\",
                \"full_update\": \"Daily\",
                \"full_update_day\": 6,
                \"full_update_hour\": 4,
                \"only_monitored\": false,
                \"movies_sync\": 15,
                \"excluded_tags\": []
              }
            }"
          
          # Configure general settings
          echo "Configuring general settings..."
          curl -X POST http://bazarr:6767/api/system/settings \
            -H "X-Api-Key: $BAZARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "general": {
                "auto_update": false,
                "single_language": false,
                "minimum_score": 90,
                "use_postprocessing": false,
                "postprocessing_cmd": "",
                "use_sonarr": true,
                "use_radarr": true,
                "path_mappings": [],
                "serie_default_enabled": true,
                "serie_default_language": ["en"],
                "serie_default_hi": false,
                "serie_default_forced": false,
                "movie_default_enabled": true,
                "movie_default_language": ["en"],
                "movie_default_hi": false,
                "movie_default_forced": false
              }
            }'

          # Configure subtitle providers
          echo "Configuring subtitle providers..."
          curl -X POST http://bazarr:6767/api/system/settings \
            -H "X-Api-Key: $BAZARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "providers": {
                "opensubtitles": {
                  "enabled": true,
                  "username": "",
                  "password": "",
                  "use_tag_search": true,
                  "use_hash": true
                },
                "opensubtitlescom": {
                  "enabled": true,
                  "username": "",
                  "password": "",
                  "use_tag_search": true,
                  "use_hash": true
                },
                "subscene": {
                  "enabled": true,
                  "username": "",
                  "password": ""
                },
                "podnapisi": {
                  "enabled": true
                },
                "subdivx": {
                  "enabled": true
                },
                "tvsubtitles": {
                  "enabled": true
                },
                "yifysubtitles": {
                  "enabled": true
                }
              }
            }'

          # Create English language profile for series
          echo "Creating language profiles..."
          curl -X POST http://bazarr:6767/api/profiles \
            -H "X-Api-Key: $BAZARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "English",
              "cutoff": 1,
              "items": [
                {
                  "language": "en",
                  "hi": false,
                  "forced": false
                }
              ]
            }'

          # Configure scheduler for automatic subtitle downloads
          echo "Configuring scheduler..."
          curl -X POST http://bazarr:6767/api/system/settings \
            -H "X-Api-Key: $BAZARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "scheduler": {
                "wanted_search_frequency": 6,
                "wanted_search_frequency_movie": 6,
                "upgrade_frequency": 24,
                "upgrade_frequency_movie": 24
              }
            }'

          echo "Bazarr setup complete!"