apiVersion: batch/v1
kind: Job
metadata:
  name: prowlarr-download-client-setup-v2
  namespace: media-v2
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        env:
        - name: PROWLARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: prowlarr-api-key
        - name: SABNZBD_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: sabnzbd-api-key
        args:
        - -c
        - |
          set -e

          echo "Waiting for Prowlarr to be ready..."
          until curl -f http://prowlarr:9696/api/v1/system/status -H "X-Api-Key: $PROWLARR_API_KEY" 2>/dev/null; do
            echo "Waiting for Prowlarr..."
            sleep 5
          done

          echo "Prowlarr is ready!"

          # Check if download client already exists
          echo "Checking existing download clients..."
          EXISTING=$(curl -s http://prowlarr:9696/api/v1/downloadclient -H "X-Api-Key: $PROWLARR_API_KEY")

          if echo "$EXISTING" | grep -q "SABnzbd"; then
            echo "SABnzbd download client already exists"
          else
            echo "Adding SABnzbd download client to Prowlarr..."
            echo "Using SABnzbd API key: ${SABNZBD_API_KEY:0:8}..."

            # Add without category first
            RESPONSE=$(curl -X POST http://prowlarr:9696/api/v1/downloadclient \
              -H "X-Api-Key: $PROWLARR_API_KEY" \
              -H "Content-Type: application/json" \
              -w "\nHTTP_STATUS:%{http_code}" \
              -d "{
                \"enable\": true,
                \"protocol\": \"usenet\",
                \"priority\": 1,
                \"name\": \"SABnzbd\",
                \"fields\": [
                  {\"name\": \"host\", \"value\": \"sabnzbd\"},
                  {\"name\": \"port\", \"value\": 8080},
                  {\"name\": \"useSsl\", \"value\": false},
                  {\"name\": \"urlBase\", \"value\": \"\"},
                  {\"name\": \"apiKey\", \"value\": \"${SABNZBD_API_KEY}\"},
                  {\"name\": \"username\", \"value\": \"\"},
                  {\"name\": \"password\", \"value\": \"\"},
                  {\"name\": \"category\", \"value\": \"\"}
                ],
                \"implementationName\": \"SABnzbd\",
                \"implementation\": \"Sabnzbd\",
                \"configContract\": \"SabnzbdSettings\",
                \"tags\": []
              }" 2>&1)

            HTTP_STATUS=$(echo "$RESPONSE" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
            BODY=$(echo "$RESPONSE" | sed -n '1,/HTTP_STATUS/p' | sed '$d')

            echo "Response body: $BODY"
            echo "HTTP Status: $HTTP_STATUS"

            if [ "$HTTP_STATUS" = "201" ] || [ "$HTTP_STATUS" = "200" ]; then
              echo "Successfully added SABnzbd download client to Prowlarr!"
            else
              echo "Failed to add download client. Checking what fields are required..."

              # Try to get schema
              curl -s http://prowlarr:9696/api/v1/downloadclient/schema -H "X-Api-Key: $PROWLARR_API_KEY" | grep -E "(name|value|advanced)" || true
            fi
          fi

          echo "Download client setup complete!"