apiVersion: batch/v1
kind: Job
metadata:
  name: prowlarr-indexer-setup
  namespace: media-v2
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        env:
        - name: PROWLARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: prowlarr-api-key
        - name: NZBGEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: nzbgeek-api-key
        args:
        - -c
        - |
          set -e
          echo "Waiting for Prowlarr to be ready..."
          until curl -f http://prowlarr:9696/prowlarr/api/v1/health -H "X-Api-Key: $PROWLARR_API_KEY"; do
            echo "Prowlarr not ready yet, waiting..."
            sleep 5
          done
          echo "Prowlarr is ready!"
          
          # Check if NZBgeek already exists
          echo "Checking existing indexers..."
          EXISTING_INDEXERS=$(curl -s http://prowlarr:9696/prowlarr/api/v1/indexer -H "X-Api-Key: $PROWLARR_API_KEY")
          
          # Add NZBgeek if not exists
          if ! echo "$EXISTING_INDEXERS" | grep -q "NZBgeek"; then
            echo "Adding NZBgeek indexer to Prowlarr..."
            curl -X POST http://prowlarr:9696/prowlarr/api/v1/indexer \
              -H "X-Api-Key: $PROWLARR_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{
                \"enable\": true,
                \"redirect\": true,
                \"name\": \"NZBgeek\",
                \"fields\": [
                  {\"name\": \"baseUrl\", \"value\": \"https://api.nzbgeek.info\"},
                  {\"name\": \"apiPath\", \"value\": \"/api\"},
                  {\"name\": \"apiKey\", \"value\": \"$NZBGEEK_API_KEY\"}
                ],
                \"implementationName\": \"Newznab\",
                \"implementation\": \"Newznab\",
                \"configContract\": \"NewznabSettings\",
                \"appProfileId\": 1,
                \"tags\": [],
                \"protocol\": \"usenet\",
                \"priority\": 25
              }"
            
            if [ $? -eq 0 ]; then
              echo "NZBgeek indexer added successfully"
              
              # Trigger sync to push indexer to apps
              echo "Syncing indexers to applications..."
              curl -X POST http://prowlarr:9696/prowlarr/api/v1/applications/sync \
                -H "X-Api-Key: $PROWLARR_API_KEY" \
                -H "Content-Type: application/json" \
                -d '{}'
                
              echo "Indexer sync triggered"
            else
              echo "Failed to add NZBgeek indexer"
              exit 1
            fi
          else
            echo "NZBgeek indexer already configured"
          fi
          
          echo "Prowlarr indexer setup complete!"