apiVersion: batch/v1
kind: Job
metadata:
  name: remote-path-mapping-setup
  namespace: media-v2
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        env:
        - name: RADARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: radarr-api-key
        - name: SONARR_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: sonarr-api-key
        args:
        - -c
        - |
          set -e

          # Wait for services to be ready
          echo "Waiting for services to be ready..."
          until curl -f http://radarr:7878/api/v3/system/status -H "X-Api-Key: $RADARR_API_KEY" 2>/dev/null; do
            echo "Waiting for Radarr..."
            sleep 5
          done

          until curl -f http://sonarr:8989/api/v3/system/status -H "X-Api-Key: $SONARR_API_KEY" 2>/dev/null; do
            echo "Waiting for Sonarr..."
            sleep 5
          done

          # Add remote path mapping for Radarr
          echo "Adding remote path mapping for Radarr..."
          curl -X POST http://radarr:7878/api/v3/remotepathmapping \
            -H "X-Api-Key: $RADARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"host\": \"sabnzbd\",
              \"remotePath\": \"/config/Downloads/\",
              \"localPath\": \"/downloads/\"
            }" || echo "Path mapping may already exist for Radarr"

          # Add remote path mapping for Sonarr
          echo "Adding remote path mapping for Sonarr..."
          curl -X POST http://sonarr:8989/api/v3/remotepathmapping \
            -H "X-Api-Key: $SONARR_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"host\": \"sabnzbd\",
              \"remotePath\": \"/config/Downloads/\",
              \"localPath\": \"/downloads/\"
            }" || echo "Path mapping may already exist for Sonarr"

          echo "Remote path mapping setup complete!"