apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-setup
  namespace: media-v2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: media-setup
  namespace: media-v2
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: media-setup
  namespace: media-v2
subjects:
- kind: ServiceAccount
  name: media-setup
  namespace: media-v2
roleRef:
  kind: Role
  name: media-setup
  apiGroup: rbac.authorization.k8s.io