apiVersion: ENC[AES256_GCM,data:lAw=,iv:qR/iAffl6UyIXR6kYCv72GehGUnwRvekekFZFXsHcb8=,tag:OgffGtp6gNCvM+uhSPPsfA==,type:str]
kind: ENC[AES256_GCM,data:QbCDIB10,iv:9aJ8DgS0N4XhDp8bmYnfZOEPvLjKHhOVieEeDaEzad0=,tag:Ebf8pvUPVMJKrgJL7OP4JA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ig8cm6Ohj9rqJfIvmKTJ45nLJnSyhpmn,iv:Z8YMk8+BLNKlxVe9rb6Bucigti89TCrjyCBSLFDLI8s=,tag:W/wT8emlxG5cOIaUXQ+ksw==,type:str]
    namespace: ENC[AES256_GCM,data:XaB95auMlA==,iv:ymgE4AyYWSt64Jz172WDWgFr+m/d1Uigz/mYsZ0GhQc=,tag:HShxxQRqMI7psZtzK+rSog==,type:str]
type: ENC[AES256_GCM,data:JC8EpbdD,iv:EvMnzUSTx3W+ugwbw6hMSHAe3kGdz9sTVc6F+4SEj3U=,tag:KUR95zy4MP7Q3HQ4dP8SUA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Mzy7Fw==,iv:8FfOIRzRHp31jVXeiCnOdBzqdrFUSBcpBxiIhbrxTLs=,tag:sA9QiSeOfBdZ3y/uyIWIwg==,type:str]
    password: ENC[AES256_GCM,data:nc7CPr0GZf4=,iv:FfC9uWkSLZD+J2naGUzGFCIIuVlqJ774gutw708QCo4=,tag:eKjpok4eGqQkXTqyuAz9cw==,type:str]
sops:
    lastmodified: "2025-08-29T02:56:00Z"
    mac: ENC[AES256_GCM,data:T6jx4qGMLTu7RwRGRsn2XgvxEcnZM3TpKcslDTK3lA0wOWurnu4VTFTuKtLQYOG5rOlpUpz1y4reWYPdQBg1BNE7rXJGETkGnPiNEdzWALT+u68J0lCDv32494nvqWaakmek/ZHxZ7Tlvv6z6EAUDCulo14oSkNIIratJvyEp+M=,iv:WFCZzA2LE22h+6Inrc4CIio+Lf6cIiX80CGcVSyztMs=,tag:1PLeLRFFuYMTedfUotitWg==,type:str]
    pgp:
        - created_at: "2025-08-29T02:56:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ//XHOW7yoPX/M95miB0PYWVPkk5lzBNP6x18cAW8VVTdUU
            /Tx0QwsKKeGP+OVxakkkI9lRf4FzQHzeioL0E7LKQAKXcX5dLdFttioRTnMFnsOa
            sUB7apMWFLGe+AxQ/xrWKDLTM5jFhG7wttI9dv2mb6G6m+AGLnG6PegK3JiQykcB
            v8N+NuYEJdopSryjIIMAtwvTL7AY6HyHXuTNfs6ikPqMrBNJdwLwgCQL72zcn9R9
            dLJuMR+t7X+9oaKwFG1lRvLjL5wh976xqjii8jzciC/noe+GqYRCsViOKIfWyhr5
            iTbRlQUknvfKmxkwgU5H3bvd2pjLGJ2ETkMcztGY8h9RTE+k0WA0iFC6ZFn4IpUG
            88ZifN/3nyUnciVcIkExbJTtDHJUFvhjW3P3U0Zm7a+ePtVOX0ruhc8yzFvvdMzF
            rpxXlVzTxT1Zn1MRbg8DiA4ftPGDVo9dYm3cuYR1ljmFhQCpI6SxcJJLlhVVp2wi
            i+XexnUzs9r5NG9bds7Ds4wqfEQcdX/K0J4GorFMx2lLZM99jb3Y6YgoxKok64Ea
            s2TAhd7GxkYNpo7GApxatkrMNLFDRdeoR3CLXo3yHEx8ysJy9RKGiuwV5OOUiyPi
            hZsSj6zaaV+Elw+PtJRz4VHxunspzYCB7puqMqMk+WGo8eo5TI+Aoiiy+/BN28TS
            XgHFA83F05TG2H/fzt/96dwwItSeFUiibauYDO1YK55VbpfzlTuT6Br/yihw+Ztd
            h0H23DX6T49oxLU3EoTQWKFSjSicaI4wKp5EBEISjK/aOUikJ3CVMGzqQHqjUvQ=
            =OllH
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
