apiVersion: ENC[AES256_GCM,data:Tgk=,iv:JEZcvwteLBG9h9VBjPlIijqpVkFTkgzb+bqbbP4klb8=,tag:q6b/HnYZHLDPxKQXtD5xRw==,type:str]
kind: ENC[AES256_GCM,data:4ZpmoUR0,iv:g87Nd6zFZbxtUvTnfqpq0PmSUwWl9EuYiiWEOHHkh4U=,tag:5OqZ/h7NIEP1AiD+uy8pQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Kpa1Oif6CcL2U2Cbyg==,iv:RJbfNd5BUZ1l+7UTSMGvRr4rg9BpHhdHIqzR2o2RvvQ=,tag:v+sylZm2B0/opFvRlyLcig==,type:str]
    namespace: ENC[AES256_GCM,data:10rixmJZ,iv:fHoXfU31IuM/qmv+k4bhs8yLVJIiovHK7hC2oxba1TM=,tag:sQIEko+mK7O93vKL8V5+Xg==,type:str]
type: ENC[AES256_GCM,data:JfxCO1D8,iv:kQubfw1hS1BwzEdQXNOfPLmvmSMGxe4ABbRQ3iFnFYc=,tag:l2Vwx4mZuE8o8JIqpKbP4w==,type:str]
stringData:
    oidc.authentik.clientSecret: ENC[AES256_GCM,data:8P6/3mRYn6W9KlwtC28YjxjKbvfuFBdtaZKQ/KJu5mumhhLWiNcuzpP3cyQ8Qy7hKhKqRbyYcrL+sBKa3+APoTbolYbhr14ReofhRt9+F5dPMBAR8e964pADow9DgFLthGFlg6SCV7nx/FClTkvPoA2tOAGQJnJbq1IpteyRUk4=,iv:bblJ2C2Yv/7D8qDTfvBCuE84xTbCnEdqdxWRpPniLYw=,tag:SkYlLBzR/JsiHVpLveFOvQ==,type:str]
sops:
    lastmodified: "2026-02-07T16:19:00Z"
    mac: ENC[AES256_GCM,data:WdDO+LHL38RyOr9BQShMcchwTerAhAAKD9fsPeHv/IViHG5NIVmScITkxMYt1pC4x1sMleLAMTzmTEHTeN5wT7PE/fNkx8qmakyBmJ6972zMLZesTViG3Ddn9HqOX7fnBqsBmLl0aW5HXD3aQaTZhamy9da+ZfwTyvBCXZt0HxY=,iv:IHxGPnrBxun2g6vSeep+iNXH6KATFVUWaTa9maP7C5E=,tag:txwlR6kEQRfMSLPeW/Jy2A==,type:str]
    pgp:
        - created_at: "2026-02-07T16:18:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//fOCSKRBVcM5g95jG3GvuevWwKbGZqzPGYb2Houm/xGnY
            l48EVGCB9uGC3hzChDPyzaFNq0bGn0243+2VKvZ1ZYIB6GqbCqQEcWVTAIi7YbQB
            r2GL0d1t9HfKufd7RM8WyvT5ll39sVl/gNlqBKL/aMGwtTnNDSC6voq/axSV32I8
            X4dNU9SH9n8P3djW/M1e7qtAInL/Rx3E54w4kVn02drbKj8xtZbtQXmWMW9ihJGl
            Zre0UL1jvA8RVZ5yO7ky3Pge/qis6rhpR9dRE9dIktGmrpdxk6PRwU22gXqwN87h
            TWbgx3UCEVA6MqDaV4D5qWzqj0kuYy7YB7yCEvbEhk/vIvUV9tv+vS6PTe6oaGzA
            FYaigR5NaqeLVXRCWOHR4Y6UyYNtLpgA3HQYh1K5wdxcf09Z/Mn5AS1OlkBJCD+b
            KX2EAeKJOUjZ9nlOCFJSVu8JnmpcrgpTjCg+0I4jxFCxSRfKLxBG019YJXISuXWp
            jbbFG8op0eOl6BbnJjsw+Hm4k3WjWQe2ZqRIlRIxAGizJxZueJkopWdQlRfk6J2f
            LdGu8M8bUStnGfaOIoAWQefgYqnW7B8uaxVj4V0nLBj3nWpUKq9vhfJvl3zyVJ7T
            oEY1J1HQ/E62G3vuOXxYDOqqxeOceGQ2wv9GJZzzHe4kVINNhpy8La9w97Oc+yTU
            ZgEJAhDy0s1a8FRfVxRxnAoJP7X0+02fjPCEnLIqRgiS7odOAaUZJm99KEcp1WxQ
            sgUy1Tdn+vQlV9OGeLywZgQOF05X4PrHhwzvw7LtYJpYdMTWUVxCuiLGuI9DYqsW
            IxIT3MuVPw==
            =pLiF
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
