apiVersion: v1
kind: Secret
metadata:
    name: tpot-manifests-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:NzB/,iv:Vu54A3O4bxBvBKFMAbpsWG2cBHMQHl+m9VaA5PWLhGc=,tag:sCwrs1k0Uxb9kkCwSEiAzg==,type:str]
    url: ENC[AES256_GCM,data:OT/rK/GDySRXt/vwp91Xlvq/4r9T41bPi2epBo9WiwqLdrreFudURlLZB7DDEug=,iv:lvA1OsoRUmj5Bk6Md+kfxENB9/+5sOZASgG0b/fjmCs=,tag:Y2yW1cplOmog2KJj0Smx2Q==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:0bZOB7LJ3U/3CYMV1rx3qwipzh8FXSny1nb0dJneM0PgA0/L7v/Idhl0jTf84h9wXvxykxc0/OQ3UoB1j5XAmAlrjcZOJa2dV0yN9x2pgTRTmS14W94NLF5e68/tlLVrkTTFrK44Xl2dAEdzzQA/zWMzvCMXqQmVJR3+AVczBfLuYCJ8L0FK2uQdO6wWsfRVX80bzmUqvK6gDyx1KAqbUjjAt5xka0glEv07JcHJwjegedLu7020ZrKMj0S2lUDxwCPu9zBI1MuIZLCyl0MpnSPv3p4iYEBqwEYP8RjS1ETf6Qg+oi2rQpTA3Askd9oS71ZNgBjqZ+fkv1H0ibQAAYhow/foXqGbhPM8zd5o97vLHPvAULNoCMZ90dIxHCate3tJM8YiLHTdO/wfgAf2mqijp7fRmsdiSKZJelJtQDs7MieaN9eap83PoFrA61ImOYHmFKSJxGWLUxB75LVrbjmPnPl6Nebx2RKSMR01HVQROcvgag6lPDxTltuwRdE0pryMVi8ZO6VSuMke0FIJP8GbqLxJfkT0BLud,iv:caXtUOALh25610SSJFxq34Jlaoj1rZzvD068+3ek/C8=,tag:gGeeCnB5VOcGseh0fHpnmA==,type:str]
sops:
    lastmodified: "2026-09-29T16:07:16Z"
    mac: ENC[AES256_GCM,data:SZQVRcdyjvFAirZdUF94xNxJdwpA0xC9F1Qdz0z46EaKSp9ENhwUW7S6LbeVJawN5kFxrdxn7vKsZ2R233SP6j7M7B7jRliYbaHNr9vzDhdnIB+LHDTQtZoMcAk+G06jGjScdmbNvjA2yQIgPvYXAgY3ESuogz6opILQ9p38kMw=,iv:DYqyJe6WWKDl574PvQ48WFm7934PQWACO1Y1hTtScNQ=,tag:L3DJDd5I7Cfqsx7ZGdbdiw==,type:str]
    pgp:
        - created_at: "2026-09-29T16:07:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/9FwVeh8fRfu4nF7Of+M1C45whqPQ3I6VZwNQ4NrqFAb0t
            olcJFGRIfLxtmvxEYhFxucmL6Qp+8Y2d7QJU1Cbpwq3yVAfU6sM7T1D9DT+2lV0p
            w5mHZfHx/I6I5N2Hp8xsngFn+bL473W9RKVZbT59bPou940N3lLyM08Ds8U3AR+R
            SQjyi776nuVV2ZtsJ/L1RLqLk2AY0igs/7QVbDUTFYEnzzCmn3ekSTIRd3gm3a6q
            Jxg/1bZbXaFpYspOw5078Zl0tVmYFBsaoYQjk0n0J9n6USl2hturWnBNoc3mdVhl
            3tXSiNr60dfFOVEiakZo15bZkvBbcnBuwLspSRP/0jIcAeHafdJEZHElHnzoNuV4
            DWt1lMfzk2w8E+FezMIbtbQa9hYX4JNNPndaCQOihfbvxVKZ8OR4UxqlkBovB/Xj
            bvYKFsMOLP3ng3tGgd/+0bvU+64LOoep7Q6sqXW9BsZ+0avx2gckx4+4mI33gLkw
            Dm5lcHKV0lOQv0DfiCYKMmubXQfOhoTOiqLvApHNlfWIVJ7I7hEWYO4JW28hf4OP
            DimwPSi4B0Urmz4Tm4/l4Y9MVKBv1Ca98sRaR2nBr4Tm4LIS9ZF6RGKe0MkO/pac
            DQRaYIyuE7N5jdyKDsL0bl2gHSe3Ii9BzznSywyFsdzGxF38NWhUxlVYXlpwEeLU
            aAEJAhAORI69iPaxLRPzrvBNpGc/kkK64dTSFfKRiMVXowOf27OgooFj9Uen13+0
            gbYs6tJF2OgsBFWBfyzhXkDS5cORYt2AB76ggaSM+fNSJ2xuh6URzWy/Jr13L7hS
            iFyl8/t3D341
            =i+9S
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
