{{ if .Values.debugger.enabled }}
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: debugger 
    spec:
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.jellyfin.volume }}
        - name: {{ .Values.jellyfin.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.jellyfin.volume.name }}
        {{- end }}
      containers:
        - name: debugger
          image: busybox
          imagePullPolicy: Always
          command:
            - "sleep"
            - "infinity"
          tty: true
          stdin: true
          volumeMounts:
          {{- if .Values.jellyfin.volume }}
            - name: {{ .Values.jellyfin.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /config
              subPath: "{{ .Values.general.storage.subPaths.config }}/jellyfin"
          {{- end }}
            - name: mediaserver-volume
              mountPath: /movies
              subPath: "{{ .Values.general.storage.subPaths.movies }}"
            - name: mediaserver-volume
              mountPath: /tv
              subPath: "{{ .Values.general.storage.subPaths.tv }}"
          {{- with .Values.jellyfin.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
