# Shared PVCs for media services

# Static PV for media-library on dedicated pool1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pool1
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: truenas.asandov.local
    path: /mnt/ST6000NM0095-pool1/media
  mountOptions:
    - noatime
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media-v2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-library-pool1
  resources:
    requests:
      storage: 5Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: media-v2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi