apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: opnsense-exporter-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/opnsense-exporter-secret.enc.yaml
