apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-postgres-daily
  namespace: immich
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: immich-postgres
