apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.7
  bootstrap:
    initdb:
      database: immich
      owner: immich
      dataChecksums: true
      encoding: UTF8
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  storage:
    size: 5Gi
    storageClass: immich-cnpg
  backup:
    barmanObjectStore:
      destinationPath: s3://asandov-immich/cnpg/
      endpointURL: https://s3.us-west-004.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-b2-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-b2-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  nodeMaintenanceWindow:
    inProgress: false
