apiVersion: ENC[AES256_GCM,data:lvM=,iv:QgeYU+tyZ2VJ6AO4EONgCw0cd0V5MiYNRJ1jqHcu3O0=,tag:sZgNZK5SpEz73neHfHg5fA==,type:str]
kind: ENC[AES256_GCM,data:aB2Bhi69,iv:M407KzM5HOAuBHcEESukb1QgNsf6Sko+CKFqixxiTTo=,tag:Qmq1BvUVnJf1t3tfoMx2Jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wglWZbqAHQrK9ttA9ZqGWHL1ThBq8cz6hS/EXw==,iv:9SJ1QJWd0fE1yKwpTeP29JaYnSODJAobKLEU+FWgzL8=,tag:KbI07iwm3K4JHUDUPwG73Q==,type:str]
    namespace: ENC[AES256_GCM,data:t8qTDzHMwRkHF0ds,iv:xM13JTMSHt8aOHfIU1ON7GU++vz7ZwIoy3CcL1PTT7I=,tag:+XVskhi4ArOxT2aFxCVkPA==,type:str]
type: ENC[AES256_GCM,data:WVdk4j/p,iv:U7XuSWmvA6jmv+vhG68WBhk14EHfnVQWOuPAIfMzgyU=,tag:95dtQW1ZB9eBzCp3ANc+Bg==,type:str]
stringData:
    OPNSENSE_HOST: ENC[AES256_GCM,data:5k/RQMZPaZPXbdQY76RjwQ==,iv:ULY+ycO8hoObzFT1m1sxjd1wNd4ryXbYt0xKgEbkDiU=,tag:NyPwfY5rv6GAlFZOMm8lxA==,type:str]
    OPNSENSE_APIKEY: ENC[AES256_GCM,data:+IIwcB9yp2XjK+9efgbq+QDPUYz75Q9N0c/TBef/3H37t7T7JCZ5XjbveLe5bZqchP5sTdOHRLlhmzJlJdvbGaSjUe9bD2Vf/on16bks6Qs=,iv:nKFk7EpiFmUJwb5Iyok5e2VGdu3HNS858cP14+JGz7A=,tag:X2/8Z9ya9XIxs+9Jr6uhiw==,type:str]
    OPNSENSE_APISECRET: ENC[AES256_GCM,data:EjnUpzlm78I6RUPZpaKNpbSidcy1VFOKK1QE8T2/tmRuSQ6s1SjXRbaivHjEuL8a/Aid0siYeK4Un4lQljWXXxmWnG0CJBth7PJXO2SGi4A=,iv:4pNzp3UPAMGpMz/GXICIZD8yl6ZHpqUKZptZRLdEjho=,tag:PbfdBmhnYkmOjSEkd5btgA==,type:str]
sops:
    lastmodified: "2025-09-07T22:45:45Z"
    mac: ENC[AES256_GCM,data:TlZ+Ffi1jANxX698Q7JTPeZ6bD6Oz7bXNb4NcI6cL/YAwj9BFJQJEdmDOCuMv00pPIcHYc1aEup3+ijRaoZIJ2kZs1x21LVTopHLTXOi3YePCgt1UWs2mqx6jjqS4qfDEuYnO6RUudpL/h/+njZKHyOIzKhc2D5hgQgb62SYCBc=,iv:rpWq9r3TjQ7a+HnXsN3K1UGPzj0Gk8bubg8z4bDFfyk=,tag:KcdkMMkXWhBoYutDAY1/lg==,type:str]
    pgp:
        - created_at: "2025-09-07T22:45:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAnphh70m6FrN/CPh+UJyNEXnPlEKAAxojnRYaP0DT+oep
            XLMFQpZRGeoo7uZ0vD0cOKpI0v+420qHoToEF83C0Ec6vBm/Lf98JIPrA96uEcc4
            uFVW2nYSTZ3HFvRxrJjSbB5W/edH8p2p/E2WJCRikQlhzHetjwBzLFOB7651Ab87
            MOQyeu+mdOFxZzNskpc+sejtZHPOu/1wclJy4KwFvsLBCMqGw9MEziFUAuOioJJc
            xrk/TDJgs7HubU3rSyNOsRRMEkUx9EvIpyNEwGhQQ0R0cMT5BafRhZMsCGIVdA9F
            uyaYhqd6P0bAah6+3o3e15bTKOPP6Vs/32TRfOgPXgI1cUMp4lL3yQf/nk8rgIXb
            D8GLuNEMjyEUIYSbGadz0j5mxWxAmz6fKF9wql2oSuV2xU/39FyL4Y0r3pycyaOm
            Zk3VUc7lAqMK0ZwrtoRMa/CQxyvowewhukpuBNL8wGWQsayNhiQxA2FrE0pzzlVD
            truOF+T61DbCRnpC65Oj5+Vm6T+piLAAdNRmod8xvaDMxN/+PYBl5OStPxjoahSu
            4ohyCspSBWEzE7WF6v0i2Qjz6JTpGutwB81XeTj6fvgtiwVubg+VcnDaJ6W4xlDP
            Qkqe1EdO1cgfiw9uTrHqU02EwJVHwn7iJOfRVRO//PF30GhtAI+DAMl+xHSiA3XU
            aAEJAhDn1QcJQgLvxLrp3KTrc2WtU+LJynB30CituPUqvhZqyRR2KwZGtiVYFmZq
            LwfHmf+kfgJiPWrtODxiS6YQOZ4O3dQfa/8gCCap2BS++VK5bXsKLCQAlZC4mfSd
            qtyrnplfqWro
            =MaSY
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.10.2
