apiVersion: ENC[AES256_GCM,data:FVc=,iv:J8HUuOfUWKIhT2aC2emYgCcBCsLm5ATPCr9hqZCifvY=,tag:zdojwNCVlm2GH4lxVWkWvA==,type:str]
kind: ENC[AES256_GCM,data:I5hh+Xo8,iv:UcX2Vrpex5gNZCQ5dBnKd8UAoe8nIcJvI4W1L0UjN7c=,tag:QfAtl9rmDlpI2LHzUnfMzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5nb27GATCOgIl/vEPUFe6iD+lM6hj+nA2sSVSQ==,iv:Lx3dqSxqzAadG8xDlyOeEVueOXQOSFOsLh2G55Y9Z+Y=,tag:1d2NQUPFA28yAHDvEkLKVw==,type:str]
    namespace: ENC[AES256_GCM,data:wLt0cXkgk8/D9KQR,iv:i6EJPIacKn3zXdgXhANmE8YvIR/k7Rv1RSqbeGWVP7w=,tag:S959INI/n9YfecGJC4uNxQ==,type:str]
type: ENC[AES256_GCM,data:hiySX5q1,iv:Wqm1ge8YKjd7A7+bZQuqrP+LU5GY2lf4+H/F3XBogto=,tag:wkbcklSoi4MDvCwFaBb2Og==,type:str]
stringData:
    OPNSENSE_HOST: ENC[AES256_GCM,data:8lwK+kWTXQEiYs5g8G7+lA==,iv:khp8h5cryc/RLpR88ziukUSOVQUwFfDhDUWtDdaWCys=,tag:SiPaH4FWJB9CSC+jCHB/VA==,type:str]
    OPNSENSE_APIKEY: ENC[AES256_GCM,data:zI4UqjU1jwPR2f3qYwvtpecGi1mb23o4oq+qeBSCzH2XFS6jwMtSqqVb1pd2FXL3QUnHm+0cesYkkCLJijcFxvE6ehA9M5THuCFSLzPOd6g=,iv:KgIMVwuzB4Uk36QYDOCCmm3kdnUXyK1bTCvWbteFrGc=,tag:UtyVLBuE6ebLaHC08bldog==,type:str]
    OPNSENSE_APISECRET: ENC[AES256_GCM,data:3rIeIVLXfrlSTQsH6vfKjebiUfXIrNaEweFqbBdYbf7U/5qXbJYU8kLQNYcgazowgOWT3zIp6uqIOpUMthtcssl81iSffIPimdTUYenwTOg=,iv:aHc0NEVA8WWbppbcts/KRUC+asVpI4b5cWyhvHhmixk=,tag:w4FEawHvt7ge5U2qum33Gg==,type:str]
    api_key: ENC[AES256_GCM,data:sz4FgPGYkbWLpk0nzyvunkRKIvq41r4On9cGZjNsORgjhjSPKZQUctHCxcNNuz9lkfNeVMFdu8qRwknIUnS3ItjJX64y9Syjwx6zIUV8jm0=,iv:LNxzpy7pszcwEhC8cTKCgMybKPLMMDo9cgt8OF9dAhk=,tag:srWFio4PpTmTLge5OcUdQw==,type:str]
    api_secret: ENC[AES256_GCM,data:3AqeVpJqcFjXW1l8kiSyvn4G/lf6E40LbjJaZhGbsrJLYhBE8C7DL8nslLRUJyoX/beCXxBBLJy2rw914eS34Ud+RVMWgkU+oFY2rhg17jI=,iv:j7vONX6aud7aBcUaM2/MyVPVyOf8DUdqIeG4cBg2eG4=,tag:JENvBvbqdlgYnDQBlHU+Eg==,type:str]
sops:
    lastmodified: "2025-09-21T02:55:04Z"
    mac: ENC[AES256_GCM,data:Oo2H4Sw6Ri6OPieIoCe96CuFCeWRvY+OewYB/cOZ9S5odZe0J/Nkef6oWW5f83mrL58W+p/BDivnad3UNXTPedwedsiRr06w4CREmK3q0EiRy7yyIqjNfVVWQq96rSKvy2+/3I94MlfzDtkDtRnwgBEOHNRmE5Ipzh1nWAU+VmM=,iv:d+32DW3JpA+111BtvZxSj1Wr+82BaXtDQd7VeQFwWYw=,tag:RWo72j9yCQPt4/7t4W80Qg==,type:str]
    pgp:
        - created_at: "2025-09-21T02:55:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63ARAAh+v4C4PYoSoosTLLKbmlk442XpGvZbL+6Gt/WBSThb5A
            xqZEFolU/+OYivgmWu/fITxQ3nj1hFmfGydFc7MdctmCpIVG9ezccQGfLKMkAGKg
            RZqslb6gSwNSTvmxKYRf64xIDjZsVegf/Vx6KAX3Pu9QM8ceXKcfO2OTH0Af5Q8H
            WWgd7/mS1FhC34bx4AXulFSLGvu5spBH4H0I+dg0AaG5ndAgFUokf/Ggnda82Ct7
            htMUAhWAa1JMiMTCMr5Gm6LFup8TuRGiCC33aKdD1nsyI7wYk+urAu/Xuh652FHb
            fa+hScBMGQYtv+bHLp3bSE1Z0L0l3bMOuoeq8+/AZn6z6+ycyKRKMNHZZR0zc/WP
            lABRyPqa/K67Sd1fmtNlZVvsRiNj5sdqy+18KItRW/zHEdiNjTc8XCAZGRSWR7tC
            ncpoOSf8kdDzXTTB8orDFMUqU20a2za6C3gDY+zU01mQKuTy0NIqZJbjV+yK8gVI
            BXF5TTZpjky0gV0VI6GetRmDQ7SNNNfi8yb67VwVCMeGaYBUCCY5p3AR5PKCCZa6
            Pt9kf5N6AcKA6A7Gl0K7A8eGQPrG3Dwc3QzxIwiT2hJQMBmbOq1j6le+e9uq2GQ1
            M26FvmI5rMRVoxMaJq5fRibP5NnlZIj1Fy9/zFs8nr/Qy1gbE6NDalfIOJz70qDS
            XgHoUP8u2tSSnH20Gn0/ASLH4ZIv6qJ0eZSumJQwXkF8ycQvC5WhTCPIzf8IvBvi
            OSXGOhhJRWhWlhQsj14xdcoUkHDdJ8vB/GthBe6tfPm8hxqveKuejte7726Ylss=
            =j7Ga
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
