apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: nut-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/nut-upsd-password.enc.yaml
