#!/usr/bin/env python3
"""Regenerate the app inventory in README.md from the ArgoCD ApplicationSet.

Usage: gen-readme-apps.py [--check]
  --check  exit 1 if README.md is stale instead of rewriting it
"""
import fnmatch
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
APPSET = os.path.join(ROOT, "talos/argocd/resources/applicationset.yaml")
README = os.path.join(ROOT, "README.md")
START, END = "<!-- apps:start -->", "<!-- apps:end -->"

# Unlisted apps still render, under "Other"; add them here to place them.
CATEGORIES = [
    ("Platform", ["argocd", "authentik", "twingate"]),
    ("Media", ["jellyfin", "jellyfin-tunnel", "media-v2", "qbittorrent", "tracearr", "maintainerr"]),
    ("Apps", ["immich", "actualbudget", "piper", "unifi", "status"]),
    ("Privacy and crypto", ["monerod", "p2pool", "snowflake"]),
    ("Oracle edge", ["crowdsec-lapi-tunnel", "oracle-telemetry"]),
]
PREFIX_CATEGORIES = {
    "talos/cluster-services/": "Cluster services",
    "talos/monitoring/": "Monitoring",
    "talos/security/": "Security",
    "talos/tpot-report": "Security",
    "talos/vms/": "Virtual machines",
}
ORDER = [c for c, _ in CATEGORIES[:1]] + ["Cluster services"] + [c for c, _ in CATEGORIES[1:]] + [
    "Monitoring", "Security", "Virtual machines", "Other"]


# Comments in the ApplicationSet that head a group of entries rather than describe one app.
SECTION_HEADERS = {"media apps", "cluster services", "monitoring sub-apps", "security scanning", "virtual machines (kubevirt)"}


def note(comment):
    """First sentence of an entry's comment, without history asides."""
    text = re.sub(r"\s*\([^)]*\b(see|PR #|previously)\b[^)]*\)", "", comment).strip()
    if text.lower() in SECTION_HEADERS:
        return ""
    return re.split(r"(?<=[.;])\s", text, maxsplit=1)[0].rstrip(".;")


def appset_entries():
    """Yield (path pattern, note) for each directory generator entry."""
    comment = []
    for line in open(APPSET):
        s = line.strip()
        if s.startswith("#"):
            comment.append(s.lstrip("#").strip())
        elif s.startswith("- path:"):
            yield s.split(":", 1)[1].strip(), note(" ".join(comment))
            comment = []
        elif s:
            comment = []


def namespace_of(app_dir):
    kust = os.path.join(ROOT, app_dir, "kustomization.yaml")
    if not os.path.exists(kust):
        return ""
    for line in open(kust):
        m = re.match(r"^namespace:\s*(\S+)", line)
        if m:
            return m.group(1)
    return ""


def apps():
    found = {}
    for pattern, comment in appset_entries():
        parent = os.path.dirname(pattern) if "*" in pattern else None
        if parent is None:
            dirs = [pattern]
        else:
            base = os.path.join(ROOT, parent)
            dirs = sorted(
                f"{parent}/{d}" for d in os.listdir(base)
                if os.path.isdir(os.path.join(base, d)) and fnmatch.fnmatch(f"{parent}/{d}", pattern))
        for d in dirs:
            if not os.path.exists(os.path.join(ROOT, d, "kustomization.yaml")):
                continue
            name = os.path.basename(d)
            # A comment that only restates the app name adds nothing to the table.
            desc = "" if "*" in pattern or comment.lower().replace(" ", "") in (name.replace("-", ""), "") else comment
            found[name] = {"name": name, "path": d, "desc": desc, "ns": namespace_of(d)}
    return found


def category(app):
    for prefix, cat in PREFIX_CATEGORIES.items():
        if app["path"].startswith(prefix):
            return cat
    for cat, names in CATEGORIES:
        if app["name"] in names:
            return cat
    return "Other"


def render(found):
    groups = {}
    for app in found.values():
        groups.setdefault(category(app), []).append(app)
    cats = [c for c in ORDER if c in groups]
    ident = lambda s: re.sub(r"[^A-Za-z0-9]", "_", s)

    out = [START, "<!-- Generated by .github/ci/gen-readme-apps.py from the ApplicationSet; do not edit by hand. -->", ""]
    out += ["```mermaid", "flowchart LR", "    argocd_appset([ArgoCD ApplicationSet talos-apps])"]
    for cat in cats:
        out.append(f'    subgraph {ident(cat)}["{cat}"]')
        for app in sorted(groups[cat], key=lambda a: a["name"]):
            out.append(f'        app_{ident(app["name"])}["{app["name"]}"]')
        out.append("    end")
        out.append(f"    argocd_appset --> {ident(cat)}")
    out += ["```", ""]
    out += [f"**{len(found)} Argo CD applications.**", "", "| Category | App | Namespace | Notes |", "|---|---|---|---|"]
    for cat in cats:
        for app in sorted(groups[cat], key=lambda a: a["name"]):
            desc = app["desc"].replace("|", "\\|")
            out.append(f'| {cat} | [`{app["name"]}`]({app["path"]}) | {app["ns"] or "—"} | {desc} |')
    out.append(END)
    return "\n".join(out)


def main():
    readme = open(README).read()
    if START not in readme or END not in readme:
        sys.exit(f"README.md is missing the {START} / {END} markers")
    block = render(apps())
    new = re.sub(re.escape(START) + ".*?" + re.escape(END), lambda _: block, readme, flags=re.S)
    if "--check" in sys.argv:
        if new != readme:
            sys.exit("README.md app inventory is stale: run .github/ci/gen-readme-apps.py and commit the result")
        print("README.md app inventory is up to date")
        return
    open(README, "w").write(new)
    print(f"wrote {README}")


if __name__ == "__main__":
    main()
