apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord-homelab
    namespace: monitoring
type: Opaque
stringData:
    webhook_url: ENC[AES256_GCM,data:Qu2gMHzIgGZ3qQgQ6r6v+WgPFCyk9igHDYW9qjghE8nDbtohn8PSnuMDe3PFT/MqA8kdiVkPLQo+ivx624C7nmDq5kxDGGYppvBht48oUJwDI/cSWbuLtaXs7z53etlgXAz+U+SG/MMIi9tt65qqpdQUGUvn2CRq1A==,iv:u/UmQoNJphJ4llUF1K44WVyYcgp4Mc+Y1NzgWrlPHh0=,tag:Uqd1++S5v/pQnB0dAlOoFQ==,type:str]
sops:
    lastmodified: "2026-09-13T18:19:15Z"
    mac: ENC[AES256_GCM,data:FImJ/Y3RWUciUeqxcBV0xDz/hmnMN1XVwUG6AUmtcNsrr6Va+OpRITwl34Tel0JWIjGfYEz117Yv34EXnFG4fO31ISCqthXs9/tJxQFBVMdgGPHbCSMPsyj7MwlOSQH3MEZxto2OzXgCYHXI+Umc8+dN6TnkCcfjhe/jx8cpAvM=,iv:9GbFzQtZjmAJWkxSIELBYhVwiV+f2XFDh1zrz/Y/iMk=,tag:Y8x3NASNuiL0bKAIrtBNeg==,type:str]
    pgp:
        - created_at: "2026-09-13T18:15:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAphugHCwqUhxx9MRyEP8KLzywY4HaSmvvG+qr97QOnZ5p
            CwAr6sSKui+OBnSX+cy2VbiMTJcSs6xfWmoPnYY9QCLuuUc+KkvBGGWPWSm6cu7W
            E+v8kJlkvSRdJWbOg5+sjIUpu9K8SugsTroXMEJG/Hc3kBfsnRHTkKByT7GSdJFG
            HWoNCRa3Cly1ti9JLaA17xgzsOg78ZpDSt2/97bUY+Zgb8WJ8KDfFGpPpGREbGQt
            7auJaqxC0h6EipdOWIZbFcZ4oTVyxg8bPS7hBMTuM1SQOsiTZpOPV+6rUPrjcZ5J
            wBOHQcbctHNTiyAYkCordAwCxuGlWSYMU9rSp2Ll1JWsIpHXOTxjC5KqGA9iMoBk
            zg7OO9RMkf+V9ku6Pay770RuidyG3AiT6yNyrkzh8GZubqocsyuc5ud6LOMCZSg5
            LD3CDDnab8juzKEdeec2jlTZT1Lffq5hdbwJx8Fa0AQa+pslWxoGNBks8qkQdSrD
            H15AV3wM+84275fkSzjbjutOp666jcZ+tZnojDyFKnxBIGn46tws/c8EA1CjQNay
            YcY2LYwgm0Fz47NUTnQVdQDtjaSlIbf2YjVzHBFMMFjZU3ogwNVn9QNTN7jVxkXY
            CI/pThn4VbZsyJ5+kn4GD/1cMV7kQs6HNNh2O/36kC7Ski6zVL3LQbJCJ7SeKYTU
            aAEJAhDegu6UWKbkxS0zryha1qzsnboSwFwGRcpoJH2z5OP3Dv7tMMhcWneul3Ao
            5AxxOCSNI33sEsgNvwShDvC5GL5VwFkD5gTpefCMIoiIZLciXCJhnHQdef1HULLy
            Njqc5Ur1IJHX
            =jX4b
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
