apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord-homelab
    namespace: monitoring
type: Opaque
stringData:
    webhook_url: ENC[AES256_GCM,data:uvalm7K1WXgYjA==,iv:9K6Z0xnt6pqpABsORx9hWPeqxK3/dsit6AZP0Gswygc=,tag:ypr9FXKOuAeAqoGheFR1tg==,type:str]
sops:
    lastmodified: "2026-09-13T18:15:37Z"
    mac: ENC[AES256_GCM,data:tysLBXtPVA2pvk20EYIxGSL0jW3hTyyQ1bcNQUcisjKasX1KK38z0OqyWoSgS6ACJHk2FS3s3tP3cjY5OlER785ZC9AIlqgJ8PA/fbhrtTIvaEjZTvTxH4xJpkmQ95CEWoqC+BO/QupxMEkXdEQiur7xI8wV3SzGPvioGkODh9I=,iv:5z1jgnspYvlzM5b6MCpioyGdM8wF+hWwoWNnwwR8E00=,tag:uW/RTWh9xQN5UtLOvRnXfQ==,type:str]
    pgp:
        - created_at: "2026-09-13T18:15:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAphugHCwqUhxx9MRyEP8KLzywY4HaSmvvG+qr97QOnZ5p
            CwAr6sSKui+OBnSX+cy2VbiMTJcSs6xfWmoPnYY9QCLuuUc+KkvBGGWPWSm6cu7W
            E+v8kJlkvSRdJWbOg5+sjIUpu9K8SugsTroXMEJG/Hc3kBfsnRHTkKByT7GSdJFG
            HWoNCRa3Cly1ti9JLaA17xgzsOg78ZpDSt2/97bUY+Zgb8WJ8KDfFGpPpGREbGQt
            7auJaqxC0h6EipdOWIZbFcZ4oTVyxg8bPS7hBMTuM1SQOsiTZpOPV+6rUPrjcZ5J
            wBOHQcbctHNTiyAYkCordAwCxuGlWSYMU9rSp2Ll1JWsIpHXOTxjC5KqGA9iMoBk
            zg7OO9RMkf+V9ku6Pay770RuidyG3AiT6yNyrkzh8GZubqocsyuc5ud6LOMCZSg5
            LD3CDDnab8juzKEdeec2jlTZT1Lffq5hdbwJx8Fa0AQa+pslWxoGNBks8qkQdSrD
            H15AV3wM+84275fkSzjbjutOp666jcZ+tZnojDyFKnxBIGn46tws/c8EA1CjQNay
            YcY2LYwgm0Fz47NUTnQVdQDtjaSlIbf2YjVzHBFMMFjZU3ogwNVn9QNTN7jVxkXY
            CI/pThn4VbZsyJ5+kn4GD/1cMV7kQs6HNNh2O/36kC7Ski6zVL3LQbJCJ7SeKYTU
            aAEJAhDegu6UWKbkxS0zryha1qzsnboSwFwGRcpoJH2z5OP3Dv7tMMhcWneul3Ao
            5AxxOCSNI33sEsgNvwShDvC5GL5VwFkD5gTpefCMIoiIZLciXCJhnHQdef1HULLy
            Njqc5Ur1IJHX
            =jX4b
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
