apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord-monero
    namespace: monitoring
type: Opaque
stringData:
    webhook_url: ENC[AES256_GCM,data:bro/nqjDRu5cBuZ0NdteSkSLVvC0D2aHYnsmomxuqT8dss/meefBLEwH5bokR7fZWdQOMsz8ZdgLxgCCQsATV3DhGHn+a1HcArKo5A9LjRFwpSlpv8FJFXxdab9LvBg28cLp1mvIgQR7uU899o/OKQOTFB7j0nV+Sg==,iv:TkYmtMSSZ4o9e49HQbJCq99qsXGHF9OoDS9MfElyjYE=,tag:jiKHrmFPa1CTmu1248VL3w==,type:str]
sops:
    lastmodified: "2026-09-13T18:02:09Z"
    mac: ENC[AES256_GCM,data:01eYWcF4+5OH8VM7K2ADEgN6BL116NOpSYKQkmWaw7F39KgnxLZ11KaZZmyzZHVxTwzhPfJAehoxoAtrw4bPUXjdihn6YAAC2mAuiZu2/XckBh+XBL47zEhnCwItnyGDOlInFpcytgtVQbqgwDb41GDsG/pr7CJPuPxSj7m0Wuc=,iv:dx4V2WkEqypTNor2AHE7AQgfvizHuPgEhRQOacE5NHQ=,tag:AOIB53N3FQX8ZniAGrFkfA==,type:str]
    pgp:
        - created_at: "2026-09-13T18:02:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAmcz9xbEY6unarxn7cucUtGzRY2BPf0j+ge5lnXzO08OC
            xEymE2nhkDRubUQ1MD1QGmc2uoyri90GsfRZWihSPNcfepp0VEAspMFYbjFcohtx
            x7l5jmak3CtErzuAZNCswUmDEcoFxvGg8U6jIWYNuDeUWHpivPwLakXHbPocUOy/
            uro2/ftT+g4eDC6a95LoXzGCgAPq2EXJ/oqw7J3Lm5Z3XMbQrPpeq0SfRud+iqIV
            4Un4R8OPXYLk8YHh8wjXZkWI5kiZa300V9f/ATXOp7pg6Z62p5QXzbbZi9NVV1g7
            RqbEllZvFG7HCp3CrS4nP1QFT5ZsIjK83ZCqf7ADcS7/M0mlBvhwu7H169qms7Xg
            rqilce/FoaTmYWNgsyOm+lixEhehnzxgdRZbCKGA0JoFnQWVro2NCOCbeWBeeFoT
            XAWwjUB9M4jud4e6CyShsPl+JiyTlDTdHSNyzqjCThE1dKTlzmYDc09vwIXbvhLy
            xEDyA/uEXaPBFfUvYAhttPoQPAPAvZ57e4ymRZK25KBRrbmmBRCDgj5xrZiRm6mA
            VEedv3H+21MqyKMUAjtHpTtHXtRkJw++32o3fMLnkvOF4rMK8vRwXDzNPJaiSD8x
            sMWWcue/Ak8U7rqVGi3jorYlXhUEf4H6sBeScVQ1vtcr4jAhEdpIIYfb9SAA44HU
            aAEJAhAlOnhfCkXDTI+em4BwDM1hqjlNCaWzUSgsaLF2fiS6UrWccNRzIpCqAVCk
            4c4aC2wtc70q7ba82GYqUPhuB6yb+MAQup1J1HYaR9XtvH+7nXUP7j6VFb93XeoG
            O3tONDXBJll2
            =KQfH
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
