apiVersion: ENC[AES256_GCM,data:6/c=,iv:vL6H8yq0PTo5uVhMxcgGPbWj85jig7btYmvZyN/y7Ks=,tag:kfAmwUEn6pUC/SLBN2CXNw==,type:str]
kind: ENC[AES256_GCM,data:veAr7cf1,iv:rOpPXT1eGonEIYNuOP7GpUfFfLs32qONpzyS9NA8Q7I=,tag:dfoUU65pbM18a8sUyIm9Tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bMmhRLzYAlMif4PNng==,iv:1x3S4lTjZRRxroUkZ4trRk+lol0UzmZIfp5fwKeZg48=,tag:b7tg6Tig/L8jEjPx3si4Ig==,type:str]
    namespace: ENC[AES256_GCM,data:I5T5R6uYtkyjsw==,iv:piMioA7pXgikNEtH/RdWb+cHFZ6+Xv8+4/bBLEQTe0g=,tag:cZxWS+r3tO1rNlyPQjEBCg==,type:str]
type: ENC[AES256_GCM,data:/7+kA3ku,iv:c0Cg7U0pKM+mki+tEa9WRWrjotYFbji5gU3iG3rXyyU=,tag:gnuj9ct/dGfEZRsu6eR/kw==,type:str]
data:
    admin-user: ENC[AES256_GCM,data:V4n8iaSfG5I=,iv:8ifaapkx8dh4wsRxzsXjlQ9R7SqnTKWujfxq2WKkUc4=,tag:pgpwPq3gv0sRtd2SPJSJjA==,type:str]
    admin-password: ENC[AES256_GCM,data:sQ41XzdIXQgzvr88G6Z/ToDh0NefSAo1AIdXw1yDpV4QeY1SUFIXevULeWlyP3aSZhBEpWKV1d4=,iv:XVqzRwYRw9IomA1VQx6ih33/EOx7P+Fz3+wMaW8B5jA=,tag:RW8add/j1EaZDgCJq/FlNA==,type:str]
sops:
    lastmodified: "2026-09-11T03:42:15Z"
    mac: ENC[AES256_GCM,data:VtDuyxgr2ePQ7+Fxc1k+Y7YzNEtX1atODB26WKJtOiHdLlRiqHGjfC4DueNoPkwIJxb1nvWv7JKbcWUQoS+yAk3MsstKxRr51dK1QNZHCuNi6yPn/84SyS7fYM/oQ4ofLJv4SWmFljBPbBKT5tB1oxO3JOJ/zb8/LQSKc49jpyI=,iv:0+G/UJqqt39qVaXeDWKE1ac2xVu/g1NTcfddbL2IUAk=,tag:bNbYCTWktoLy8C7t7NvB2Q==,type:str]
    pgp:
        - created_at: "2026-09-11T03:42:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAl/oDitvDs/GYlRjOfDkosptzK0+aspX2M+C0hgFBUs1L
            eA0UJ8qMLcv/my5+4VSxgMvLA8OHKf3Gr3cgonCHeAzB1Fd6dB6w81WvRNARlnrK
            Cha+Km/fLvhwovpTCgAboKttcPtIsM2xwGnCYGydsBlLKeZtImSATW3mGhkiukHJ
            LiglQbyO79l5n1wJtlqVEPKLceiLKYHRQ94Xwfxv5GkVZz+nqPbXviE3RyrCKUuw
            cJVeD1jdDZLIj241GtHGYJUGyWIZx/8c5z8Q4zAEitCgHzv7sZ3HsqqijVm61YkJ
            EGroWr3wlRpLZdwSGHhKD+b7H88mGFAdc6Ykh8/WqkF1NKCvVLeNMnagF2h6j46k
            vsLt1u+et1fQZ2QvN7NzxGw7+AXI2x1Iye4bjT0Z/CdPesC6JrXrVnzp6aNOn1qy
            MOiUbPNwB+rm41dYxgCcrb3fa4j3NIOcD/gWq+rXeygnMmLMI/u27OVX+tSleuwe
            hEkwJAufQjTCyQslVx62OHWNLwXNvtr9vTJEg8tdI3gnemFb9Wwm428utOWMwToO
            4eKwG1zKymXuCuOUMncHK3p3Adug7/XETzrOBEdAm2iq57UL9+3qrMadYOamyssE
            MR4hpsIWbiwxGBumgBvEB5IL96w7lKw4jDvgVRglCxgJlzkkDpHU/XO80bmxQ4fU
            ZgEJAhAhfuW8JRNfRqasl/gYYH+aD45LKOo0UeDS/VXOA8fYvAJ8s59Fku6nehsX
            9LmK/YvnhJbKJyjrCe9s7yaIhg6lk9spouMqnbDrocm6oY0pM4iubFejROV3mOdc
            JjfIP3Wp0Q==
            =t1vL
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
