apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helm
helmCharts:
  - name: democratic-csi
    valuesFile: nfs-values.yaml
    releaseName: nfs-csi
    namespace: nfs-csi

generators:
  - secrets-generator.yaml
