apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# relevant crds can be applied with
# kubectl kustomize https://github.com/kubernetes-csi/external-snapshotter/client/config/crd | kubectl create -f -

helmGlobals:
  chartHome: helm
helmCharts:
  - name: democratic-csi
    valuesFile: values-nfs.yaml
    releaseName: nfs-csi
    namespace: nfs-csi
  # not working w/ Talos
  # - name: democratic-csi
  #   valuesFile: values-iscsi.yaml
  #   releaseName: iscsi-csi
  #   namespace: iscsi-csi

generators:
  - secrets-generator.yaml
