apiVersion: ENC[AES256_GCM,data:dNI=,iv:2xZl6rKy/n/uESLrXZ4xAm3vv0iIkLtoETX1zCd9MOY=,tag:Nbv3sWOUQHEGk47DNEjgsg==,type:str]
kind: ENC[AES256_GCM,data:VOFaK86j,iv:1ErGWV3YB8W39PsR00F6V6HuXIiueydPCv7d/vQVQ40=,tag:fiLl3ZtK3lIs0O2L9YqFPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:F027fPZNApHmPToXXoH274dE0f8=,iv:NF5CGBm06G2fG2Ja2LwVbChrOJyPp9ZfSB9IZ5w0Ke4=,tag:2xJ9aZEari558v+Q0/vqFg==,type:str]
    namespace: ENC[AES256_GCM,data:hogIt+Q6Tw==,iv:L5LwuQLdOw+r5X985HFW5vszR2HfGdZ6llqkhO+Zako=,tag:37ZpkaeOhwjsWywXlOR4oQ==,type:str]
type: ENC[AES256_GCM,data:Xo+I3VmF,iv:af64nuDQZlEjAB+m+AUjuZKaHaaWlCJ6mruINoFoPLU=,tag:qxqGpiRfJmxtJGfFQjg/og==,type:str]
stringData:
    lapi-key: ENC[AES256_GCM,data:+L9jfZaqVM8muCRaf3Vzhlvzby+I/u7fJolPmz/OCgFO9Q6tEsza/DLP8w==,iv:1aA5AGJPzCizv0WCTG7B7pvL1Pk8rzHmmpuHVK+zISc=,tag:hlY8SxIuqsXMHMdilyTQTw==,type:str]
sops:
    lastmodified: "2026-08-31T19:42:21Z"
    mac: ENC[AES256_GCM,data:cn+5SVHVWuS8YqPiuTnHX23QszPH9rbCg9TGHE3FBZO0Y0UEq3BPO6dRnGc0khPqGajUkI0Rp0Iquys7LEuz5n/oyTktB4bsy4jOyWxnpIly5C56Ik4KYObNxRlKOZ4ZT52rq5PoHucJGFtHK4yLSFSuWhpe8JSEFaiSrdyOPeE=,iv:DVwCtA4Mxfw4F7aTG5p+jGTMW+Xda7YK6HsZ9khnZ/M=,tag:rJaPi8gNTeTLvznaGCX0LA==,type:str]
    pgp:
        - created_at: "2026-08-31T19:42:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAgT/islQvd0k60Q4ESq4JdqpqxAdK34MxTkzYxCHnqxNG
            WkYydwl9KIZxtryhAa8bdLK1RTnompnIx82IM79yKurmkMBFMR7g8pq5lR8KT00M
            9XoVnOrFITlUR1Q71keJt5fNB40SZQbo1yUzL6o37gZCrbUpp+CZxWodQdvTSKwj
            HNic1dfeyP/uKw2ccOmok2r1UZgrSE0oFhSVYDvEyPeZKndRhZsdzJxs8y9/VIJq
            Yul0dp8q2OE6tvpQj0jOgZOIwcfgFtZUfBgPFb7rsyzF2HuNPivVAHGgjpmS8tcO
            /ad3knIcUGExszv6b0F2W5Nbi7zf0Cs3aD4qjj4NkYNvp6AdcZvWs6DQ7/h9wPry
            ckoawG5QzHf3HN3D89K0X7IfaZhGgCxLoMG34uB877Z9HqRUrVHMlJDbF440tyuJ
            p81dw28KdUsPWI/xY/DPpeWb6A0jfuFABbDt3UUDK/BnXMqmUF+4uFr7ZYOPOjmg
            2VyGfSEUdXETSlTvdHPmkvIfU5+bhEchA6QKXaP5WhjMmgegtVvuyLtk93BXjAYJ
            XgpVk3Vo5UOjFCJYQelK3/PLK0mTaGPIujTs+Pzml4X6BI72SOepSHVA3O5x/OAB
            sU576gHkEtiG0krACOWSoatoreY6ctO335AWnWMaqpmmRClo7ZpsKZVFAIkKaznU
            WwEJAhDdzadEZlzaelLSAmAsVsEUEB/mfH0AYbvBVixva/7+vSzC59RqmpKbAxWY
            skTujGRfgP/AhBtUZqhMfN+jgb7LFuewv5pvKc9ilq08VeoxzLyIxeqoBUM=
            =1Bct
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
