# PV for media library (same NFS share as media-v2)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-media-library
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: truenas.asandov.local
    path: /mnt/ST6000NM0095-pool1/media
  mountOptions:
    - noatime
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: qbittorrent-media-library
  resources:
    requests:
      storage: 5Ti
---
# Downloads PVC (dynamic provisioning via nfs storage class)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
