apiVersion: ENC[AES256_GCM,data:Ias=,iv:AykDveY3a6v51zXoZVcG783IHhpglo2yzmJhBOJXLCg=,tag:aslF7WaptIluviU4yRYC7g==,type:str]
kind: ENC[AES256_GCM,data:Fe7ZYWIM,iv:V3jAjQDdFdiQgEcsHj9YCOZMKwLR8bd8OkJtszDmyag=,tag:5+uQE7w6YJgznojYVwg8QQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8q9nlV/IpM+TOznTJy/bwIbjg59yHQ==,iv:HokAYxF9FE3BqHTYUJFH+lM3GVTt4fH4/EoETHyRVrU=,tag:lyFzf5kYpSv1y5qh8V9oNg==,type:str]
    namespace: ENC[AES256_GCM,data:zHP18W5H4hA=,iv:K7cT2lWJRZ9Y4syZ6LdpHqmYoTaVJjvUcPNa0cq7ZQg=,tag:4zQPBnHW0ENMhwrb412SrQ==,type:str]
type: ENC[AES256_GCM,data:zYrBoY34,iv:O9cDiLlYiBqhsE7NglgQTDwtFBNBWW11h1YxlihG3BI=,tag:7M1pNXFVsLlDcXVKJZd64A==,type:str]
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:QlKd5HBpDQnEezcIykySazgfET1Y29qJY/bZ8sLbZPAlXrfVv76AGD7b4WNRU9yLOu1GBqo0kUaFiUeQWXy7Cncg/Asfio8NLBJRUFCcN9g2CwqED0lpdvH4T4aG0XhDMrTU2jEpS/lGWKbwdrbWMlloh3DOJ/za928IH2gEJG3vrgP3Bd1w318wyjxQybz3Yg7ErcsGvP3yqKJQ/76cKvHFUm7dhDaFiz+m8IdxPXjP1eGtbtEBZcljAZfvA2tSAGaRuw5kN6IfYHCt2SZW5i6VUyeZY5/Q6IsPixAxk9wOOvdRoOj5tQmI6jq7//5SUjTTEymv7o+XYUjsI/GpOwST3xzEhYOtZM2TmgYGXI4OjKJD3X3rAnEreiK3n0w4VCPifDaiA3tD6dV+F48WA8sDRcvU0W/7WHLuNayAoFh04djeXtnM9hj6QvnbtfF3WzawbK8veGYE9UwrnWAw6GdZVDcDr+EBxjat/W7+DIGQnhDEoArEftZP8pPTzkLLPAfLHyTxYCFGOKyrRUR8K1acLcgirUHkFhtBj7UAMX4cmrogIePYe0I2hp4rgHyXoU1CdRY5YMxHYmi/Mtwir2mr+ag/sc+9KR2OlOUpyI2zfgxRmEqe7n67GUTKDuaaGfZh1Amu+azliXPENl7j910=,iv:0mF/qMACeL5zBPOuVzVoFsvQIUdsB3RtLWBD5cNhiBc=,tag:N4o5thTSWapc+P5YrAuqWQ==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:28YW29JfoN5uq/n3hOKP9MEuAPh2r9SGWpb/pZeKmy0gdKtmF6LwcyF6F3SlAn5qHzo6J25VJ1yqb54E7pWe1bMjmcDm2/vUt4cbOeZoy1xgc980ixkk8UCa8/tYm4AoaTHGWmqZRLlnOWfRdliz8bMzphdvgpr9sjc8nxhW3pKVnkwUus4=,iv:iixbirdpHWv2gHSyZrbDVt5YjSKKiZtYUQ/OkjC5BuY=,tag:uKlr/Q4QFI+O+plQu1g4Ow==,type:str]
sops:
    lastmodified: "2026-09-16T16:00:42Z"
    mac: ENC[AES256_GCM,data:3tUbLWNeqfnKa5Ds5JS1j44VDa0ebMpx0TAv+LjSenclOeR1VCIIfINRyftQ04gkFQRADufVdIz5yplJ7vb2zwuAdWJP1UyDWohzyh3QS4imeYiMwrDGVjxiH/IZZ9wyVKjErnoZxe/Yt7ggnoSLCz446ugT2qBenz6fRCJ1ppI=,iv:p67XGdYcEae8x6Ri84bUXEO1s8GVB4pQJIXMYi4bs3k=,tag:+WPGb+/+pHDv8AOlOO5wGQ==,type:str]
    pgp:
        - created_at: "2026-09-16T15:56:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAuW1/kC9aH/aWqtOM4yeYN1DhvYRvph3RHRZyCGNY9L+5
            IJm/NkqvMuO975dUOBq82dJfv0Txri44Wq5qDNT2Ln4LNqz2pWyKVqfm9NLRu3IF
            beR6XWJ6t9R8/8/OOSLJN1JFEscFl9vSdswmz+OrHXDKf7lpDEkm6zIHlk9dzOZM
            kTiCyiJecTnG822YnHztAf/Di+xdvb15jYtiBuWHeGw/lS5xgxoOVaONBGB8anc1
            3Wce6tBH9EqTcT/5LjZEmbGCNl4O5JmKFiXAN0V9MBPQAgHAMrMm/G7iRMUEFTt0
            WfoRwZHnQhiqLceAFHT3mQPV6cZ0vvIr0HMYkrHuZWgZgC2TKawjEz3wqCPcz4Kf
            ZDt3cc2jy0Ah/FkcyTssstR7oWQhVLpDY2C0fkD0QVSCwGNPwX/HQq8w7Y+yt+4+
            Kn52qAvmtXHN4gnoknEaDcQ2JGMLl6nrJL1Ljk/jmBamSq/ftaRhDXIR/ziN90py
            9Ke0bagnKfF33zFo3l67l5887cQ5fBH7uerFdgkB4fx3EtJs5OQOcJnzMpt1hKuO
            un3AzfKh4CO0MfpnlLiexEEostbfsHFzflq3UmhzWh9A4iV3MtsynCtotuH+maUe
            X5PwDVOs3a/qn/qGKi+gMPmxZ4DvF/8/HX31/RyeOKJ82o+xjR+9AoJVP1mVP7jU
            WwEJAhDFuA9MImLikZ6+PrEGMQ6LCmcJEiF7UoNNmVtuL1ogFSyAXmkJ7bucx4XB
            yyia8a01FcJ3HH/k4LMcq5YuUZJm/U93RvaXOyPI6S0qxod0zX/Yg3oEo+Q=
            =5z0c
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
