apiVersion: ENC[AES256_GCM,data:SCI=,iv:D41K/pXZT2FP/Ih7cfpjCiD0vrzq43YwA/E7t8vx3I4=,tag:cv28OHoBU1PkE6a1+IsqXw==,type:str]
kind: ENC[AES256_GCM,data:tBBy3JOP,iv:SxUEehkuk9nrsrJHgcjAi7QR1eokmz+JsvGbdr+6ZWY=,tag:dDvXWsBZdRIsJcUsL/qeBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UkrbMMmbUZb/PUw9Ntke3m6h+CZv,iv:O2clbjAdSY8gNv9IRIv4OcJB9fm9cftp9XCS0eO9i9I=,tag:B/NboLARfr2ongUG9/N0XA==,type:str]
    namespace: ENC[AES256_GCM,data:wpDD7rQSZXE=,iv:FBEZ8thcS8pekgU+77RvAJTA8yTedD8GHy1oPXwjzxM=,tag:0mdK51ewm6gQS1dEL2NUFw==,type:str]
type: ENC[AES256_GCM,data:sAfCdeTx,iv:ALehoOePcNvRkIdym9wrkX6EkHJ7d6VmaZ3LTyCc+C4=,tag:SiB8r0ZKo2EKK6OzP0Khog==,type:str]
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:dOAp80nnre+6O6e4aRffmOBeo++bEJsQARuvY4fCHxSuWKn2zSYyrmOxQFbzyodOOSyUWl9LEI3v9NvNJX9I+DpALkanAg5g/X1V1SFEyvhwy0Tw7eAOhtKwwug4dQ4H37VIlZhYP1eK0JVz0QK+Gis142+cRR4dgllWTu+eIiEORpVjrY2vEw2FyiamywGOAHuOPtX0Q+Gi1e7S+jqa/qLIQlrVWgLRoqSuOAtMXj+qpItzYN2XKc4/d4jxDYTaTxkkshFjmqS87tJQO9NeEyLqJbvHMfWJ/Vy9MqnHppC9qe7OVEWcbLilGBKf2On1KjKbAxnRJfqPxdHVsO9x5F38za5iw8WAt+DCpWkU53y799Y1wLX0RH8iz3phQRkZbDf4O9JQrugVYwhOUY8NPe5nS4gyPVCgxLoozkhjEwD1RoxnaFc//sVgPXAUBrU5fw9kGtBbCkdCtGI9ELynObu4JqqOjmE6re7dPh7qazxZ5pjtu4FzBrmQmDrr4jLrB9NBrYDTW+vz9VAo3kEDgBpk+0BjLeIEdQuiSKAOzglsr5VEFUKL8tn5f16zw2Lrq7couRqREu9Apw+rJVwtUbvZFq2f3YqWENChB/fdDuV8QNQ0Z+9kQ1XB1hJvkc8KwMn4N2nhuWqqEYtywbo5bQ==,iv:93YTwqBCHWYXFljkKa/Xgz8xHBjwExQ6pEbrzfn1CEE=,tag:DrS2kTFFboMJ8NIWB/Lohw==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:UiOPmLt7v0BfDLvvWi/yILEuTCluOGQaXrcDAY/W8+L9IUZ7r9C0LMuCGgTv3FITfRyT8n863vQHGPjWj8ArOYpDKvfMvUUBu/cAcCCSENFiYTfAPorZJqlJpp49M88GvgkBsPZC/iwspxsNhjpJJv3/ULwTNSAJ0NvI3Gubq8fwKhywmkQ=,iv:0lbIBnymPUfzRrLIIrQJE6cQdMWc35P2zsBmlZzi5SQ=,tag:jKd3UdFklHzCBjW1V/I6Fg==,type:str]
sops:
    lastmodified: "2026-04-09T02:02:15Z"
    mac: ENC[AES256_GCM,data:qMBUGtMkO9dadhcLPvT8UOi6yCReDXjNMF3bmmyywk7zEuAHce2Y+BPChFR9eCb0LJ4KUC2RuJm7alCAxJgRWRq2vfS76/gPUb2NNjE1ONCGVsljpB09qR5PJOdrCft+kpTbhByk3MXehdyiJpgkBh+o3rLF8mUP8TziiR9kFUM=,iv:50unu2Req+VonvloFMc4ucD7cWqVkUB41Zbwn/E/u2I=,tag:9mxWW5Z/H6CP9xGjOODgeg==,type:str]
    pgp:
        - created_at: "2026-02-09T00:10:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAvYWHTzsvJm+AW4MyDGVR2MZd/gm1r2vSv8vkrqnGHp4P
            T12Xh2HLsEDBV32/28pSmMbwjwNWtb+9qjSfwNrVFxuUN0xeHFdgi9nYhhKM2TGK
            PnRws+iI5wZuPfMeWP4EYtFTeBlDdJxOqDBZOD4O0sQNiPRobRb+MChPdvMAu6mX
            A0oRTnp2U09NKfXGbRbLbCcyq+OAvU5esbu7CSHNhB/kV8+9NC8I2wOLP+Q1Ca8r
            E3aXTjDIcx4LZG2yKw1x3SACTygT60bZpbMGMj7pBpbXQDHwxYV1k9DW+vf1m6Kx
            ytRIz0sPFHI4GF8QZI1dny78MX8rXaAkQCvuFQBDASCpPAkwMPljnPHmfXBYswcu
            V/mdFeDJxToaocEj6L6gZvQZ/85uudehLW5mp3D4btLR0D1HSRbSWQoxNSlvriSz
            j6/MRfE74ihjIKizbmYD5r6CPm03O7yyDGN3cT1VXwChW9Uv/gpMYraCUWyx7p4F
            I5bpCHDNYxq6QyJn2BRTx+cU7axa7kCwTKihBROQylFphbKjb3asX0YPEkkAed/J
            TV3bwwtF2t0VG5mKGbC5npuURjMPy9lxy89IGl9HuY6avZzg1srIit1YvpIFY+mD
            kZtHNhR+52NKpjbJmi28+5q/uhUFWrJ/C4qkAfX8Iz3NxZ68FLbLUkuHE+1Nc8rU
            aAEJAhBa3zg4c3EuVPbibOXQLHqheGWCe+9Q6RBO8y7sxjSmFZDF1/khfmm5nRsY
            AHCav8q9MHeWQ9RD9XLW7h7mCl42lEZ8ivLuqJThwPUy6sQMuGCTACzkWWBzRNbE
            iYAwSkI3aW5z
            =7cZd
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
