apiVersion: ENC[AES256_GCM,data:S4Q=,iv:LnzkXwAFEvfmwvBJkxe6qT8XC+ixZRr9urJCBVm8KwQ=,tag:Wkf1OR8N78TEYXjR7UxjRA==,type:str]
kind: ENC[AES256_GCM,data:hurAqSN5,iv:GiT091spC+2Azg1NQCHQqD5AFtzrPG9dz2MY/Gwdu7o=,tag:lQWmutVI5PbOtnSB2G5UDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5rzdH3pH6WpSxktSD7Tjy7KDUIJh,iv:0BlAWRDStQ5WzmxqmixgbfUIy+yO2nrgrkT8cNdGc4k=,tag:6tm8H2dx+cBf9DrFd+Dcvg==,type:str]
    namespace: ENC[AES256_GCM,data:OgR1fNiB7UY=,iv:cgouZF7Q0w1V6lFV62MvSwSnHULTTICJK1oUb5ocmkI=,tag:WYSVmd7ttD9YLmTp/U8xzQ==,type:str]
type: ENC[AES256_GCM,data:kxSssIY9,iv:ODH2IiZ6E8pmu9xMKUTIWLWGWZDF/P5ZuXbQF98iO0g=,tag:2/RbZTXwEMaipO+xWpCK6g==,type:str]
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:g5sYoM8zqbqTFUXRc9DZ8q4maV1XiQyMBr+fs6PTF/L4mlVeYJtDKCHtAj54/mtgU5W+WLwBDfm2UBaSObW15DL+2bM6F9O5IFl9ET6tSEnWBOEiC8N4StO6fH0eWq9LEzLklNmFVekyDNonbKWwO1N6QdHr+MqQfdvB7T3aWo5bH+GBApSe3wJWkPO3ZdaqAoo3YUU/b3A1l1VQD93VbpQtIcHDFEJiSd3dMWWzub3vNwvkyA2ptpzGUGq/U04JCEX4A/g5e4GLOBerNhA/zVtoc01hAtMwISS+7OcQD3tR3uKFpY/45kJTLYM/WdCUa3sK7RBDKG1k9KNkDbdfPgUA7xoLgTyZ+tajMDP/t477wpBaGurnrzVshYDwQylTTRmFLai+cawbFj0+MU5K6XWtwD/Qp0cHt5xXwql8h5tsB6bRoL/90beQDPbu3WgoaNvsGWcimJTky8TqV7osgJqei8q916QRNAaQFn84ZDMnK0YT7seVPGStgT9xEvxSWcGPi1tsXED38qccggYO58OdcheOekdVH8xYeX+E/09uecAUGUdbXeoNIMj0lFWQ/W66X+B7/1XoWjym/fBix0KqnwgqnWGqW7LR0jzITGRvaWqzAYQBB1fojRK3D3/i,iv:joj4fqF2EwAxK2xqBq0JTaDYqjdcVNifnkGKoux92Fo=,tag:X/zU4OGJw3cwRqyFu3t0mw==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:/FDbwdnBZKgQwCGBuk7z9fZFp+EETnYbzPt3aZuGBIKutDcRwkDdIimky6zD6SvhO3NmWm9/y1k9jeKgkxrkEDDiuF0Ki7nyCRMxC6BzbD9cc23+hOOTbuGZi/aBxqVDAF2QYWWXwGT0FgHGUPRHVOExkIx4HBCyMFr5jJQh9re+epIrC+g=,iv:KxzhXyJuKn5vFLSnhCysJpg2CtV8aRkNBQsZIVMQdn4=,tag:3pOjkDdEZDBuZoZjxBL7FQ==,type:str]
sops:
    lastmodified: "2025-08-29T03:03:37Z"
    mac: ENC[AES256_GCM,data:xTrBNi5evPmZ39lbEoSqs+YUntyLBfyOsJaeFB2Qz8HufyJTBL35eYTPbJeS0f7dBAeHS7UPMUWRtFjqDbg9dbt3+Iyn6PzbhZykCXi8AjE3jX1xCjLXiY5dXyIHK4NhLvCcXV54UahnqVp3tkl2ssAu5nJqU2wmPMH4UWQbKuM=,iv:O8Vhi2fiu6LhDFGXnjzAWJz4r3Wh9N+Vj9aBPDYXSjQ=,tag:SR5VkiomR47EB/2Q+7Hn1A==,type:str]
    pgp:
        - created_at: "2025-08-29T03:03:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ/+P8jkQwps/Ozn+QpAqcrNPRmqeKUHxcLsTy6oUDXwuyJ9
            QTNSRBPw+FAuL9JiGNRk2A8YRNQqYrYDi++Q7WOa2W6SKdXJbZQzgiyGfeOaDQ4m
            IZh+rfQ/Kk/r/+e1kKcCMp4GbFB1qedhlhUxu+fwi6Jmrv1t2HAr4jNpBILmemYd
            KqopTfDPrLVvyS3DWHslsXyMEJduONKBBXktommV+S36B7aZjpWguEpghm1RW6lF
            vt0MxilRlYRP0GP06qW4pLQXEFjG81VhpqP3uANX7IKoOh4VDqEWTGXBBCmQozx6
            Cm9Plspnk2Iz7fCGBulCkDxZTgq2qhWkxL0pen30nyzy6qhGwZ/h2KAX16g/xN3h
            +ggOy7baRDQpfDJqG6x3U3Sx9zLaVEcKvA50NSALPwVCmZ7+Fa2VwRY27Hku1Q4J
            K/IELfjzE2gRAD68ylqINqZy/WJDJ6OPoPJjZKwZYd7XxpZDxNIQ367YU2yV/WK1
            1+YAZlOKY48ix0WJDaLiXqNyzQjzE0jbACwj7xKZWSva3LwqvkmoS1woM5/5xjVk
            p8SiiYd6jHOpl/kfwU+rdzmmIeQjbK9gPpfx3ZAexd37aZ2vZ6iyIvY6+qta33AP
            803V+5dSnllv1SU1glqh48Fc2l7NUVb03xHj2nOLdKF0XhZzaxT/GElcU7trpaHS
            XAFwTaqDKHgrsT/HE4OAC8sM3/bW7BQExOf5XdT2piNI75dFDMfKNgbqhgBZGLHE
            HYz3jSaCmt5hON/k1tc3EK7Pm3LTZbSvON1VyDoU2aYVbE1Kj2vjQ4l5C3hB
            =br3W
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
