apiVersion: ENC[AES256_GCM,data:XY8=,iv:PxNyQS60rshbia89leejJe9kNS//0pFHYzZy/NG5tTo=,tag:9IclmJae27KuqlIFGgIgMg==,type:str]
kind: ENC[AES256_GCM,data:UJTTLbjT,iv:aIo8bdwuXJxTYCvJO4qp1I8fSwVrGHUnSvVf2PWcBa8=,tag:JfXEajTDifqp7PT4HqMrRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IMVSLK9P5TTDGVY=,iv:DFd4eHfkWxLwjz8QABRzfA7o4Lrwfp/bl39XoQkd1fY=,tag:+J7LqpwyyUuytlvquJVIzQ==,type:str]
    namespace: ENC[AES256_GCM,data:5oTgIhr+,iv:tRfgKTlA820Fx0o8rSs4bn9I7gmln00I4xZNHclQ0p8=,tag:zIx6Hx5BEr/dT+m1p+n4nQ==,type:str]
type: ENC[AES256_GCM,data:DoFD89Uj,iv:vcBbvAH9EnjlbTNgn1UlaGQK3QetNX/qfti5IqQGB6M=,tag:HIZORh6uHsQelSgUfqtyDA==,type:str]
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:OfDVqJrcjPHLq0rEO/dos1O12bRH2nhBK3ND8iQ32K47t/R6Ghq2ag==,iv:fZcJWtkXdTIKWiBJiMhe7W3G6hsWyCcvOf0V7nyHxoU=,tag:rJsuq+3oj+xitYryb01Xqg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:vRjMYczIO/gLQBZ7dljXgwD3CJWlYB6NzGcjEVkFkBHtZ6u+SYhnapwPgKwNBVCbhgm2VbIG5Mf3S/tumyjioqFsAm4VUbNJbHOa3V6lParmAXl+8t2ID5QSLiqF4yyC,iv:01+7j50oHhWPKJAAcBr717tCMVv5mEeG8Y5PItUiEOM=,tag:173DHKOMeAF32wfmkRCwVA==,type:str]
sops:
    lastmodified: "2026-10-08T17:03:18Z"
    mac: ENC[AES256_GCM,data:GXy5tpkvCMmFBUE6KffKSwd2azMZpTg1n5svcVCz3YaGBihneKiSSJb3G5mJB24PJJc88ntQFfea2Kg1EEFX2irQU4N6UOy+G+e978DXzDSakuYeIhiPOSwE+tURLB4h4UEhlYa0Mb8BDPBybOHY8E00VpFfeE0eMc9EvYIGf8M=,iv:gtZqe1pVpNmp6wEA+4ZV7azHLZ9CQHhuxotTmEaxNTs=,tag:7fUhp+CWf1Hx8ffZmuUa6A==,type:str]
    pgp:
        - created_at: "2026-10-08T17:03:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/5ASzTImd8UC8+VJL7Ffh1Zv5GBsEH4WVM1cWE3W5Vs59i
            X2u/vvek89+uiQInmm+OLeVsPNW52Iu2Hc3OsbMrNPUK2JrHx3CyQfTkG3mojfKO
            OiHxEswiviUZj3q+ikjpb8Vgme/YzOhetjLJ7TuJGVmfJio1IlnvTdW8oKBoga9T
            4Q/oL6+x57xfU+t7ht5OVp+HPvqEnw8oEJIlhLQIQBfPDd1zgZEPtt0Z360r6XNJ
            VYbP9vyfwEPphWu4FZ9nIV0Dt/hixh9dIuc4AupAliGDA2uwqgCPzdpOZMkg0W96
            bbtT+0xb+aX+J/DlHC0owChKCv13F8UflgiAu+T67Czn/+MmTyTc5sng8pqkT29Y
            V48lFYinBicK/9ssDR8vAWiriVW/stYvGYsn2x5cWuxN9x2BJuRlWtyyLYWjwSyU
            kTTNLJayiV11RKWfJEyE+dIziWbCeAwAwApS48sVBdKXFrDAe8OI3xS7x9zn11KX
            AGyKyA8WB0kORImAdRRxClfBLQW/peCB5WpcCgiWXKULrz8NcxxkRx0eht3qTohq
            iSSw8teikU1Nf2PRcbHxDB8d+uIm3UY/pe1a9iNqYkXEasB5bWXcU/fZMjUaOqET
            V9HN2bCBGrrpliZyINk/qEIn1qTzytm8M9CtAU2/yFxPd97XF3ghTB7mXnA/61nU
            ZgEJAhCJ71sWwXlPtRl06+0qEUbGwCwgueDFCrJpRj+dCmij3nzHkRXB+pVHMV+f
            qPA4q0NH3La7JV1kiW9KdqWV2dTTe5tSiAnCdSCGe4uf5pAZC33hK4DJHGYmYKYc
            1HwKuUyWrQ==
            =cPMM
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
