apiVersion: ENC[AES256_GCM,data:DSQ=,iv:pvh0vMcZUAAK65jZVrLYWwqZ8EaCuSPDJbaDBYFOC4c=,tag:Ek8Lrot+0t5El8+1qlAohw==,type:str]
kind: ENC[AES256_GCM,data:9J5+Y9ds,iv:huxokpH8S8J3irIqSx1AJg/udpqBcMa11UqMSz8tB2w=,tag:SD91B72KVuLIkARAMqC2eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qmt3jjmBA3HcXC4wrqQ+,iv:xi84dX6TBd22YzOITTQDRr4MGRTKnVDUVbG147G75QY=,tag:1MIY4jCnFQMjl9ha4+e3QA==,type:str]
    namespace: ENC[AES256_GCM,data:2ry5afcwyOdscNcYhe+v,iv:p0SjUhEwV+i1rs1cO7NotyjMHpRoZ4JDdgnb50TUDdc=,tag:wYgnzpwyfezECxmc5SIHIg==,type:str]
type: ENC[AES256_GCM,data:WjInME43,iv:VZokkMhrQNxXUT270X2U/1jkTBBYTboA4jYlan6DExI=,tag:3O3STKjibShn7UaATXixVw==,type:str]
stringData:
    privatekey: ENC[AES256_GCM,data:xT1lMrnyTlbco4y77TxS/7YDT7UwAI8kr5c0EzWz817gtSBmu+Iz4Sd2mFw=,iv:67Q4685gCJdCm1cln8ka1lnnB0GgWsC1eUZ+mIaXxww=,tag:9bonOdCOM0Na4e/4PQg/xA==,type:str]
sops:
    lastmodified: "2026-08-10T23:08:03Z"
    mac: ENC[AES256_GCM,data:UvaNDcc2Q/Cr2Q9Jjtxbvn+fPDEzGxfiCQceBqMvR5rtv4gVXe2Cxq3Ahu4DNy6Di6Z2CmP1ipQkQ9NPHN8MJbJxDQQhTUgXpJbVN6i8q9b8MFL8gITC8Wt1p4Ty8y3fRY1vpsBKFKY8GaTNwS+MyqfhI7OL4Qp1DYuwT4/QJP8=,iv:UqhUrgLEl/NEfQsTkozCJg/+5viCs7t1zi/T6S2BLRM=,tag:hnKYPcg5upubiiLYVRqhCQ==,type:str]
    pgp:
        - created_at: "2026-08-10T23:08:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//Rhyfq7MwP37GVPIso2t2FBb1sGWlSmuEwKjOZkrysAvJ
            lNfahjaIAFqUN+pG2E38L+GvyhJDlYIUGJ23y1QbRnSxciRCAdaUH0LdrNQQq7d+
            D2P3E7AIwq5lyeGXeVvokARLxekFurFaiT0RofQxiATmaWQJN8GdA+CKGiipzHRv
            r/SVT1fx4R2PqdfIc0s0UuAAjxsQ5BYPEW2LmEGFM5yRuR7H1ExcJ8rk/d/utokC
            t55fRzy8nh6FC3xuf+efhNw3OxP9Tl8hsqXKKLuIo0rb38cIydUSUy4SRozdUy4J
            GtC/uTeiZqtTBDxYIkSKmGquJNvYz83PrUtp+RbgQaD1JGM/vH/ydA5bx7P7nxN2
            eauKpau6tKcfD26Z5NUuGlH2ZFFasM+d4HYyu108tjIJ2csF7nDYSwnHB1nHGiK9
            JN/fWhX3CvzqbUFWC1WatPlJNqLNm9/QEnYIflJMErpqam8PMdElLug77AK0kjp4
            44Cc3encQxwxMb2lyPLDt/9s2oXQh2CmywIq3udGIzZKeDlH3IthNKy+x6Br1VM5
            UDB6Eg/FufP+TYvKAH843VCfzz9bT+mOOhHieo/qb6KUqs5ogprky2PREn0VOv/m
            kj41AJ4FZ3b8tFBig0YtK6PeM69rS9ljmy8gYj5Pn1ohoXrkpnM0dxvO5Dh96bHU
            aAEJAhBjsTNpOxjLELcyI88g8O4qkrRpoQCNEXQRoScyJGRtVPoy2slaCpuRRjA3
            dXBnCb3SYJjj5meEEhwBzqe1jE1J6rvXbLxQvhP8dbpmWcp3Facm/ms1x2GNHVIT
            XLpfm5tvciXE
            =LrZl
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
