apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-iptv
    namespace: jellyfin
type: Opaque
stringData:
    IPTV_M3U_URL: ENC[AES256_GCM,data:VGO82xLawGtuXIZTKSYYdvo67RyufRf9/F0go9nefDfVXDU2U06rNxvBUqz5K5Xg,iv:rH6lQPfSxUh3WwefXTbMISms7jtEcWyJj446fxyZVCc=,tag:Vk6hJr18cD+5uWocnJjy3Q==,type:str]
    IPTV_EPG_URL: ENC[AES256_GCM,data:uUCUG7Wl/AsECDKf7x5283ObLPeYuPHaEZa0b/uWBrB5bejDScN22+HoEMBGjsROlHGak/U=,iv:3XR4dM0jUuQEc4Ni3gFNJJpu66BVQmw5V6mWhu6ra9I=,tag:RIC9BvHCoDed7zGQHUQ7/w==,type:str]
    IPTV_TUNER_COUNT: ENC[AES256_GCM,data:tg==,iv:X0MizF0xImUovrGCUDQNkEeH2JRlnit3CnQVFQuNu5M=,tag:/RUNwkpuxRnbWg37N7K+8g==,type:str]
sops:
    lastmodified: "2026-10-02T01:46:35Z"
    mac: ENC[AES256_GCM,data:0OU0WMppS0z1Pvcb8pM7V5t7AQIEtRDSvNX8StHAJpWhstcXP5ZGpGVRBo1HySzHXPx4z7Lf4ySiJaOgwJtTV53Qx/bq2ACuy4KieIhV3XzKZuWeIcxMS5suVxITAJuYe8G940Nv3jE2pk6AWHBdNlSssZS0zyuY0TGPl/IKr6s=,iv:tysqiv4FezwpldfgOERw+VBotA3xEDWHUDIayj1czXY=,tag:FRGYe7HtmgmhHByK4MbOZA==,type:str]
    pgp:
        - created_at: "2026-10-01T20:56:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/+PZz6/RgeGPajFGRNJobz6vsbQpjtuM++b+ClHHVlYrkw
            QgKo/alg8b86xkUSat5gwLspoZ0yVQRAyuN9S868IOyLkqr5T61rdN/tAGZZk4m5
            3sQuhyeZubk3UsfmqGMLgoRmvpsvnN5d9l4gy3SeN/vuWPj7oeLo7mZWcVFbOV5a
            yCdj+lUzb1wOKQoV19Mp1amep63/U64pg7+TZ0T8aD9F7GkhFaBqtC2pd8ngMdhY
            /7W4idf1E5yYOHlg4vzszT/tMFIGc7iDw50TCFUyrP1L4zNFwscMDFCZ94B1r9Lv
            HbpEh9E60iusrS5+ek7b2uOBUZHfKu062fkkZNasGXrjq5pXii9ZbmMtTU4+yFH5
            Kxg0IakylvVXdzrMyhNm66zzvsYXfPmi27TWHJy+ZMqAAhsMxFzbIH/6SrO7Mklf
            TsXKdLeuZ7gO0sl4NT38UdXL+Be13NgkXh9yorSF9MI7Op8fIE0pu+J0MdXe9DYw
            ReIES9HKLU2rCp8CVWzmrMGbUlSMWqBSWJTOyV5TyGjtYWJDfJ+a0Efx44b+5i8J
            qajqD0dC0Rb1bRBnOOAkCOhR9Rddq3mpUv91+D1zO/yRH4zcbGWhDd13xYq7f2c/
            DePSisl/72l+0IzT983BGIJ55DHi1+kL2tgXWpsdZj4ajdU6tY5zcBMXC2U/yrTU
            aAEJAhAevrcDJ9jZslPoBUAb1Vr7cBotNcCJeTEvXIpvcy4jWEiug9S9DP5e+8es
            05SMHxWfVnNKiNdyN8WOnIj7ufYaVkahB8qVRGLgddkjhezjJIp03x9hzX++3w19
            2PSIGN6xhJ4Q
            =R7kB
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
