apiVersion: ENC[AES256_GCM,data:I0U=,iv:MdL1GKmfYMt1zYQev8zDRbYetmO+JAGCFeQyjhOg/mM=,tag:rkcLfL2dhVV8Tmvw1F59cQ==,type:str]
kind: ENC[AES256_GCM,data:by79V9Hr,iv:Rt6tfXpA7P1jJ4uVpNadFQF0cZPWyeURpIyQ8eA83C4=,tag:XV7UTbYpbHkgztb3sJ/FmA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BgufxRMBixsFnH+pyQyFIcM5ZGAw6Q==,iv:ZZPIwzlvV6Hb43iLZrRj4Wsb30FiLYp/XPlCH42tCM4=,tag:lfdJNx4hd79Rc64XWXhfKA==,type:str]
    namespace: ENC[AES256_GCM,data:UQfeXMiF3aw=,iv:cI4IN5xQBOlgXU2EIm6NQTGWfBGG8/8f6F2ElBZEGTY=,tag:MJ6OedFvLrQtcViSnufaZQ==,type:str]
type: ENC[AES256_GCM,data:qXpXU/Qn,iv:+GWP+dsBYDfro+J5LiFXabuiaiY/G4wjgFwmGMwaBiI=,tag:i677epm9LYBvnWkzO626lQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:o4DtevGnhKyEPenv87mX4AWAVxGZ7dXA5QXyxXPlcYHNjIxyTycV1EXWvuyqfoX5RXS1pglZpCBKDqRl7C7gLKMMIwgtJmil6w==,iv:shbTdjjQHEDos8ubhr4OlxZwyAEGghZwtULpVQNiJUs=,tag:O30qmeLmiiAZf4UfKDOr7Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:mj7Ua1nVNAnm6w==,iv:oBCwceIgSE9Sz334cbUKcQPg7k/d34kVANEMuvJSg/4=,tag:hat1v1FTlr2ugcBTKMjPzw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9Hnow7w3OgUf8w==,iv:ZWUq1F3bzT5fkWlEeC2d5/c9nmHzzAJTbn4NJEjkJPs=,tag:42tpV7ismVd7qIbpZyybIg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QOFK7E1vzzkVdg==,iv:6R3u7mAzNU1YgOkv6IzpSD0njT3m+IQcilZCmRY1ZVY=,tag:vJZj7fLheMoI/0pUWQQ0+Q==,type:str]
sops:
    lastmodified: "2026-08-10T17:36:41Z"
    mac: ENC[AES256_GCM,data:Eq60ZMXs6na5PFx1ygealBptAYrzHH+GWU92Ss2zrk/ToLHWB04EIuG6q28LbLkHYlnqSSXu3SkvurNZ67leTF78Ge7LXyFhN7n0DigI7jEhFPycl0vcL6tu06SKonHiHrkLoZaY7zuXsEZNymVZnKmAXiM9AsHThdEo4NTtk+4=,iv:mCGWzG38WH5ipgibiXNxKNndpV6l0b6hbYkPGbOqtmE=,tag:rI1WHDqxCV/lqkYb7XGv5w==,type:str]
    pgp:
        - created_at: "2026-08-10T17:36:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/9EhSgI2VfQz8NjITUBE9cflXnTbvy+ClNiF804HtUQwck
            USqW+j3/mINhUW4M5saXroVPmZyDypqyPOY85lAzhtxCXl0FjPDiBY/jLFO/NCqZ
            h0L8/GlZC+jedqi3mrW/CwAosAGuuyNZ7nNPY/Ug7rtSWYMKhMe5dCGd8/sFC3pS
            i6MvbuaIcFVGKfubwrijr1IzbogZl1fqOSdfNFXZR6+pJ9q5BtWpgwajCJWp3/xA
            t/4x3sIyMSn2xSxRCAZ3NRcObdafQkCLC/Qi2OKCtGjMWNHoAm35Ahq3LpLw9pmn
            MVdfCKe4jfdTjLWzisU/akouAdhirqdaa9CqPKR3OhcnGTePd9OoN5V7XQ+WAarK
            40l4eomQkRG1bXhWOxHHat0CrEPn7hoSJ9c1sRNBa5E7DM3ozkd6axTMAr1CLGQb
            VVW0VoZsKMgE712fj3OHOcgC2lmGW+0A4Z/sRoN8JIp8DjzJNiHb3i+rnVw9QTh0
            3rR1znzFG9frEiTTi5uoxR3s6FrHPVOVKgtmvG6ukv57vOyq52f85ewxLAbMj3vN
            znzIaFYUVKMeWZE0Aj9CTu97sLa4L6AQRVLSOr7scGmYVRIp0+ViFje81Qv0H7MG
            EY3qTX5pmc/m5szflSexKcVDcmO4yBO2+mz6SVayQS3mkvkpqg9gK8zQyQnNo3bU
            aAEJAhC4ZKlNJMHzF7AQSSN+LcYJrIXq+2cEYC2I+URl87BfxPhH7fCA71m7FecC
            7ptlYwuwhNkAOMPWUNyX08RD+fs1i8aaI1yGGy/swY4lc72Z0VAoUEGSN2JezrZR
            2K9ceRhgIaZt
            =jL3/
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
