apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-iptv-private
    namespace: jellyfin
type: Opaque
stringData:
    private.m3u: ENC[AES256_GCM,data:gt7oFRU1G2JXyLq5Sg0i/o3tmzzM3tkMkdscT4W0Fri2MJCfBY2ZrZQ1ufHzRBP/Ybm32EHol3KnSe4gWfrT2yQQtPHSefLuZQZPHzFW7rEEYaxJg1iGFxwWgEDk+rH8tgiI5HDvvcKy9pcqLbuQS7uALuBDXuQYdZjb68DXxuB9WIKHTiEvKiqtS9X6ILitjHGO6/jcMz0GlTR/R6FrtGrCpgrOvZsNHDOM7HPd9+yBtzYZzjHrKPvVgZJ19gQQZ8zXRa5HtdVHHbu4pXoVuchQ2m2Sur/WhqRGSYzWUNUuACniOYEgXZ0mwEbSwbUzg1OFMnOqS1sFEswBZYqN3tQCdsBHXwxtU2ZreEgBx5ykQCVBwGAHor4exYaS/hxGFtILcr0zW2vZw1lxJ4zCZ09fNwJohAja6WHmEVIQOf2PUXTw5dvIteJLs8V2h0p8EW16858SA6Ij6nQeLKr1vUa2Cx4cZ/oFzaaXGWEjpl/qwIXdViISQe+JoVLVp+0TWlRfRXHNmTpHct10PiF1JewO3dGYuIbFo6oGNRtuw2oOSsQrbYCgXPyy6+r9z4VBtS+dU9sbqvCtrj+YpAjrXAq7VfUFl/Et0htW6D9chhw/aBBk6Lfnd8isW/ePjbXwyKmDyqIZfweXDnwUYprnKOpLNWD8PxAjy66nslYRy9dl33qFLVgooxflm9Aw2u9glc9c/M4iPMf4TJTRS5Q4lPAw6RFJX3uBDgYxJaVFroyKCELGNHK3rRif/UrI6OfqsGv/0dMQ79quC/bjxWVCBg02fbT0aRT4F/kXUCC/dnr/+XFO8pP9VKlaYFCDOSbnmjCPtEY3LkRjTLCYyzMGpCW/bZoL9q/vrF6EXcMTPcc0teBXbxZBr4bEItDkaCK2eY+XwXpqwyxdEROVlY55pt6hHbRDXbTsLWzpYIGK2t4X/W2o0ZfLG6PB0TyMPRmvy4fyd74H0sqUeq77gB6LvSDAf4n3cweoRyKqDNV6Xxlj2BlFoxWyamOvo+QbcO/n6rR3YenxlWeEU6AfDzOjVipVlYUxPHgg7YOJ3RBkpJERzp1Vn01pWwUA5liN3rgoSqglFzK5CeyB3RM9CU9m708znL6oVPmvS4CNv5pWBXQVR2fTwSIK91UU1jPiJpfephoJNavfwXM19WGKG4OX5tmZ/XUnJTc5jKCVjMaZoe9zIzF1ahnU3x55Az4BuRjeaFANU4KhB39zw9CMOiWFfIF6v5cSnDuBjJMligTg8H3ZWGEnEgk5gbWPFR1ejtrGCsUZKHDHmYSqQAmXVPY/pUW32hNI89VpwIWCt+XuAD7/c48ddddwklEAl+P6COqbTEUpGc4qG3e/Tgn+TU0FClfeR70se6lTHvFkL92Ckl03YVdw30cGSJZSUiB7Cji00BMnljqIq9DzwLYS08N0v/PgSA/TbZtdfk4OWF8ej4SClYq/P+vJ3bzqLfIU2RKCJcez9nbRYcvzgUevMQFuj+ukQE5A2S32823deSrObB0FORAowgc3lh4SgULTgm6FcZi9YPmScE/e8cGoxzv2kBrDXygdHZLgFn8g8Y+a0CtHVDwHCJ9+uT9mN2eb+857M8sM2tjwflp3njH0yFidAku3FmMoyzIaLhQ0DRXG3uhnRYRAzoqV4LtEyffdCxETHggpNsd7VpgxqzCWE8IOutt6miGBAHCb2JapEGD1HXA4U0ocmd6OFS8jUxCLKW4hKnNQ8B5VsE3P/0sLSp0t7XDy148OSB75u/Bht8YDL3P9rkaOD3b39d3DmG2X1tFV423JThNemHp8AVm8FSOJE6BIr7rZaDgQcP8fldNhfbHag3ztGDzHkKnN04Iu8Apxdx9yVaV5i6wZfRBAJnE9guW4utxpYinVrEt1e/O6SuEF6c3ITSvooCmiZHS7deh/bV2sanFujMGhv7xVpFMrm2BBZ7opKxf4RIqxJqsM4jKauqNZHIWXEX4eFUGF5eR1YyYmRZI0tGKsU93q50bhuN6ABoiAPNLwr5LCMYkbWOY3bb9spfNlO6DmiXqnuGRrymlCF/EDNhCuCVsE06D1qe9H1/+VPSGPDr0QsaOYf0iQlMxoC1HvoN2cl5Hwmlm2I1AnKL8bBVeDQytsnarawEyuexDcwcg2N9ZfHFkqjkgJ10Jqn2rQBKgKHI/Hon9HAt0xoc+rq0ZsgDAlv1Tf2iCtwL/AWzwMCJnMT39CnP9FQzlYOW7V6Do1hZyEOObh0XIvTmxm3s+gUBeOsIdPkYBeoXVcLFrzM8z2qhE1b1OuGz2jbDzRCLd1MBJnmRNiY87puANOuQHaEGUyGNhE7HUwr7+T0A69fFJK2nvGc1gDoBGWgJg5rtGoPRh1iqSCoq9/C3iOvsDD6AjcSwOBWaj/l7nZLTPfNR8A7mA2tYs=,iv:qZWF2vx1FwAYYZ4AkQSC6jDD/yJ/PcLyjT4yzxKr3no=,tag:6yDRawQBociiJV+89mHgwA==,type:str]
sops:
    lastmodified: "2026-10-01T21:02:24Z"
    mac: ENC[AES256_GCM,data:2OjahXyFrjvPAhlYoIXHXl+b9ZG52pgVSFqF05oALO9wxmkPUwyw87DrVDuZyky6GJ1bnJc/1erx4hOcIhVQ06mFgXmjU9iiuCZ4v9Bl6FKP1bknhoX6ANUIqO5zUXyAikaYtdluIiF9tGEPP5TvfMXMKTHeg1Ny4Kb7pm4Os0U=,iv:cfuVIxhjrH7rrusjYpc5UuDDNA+Is7pbSReT4W9fPlw=,tag:gPUuEqIM0p7mHpZaIO7t7g==,type:str]
    pgp:
        - created_at: "2026-10-01T21:02:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//fiTWrIY9AOwtOQxvcP9jUV9TPZCYwSGw2oD0lytNmF23
            Fc8RL0meW8QNhkc1oVFF86s/AdqKTalQlwFzfcEt7nIM59CpMtE7WgUyeCezvc7e
            p2ass6/I/aRzH3ffj46uTu4BEIjHsbMuLCba46Edq/jXnukmWI4ykktTBos9/XIa
            he/7THEbDHM+30jZ4XbYUHGYfGiUNWBpU6p73iIa06DCxhL5WTHHNyy1p9AiuOWS
            L5XkH41XwiZbZILF8tHPAby1eWnqJzLGziE6QqdAQETGCGklgNQKEf+CVey7LANN
            Ww1hohcpNyIvEMGqqW4jQpxQ69k9iGTkTOkAkH+mHy4ip+isSfHDjdXlDtoPQAQm
            XHobZ5BnggnSSqXXdDU6Y9q+6k3jct7DKyh5TmZShmnkfApdrgrIduFUkvQMNP0H
            eualjIJ2k84nbE+zIvCMRUYI8t30JRgLjdoZMXYqLrAQYpjDCN1FAZLb4Tq6AfC8
            8m7FVzJ7/HrsefDI0U+JBw38G/X402DVmE1obaUgy4mSfWMXvnb1AvxsfvHIixq/
            3VCX58SULiQ62qVw5KnJBRSa5xQUkTTHBdqKoOTKwHXqdruK9S6WTX2+wJqHzfd8
            dI67ql+Sn5JQayaFwydeggNEgyk+COGIsysVtjHcR17y5uxRd1XutEzwGR838/PU
            aAEJAhBFn+840lpRGtbfqvprWs6c6ApOFAIUqo2BvbsQ3nbLMGnVsIGV5XCHFPT4
            01tQw6plktybsT9oA8SR6+wk+u7GntJZdQQfejmnk2gViu1Upf15iibG5JduUodC
            VZz6bGCRgC5q
            =hbw2
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
