apiVersion: ENC[AES256_GCM,data:cLk=,iv:4koRUDsLOFQfF5sCI4RaJpWV5kjQrqj8U5dbTbDCzvU=,tag:x9w680+sgyD8yDR7lDaV3w==,type:str]
kind: ENC[AES256_GCM,data:ZPp4yxV5,iv:YCsTMjLHcdFsOyR9YUABIGdx5P+MMF4FWlFrQXKl/oI=,tag:8q8r+txbbNINp/f5yofZbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:q7thZMdJZI1sYKXaxQ==,iv:jzQFnTuaZb+X2QBaJCdoRenSLA/tpwdpHHOreJiughI=,tag:LHSubxKSB/5xV8WcZTnxuw==,type:str]
    namespace: ENC[AES256_GCM,data:jveyW15pFoU=,iv:g7e1JkzyNv+SoayI+QKDEhuTjjFQ+pdj2eKOOW5lyxQ=,tag:kBahStLZK85fDK+i3uD71A==,type:str]
type: ENC[AES256_GCM,data:YaopHV2B,iv:qR/JD0p2/86FQBEMV7ItUnJHjab2gFJLjp5jPdYlX4g=,tag:39E/Ci44lmjfEuFwzVsdQg==,type:str]
stringData:
    LDAP_BIND_PASSWORD: ENC[AES256_GCM,data:yKtcG/8FVP4D/WEPJgY=,iv:CNfLJuFPBJI5Ed9BKa7cToZycynUeZQOU/9ffUsEpb8=,tag:JfB31pIGc8P4cYlmln3p7w==,type:str]
sops:
    lastmodified: "2025-12-28T23:39:42Z"
    mac: ENC[AES256_GCM,data:ErXm/2E03OccSU0RZE2++JH3Ou446/G29D7qBKFpzUBWbVOXyXdFeFIU87TeZ1csIcfLjYkTVPGQvr2NiIn2FRPkVvSR5xjfzhifTPNy7zYRB+hq2TDAoZepbegG3HQ6OdrGfs7OtGfoDGsBbUewthgyEpinR06ghg0dM1bultA=,iv:KO33WymAuKXPAUCB9JISnSBchLdWHR+P+0dXBu+mGSo=,tag:sFvHvLCHQyrtbJEM0e1ICA==,type:str]
    pgp:
        - created_at: "2025-12-28T23:39:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAmP6KmEKE3zs12BuX9nEcTd2coVC4SQCA2ZCKWWXJLPRQ
            w6naSvPFQSlNLFjI6wMHgHu1/P6pW2IT/81OeQ9GAMCGghlMhXCcNYVqFEYkdYjO
            7tf3CGmJyUMcK/Jpg0sFE6JUbxoPyUosdd5lwiuO7UYlytCTnHqReh6DO33SDOzN
            yr1+clvq4GGLaPN+RqNA0IqG1ZvsK/Saul87eTmcyibp9QfVGZve+fe/Geo+gDDx
            ybVpuNKflQ5r7SASRWioBBBcJE9mloOZdCpA6VKLLJNxoz228e3qGsL1kKjT4W9C
            1zNezTiI7tk6j/zyED1g2wCfsK/cZX7BaFaRdhNNOk5Qd1lI8O0OuWZoxnqj0Nvw
            jgT7UpMDR6nGKd+G2dNdpeHY3X5kCiiVE8Nrd4aIzlW7LPvMVwNwNd5jwmMIxflO
            37rpuF7bT8yqrFfY6gd2hAW8rG2is7afZz8gr0z9qAl9krPsmNOCPgi3gCSXySrt
            W8FDPo/y9kKReM0uIBDze0JHfXP/IM8Ylvpu0qJetwccftwQ4xwrYchlCdQkyR1M
            x/ep14aKwhwOKdSAttCHCTyOmAsneaCm9ct8cNV8hD912e/Hh6QMCPCaw36yF2d8
            tG6AK7zUbNtP/jkct9UaN9amLzxZ/hgcCKcVHDC4wCvXYZ+M8M3pBr9IcUb6MYXU
            aAEJAhBY8P1NYcptXiAjZjiSm2lHwdsWElbYBLBOhYFi23+fdqR29ev0LOpFXeEh
            OVhCHxx9Eoahk5xdm7Y2HZ6dRSYkVcU9D+Feqz9Wn39u/S5p7b90gfPsG1uHjkmL
            IMI2wXw5yxfQ
            =301W
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
