{
 "title": "Starlink",
 "description": "Starlink dish metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "DishID",
    "label": "Dish ID",
    "query": {
     "query": "label_values(starlink_dish_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_state{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_uptime_seconds{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Cell ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_cell_id{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Gateway ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initial_gateway_id{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Satellite ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initial_satellite_id"
    }
   ]
  },
  {
   "title": "24h Obstructed Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_last_24h_obstructed_seconds{instance=\"$DishID\"}",
     "legendFormat": "24h_obstructed_seconds"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_currently_obstructed{instance=\"$DishID\"}",
     "legendFormat": "Obstructed"
    },
    {
     "expr": "starlink_dish_backup_beam{instance=\"$DishID\"}",
     "legendFormat": "Backup Beam"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_slow_eth_speeds{instance=\"$DishID\"}",
     "legendFormat": "Slow Ethernet"
    },
    {
     "expr": "starlink_dish_alert_mast_not_near_vertical{instance=\"$DishID\"}",
     "legendFormat": "Mast Not Near Vertical"
    },
    {
     "expr": "starlink_dish_alert_motors_stuck{instance=\"$DishID\"}",
     "legendFormat": "Motor Stuck"
    },
    {
     "expr": "starlink_dish_alert_thermal_throttle{instance=\"$DishID\"}",
     "legendFormat": "Thernal Throttle"
    },
    {
     "expr": "starlink_dish_alert_thermal_shutdown{instance=\"$DishID\"}",
     "legendFormat": "Thermal Shutdown"
    },
    {
     "expr": "starlink_dish_alert_unexpected_location{instance=\"$DishID\"}",
     "legendFormat": "Unexpected Location"
    }
   ]
  },
  {
   "title": "Tail",
   "type": "graph",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_uplink_throughput_bytes{instance=\"$DishID\"} / 1000000 * -1",
     "legendFormat": "Upload"
    },
    {
     "expr": "starlink_dish_downlink_throughput_bytes{instance=\"$DishID\"} /1000000",
     "legendFormat": "Download"
    },
    {
     "expr": "avg_over_time(starlink_dish_pop_ping_latency_seconds{instance=\"$DishID\"}[5m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Current SNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_snr{instance=\"$DishID\"}",
     "legendFormat": "SNR"
    }
   ]
  },
  {
   "title": "Current Ping Drop Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_pop_ping_drop_ratio{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Current Wedge Fraction Obstructions",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"0\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"1\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"2\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"3\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"4\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"5\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"6\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"7\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"8\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"9\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"10\",instance=\"$DishID\"}"
    },
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{wedge=\"11\",instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Wedge Fraction Obstructions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_wedge_fraction_obstruction_ratio{instance=\"$DishID\"} * 100 > 0 ",
     "legendFormat": "{{ wedge_name }}"
    }
   ]
  },
  {
   "title": "Slot Timers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_time_to_slot_end_seconds{instance=\"$DishID\"}",
     "legendFormat": "Slot End"
    },
    {
     "expr": "starlink_dish_first_nonempty_slot_seconds{instance=\"$DishID\"}",
     "legendFormat": "First Nonempty Slot"
    },
    {
     "expr": "starlink_dish_backup_beam{instance=\"$DishID\"}",
     "legendFormat": "Backup Beam"
    }
   ]
  },
  {
   "title": "SNR and Pop Ping Drop Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "SNR" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(starlink_dish_snr{instance=\"$DishID\"}[1m])",
     "legendFormat": "SNR"
    },
    {
     "expr": "avg_over_time(starlink_dish_pop_ping_drop_ratio{instance=\"$DishID\"}[10s])",
     "legendFormat": "Drop"
    },
    {
     "expr": "starlink_dish_currently_obstructed{instance=\"$DishID\"}",
     "legendFormat": "Obstructed"
    }
   ]
  },
  {
   "title": "24h Obstructed Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_last_24h_obstructed_seconds{instance=\"$DishID\"}",
     "legendFormat": "24h_obstructed_seconds"
    }
   ]
  }
 ]
}