apiVersion: ENC[AES256_GCM,data:+Vk=,iv:UKQAvoe1aVqpmJRsaSLmfAsVDpgi4V+d3uAg7SAo2nM=,tag:Rxqp8KUN6vZOAGXVCuy10Q==,type:str]
kind: ENC[AES256_GCM,data:ZrMhVjv/,iv:C9IlmJ7QFA9WKuMPBIQqGc2LRFKwOz7lw2eE0NN2/E0=,tag:k/KGVrRZePaQLBI7I4ueyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uBFUGYvfs4OjZfr9c6Iqzq/0gxUsoBw=,iv:5DFIXihlvWGuD9UW/0Z8l/7MCz8SHgm+NeOxZM+lxXA=,tag:DhDnse4iqGFT/40+etl++Q==,type:str]
    namespace: ENC[AES256_GCM,data:2MGKB2A95NmjZV8=,iv:wsoNnVkYqjrbNMhpMatKDdt0suG6qoJYvNcI0v19pd8=,tag:8ltFpk8DKtYMnSRJ+CFT3g==,type:str]
type: ENC[AES256_GCM,data:x6N3ZpA9,iv:2a0+VdUfnWGVd//rNnxbzNdK8qm+vClYq36DjTYz+6E=,tag:Ky+FU/z1KLXSeT8ZbmeQFA==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gOPaHwKujy7FHeHeXfquA7GfzzAdk/gyRtJRHZiTq8knWhrEbyC0NUQ59duggTS7+uMxOipFdbImWuKs3dsUZDmsiOeGlJXxb8k=,iv:UPlXhz64aj/tVLNXMq7hf+hvFs0JRk6glGs5aH51mQs=,tag:MljBp26WUMoYYKQSPLGB5A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:M0A3wb9ZL8LhJA==,iv:dHnd0YHKVpxgBUy9QmwQ0oJWkjJvXF3QLzPc/4dPEbI=,tag:q6EBhhapiO0QjY+PSu2cPg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UwEJ3yaqJ8R0uw==,iv:VA110g5F6PsldDmKQLP3m8S15Q6PrxzTVAPBQYmWS80=,tag:+r97nw0adzjxcZUkbFYIFA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rxmw+PouN4TWYQ==,iv:aRKD7okcrYnc2hgBhrg0s0Ia3J8B2Xlfd35CuHsNREI=,tag:D2gRDxtSqFlaB0x0WJ4jdA==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:I7nCPtC+cw4Uk8u2klfYQpkDTnfxpWwm7i3RI+F/TIbwjtb5+UIxkeneuQori1LyPcLgsIdVexX3n8cx2V3LY8uNRWEc1MzptCNVG1MJ/MWVxTkNH5mU7asHC1GwS5aZ3vWC/fBLkFfaUKfeO3HC/Kr4LKrf8Qjik1nh2/i8F4c=,iv:Q5StceBlrrwzBkh/1eT2cwiyi3Ce0OEuPZiueaiXP6k=,tag:pRgymlAXB5yRYWVX1nyc2w==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/9EvLX+9Sk/D4kZqTlhIRtzTBDFTL2QapHQQ1bBrbCuPuB
            NumPA8dKioudS3KLkIEHWKGQYRY2lrSnlOY8tiq11eWw9mvS/LzaliO1HnC5MLjA
            qrCXvBwNIIJEq3x2/Vh8YeyvHehGkk321gKoZBrxzhVhrZ2/U4ktStMF1o/nYplZ
            /G+T+uivsojUhi0wwvhw+FmLYqggwQiE60ldZ7HOjNpJxGRuPZUzmq1QqdvIkHfv
            O2ELA7r3zuiRSV0cFJnDqDovtjTDMehqVSmj0Ck3dKwARIKJvZ8N3b8UAbchEUdX
            u9BICX05s9q6rSI6QAs490sTNHmQd158l++/eGkfvPKXXG9suIb2+nfRyUZwpH6e
            y/NnYphZNifYDCSEW5UqCBlB0ttKDDZw2TGm0oyzZvKRmdbEzIo6rSJEwTxSMWR7
            idVVbe6eybvGyEgkZqZ3e1Dh6ToRugUL0JTkUWil29z4NRHrNe5inS4i5JhtfGbg
            6FdbA0Jry/VjMexjTBwleFySdypvgZYdP6LNt0o9qQfHzeonnE9PLbSibKAjJbBk
            9XKaqlBO1Ti7ZQIAlyPHV+dpZBJrUNH30RCrMuYzE0EwOsBkR92I7q3EiJYdj+Su
            LDXcH8uzFEpvTbayaFjZySWX0Q+8o8zkfU9Y0J6wHJXY1CRNjGt/4aXxMdVDgOLU
            ZgEJAhALEdgzDxdlsMPySKDOG5CrsHnJwyDoaSNfPKP7uxJqvCq1jfPLAGNlEIdP
            A5+cFBNSw2uA/FMg65GH682MB9c9WkC2ZrwmnoQ+759QKekvgjVni908ycrLYBXo
            jGRZlk+MfA==
            =vNFf
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
