apiVersion: ENC[AES256_GCM,data:WPo=,iv:E4linw10LzzYd31Ot8zF5NWeJonXbNkQe9wOJu6ubPc=,tag:fXp1T1eICJ93SxqrqaKKUQ==,type:str]
kind: ENC[AES256_GCM,data:FkXd1Vpf,iv:p20sUVFhTSZXA9jej/4fxzrBHiXh73sPWoxYBYt75tY=,tag:e4qm85lxflfretfiOShteA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uKs6J/A7Cp69lQqpBxFwuEVlxw==,iv:8cLuAC8ixd+dNvHEGe73S4Ull3SXvSiMABbQ+lJVEYA=,tag:e+ZTIx579qEUOZvsVaNmVQ==,type:str]
    namespace: ENC[AES256_GCM,data:Y2MMYEYuEQcjoSZln2Y6Ltux60c=,iv:VjQz9j7hkwC6s32DntU4EE6BNxWf3kIf4Pw//4PbMRU=,tag:1rsMWUhg1Mpt/GRbRaKUxQ==,type:str]
type: ENC[AES256_GCM,data:DmC4u0aX,iv:yWej7wUZdtYzgb69khU7CxKFRWt5l+kDVCMzOoz/3RA=,tag:lH2zMIZ3JIADDj/qk/3oJw==,type:str]
stringData:
    jelly: ENC[AES256_GCM,data:AdF2AuZ1XcSf5zBcxZgzjmrudzEjtF+JL7UaV9hInzAM83LtHrQnllcfT5w=,iv:nS5j0yqNWn0C4pjKfR9eL0l/A4ePOhTy5b7KlUwuvNM=,tag:0n2M47w79guncI6lW/T8pQ==,type:str]
    monero: ENC[AES256_GCM,data:AsHnZc2j/z97MHKM8nxFG7oyrr6zT4BjG0IMgOyftjwlRWlocH9fuEPjk1s=,iv:GAuhHIzEvKo4awXlytipFvshxmyrsApkcBF83k1OZkI=,tag:BpUDIBuOKZSAf4IZ0+v90g==,type:str]
    snowflake: ENC[AES256_GCM,data:TjXtrhw+miAJfBeboZuMqERma144aVeV4n+rkRFEaAwQFRlnicaeGiVfk5c=,iv:/z3SpGtDoNn0Lv/+66A2yscuvmIdbchQxzybVZIlcb0=,tag:kk8he88mMDcPAw1iGDZbCg==,type:str]
    signal: ENC[AES256_GCM,data:izDS79m1bhlvui0NI9UPDzbv1pRWdBxUmWH5mu0InjQrrcb0hU76GoYagYc=,iv:7NjqKjRyF44/PpL4oBgS+odqKTlRHaYAJBDZao6rSz0=,tag:yNMe03Hju6UAA9EBL9/jPw==,type:str]
sops:
    lastmodified: "2026-09-15T17:00:50Z"
    mac: ENC[AES256_GCM,data:xPRgZJkFxsJnMaVpRAakjwnNa8lEhQnfvqocw9DQYmaUCVoizvz+kqWLf0mE4QprmyIPWm6mlFL90SzMQ5BKxK+TV1xkrjz9ckrRFdgqThSpFPHA25XtoxAoDJhdj5y3CS2QAHkKxZFsxUUSSpQMdy6ZaSWWVYxgROF9xW0D+hw=,iv:ihfKzPgSEfXez82v0xNxeRxUXnCAAtOorb9THKRDNio=,tag:8gGACEazqrHDVrTqWiV1zg==,type:str]
    pgp:
        - created_at: "2026-09-14T18:12:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAr43CRNSLRVA6sFTHgEtAVeXv3yjqBYSSmEwpCdVNS6fi
            QeFtBn/D1liEpSnXRBjQ7qLbr/wi0s6Ooo+2j9hJqe9TliMtEZao6PjaPe9BYQHu
            aaDmchbmKed/nsrbrtMqv13VLcSqnj0PoyI4g5oNLyidHTtDYBHVcC5mJQ1LZiQZ
            t8pvnpi9p3WeVIpzM1ktl3QUt6+Xqx8ddIgF8f7tLNjxLNsthwhMf7NA/FCYfC9p
            g4RsDycU7s1oyrX1xvlZjgDz5bFGzddljZJhCtlQCnSH6mDbDd9TT3WIjypNOy2O
            uxeqYvwOiUwq97I8em9I2YejgmKmqxjRj2lpIK1RpgwaOSHtmFltwod4ZZF9aiVW
            M5JUlIgy4NwxpUgrv4hxtrFHrYzy4NSDrrSy/bPIuXD0mYVJ/thkvnl8Z09Z0C7B
            Cy4id0rXufaxnZmqD6QuY0zbcKXNeQTI1x/Tljv8us+QKVirDm2D9ZtDFL6BPkLz
            iOwoexHE/jLG2ZNwSs1uDlTlvlJg/xkli58xdlKWobKYgZ3WlrAnfkN0ALyiqxkH
            llyZXit2Zzt+rFrgyubrNApMqU5XfobFHGCtwNXFy2LcwqpbrToRMRuqb6G0PkWE
            fXzl1Symqdb9KpitOOnBzJctEGfsy923seSBcdJISNf0r9JSJ+OOO8ktWT5/xv7U
            aAEJAhDm2SfxUISF7fx1cE7bvMf/7kn+evV+MhokGMmNT/7PIGSEoWBSOg6OCVAf
            lSNo3K73IsuvuiKPJ44w1L9LLE9Rwj8er3OP7DCuB+UiBYFmWRjUWrEtKaWhbLhY
            Hs2wMVOPT9Y1
            =YXXx
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
