apiVersion: ENC[AES256_GCM,data:yyA=,iv:GXnwLFrcOuZYzEbL5urqyZ6VInZvDRf1lArbQOJp8gQ=,tag:CZMeCW8VewOeIEAorUEupA==,type:str]
kind: ENC[AES256_GCM,data:QtlsS6Sk,iv:bBPY7yUf/NSDqRX3IaOYSvcM7+AHuXVptEY93q2IUIQ=,tag:CRDAiTxRcIVAZYc1Uwe5dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XxIno/JMDBNQhQOpnOferzSB,iv:u2QNmppCkuSqn8t/lUyq3SPpGXpSeP6NJJM8Z9+H2eA=,tag:0pDEHYfp3ee3vqYCy+xlmw==,type:str]
    namespace: ENC[AES256_GCM,data:Fe7S7qE=,iv:6anrTEr8ZpD8VP/B9XHpnzNFcLbQmqnMhCar/j1qdD4=,tag:A98hUSFiNHjRHC9i1AszQg==,type:str]
    labels:
        argocd.argoproj.io/instance: ENC[AES256_GCM,data:nT/48+o=,iv:kQxZ092OwRWr5grNCcNXhnvJ132183Xvh2ixt+knHcY=,tag:EI3/5Af38vHCno6a92jCyQ==,type:str]
type: ENC[AES256_GCM,data:mGZ7bkRz,iv:xyQz1k55WlKrj+cPrSFIRIeqEZnC3CUf6E9NGHu54CQ=,tag:ZsTUkBuzIh64C62RwnD/eA==,type:str]
stringData:
    EMAIL_HOST: ENC[AES256_GCM,data:hcPkAnDqZWtMmo/r1Q==,iv:OuVjvaWjRKqshnU5zMj1USPY1oG/aQJ0IqQRN2Nk7Vw=,tag:fvvBXJxV1/SzXTGd4sFqIg==,type:str]
    EMAIL_HOST_USER: ENC[AES256_GCM,data:dEHJQOGDos0IW5DIxZgHtHNyRvvO1EytQIU=,iv:m4y450ddR6m2BSV9xYueN+oj0OFsxYVnEss+Xht+O5Q=,tag:7e6AG9uNvxfYbPf9K32xpw==,type:str]
    EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:jgQCOUrRIGdMSxfa,iv:mL3p5DdMo04ljKUfwdZwRFD+PU57zj0/29dnJzIx8jM=,tag:lNSXzCDvyNsbLCj2pBjJ8g==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:ODYy,iv:Z1C3At6ERNzJB+kYn/Kuike5yurznyJELutw9+4faQY=,tag:Bu3pYQVcTxRXtM8xZplo/g==,type:str]
    EMAIL_USE_SSL: ENC[AES256_GCM,data:+g==,iv:WLJT1sJDfG6lYtsRpFOdvM2hz5Tpn4FFYv/Rruf1ths=,tag:eywqF9C9wll5IoIo9Oj4ew==,type:str]
    EMAIL_USE_TLS: ENC[AES256_GCM,data:YQ==,iv:YrERiLetJNpMyHNE/x+Dw/OUvETjB/5AcMoi2PMcnvk=,tag:EKf6CzX2vEkn7uvxr/1qjA==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:b1LG3WrC8H1Ya+6oIKR6Er8bsWke0Jzxa+w=,iv:TZL8LzCI6Rh1Bas2qedJe9BMlfmscM4X38mbJm0rwog=,tag:MyNIhahZYqR5khSoJIrVAw==,type:str]
    DEFAULT_FROM_EMAIL: ENC[AES256_GCM,data:W5MQ9xns3xvtZe8b7Zuyp91r75r8JGg6G/s=,iv:kxQV3YZWJVj1tPsXqCclPt/fXb7mZMWrwATzWtGKMwM=,tag:amKwsQkze3sjQdigeLMQIQ==,type:str]
    EMAIL_BACKEND: ENC[AES256_GCM,data:MdHHlAeZjA/lu1A6dVs2Q1TcxacLCJq7NNb7R/mB9CaNZLMGqQEdZSb7yA==,iv:Ad0rM3BuE0og8TnzILsLXFiYcq3a4PAod64hg4+2qIQ=,tag:ji5AVM7or4ahIIhVGTQV8w==,type:str]
sops:
    lastmodified: "2025-08-16T19:02:13Z"
    mac: ENC[AES256_GCM,data:WApabKdYtNr42XPY1ELthoBMrF2j5iXc8zNYgsZEUjXd2NMHKDVVK7CyPPxNUPxgq1deYTK2axo7T8xHrrgd4TqRsLZxVyASwuo3ejiDSXnPNh7FCYKxCRKzS/QDDxMCiyhBDLtzn/YMrQU5P8S7txeRobvwYvuE0vU33YzmLCY=,iv:joBv1uN96STiu7VAS2Kh+moa0Yk8Qr2LQ2KKKE+yYGk=,tag:Xx2OtpjwBHu5qZx3afacvw==,type:str]
    pgp:
        - created_at: "2025-08-16T19:02:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ//Ynkn6fC7zDIGcSgc8ViqwS2e5hkoLOZ1Yi8nAZfMYcNQ
            KjmtJ+YxQt3Fz2/wuCyF4/LfPq0hktRARxJbiIR9eRdBevAc518B2a0PxrZBUGe2
            3C7r3dhP4FJ23+jsTXhBnJaFcUgooB8UX0bzWHWfEoJG49PzclGQXSP2XNZscgf0
            QviKGUJ9tUHQBIXVSQmjTLPeYzHRWfVgjX6SREwNTIOjedEFd3c8zOm01UkPoI/o
            vZFweF3eukMBRAKheCzXGZWG8+D4a2+fGhaJjL55uoLEeEZT0kmpOOFIeQD8zVSA
            amZQc5CYgypd58iBwChkoYaMle6G990pzFAmGPDeG3UHIQbmgAA/hyrOUq21rfKB
            JJC0mQqwhoAMMmZL5o5jus5fRAAy4kKw1dGlEzrCo5aksnu8zS7RZKNGd0fraoh3
            /QhypeZzlEI4LrtfkL/uu+hvHFLAbzCy5fwtGBtGzpxsdnNMdsLlh65LKSddEJbT
            3f4jRLTfVvI6CgDp9EnaDm7piiq50Qqj4CQBGJ2bo5K8VByL3l8bMquZWBXuRxAV
            UMm5mWVmIan71/Xcive+dVVQu5FA+8QmDBuCqymcJEnwS+JNgE2n/NFIVjb6ARb8
            38Z53WqUEX/nge+b+RxedP+WOfZ7giNCFIznX5L0zeIxOO8Y3MEOYJSnPor5t+/S
            XgEM6x8ddgc70KIc40Hp6bANvVx6m7pS4U8ky8RjNVdpbyhyAO6eNgoLw8xwaKWU
            WZG/GrVA6gFLWxhElV+i38M7KO+yCnSu8EFJTskh5KVsA3zxyl9AY8dp/r7e0w0=
            =89++
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
