# ArgoCD SOPS/ksops integration - Best Practice 2025
# Based on official ksops documentation and community recommendations

configs:
  params:
    # Enable Helm support and alpha plugins (including ksops) in Kustomize builds
    kustomize.buildOptions: "--enable-helm --enable-alpha-plugins --enable-exec"
    server.insecure: true

repoServer:
  env:
    - name: XDG_CONFIG_HOME
      value: /home/argocd/.config
    - name: SOPS_GNUPGHOME
      value: /home/argocd/.gnupg
    - name: GNUPGHOME
      value: /home/argocd/.gnupg
    
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: gnupg-home
      emptyDir: {}
    - name: sops-gpg
      secret:
        secretName: sops-gpg
        
  volumeMounts:
    # Mount custom tools to standard bin location
    - name: custom-tools
      mountPath: /usr/local/bin/ksops
      subPath: ksops
    - name: custom-tools
      mountPath: /usr/local/bin/kustomize
      subPath: kustomize
    - name: custom-tools
      mountPath: /usr/local/bin/sops
      subPath: sops
    - name: gnupg-home
      mountPath: /home/argocd/.gnupg
      
  initContainers:
    # Install ksops and kustomize from official image
    - name: install-ksops
      image: viaductoss/ksops:v4.4.0
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Installing KSOPS toolchain..."
          # Copy binaries to custom-tools
          cp /usr/local/bin/ksops /custom-tools/ksops
          cp /usr/local/bin/kustomize /custom-tools/kustomize
          # ksops image includes sops
          cp /usr/local/bin/sops /custom-tools/sops
          # Set permissions
          chmod +x /custom-tools/*
          # Verify installations
          echo "Installed versions:"
          /custom-tools/ksops version || echo "ksops ready"
          /custom-tools/kustomize version
          /custom-tools/sops --version
          echo "KSOPS toolchain installation complete"
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        
    # Import GPG keys for SOPS decryption
    - name: import-gpg
      image: quay.io/argoproj/argocd:v3.1.3
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Setting up GPG..."
          export GNUPGHOME=/gnupg-home
          mkdir -p /gnupg-home
          chmod 700 /gnupg-home
          
          if [ -f /sops-gpg/sops.asc ]; then
            echo "Importing GPG key..."
            echo "use-agent" >> /gnupg-home/gpg.conf
            echo "pinentry-mode loopback" >> /gnupg-home/gpg.conf
            gpg --batch --import /sops-gpg/sops.asc 2>&1
            echo "GPG key imported successfully"
            gpg --list-secret-keys
          else
            echo "ERROR: No GPG key found at /sops-gpg/sops.asc"
            exit 1
          fi
      volumeMounts:
        - name: gnupg-home
          mountPath: /gnupg-home
        - name: sops-gpg
          mountPath: /sops-gpg
          readOnly: true
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true