{
 "title": "monerod",
 "tags": [ "monero" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Mainnet",
   "type": "stat",
   "description": "Whether the node is running against mainnet or not.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_mainnet", "legendFormat": "mainnet" }
   ]
  },
  {
   "title": "Synchronized",
   "type": "stat",
   "description": "Whether the node is fully in sync with the network or not.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_synchronized", "legendFormat": "mainnet" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "For how long this node has been up.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - monero_info_start_time_seconds",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Size of node's database on disk.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monero_info_database_size_bytes",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Amount of free space in the partition where the node's database is located at.",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_free_space_bytes", "legendFormat": "free space" }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "stat",
   "description": "Total amount of data sent and received by this node.",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    { "expr": "monero_net_rx_bytes", "legendFormat": "in" },
    { "expr": "monero_net_tx_bytes", "legendFormat": "out" }
   ]
  },
  {
   "title": "Height and Target",
   "type": "stat",
   "description": "Current chain's block height vs node's current height. When syncing, let's one quickly tell how far the node is from being synchronized with the network.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "monero_info_height", "legendFormat": "height" },
    { "expr": "monero_info_target_height > 0", "legendFormat": "target" }
   ]
  },
  {
   "title": "Height",
   "type": "timeseries",
   "description": "Node's current height",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "monero_info_height", "legendFormat": "height" },
    { "expr": "monero_info_target_height > 0", "legendFormat": "target" }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "For how long this node has been up.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "time() - monero_info_start_time_seconds",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "description": "Size of node's database on disk.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monero_info_database_size_bytes",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "description": "Total amount of data sent and received by this node.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "monero_net_rx_bytes", "legendFormat": "in" },
    { "expr": "monero_net_tx_bytes", "legendFormat": "out" }
   ]
  },
  {
   "title": "Free space",
   "type": "timeseries",
   "description": "Amount of free space in the partition where the node's database is located at.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "monero_info_free_space_bytes", "legendFormat": "free space" }
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "description": "Rate of data transmission in and out from this node (p2p and rpc).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(monero_net_rx_bytes[$__interval])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(monero_net_tx_bytes[$__interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Mempool Transactions (2m)",
   "type": "timeseries",
   "description": "Number of transactions in the transaction pool (mempool).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_transactions",
     "legendFormat": "mempool tx"
    }
   ]
  },
  {
   "title": "Mempool Bytes",
   "type": "timeseries",
   "description": "Total size of the transaction pool (mempool)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_size_bytes",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Mempool Fees (2m)",
   "type": "timeseries",
   "description": "Total amount of fees for the transactions in the transaction pool.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ɱ" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_fees_atomic / 1e12",
     "legendFormat": "fee"
    }
   ]
  },
  {
   "title": "Mining Difficulty",
   "type": "timeseries",
   "description": "Difficulty used for mining the last block",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "monero_lastblock_difficulty", "legendFormat": "size" }
   ]
  },
  {
   "title": "Mining Rewards",
   "type": "timeseries",
   "description": "Total block rewards granted to the miner of this block (transaction fees + block subsidy).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ɱ" } },
   "targets": [
    {
     "expr": "monero_lastblock_reward_atomic / 1e12",
     "legendFormat": "reward"
    }
   ]
  },
  {
   "title": "Transactions in Last Block",
   "type": "timeseries",
   "description": "Sum of inputs and outputs used in the last block's transactions.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "targets": [
    { "expr": "monero_lastblock_transactions", "legendFormat": "txs" }
   ]
  },
  {
   "title": "Peerlist Sizes",
   "type": "timeseries",
   "description": "Number of peers in each peer list.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monero_info_white_peerlist_size",
     "legendFormat": "white"
    },
    { "expr": "monero_info_grey_peerlist_size", "legendFormat": "grey" }
   ]
  },
  {
   "title": "Weird cases",
   "type": "timeseries",
   "description": "A couple of statistics that reveals weird scenarios found in the transaction pool.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monero_transaction_pool_double_spends > 0",
     "legendFormat": "double spends"
    },
    {
     "expr": "monero_transaction_pool_older_than_10m > 0",
     "legendFormat": "older than 10m"
    },
    {
     "expr": "monero_transaction_pool_failing_transactions > 0",
     "legendFormat": "failing transactions"
    },
    {
     "expr": "monero_transaction_pool_not_relayed > 0",
     "legendFormat": "not relayed"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "description": "Total size of the block",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "monero_lastblock_size_bytes", "legendFormat": "size" }
   ]
  },
  {
   "title": "RPC Connections",
   "type": "timeseries",
   "description": "Number of RPC connections being served.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "monero_info_rpc_connections", "legendFormat": "connections" }
   ]
  },
  {
   "title": "P2P Connections",
   "type": "timeseries",
   "description": "Number of connections based on their connection state.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monero_info_outgoing_connections",
     "legendFormat": "out"
    },
    {
     "expr": "monero_info_incoming_connections",
     "legendFormat": "in"
    }
   ]
  }
 ]
}