apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helm

helmCharts:
  - name: home-assistant
    releaseName: serf
    namespace: serf
    valuesFile: myvalues.yaml
