ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.0.1.13
  hosts:
    - host: home-assistant.talos.asandov.local
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: ha.asandov.local
      paths:
        - path: /
          pathType: ImplementationSpecific

configuration:
  trusted_proxies:
    - 10.0.0.0/8
