apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: twingate-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/twingate-op-connector.enc.yaml