apiVersion: ENC[AES256_GCM,data:vms=,iv:Bko7ZdnO1nBdx59ISn3daWjLB46CvNQZ5ci4BMhJtRw=,tag:6ZwkwmdrU/MznGZH+vdWgg==,type:str]
kind: ENC[AES256_GCM,data:XlxIZl6L,iv:2IqX6n23GQazNFjsKmRm3zoAbLF4rSFVwbumq0UmcJ0=,tag:9La6+nYMrKcoy5ztSIiWWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d1PLpFKTMteo9CL+Hut0CyMxg/dWTXRg,iv:QrQ9sLl7VQOtKkoxHGua2csja3+gC/5a7mq4ybBhgqE=,tag:QIFVJxgr/2DbWqfXpQf61Q==,type:str]
    namespace: ENC[AES256_GCM,data:PBLbA6KzCB/xy6hxVR1Epevh8n34IjaA,iv:WfFOdvOnUe61iY9swPjq+AJdBaEL2QYFH5tK8UBQpQI=,tag:zcg7M+fnEngnJwwbMMP67Q==,type:str]
type: ENC[AES256_GCM,data:BanHMeLJ,iv:5sYaSnAF6U82RgKMZUiM5+dWAkbKyMgINU7gOJsFaUE=,tag:XEbqzm3Q+66byQISR8oVRA==,type:str]
stringData:
    tunnelToken: ENC[AES256_GCM,data:Mm6BpJCdlvssjQqKRUNcCxG297fwpeCbIlVWrj/D4qeIleva5Nno0aLVSWNX1uVGj8jxBrVFObJRytQsYtXQWiXsqERrzn3gDLBjfckjyNKWUgpTEJ1Ijm9drPajXD6IgOW49OEdwje5oHAKNTauxPSJPNIXj53BvUCEKIuZBMQeEUzZuf7Wf2ScA1D6kzbApbRQHYZgP9MN5cIO7v3ksZ01CT3ohH7hGCG0c8x9nEEdyLOfh0MDEg==,iv:1gHINAePFm2Cjflnar9Yd+PM+YutHQtS7QoB/Q2PU+c=,tag:vI35E5L5Wokd18OBV3cgPA==,type:str]
sops:
    lastmodified: "2026-04-21T20:19:29Z"
    mac: ENC[AES256_GCM,data:mbdQkp3ByqEPDZbmr0FxpiL+FH6UT/w7lx0kHnGhKHAsM8WLbmH7lkQcjmvKDBzJEl8k77lTRJW5gBjyAMh4sak/eqfZ6x2yr1axnknCgK4XyQqHegGfOm0Bkp7lqlryPf42W2qbyCg1pgvXcHtf3syBVpqQKz/9Yc4plHNCDrg=,iv:s6d7g+zUtTCzwFdN56OS1WqbLaB5Huel3UICcsipOBk=,tag:4RsEX0iu97BlfEz0z8UUkA==,type:str]
    pgp:
        - created_at: "2026-04-21T18:55:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//QhdI1CQOW5Z5VwRIlSrzZnRpeo318KVW+UP2SK4J4klQ
            3LprVBr566du53Pu1l3kf5dlhq2AzGW90zUd/3JQL2R6uAgbyOamx1foUe+sg9Ow
            AbEsOQstVPLBNOy891/62fIb3NElPe6Kp4g2hE57J6csEx88szmmvNj5r2J3p7Pw
            zy+5gT8ww0G0PTG6zNJf4fynjxCbtYAG2Fb7LpXRUeTeaQVAFhukdtbet2ly2/be
            quNQ81cph/sa5IhJPxuE8GTQNJTwtups+A1fnbA6ZUQHKlaq0MJRit7+f18LQocN
            Nm9RaKK1XxZMKvLpW20VIFLj4dRWTTg2Hc3s12LSpQJJt0B5HmB8yfvCWgRDX4xM
            kcZCgDqb44nJXXAkvTpEx0Rp4jXR+YC4txrCro2CrfD7PvOua7WLOZrRwCdOIVjs
            u2OYi4qcd1NT805bpTmbyerDql6iLZKRNdiiHdqgMzgKhroL/Sg51cdmYts5kp4B
            CZohL5JJugO8kn/4my78OA+NmqCWK5r9fLCsK0T6ZL5CgBoPXInZeE5lkMYHFSAH
            gq0tvgoSlpQdwf7p35xO2tcDqPEyy6N4VocJ3TXgwgtqvgKth3YQBgifcUsD0bE1
            4aQh2CdBBQLCDx6Nb/qy83R/TSyW3aS1JDilE25+GE8TM5fdUXKW7P/Wn5WHAcfU
            aAEJAhCUtaIwdtMfXGmj2SEh+hyiTfLE/Qlpwrm5DijBZ7AVn4lvtaG0TvW5uARl
            uujNP4h0m4CE8Fcg/gnbN/WQ3oPMsag+DlLuS4zA/AbCAyqHbkZfoHutE3m8xh1Q
            PJYeD3J0Q6Cj
            =GKsd
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
