apiVersion: ENC[AES256_GCM,data:/BY=,iv:I3YfB/a/P7wqbS7C6EyDZYdNnuUVxsNPOEpHvSb0sOA=,tag:JhfW3Jf3inDuKSRWq8Qdvw==,type:str]
kind: ENC[AES256_GCM,data:9O+iGNmT,iv:PWioL4aBkKjbCZlEXq6sSNpW36j1tWzFhT+sZQTGX10=,tag:cB5nwF+Ov/koLli74bP8jA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JMwY0bp8fROvNQrn+5wGiv3T9NQ=,iv:U63rbSqac0xhjdNpUQZt6uq7qSXoYoYfTozav2GAY4g=,tag:7R/5v9Ix7M1cb2UoCVhrZQ==,type:str]
    namespace: ENC[AES256_GCM,data:9ZoXn11bH9Ms/44j67UxriHCouw=,iv:giwLVcIOXBoaOm0MNZYYszOCaJfNlnPO2VQOtx5CSGQ=,tag:jvI4Da6owRaCMjZBr7COSQ==,type:str]
type: ENC[AES256_GCM,data:JrM7ZwCz,iv:mATP5OL9ELQhKLmWk2rzuQXdcppeLo/qJ9K0XXzv+DA=,tag:dQy9PNPoyCrXNtlsJKVfWA==,type:str]
stringData:
    tunnelToken: ENC[AES256_GCM,data:uYsJJlaUmvjBwVxmwz+bLK4Tdd2HGhEBvLEptyDdZ6LS7GgkJkObUybVgty/tlaP/jNjxWq0fQSu3qIswJ4AjmGldZGHKOBGBjB46ulsRF/TUg001iTxez5OrfAABNOM1+17H0OCUl90xz81Ikj8jRW7R6aSz9zGSwMpUraQiaxsOrXdPDgEt5oZ8sAFZCV2lOY0YVmzpjJPgeQPSaLHTmM87tXgrGdhbYXtT8fYN5eFEaEBbPWZSw==,iv:hoFQC+F6X+u0hkaJJk2NqrsEz53FiQ2dgxmXs7AhNDA=,tag:/iKqQ42LAH/sbi40jcBgfg==,type:str]
sops:
    lastmodified: "2026-04-21T18:47:11Z"
    mac: ENC[AES256_GCM,data:uBO+doKHBMxr+kgHcgrC2J66VklBCZvb0caKvybmKH1bRDPXKOy1THwl4MLtvzWlXdjQca10VQlt0XVoLlIhLFd9HAdl9XCUBhMVQxJmSdJVVKxvR02ZY4QA8rdG5afUy2v2rxcSfgAxRrSl9NHkgWGwMJ3hIInj79hjqwCJyD4=,iv:zrnmcGbO4R6umP8ArgA4e603iiWJPMB15vcqqfdDY/M=,tag:bWYMXx/wcf426NvpFJH21w==,type:str]
    pgp:
        - created_at: "2026-04-21T18:47:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//YRizg8wBCojZi2GlFl740bOEjOyLYCqFHjA8E15ykaK7
            6mJ8tx1ycZrl7pPC8uzf4MVKW1B5W+3ExTjRraYNesBmV/VWd2ffQikfN5QpqU6e
            AZqV6oLTtLdz/sKFGS+8dG47OgKmwPrTfVQhx3D98vpkGwoS88HO9p9cAwMW6IoO
            66CjUr2kcvEr5FUQpUaqub5RdXBVDfdkvgNNEsUFEhBhIxDZc8DlY0uUm9Z2h9me
            HzsxYZBHKgbgDa8YodHNXPIXhaijNobWYnfS/g0UpYHYmtsEP7B0EEhG+AWyc7cr
            oJB61XQYcCn912sF7JZFvlZ7LqcP8kpCCC5+ng9xJqEhbs7FDoQxxjLkho5Cft73
            3lJ/Z2ln0HpqxevUhIiXmBCz8L/TTCQPRld4weEw3s/kAWQvePZz2Ff1J6eJ1rWW
            d9p5EMu/ar1JR/oM6c4fbqgq+mSbgTVTE6GqJP/R/AnEb/QcdcGVxgQByXWMpQAv
            FvGWcB5Mm4Ed0yxYsQLrOPjcJGSYedtdD2zm0bKJ4s3uiTONHJrYO8wKhIC2qF6L
            dR67fc5erc+Q2jKxyaDaAC88RV3IxaWPIexOb8HMChCkPtP6zkBBWEJ17UFzcQgo
            rrNhp5kMGO6u4hsQwdK8FPFsWcomkpockZa5V55Dz0nRFM0z2rpCdRYccs6ZIrnU
            aAEJAhBX3ighl8wwQnkBz6HVMhtOG7nGBLDv0zhn/tgE8XhX/KuBMHIGMgDEGAe+
            Kadb8MPYOBR4mvvHvWl46NkEwFQfo/L0xhn2W6wVWFJw7fjOFxEHs1Fw+7fI/ALk
            j6vlrw+n/vKT
            =OgA3
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
