apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: talos
spec:
  endpoints:
  - dnsName: truenas.asandov.local
    recordType: A
    targets:
    - 10.0.1.14
  - dnsName: talos.asandov.local
    recordTTL: 180
    recordType: A
    targets:
    - 10.0.1.17
  - dnsName: talos-kingdel.asandov.local
    recordTTL: 180
    recordType: A
    targets:
    - 10.0.1.13
  - dnsName: talos-gk4-f48.asandov.local
    recordTTL: 180
    recordType: A
    targets:
    - 10.0.1.28
    # Provider specific configurations are set like an annotation would on other sources
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/hostname
        value: "true"
