apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helm
helmCharts:
  - name: external-dns
    releaseName: opnsense-dns
    namespace: external-dns
    valuesFile: myvalues.yaml

resources:
  - dns-overrides.yaml

# generators:
#   - secrets-generator.yaml
# Secret applied manually
