apiVersion: ENC[AES256_GCM,data:2z0=,iv:4hzfAD7zm4HhaRu4zDvirODna5UQsc+iQ+DF9DNas4I=,tag:IUozSm+iOJ6GMfs0WQJdOQ==,type:str]
kind: ENC[AES256_GCM,data:Bz7cP/su,iv:3ROjO3ByvpYuFowGAGH+rNhH5yhh36rHyHKEzcs424I=,tag:r9Cb8vT1K1aQTyf8U81R6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0UM8hnoVmjj3yq74i5HLUCe2ZvM=,iv:Ps07xlFfHFqgmOMhpGfnL9fQzYqRnBJ5j5+WZ4+7ASg=,tag:SlSg14kx/TCcBDpXCNghSQ==,type:str]
    namespace: ENC[AES256_GCM,data:SJcu0fHelP4=,iv:UMj5Fp9xYfX2gfPljPRjLGV2SEmk48uIW/Jr8l4T8lI=,tag:aTothgzOVrVV4wIZZyxpWQ==,type:str]
type: ENC[AES256_GCM,data:rRnkXvuu,iv:aqicSfJkjVcgRyjKkLiK23tQ3y5sT/OeV5b021/+AZ0=,tag:z9oOEJS2cYrUnZJq+1xziQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4md1oThfjvRsQXrYzbI4pkYnCI85+troApYmlRf3YFLbfyzQi+VBJqg2TYKFszMP5piIPUivfeDIyrBbEPpalg99xburmZU=,iv:7le5Yv+I75zLhuHFHL/q9xPqtYOdig/s2VJofIRrAOU=,tag:qz2KwraGki5HpxMsLtls1w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:7Qu2C7PDnfW/fQ==,iv:Ha5NAHYHcT/5hhwlGBKHdTPGiMYBQRMvTKEGaI3ottA=,tag:3ZVuqFHYe2NhvlhFg/c+iw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:x+k7ChKUfCy/0g==,iv:BpIuRy48uMMoZosa7hAZVD0E1U/qutYeutTaQnL6Thg=,tag:Q9QRlIgQf6y3NvbIjzhIkQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R8hqTt0uv0u9bw==,iv:xJ/dNVnJK/wg8XEX1TxlDfaYcxaMicc/63yzX5Mg/ds=,tag:ic6KcTlW1t3xXPUl1bg/3w==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:1bdHVuhKwBpcuCQHvsXj/4OOuMCDOUG7erG2UyPCp1DsvpkBFnbkfp76riIMEbQwGzpDxi5IVXQn5pK4/FV4/z4mvHIOGekuZf4+kXBhq0LET2RYsOpYFmTVsELq0wes3fUBz7txCsp1GKD3g7cFuj9zDFrQ9lHgprEvA+c7zMc=,iv:ga/wp4zUOO1VpSn/W5ew1xwviJCCANlE5dtanB5ySjI=,tag:mWhqM0G27f6hYKzVzrhs7w==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAx3YT4Whz9cnLl2Tf2KI+l5eIvgjX9b+LU+VAcSJhKa3Z
            qyOp6I2nLcqJWhVDf5t3JQpBzmEGuq7aNYsMgG03wsFWU11/Lc46Gcb8ErJWvbdl
            dpdfKh9lc3loPwDFdtXmiuq8/kAT6HtMhqJaAhe7mZEwRY40YKl73yTDaE5SjyBH
            jdXrgDjWEORWoWMdVCyLve+dUvT9cQyBrkDBEw9IPmWrlyGdI+Lz4Y1YqPVRKfcY
            vCea+luGX1n11BxLEf52lTJemfk0cpHJ/06xvJXXBZcoLKr75hKZVhPkzk0ShJz5
            L3PbEr6L1XJzw6xD/A4/qAVVyjRDm0U/L+3wDNjGwLSmIeBSYrSoaFYIIOaJJKrH
            S6Emi5pIu1RlvPMJqXVlobkqknMvaT9t9yk3unCIz7qEhoQ46uoRjUG1rrWJigxl
            8EaawfXctlQKTZ/2iXnGfN1tQSMgaYWZHM/EtZrDJZH63uJLZei4F9+RnqFS5OXp
            wplf5BmAAC9UlatRhkgy2F2T/waaP7NM4AxDW/EYl60uce2SyALsUIBB5iyJb6TR
            fg4XBmLqnXt6xwjH8xbaNyZKASfUZwYHBp9UL+cfkt7aAiWaY6N4OpoodP/sIUFa
            LS1N+UUjaUqzIdUKVAfq7IMoAFjmwiti53TnNUMP8NhsWsaltsWnd/1C5K4XtnLU
            aAEJAhBU3XsrlZ32toxXcoGr2/nO+VzOadTpwKQd3DaV82Y3ouDBX/smLPwJVg08
            5N3KjWQdYuPVDwFjeNb5SWxeFGCACNVRphfaaU5vbc2DVMKXsYUTy2nRQc+vOpFv
            2vJ6B46an7Q8
            =OcTs
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
