apiVersion: ENC[AES256_GCM,data:d8U=,iv:6C3yhZKFvJU+8JsVRQ8Qgpk9ZmuVme2eKhlbplrOz8A=,tag:DE1n/Vt3hEQGkMsBd87PIA==,type:str]
kind: ENC[AES256_GCM,data:YS36bDnK,iv:+1eVc8h3DWJ8chf8sHGqcQsBdstjGLf4K7bij3fprPM=,tag:23yqfSINEprIk+nQTkIIYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IsarYEfpcBVitZncb4Jxx1qBI+NORrUB,iv:tHvOv//qCrw3aXnvtZ9jD8hVhVSy9DG0Jgs9K9PkEcY=,tag:OLSBgDO2a6gz07QAzbmMJw==,type:str]
    namespace: ENC[AES256_GCM,data:0HfsPsoQfL0=,iv:r4J5QEVIkwURc06l9drHpj++ImumgtOSgtKv/AO0+b4=,tag:93IH8BqDCkkUBYOXVLxJMw==,type:str]
type: ENC[AES256_GCM,data:xf4e5VVv,iv:OhZGKuSjmmbbkLEGWCyZnQmO6aF04EM2uBHdYlsIDaM=,tag:Ljr0hBqPNp9EHuxJUvUh0Q==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:NIDX8XAypJN9Iev2lRQVhJs/yy5r2yUJnuY8n0/A0IQR+21XqBhTIPEuwwDxO4jxb+B35z/qaWVtWGN18Oa9/qyx/uFmlDYwsNIt,iv:VkegoJ90D/NGfcvZXQ/DAPphygxhmNBjaSBDbb5bXM0=,tag:uhA1zeyRXRJomoXzLmoiPg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:EYXWjdLaCV83LA==,iv:JUCGgjQvNJEBl1YYakfS5Y7AdfdY1aw1jw44p/0OOQk=,tag:+6aLjt69zxOUDsJ1lkWj/Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bNTtDBupHWg56Q==,iv:xdkA2b8rK5fSpqeZ4Y6gqBFx63eTRjH60Du/tDUAwpE=,tag:0rRdzMVzCJFii4ZRPrbwEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JWp/r6HFw8C7kA==,iv:10ewh2UIOKsmNWPpH9rGV7NnQCYpljeubAft2LLlJ5k=,tag:OGAtl60B4dMUshy6if2waA==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:U0C5aKSODK2zzYbPqsV8pVyQ73HkVr/+W8Yceso5irjoPwE84URZDWe3CV2UG8EWzHUQ29AW4dHjQ57EK7Xpu6IbGEa59Iqh/zcRB5IrsNwNl8YXarauMF7z0D5kLxK7aAZY2vqYiR6umwVj4sRk/RqPb6zOh0VKf9FXpl852aY=,iv:5LMblEnMr90pD1efWCc8E0D91/iFWb7qOuIUqfxJ980=,tag:U6fSvIcZ8AQZK4ota7EA8A==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//QKrBiZzMtIOb2YSexvM4jnoHpV6h0S3aFMa6XrBR104a
            my6hbeDyL1e0fEtwjoBIYK+5hD6TDtiEpgBtZ87q5gyEbM1zjEVSENJZrge+u8aL
            pdPTaakyJM/WkT+Iycm+mvJ2uj0Q+lUPSBCZvWnHBwy/sa84W2LHQ8bSA0mqrNT5
            hNIGwIt/jKwb45PLsT3+Bzn2fYPSTh066DO/MNJP7xBIH47GhfrofI7TIJKev6gS
            YWL+eS9EpR8otrQ6Bwqm8R6zIX9QZoh/k/sh3m/Ykpca6E6r5g9AQmct2XRqVieW
            SocxJPqGwi7nCwRT00z1Lor7APY4sf1QLjhVd+S4FFlVAzONJaYgsJqxYgNkIe6r
            WD8YOZKEO4f7WyaB1uVGYG2Fs+S+L8ubGe25W50uvn7dUWk88lgxYRlJQv7J7qZw
            bX+BzY6gvygX0hVzLREqJUv7IioIckVIiHMlcW7Y1nAwJ1xFvyBwhttPSE7Lf78a
            BZE+h3sFv46RD4a949AF+EFqAt4gm+BWzsDlgSjsB29hRu1S9a2CIcQevmEvaCmc
            fdeBU687tTUczpvrg+Eqqt8Agwmswu3WZA4aE4tD10MS+JvL1+fT0k6wAdOMwvAH
            d39JKkplEHPg1HkdIWop9i9Nfl0zj/LIXb0QypBbNenT7YfAQZGDrZHk3qdQuavU
            aAEJAhBTFKkXdvUK/bILWgwd457imKwDGnx6oddQZFWw8VQHwEDwNB3hUyowOOWS
            Xl5xl+c9xLFrYZoHyYAU5MZErzY7SMHg+9ErOMmEukZf9HlEuFtuZAu0frzrIMsT
            lA5lYoBXIuEc
            =E4tS
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
