apiVersion: ENC[AES256_GCM,data:tYM=,iv:rHV8D9/Ea4BZGSq+hlsIw3FDqivppD1hTqdYblRhSUo=,tag:1PIh8TMOVRYYsfqtjP0Hqw==,type:str]
kind: ENC[AES256_GCM,data:XkNoCAmB,iv:ZevjDe7gCjzh0prPuBlW1qzaRbDTob5hwR2qc6iPb2c=,tag:jHCBuNVdjPpaW5+WJxOwfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:43kFU5H6x/droIRG6VTG,iv:BoOmdtc0qTuqk/2fSv+c2N+Qb7xCbKQpJ9LWZ+Fz1aM=,tag:S2hRLyUu/WQy4fNz58YgZQ==,type:str]
    namespace: ENC[AES256_GCM,data:7gdJqS2Q010=,iv:6Fwn1hAfzjseGK+HVBqx6rd5ucB1qa+hDGfxyZaxB34=,tag:JNsBStVu2MtajRfxprjfxQ==,type:str]
type: ENC[AES256_GCM,data:ppGwVxOc,iv:4e8nZA53e+SPFssdf5i9M+iC88TDyaKqwVF55n+Q758=,tag:yQeWwUT8vk0zWWz9Lc7XhA==,type:str]
stringData:
    apiKey: ENC[AES256_GCM,data:C8w8pmI2XPx5MFQfushV+Kh9xOKCR9Xj3Rk+LBr1wSM=,iv:YeYsJaJpBfMLafKOcSR4EtjtaK3l0DzjaKADv4LhujE=,tag:RLMSHNf+8pYH7d1XdlHIDQ==,type:str]
sops:
    lastmodified: "2026-07-31T02:09:27Z"
    mac: ENC[AES256_GCM,data:7XRubKud3kbErkWe+Zp6M3JPRvMootmTD36GwznvIMB8Ewiftf53vqaZNeeBRV/itXNKnkvcQMQgNWHjMzlinZEhe5EJ32pT2hX/KIv1I1n0z6FYsPuzMVk8zUxMgxkyhiDIkQxyR+T9UZQjNO0cfhuGNMXMm142cpOuFdMyG1E=,iv:tYXRvHSDMMTQfEMOMsZEjsghWAuYFZ17L21v/qMtnwE=,tag:oPW5uEz06kJQoSR4HvbcVA==,type:str]
    pgp:
        - created_at: "2026-07-31T02:09:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/9E0jBhfTsTTr3phjQG5r1es+5v2GL/isb0DZPlFIlVH0m
            FeWU2nmsH5f5lLBCg0KBx261G18tw4IqRZKENmrSfMW6L6amJ4HRyfTMtgmnBR6C
            e+ywPtOoTGaNYNvrr3H1uQRwTr84oGIdiUiBU6N6XOz0IarbUZ2vGjaHEwFNptAQ
            D2KjWUQGMLvYs4uGFP//FqZQXCE7Umh3727DLZURZ5OeyNQ6cBhDLaS5ZPikX+Tp
            eW5Ojmy/udU/riq6JUVE7T1XQcYXkX3vNACW3EwIsU3EXIMKggeqkt65iYg1+ZNC
            7ldEUXnrYoyhks6sZsHRqJonDvmjSsw8MCbHwHpJYqPnHgGztgmmvUtOtm7ka5H3
            QoOqTTxhK7Kt/8vKTdPggbJgBSKSeAGjYMT/R0DZaRPpHILok1/rYyAaoMDb+MT6
            Ru/3LPDxAokcMvvv2aopE4hvJn1JU61yK+UaPuVzMctIesFVbdqoiTjAP4WsU1cv
            FH3p8IDhwgtnqo3+wBYEerIvR7usvLA5Wuh/9ZjN3LvKEBNHm+pfT4rcpb+ToupN
            29eq5P6SHi4Z/VCM0Y4cG/3G/Qf1UIRmiCASSoZy6vmi5tfqMkpZRZaUeNiUkn3J
            WaQxY9gpiB39GredK3W8eqDxJ3VsVtYfF/eZ/II1aAJ8/4aErkChuZgeSMknNmDU
            aAEJAhAxKm4ebBrCgnyBBXF3kYZkz/21fqOdHu1pP7w/hDcqgsS7I3J88fNfJVSa
            TGmEs+bpGrJjB8HHdqwhBXe9hj6w3S1U9Gu/G3Z5KumlO31OjI6Ln6hnvuIZREf2
            UY3bGgyrySwS
            =j726
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
