apiVersion: ENC[AES256_GCM,data:x/Y=,iv:8vzabf9uMFnCUrJVx/e1YIhqiaxgZJVN28ipzkxyqS8=,tag:5ueRv1WjXM/GcYDwkrrwPw==,type:str]
kind: ENC[AES256_GCM,data:3TbnhSip,iv:TCMVodWbcOOazZRVilXgiC3PBxlGXSva0eQPHh2jWp4=,tag:bKCBZbS1+534r4iyq5Jf0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KRTI+0mWVZ9vh9B1kmhLOdULj6MtIw==,iv:qpPmV+RCbasyT0XIKyY8U3lWL6XlL+O5zqxw6z0OJX0=,tag:hsORPEnCa2L53GGIil70+g==,type:str]
    namespace: ENC[AES256_GCM,data:/XWDyZLbv0U=,iv:ex5CJg5zdC52WM+uR88CSDqohJAwni/SF86Fd6FEauU=,tag:aFOlPs5VdYWX90jXB84z4g==,type:str]
type: ENC[AES256_GCM,data:+VWZkNRN,iv:44Adcqg4awKwICfLaETJxZcK+BgE7lp/Feb2NYRfi+Q=,tag:AE5S29bPwa5LNx3PotlEsw==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:DDaOHGxxK0uJxjje1V/AdjGuKehJNL4wXNKu5ZS7nQuLlYqeyAglnl9axC5Nl4iiso9hrGAObTTCi4KoZi3ks4BFi6htlc3Ajw==,iv:7rnIieZk7mB0W8Z8Jam2+YbjsyrqrTssRV8VpcJsJGw=,tag:lVKv+w4l73isdVzyoq0bng==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Jutkr5EHYec89w==,iv:Uqhv0KYEZ0HgPxon6wCuD33aPYSAdtEkGWeXW2flqGk=,tag:GBad4ritP8+4aVTYqnkFrQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:v6fNaEwrrWpogQ==,iv:kw//ou3/3hr4pXcAwU7aqlg+lA5xh8/TZqtHPl+dDd0=,tag:+f1VdBdHfMeTuVhfExIWqw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VHqNaQAsVgrTUg==,iv:atxKsjVw+xkJkuiqXWaPJ5nghZZSnbDAbkmLLVyFE14=,tag:2RD0wQ/vLfn98RazAi6Ddw==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:A1RL9/LedIdjfnSMOR/HWkWgwjdtChKPPVIWVMGlaNBTlRsqOxWdt/lSuyJPuEyQqIZxtfExgew9L/3B8AxVLBzYWK82oLDKEZohJbbzdX3dPeSfHGmMzTwq7QxfqbW1pnsXR6AfrNg0MnwPNPn/i+/tpgFIuSO8/n4qNguni0k=,iv:msKI2Mu3OYv/lmuDg4/+8RR2VpfinLU9MZEdx1JrdLk=,tag:idCOGKgOFn6Hw8KRePDvBA==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAxGV1xiGt+q6vr9ki70QGigOv/RPsaTOhf8SyEzlrKgoQ
            u2/Mmm2AGkkc/Yv261QbMXPabJFbWcarUP/cBgybKRU1RAtQiX8aN05CUaOpgrKp
            dC9nkurcipQeEQB/Y5ArBwxeflPy5KlMCrzUokoHVmShPQeqnKn97XHWW+XuQKoT
            A+YY2wnnUdVQ2tJSeorm4pucr8GNErd4bdGg59nGOCcRtMLibxEFlz25Ztqnvunr
            JlVDY0X9fV3/TfZljidVejOLZzR538iqNcYrd+Fih5W417TvT5ZuP8bkENEqTl4G
            J4AO79ckUtFpceGCtRVVzYkYwFSzpHYerAEtVy4RLeNJPUYHl75WOY82MfKkKfUE
            xOSjK8KTJ+e/q0+YlTxinL+gKYXtA+YYcObQZ7QWWY+AJfq9dotB/6ADmJcByQo8
            R4whkGD+BUCRcbLZXPSyP0EtidBtzTEQpm+TLfm6vpNX3PMHfcle0zpwE1Wtukj+
            R4PtOktppFK5KOt8E17/qYgtlpVPAQ7dQCf32a+X8CWAWk5IYMxZaNHioREdpRN5
            vw9n+KaXHm5P1rRhBYmS9BCHP6WH1l2/hoiVvoalIwuXHmezGx3O0q5GSKvqSA0e
            9aRatzMWtoelQnZa7lD88hm398N6s/OjODjHmkUFNhUTuvaDdHs0QfVdD/rn8u7U
            ZgEJAhAnc92krzSAVt/ECpOnlgjNwU2jRxI2KJ/EPtrFoHpMgygRqKJDrpR9orx3
            mXdycxkIvuP2TWeztDoyIVhbuUpmLa/tr4VT+hkYPdTA4PdAIuA+m4Sq6rBeTlc8
            hnNKZ6KFKA==
            =vkmU
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
