apiVersion: ENC[AES256_GCM,data:Ooc=,iv:0bvzuQdec4pBxOujMq+hq0bSAaQb/CyXZLdbSiKL14Q=,tag:L2doT8pnqf36VCE5tZ8EKw==,type:str]
kind: ENC[AES256_GCM,data:AvhGiHeG,iv:D+iBcyl9cMqFdyNJY5+85o6LZKrghc3fg1eRo8cnKYE=,tag:+RInsX4pIgt4YJ09S46gtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aVsXOGygHxGEObQSQ8pFjFRqKy4=,iv:VLaJtvmYXtbxWrpq16tOac8LHeMfHsqrksUL+97XcZs=,tag:P7XP7If199gWSZFZ7lYcrA==,type:str]
    namespace: ENC[AES256_GCM,data:euecdd/8TJ8=,iv:7B/6IKmGUO523olGG8pafk6qi7O40Zqfin1h+sOQzik=,tag:WXwsWx5qw9IiY2MNxSD4ag==,type:str]
type: ENC[AES256_GCM,data:PmXdrY6K,iv:KCAm7wJRtC8NHK0Vhkfh7Q0Pf5MJ9er+kEiDGL961Rw=,tag:f4gMeczUJyPIUh23yvI7BA==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:3XwmrXhWvLjLr9DurPLYxkhzJunhcvUov7QvrOZP13fub+LQTQWSWWatzbRRSrPn+IG8GQcNnxoLhSKdDxMsNnN+2NffivA=,iv:yfs/QXxmR05VRBci07CzpeAzeKGldR7aOyt5EPI6PKE=,tag:eZ3mZ97lshZtQYpsnNF9/w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qfI77VOKQvaTIQ==,iv:+ZFzvgp88IBFFnhA/illuDyrQGSL20PqA+VvMo+u830=,tag:5ssuFVRFCbEY0cLkaOTFGw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8h/1x/XFbehALg==,iv:81LHHdtItiRcQCKc57a6G2jLT5bLphfZ5qq6MyStPmY=,tag:2FHYoTmb5x+tl95jFcamfw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0MT7TsyRiylI9A==,iv:kXbom0rCtb08cI9d/EZRPDRBvtZP2IbPByM03qNK+4A=,tag:iXI29E5oGwkibkY9bOaOiQ==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:cC1E8OfnGnORQ/3qoYsn7wPOI3ghHeRoAyC+BC/SUAGPBUlbf4UbdFKTodPklSCwxbFJZETOLabpgBzUEjqJE4IuZ3UDgWIl/FV6MQ1+OLijwFb4Yx14bvbBURpbc0GRSzOqzy+TrwuLBB1LliXpj3cBfN8AYry8xmJV5mmur0w=,iv:twz1Anfgf11ATz2K8LgfiAT1GfVisFygWrNk5GxCkR0=,tag:MjjWuCTNqD/N+8FGK7uOgQ==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/+LeqVVwV4SfwWUq1xtwr/R0Jllm1JzoGOaQNgwdbVBxTd
            VpqT/3PPL9AWNZv0bs1eA1XsN1z9Cf4lVn81UVvDou+EiqIhLWPq7XtdL3qPZ4Gk
            oWFtEe+1LtMKU4bMtJgBdR0SyznRDcwPC0pKUvhXgQkriqIJ92qw3EoIEH/j9I7f
            cInWqtv97DgLFO1obLLjqPgE7KcmK4HLFWM4bchrSfSmbs1uhBiuqk3kC5fX9Wlj
            l4LqmXB7Dfv0D9cWlCAeFcYZaKVOHodya2wJblu4m7xIdFE7gxM3AQ9cSlo7Jgw9
            UQb/6Jzc0kqZi5GZf49k9CnzsLPh3VmxqGYgguoipYVv6lpOnR+fX9siU/+YY8AY
            sYDlKVUYTyFLWq/qBV6oTOud5muYNOimS6NZ/0Q27Xc/imc9AOIV9wfIAvtn06Zl
            05CiXV8Hodpd4SfcjPFUVjKWrXetW2k0SjXLF7zcG5FhKBpiv28ygJmasB7ljrAL
            G09ealefuyoIHPQFMxxWFpf1IUO0uD5/vp4KVjigIaUfHVucu09EpFYHcqXntGNv
            QhkqyJMXIFpSLRonS+uXcWex9ZqVtbTMMTs8HHrS4BijgXP3v8yx7ds8imwlMo0Q
            8zv2OdILa3d01LwUegFO0T78IdgtKTuz8+Yble/bvI6M0D5ZZcILYh2SLyRFaNnU
            aAEJAhBh3ZrKUfzaAclXQrDTBYeZ60Gyb7YQCtbN+MNBMb+JhcvnDq3JEVmH3Jhx
            Kf4bxvG0qoVzWoDjfAMRlO/gvW4eO/OfB/g77zY95LAHOKgQ4s9KAx/4Uc58JwMz
            ob3eAppkkrJC
            =xxj7
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
