apiVersion: ENC[AES256_GCM,data:W3w=,iv:KrLLkz3TkEDv5qPpigKly09A4I9Ue86HhKKLMYLp1Uo=,tag:ET/MvWw4c0Yndr/heiA+Rg==,type:str]
kind: ENC[AES256_GCM,data:cToPJiX+,iv:r6uM3u2kyGYk09wno4sO3oBJKgLtPzcwcKT43Qc863A=,tag:ioDzSbGew82HnnwjOkelfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xwGtO1ib5fDrkRWs+W4=,iv:xmIZHy2WKDJkK0/gTc1p3dsBAi+L6syILBFd/2uu2sg=,tag:L5zwQFNk4FaXh19m6KpNqg==,type:str]
    namespace: ENC[AES256_GCM,data:VaspyvH8hPE=,iv:1MR+4vqh2dG2LQCOZSgvF08k6SZV6YYuUmzNjq6dpaM=,tag:5AeeLl6+t2TC9bnCMVAjmw==,type:str]
type: ENC[AES256_GCM,data:jxrah0ng,iv:fsu48gmWo6W9nrnjquV+ae7nDwL1KfkI107nsnkyi4c=,tag:LVKlSxP6c8OeHETYJiSRkQ==,type:str]
stringData:
    apiKey: ENC[AES256_GCM,data:gGdgk52yv/CoeLcB3tWAvPf7V7NjB08aPiiqpjalgPQ=,iv:RDjZVam//wGMeDYYHlGw/g7qU1ZUL1qyjm7npfLHthE=,tag:CfdmnywaG9Yvw9/jsbmjfA==,type:str]
sops:
    lastmodified: "2026-09-23T17:08:18Z"
    mac: ENC[AES256_GCM,data:YVvqx85TaYUKpyF133oiW6EuceXXE9PHluWOGpTVXkxsmYAHse37BWDyyamMnFaNmHUmDgGqHnzP5HNVDj0cN5Bouay3N90E1ZZW3VrbEjp265XdrQlMHxf4/e3ffYl9rrp5Dy0eRBQepFuS2LBi58C2vcSE87QIo8+yE7XgSGk=,iv:0+OkuwM9wRiSVKU1gwg1GZDzLccVGE1evo7C1qeOVPA=,tag:HOYGx/hRasflxqbm9W1KpA==,type:str]
    pgp:
        - created_at: "2026-09-23T17:08:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//U/23woPKl+zRUhM+rIToxB99jugADWCh1m8AUckQKaJU
            9POF2V/7VqeRhgcieaYrTf/dgxCJMl4dmEPERNLGfBCjoZEAFOaNCqSPy3TEjnfo
            dvvERhCdic/pv6PQWXKl9HsyFH828SFFxV3pCkd477Xm7ljl5HZuQUz1LvZfam1A
            i/hErxDyhBYZrZ5TTCmsLPTZ01iUXq82eXriVJs7YCX3+jMNeuoUON8GDAqDzRQM
            jzDqOvA3dWHTNViCAaZVWNTDjrUdcVdnMM2lNeYx/rmfSWzktMGnscqYQDZVhVoG
            5oxrCCKVQWTOk8fwyvPuemeFgzTMwcw9YisAYLyPB5aSKkKOz9AZB16h1ZLO3FkM
            urBhOdTwjvO8Iry0wo6tAX7oHWTBNjMPpJcRMXnJa2JB27Ptdnql1mkuC+sGAlrY
            vFNyV/9/EKia/YEaNzIkXTfwDg2ZY+4zbK6NnbOEGlJSCXxksXBug7KZtoMqZ8ci
            XCA4Lk7BlFXCV7LMlU4OO7IaSoyPHYvqqDg8PkHbjSTJCRSFboxNERaGWFT1dkCT
            wtUAPeyfXoyWMdM17zVt4maZjGwX2bWRQu8U+zI8Yh1pjMjLnITAP+vyjU9T6o0p
            9h3rc4ntELb4WirS+ia26D0MY5/VfYfnjogbAOl4Ao9T3wA8hGhQzc/PgT8URCbU
            ZgEJAhDrwuWXIo3TlDgtMFjUC051FXnfFLrmp16Xl4ShwTBllunnYLF0KSlEEgUV
            C+va2YH2xsmJdNKisF4Lk4xExFq4r5dnejb+UwFliQ6G548MC0A1yxe6xLObeq+B
            K6wjHMWNAw==
            =x7Tv
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
