#ENC[AES256_GCM,data:T/nfGFtKnbHmJMCQnWLKweNrbHUggigDHeAlclNVJvpAmeeg0euGhyLSaMggknA=,iv:X1Nf408NGuYMl1z5ALndBVSts2dP/8f497QzZaXZVug=,tag:jcmtGHWBAx9hase1qc1dKg==,type:comment]
#ENC[AES256_GCM,data:VEOtpVdbf3VBti7CFu6ymm4S2UahC2C4HNDj34gy7YHJlxZRRaiU6sbnxdommp2eAw1u+okTWBX8slNK1bvEMcf0VTdgJx7Y23M7bJUPa/8Ek2M5CuVMSUrfHMdBF6u9orLObrXgs3KLM5VVZJjpJPReAPSJxNIIzU07KQ==,iv:IX1igPEOhsp5noDa6A/vVVt700OJSoQeiwW9Q9+RKfY=,tag:D7DZMAtDUg0kxxHtrqvd6g==,type:comment]
apiVersion: ENC[AES256_GCM,data:k8Y=,iv:OitGWQHDV7PVIi9J4yI3fyeN7nJFyXMOWJIr6tNt6CM=,tag:3UPRub5IO21sVus45Zk88A==,type:str]
kind: ENC[AES256_GCM,data:qYiseo4T,iv:oAK6iHQQcHr5NcKdFgqxOuv860InBHbFMr6ckQdr2mc=,tag:F1Nx8L4egMLJbjK4OFzJ1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CkwexgfFePcYRElogxF8,iv:FrpHIGqz82IbL8IDdFSX1KIX9Imvc1wfjQ1SmrWtipQ=,tag:fQVRPEyn6GWmvCKWAWkWcQ==,type:str]
    namespace: ENC[AES256_GCM,data:ziVVSHVASX8=,iv:ehUviyGoGdHcb12aWyhh2qQExC1+WVRgfJE8e14o01s=,tag:w4GYo+ujcOQr3U0Vhfpx1w==,type:str]
type: ENC[AES256_GCM,data:tNiQrtW4,iv:aDTdBR0nQ079Dw3Qq1bxSTH83rkFTcZeydiGeQcYIo0=,tag:3+IFVku1WYwH4YXISSKe+A==,type:str]
stringData:
    eweka-password: ENC[AES256_GCM,data:6NKuzkdmJmE=,iv:iDCdr3eBcDNVfL14j0rePHJ/z93XqWSb/gfok47Eqqc=,tag:yWPEqEU92HeOtv4JnxuM2w==,type:str]
sops:
    lastmodified: "2025-09-07T21:26:34Z"
    mac: ENC[AES256_GCM,data:EFpPoSovK4EVNGEGmCnL/kJIOUnpSQGRe0udyrHX7r6oGMKrvGBbbQ/pYXXjzbRbDWvxuvyokFo01dHOSJYZ7FyNoAH8rEWsTE12cpENeoXh2AA/vKFLVPafCgvNLyb98QS86nV2EtL4M8bk5KC6ujQGiilkkRvaHigwmEtZoyA=,iv:9FBzh59s/9MUWLgmycubUIxzklUFe9bLXIC9KZZQQtc=,tag:gInBwYVWHAXj5vqwlLi2XQ==,type:str]
    pgp:
        - created_at: "2025-09-07T21:26:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63ARAAg9U5tsjpVAlrV4Wwjc+4gM+2RFZT/gofO3N3F8Gso1Q2
            oAtRRbT7odQwD5AU++9X/c/Dx/m++CeLK5BDoPEu94asfrOqONfwR2+HAgzk/lFx
            +fAUYkcDiK+5eKojw1TW/j/CbTpT/1vnXbBb/DOhPbISESsm3dO9lVdV9yxaLEV1
            +2a5IhfqhHCf+SEF6irmhVhFrR/OMrPzwv5n2Y5/QVZWpIQ98m2f2+9CmJnmTPpY
            iGAhRMGMZAmnhE4LmHqgP2V7JuwvX2kCJ+wwrNpgH9Dx7YvGYbzcxQU8B+8jgt7R
            jm9W2qPDePiYBjzRLGyfUtA+rdmJGB9K29cBjOf9C7SOxHEHt5xAoXIKAIQAMMZp
            LdJQrgJ+O3/xa2hgiQwYpJ+MMpYMfwWwjiHVl/RN7yAKvl3rYjE5p0vCqc5VNO9x
            6iuQnxtqqK2cYhAewkjFwEoZpTPPT6fJ2YOOyiOB4ZhBbO1GOnSLgPBN9109PLC2
            mBDpvLh3gvsS7+ge3LlsyPeZagYy1MwFklzePqMEOb2F4P2/ju+tjfWZ7uSAdAys
            65hEPxjBgjtE2mV8lS/jc2+0YKWbvYN21A3rhfXKJIQggalMjZ32EkJLTDAuyp0C
            +//1PRjCe9jYYW8dHSV8S7/cXkTGExCXFVn5oGXXiHL7fu/KJlJW2Oxvmbj8Xj7S
            XgEP4TQ2ozIUAjHybATKBjvfnmGggAXa34DQzj0LpXh6jg+9hlKtknS4qe0WkvhP
            98qUBIHAa+Dpx2GOh/92zX5XtxHXzgdwm4geewn2aDSmIlSdNDskkRLd54fzSkg=
            =jnY+
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
