apiVersion: ENC[AES256_GCM,data:BbQ=,iv:+o9TmoQJCW6E6kX/iHLVVzELCl+DfKKanQWK5PuPcZA=,tag:TxeLcVLmJBJMikm60KtEew==,type:str]
kind: ENC[AES256_GCM,data:44ObgDxL,iv:5nmnAmC1/nFefwmnKyzwZoIQ0vmTNpYD8ktlX6Aa2zQ=,tag:HVSxX3zkWNoRoEZH9cVOEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AHCyz+zXdTTVaZHX+Ok=,iv:fJ5t42qNdPJLGeBC5sKZyLKAz2z5iR8KfaoWLcQehVY=,tag:zW6np+jsrg4Q4gyJ2De3/Q==,type:str]
    namespace: ENC[AES256_GCM,data:BTAFKexdJuY=,iv:mNHnb1a/cn8XRyySZ0S/BdSwHLv63WXkofRBP+uPfkQ=,tag:/dl+Onu6Aa9u6STu6QpPcg==,type:str]
type: ENC[AES256_GCM,data:qtNBIxYW,iv:cRoyuSayfUCBx1D49dAPmXGfQ8FGpyFt3MLMHTsJRnQ=,tag:VQZvudGpG3rJ8KYF9K2p5g==,type:str]
stringData:
    apiKey: ENC[AES256_GCM,data:cMP/y90SFrzBhbrVMOZAuo2gFaNGjhHocAY4ZJjknjA=,iv:Bq5XayxBMqkARq/3HybkJvbl5VnCu0ZXLL3rh5bwtG4=,tag:ZO+G68Och8GbsXwaYDXHlw==,type:str]
    nzbKey: ENC[AES256_GCM,data:HEKu4O7bR6Q7aERiX9LsLjlPcoX8smgnXTuirtqngO4=,iv:G4UrU2WcAghinSsP27Gwc9wU6BuxPPFeqXQu8JU/re0=,tag:9wx2dinzAwD7qH0vg6hgUQ==,type:str]
sops:
    lastmodified: "2026-09-23T17:45:48Z"
    mac: ENC[AES256_GCM,data:OBnhVNxKjn9skv7+ea+O8sdIvGAJ9DRuSJHCnoJlifXuODNDizO9aLglfgh2h/B063bOsGW/pgLBP+lCxqAxGBX4AHCZmqc6ekQMnr7zumH8jKWY5ymwKlfcyZC9IlnjhU5uH2R9m5so8Kc1tZRlyVXJvCdrKRa2J9zPmGLRh/c=,iv:0KbAETT7lHf1h7T5REwMsNNQ8mAMafnoIGXeL7tVRyQ=,tag:g+C5giDEfhWyBbpheTqa/A==,type:str]
    pgp:
        - created_at: "2026-09-23T17:45:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/8C19F9BjXOXj7Epb9eTtrX1+KYGAbbbmSfFGGbeU42XlV
            OwmS2JRtwMhgw0AidffeXWUzakxXmKSN88nCtsSV7symF5ky0l2drwx4rnQtgD6c
            81/jLVZgzm74psIqVldqvAgSh4W4GYkpewPZtA88vAiEXMduNaZ4wq64N/8G/pZ/
            HPZ1YGqJiRhaVSrS+DXT8g+wIekqmSLY0EAkWUvia5+Y+McCfjrpbv4xDn2jWvpg
            57WT0uB72pwvWnIqfJcyN9XIF8IQeT04jaBpyOSdElPUXCXa2vVDVA5RQzsru3IO
            VpgLqNocgp60II+Eav3cqvBdsoN0CslfpRsFghpbqqsNCwtUtzWM+2wA1ZkrMPpY
            We2VlSy0Zx8c8pjdc56if64dozo3xmC75VIG1kFU+VILLCXRDj7P7zPTTo24JixZ
            47bvm8eOp51Ys/yRWr3Dq6qzB8gMsIk6nsWmlqx0dFdHGkj0SYd93plxxldfUx4D
            7CeMBYM6T+7a6s9m2fd2RLxuI6N8uNBKqFCNZOaiks8gI3HHdsYj+AB+CIa3kPz7
            4Z0Oxh7dmfW63J2s+2AbY/lhU9YfLb0AgnS2JqXmWtXmlHAXSIEIYbLRISXFO07B
            AhPaCCkpXeImddujM9LOe6SAMZMNcXwjgAQI7if5+878gW/GJGkXiJ1/UIh6J7PU
            aAEJAhDzGHaRzaiWK2a1xDiI6hhj/L4pY6cbU2CvTv9Tn5DavpoTX1vdUaF+aLv3
            UL9p7TxX9ZYk9oKW1JAnigz+j7OMoEfqs3nLlitHIMFoaSKZbE3VGS8CewpMgEl6
            j/rNhZPBpSl7
            =iteH
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
