apiVersion: ENC[AES256_GCM,data:D3w=,iv:jYM3l2v+jqOvFLSQwNq0Pp0K4qhhTK5SImXNVGM4kl4=,tag:yrNJgMRO6oP/9KYnXaL1Vg==,type:str]
kind: ENC[AES256_GCM,data:4tY+Ts6Q,iv:lhxvCZhZzGt49HC3vBgBPP0AhnGHzzXBXwleqF5EVYk=,tag:/acfMZW5khtVG/wbv86dLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EIOXQeISiED17trMI3FA/rQzvcs=,iv:sgxKQUgoQyaWX99DyLWR9CdWzyJGlGLEJbvsGR0TIWg=,tag:SmNvUkZIeHwNstVYHUvlug==,type:str]
    namespace: ENC[AES256_GCM,data:UOavkVUZnOc=,iv:KyPKjFHRFDcexDy52ZWk1s8BgX/3No+zG5KlJ7yHNFw=,tag:fVLgFp3HnZZQwdcXBEKvuA==,type:str]
type: ENC[AES256_GCM,data:YFgCnUaR,iv:J7KgqeCATt5UVsf7d4fx10SKoPzNvYAVvlyZBaPQguw=,tag:h8agCDk5sYKMxycomW3ssA==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4BnKTdty3ZcOfEk1zT1HwQljDz4Kk1D0nW3dQdiuM+Y6yPVNXAWAIV4dFGPMi8x+67OnZ5JSWNu3v9UcHkJIE7iUPRAW7sU=,iv:TnhxZcbMoyyvR4rsjO9iDPwhB6fvaVJ/KZhXrbP4Pvk=,tag:7tVr1O0WHdrlZEUitZx7KQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dISaoUNaQahwbw==,iv:g2v0v+OaU6nIrneqlUrpMph5x+jYlptBn232molS8VU=,tag:MEBi9AC25wWbcndVJM4ptg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VNEnhE/Lj5CIYg==,iv:5l15oE/g997XZ+WDg1NPGsbsGU7cAQSljR27ZMJYCTY=,tag:nZiJSEBNQTAiSsKAV190FQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gdjyhS5A0e/o4w==,iv:jf2q2MNuM8IPlA2G4GzZ8rH8CpoOznrCsGWhYm22yDU=,tag:5rsEM0i4wOXSFJZ24aUaKQ==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:w+wEaofKhy2pQ3fzaL8zb9KVfCsBIVq40Ycek9+6Ipu4XZw3SjnbnPv2lH2gtDv3x4XHHNKZjsDWsfefnsoVJKlQ2v4V+oMIab9XJiVtNj6WiCOIEIiEpfrO6hMnx/BYoxFhMdpCXbAh2ZTMLFxolTuQTt1AEVvqSKbR/0JkO1o=,iv:byGXJhs94wPkXVWumyBaVyhwe1NAxVezhGyyDOIMRz0=,tag:cwoSZM4zexkNJueU+6EMdQ==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//Wu1yn0zzPVq+ijb/4+dEPKQ8JtkmqeP7tEOW73qrJ7yW
            NSkw75KBOKLFS9nE3lFSeIOuqZWDomtRi2U2qXVKO/NaJ5ZyYqaDwTkElg4LL3oO
            MBe8UeGVw/2tPauvArFzNxKtTGL70ZdGFyGHwAC9NmlDBayrW1Wnw4BplfWBaSmo
            +/PnquxOkXYqU/FJHhdl2zA7CRlw/OcwtQvaXU8+J+U2xpJaIvYVlDTbDCmEBnL3
            ZfTtqVxmeHwb/eOFKZehsUFZNrA44yGRbEjx5RutPUE2qsRxZMblWaRkDMO10TNz
            4jxp9APRZQyncK6yQgJINc+Brpu5Fb2798kxfePVRmWxn1Dvw/Nkl7wIn49XvmB2
            Qb+Qf9y74IqrGUbKJWBwfVtCA1Yv6CXg381MsCic5NDh8nWfaeTzbtSLujPL3CYo
            DvglHfmV0cOn79pTlf6sN1cKsvXPmL+WKWby1h6MHXlf429fNCIU4hdy0tz44Snb
            1DZ7faxt59lAx9Nqn3TpG3ngcQxL9qNsJnRn/iW+hon2kbgx2AgpnUuILKusdOfG
            EM8c6gWRSfRHmYg8xqpZqhz+jn3FTe6Y9+Ml9ivkSwD0LyrO1YUuAO8rG/a1VCr8
            OLDp/LHVgykPU84f3UiVvZctXIPpah+FB6dyop8ZlELfRsOPFC3RypxSHNl6q6/U
            aAEJAhBMpm2876oSGZJcvcXMHjcpAnoRL5+IJqeqkdruaOiAyh+5ZF5NQS65YcZf
            XW+3Jmz+kCSgjB2EMTl4jbJR+hKuZtjtQmSa2HqUDbMfoWluPx9Wlrn6xGtUcsOF
            G7yMEs3q0PBW
            =kzQZ
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
