apiVersion: ENC[AES256_GCM,data:IiI=,iv:ydJqK97yWGkjXOITxJigPhlpQpQk4l5ivXgqBEq8JgM=,tag:0ZUBJ/DO9Gd5Ns2DfApkiw==,type:str]
kind: ENC[AES256_GCM,data:Aity6KJO,iv:tJ43yVvrFDsDqt5WKjnPDP4hr31znWxsk3Nowxvrn6s=,tag:NFLCczKQQ4oDmQ41advxJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YPmajiiDgM9+drZDUAuA4ZHOvaQ=,iv:++hsPv4EJtBa05j0LnW+GfwrqrLNxdnN7JD4Bvj/KP8=,tag:2ld5Z2/btAnG+RZNKKmxtA==,type:str]
    namespace: ENC[AES256_GCM,data:qpRnIcngt/Y=,iv:pzywdqHq8IBlI2fCfVHD/6zX/8pcAOcQzGGfIQRU2xA=,tag:2sVyN4E0JyMqrThaomz2EQ==,type:str]
type: ENC[AES256_GCM,data:tPbZHAma,iv:9k+4bQPE/O/NAblJTTFzuIoNm0DYFzukQUOouTXvM64=,tag:y4qwGbWkZaya3oqv9TJevA==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:rHmdIuC0396a2TOFntN6B9MsfAXhnJqUhZ6Vrexms05bI4xIld4owvNCt2tqd/ut2R+3e5eIwN9uTBaSkavJMXUJ1ans+jM=,iv:J7+vmP/SvTwvfCWPIhYksz1lgY73dFQ8OdZJ+/04MNc=,tag:z5IxNOx5Pjo+qOZvEmuT5w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:blqWRhsMUapWkg==,iv:tDJnDRiuhhCfuuMdBBasOj/WAhS3RhOBTG4OMlWNdPw=,tag:CiGPw9Cs3QQlbnclt488tQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gpCvVDg00uimnw==,iv:jq0G6NGlQp7uPSy6en8PQwwFj+t7fyaINe4Phay4KGg=,tag:FQ5txhUstp7M+E39bfOxnA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0qAsUHWuCB/h9g==,iv:b/4XrUsqirNf1FBuCLE+/OTAug7R/F/0GYpb1nGMZUk=,tag:DhhZqCJ9kbY4SsUt7l1+Zg==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:H6KktkDSsuxQp/qfmH66BkcMjphQN3FWIobKUuS8sV7SI6H6Nmwk7JGEvxRLVRMKEYQj2XVzHOAcU9ef5x9Nqzq4CcNOl7oU0iQFweAXKVQGHTjYpmvwzgYuQ3Y4EP3iysLJgAvsykjBIIVewvNFCxi0f2PX4Ie9hYG5zdkjl/A=,iv:9o4ah0ng2QSIMnfL39t/dnksKJoNe7+mokNZjDjOhc8=,tag:ex/+CqhBSKzNDC7DGGv82Q==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAkft5x6fYqp3/UH8cPX4uLgMMbYWzYjbla6YF2LoJZxGQ
            Ni2AVUNuv45ch7Jr+AH009JcZ9zD4Qt7MRecsyEjmusp3/OMUyZrjT/3cP8WBz7N
            mKvePj7f0B380yuNNF0CX0rRqcf9IcqCp4QSNRv9/m1tfBNnvbD0JANrBEoSXqK9
            xOQaWyVCz8JdMoFVViqBXcIwuTcbyI971SL+YKTO/9FkBag9lEKN8F5YcuKgQWYt
            SnMnMs3WB+lFaVXjfj4G1zIhhKm7k1vPsFORK+RMsMnRExHK5EUEz2Bo8dygsglX
            E9vYOXA6Nui2YNHSW3QnTTYPxXAHhZRvm5t4jOXzOpSQ4qVp83hcZO/Ryt7okPug
            TgVLhQ5NGrkVQbnPAuiUV5l/NTSWIkEhFxxO7ri91NX526u/wHQRG8DKejFeqRaR
            8P3kiH+2lr0/vOErCqcCmtlpiyklC29GANAAJCc8pR7JalAGGGfOxpMWf46LeG11
            3F5aI8tIzm5B1JCqh6cqvbWQeq06Eo7JQsFl2F9WM+uN+u2VH0X4AqZGjGKXMbi0
            foZEkiEdS6g/wy+1reODLRlIig/hKeJE9FrGFqy0QmMxjsxymtqGp6Tg5yFEfaZn
            4zKWmFvn+EHINrwWKWHJqk57HejvNPO8omP0o4T+v42o04d/ACzHcwm5ZBaT9crU
            aAEJAhA1B8tawsvIYIbZsw5kxYZ06wrjqfGBgXQHK1YUypA23wpXaOz9MKKDmAcm
            gNLxa38RKYGz4M0KcV0MuFuYXHiRykXwWSFimh8MGHpBF7LxcmH9aEzY/10fDv9Y
            5zQOD58jTVdJ
            =f7xk
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
