apiVersion: ENC[AES256_GCM,data:FxI=,iv:d2IsIJvOtA2WF8BmJ5lPHTdGqDb8UPPykMQ113alU4A=,tag:mkruku3GdWv0uadGUXTObg==,type:str]
kind: ENC[AES256_GCM,data:TZZJYwSZ,iv:3xNld0m531suvAx+DNUyZx8xyvR6GxPbgado65t7jbY=,tag:751loiy4K3bqq5IgolUvzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3vBHYHeBZ1cubdH8zHBQ09obTCkQ+b0yGLI=,iv:uTYYL9ITcW96vJO22XSOf2BLP1gYdMT8/cIQ+m7W4+s=,tag:aOu7jkDqc+lNeduViwkuOg==,type:str]
    namespace: ENC[AES256_GCM,data:AXI9NBH8nxw=,iv:EyVefWwBuY8qJvDTULSap3T03AC3KWV5rp0pUsOMkdI=,tag:VCiC+/f/KmL9KTRdSiMn6w==,type:str]
type: ENC[AES256_GCM,data:VM+lNpeE,iv:jlUsmdOPrMsCQXR2nXSCPPTeIWTLtd76yx4c8S5KKJY=,tag:CrJqTnyQ99g7rCYCe9kFVg==,type:str]
stringData:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:oiWO/ErTUzqzScL+P1CQm8c=,iv:efW7/FnluUVYF3CLanf4Ba46xDla0dGGs/6NppwHhok=,tag:bvwEodu0fqZl8dEhP2Iprw==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:hM8sYQXP7YgoGpMU7Q==,iv:XqbpDDTogBxZi5a46/RxH2rIJ4EMhINNugpzBPWEgqg=,tag:H4L5TN07wCHMEiN5fLdcwA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:IwSovH8=,iv:x4APn2/4B2JenwnkTv8xhTUPX+zpGVqdDWI7WKXiacU=,tag:Cpro86n6oPZcMYqQ+lASWA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:25FVFlFrhPzVXFA6ER3B+MvsWi/Jtd4/Z6Qg5J6D/XfFoApMGP0y8PM5p/A=,iv:U/D1Up9OLm/kTQpdjIL5fOI4cP28pM3YeTJdGal0xng=,tag:Mv3XYDwqBtxplp+sxV4QvQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:uItDvdDFVtr7tH5MgfzSJr2kaLJhtPt9ipOQiUPZrt7JPYcZ3+8mAv/GOhU=,iv:/X6Acy556HddxxQRnPUMLhdRkVW/o1TbOQCJoN3HCTQ=,tag:KZUuUtsAaQvHHBLl9lC2uQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:UyQR/nW1tu1hE0/vEH0NXixiv+pTZqeMApXnsOE3gGCoLuQnszdZ0W0chbQ=,iv:ZxdRdUjJ5+udDQ6RzBnfimnH2pTVgVXYD5IOOVsHhPk=,tag:uxI9qgpO3R2RmvcF5TXcFA==,type:str]
sops:
    lastmodified: "2026-03-28T15:49:08Z"
    mac: ENC[AES256_GCM,data:6G7xqh1tPiHgPfwaUF0wCh9vitmdP4Nqn7arEy67YywKihc9G/Jmg0m8E21e/4rjxyGRipd5e4yUN0iivAoDiXv6IjYJAvPwSeTTLlBgxthR7GkrWuFZBS6/fGT/N4SAz1NZ7ai98OsA+kNRRJJjld4iV6zxUuJ/qAUnnmRJUso=,iv:478k1j1QuFHbvOWvtoNOLCQVcCzLRb4OWYL7oq9eeIs=,tag:lS3QIpw9z7BCKaSLtuvQAw==,type:str]
    pgp:
        - created_at: "2026-03-28T15:49:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAgxveoZvSgI+APFGj+4FvISHn0q3xyQDblSibwSkUfNb/
            2psM3mdGuoYGLTNZc9xX5PsYJ5FhftIGeyfe7ZHr1idQAvE/db7X7EGBhoMZPTNM
            SEhHrpvA8gjYBxKhFZph3EK/KVLlSaqLPM++JjS2ElenJUJoc0AM5nS1Md4SmMLI
            IMAFGJk6YlcEYjRt/zZm43WrVxXRNvGf6zopE/q4B+EccI5E0DyKi8TSp6pMEZ9F
            Oh7D0jEmalILyPTOOBPoNf2qj+r3HE9TnkDVSsLOPoc/ETX6+xM72cwYjfCjSdIi
            8lgv30VXOUSeUBKd0gkPyaExEzQWCQ0kDnO6ciLh6WrUKpj6cSATsqOlajdqcshW
            qxYnwJPFPPPpwWCVzyMI95LUu7GJwayqN4n2H9lrHZdAQloxVqTzCe4gR6BOCpjT
            SDTbkXC3oiKNfMKIwnZid+Z3GA6PGM6vJ7uE926U7/9tqKyLwG3ml1o8so3IUO/c
            4XoPmePJ7UTAzutGviUis3qDdquxnQq0PNWDF4sjZtnTxbbTCYVqXfrpxd1X5gOn
            zJ8fV/z2GU1KY9deCHsld2d/qFDozYHKzIerJ951yFMmgQZMVSRMsYZCuaoiPHbf
            MpGQhS6HgcyVetB5yNCr+ZHyavazRAt6nFbStnci+3+SDv109vpfCMhYwBUE0arU
            aAEJAhARGMEXzNia3FVkVw6dWHSqPb5W/8B+SvaUm70rAD9gtwp6P/ZDqimBsVy2
            5raXSRPLkLSD+jNAf3g4tGGl4Nu09i2dL8TIzh0anKRyVa9kyB4x2XIjNhxuG8Pm
            320ulnGcXnlH
            =rL1X
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
