apiVersion: ENC[AES256_GCM,data:KmI=,iv:fQtEyciQ+cDCqowowhV6jVQ+Nw7HXEdGHBJBckjUy4Y=,tag:1AFWc42qAqe9wj3Z8E5KjA==,type:str]
kind: ENC[AES256_GCM,data:w0/wiPij,iv:ed5xPzxX+jnFw16DTvui+e+8KKQH8o6HBxJyJnegcHc=,tag:nQThSYm63u02BYAwjgN8mw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ystUFZ4i30JXKoc2tVykH+v9cEAkvOcvjYM=,iv:w24G9T0vNLfEFcnnqaFVtUN6gJdoN6piEBl0IBBiYRE=,tag:RFkJBTy3hLZ63m+1i36VIA==,type:str]
    namespace: ENC[AES256_GCM,data:wHuOSCsNK4o=,iv:BBgi4QYzl+RlYfBa6HeXNkkucQoLFMCrUJQdC6ujv/I=,tag:l0xT3l6JBwHdN8m1dDfLuA==,type:str]
type: ENC[AES256_GCM,data:C2II/EmJ,iv:oXh7AxoDNgh8C7M/aBhzCDM5V1jrj41UrMoQZ2qgR0I=,tag:G7w9jYWfyfieO0KAuZMwUA==,type:str]
stringData:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:EgdV9xMzn0sSHOnbLgc1kXU=,iv:r1EPVUXo22acsOhIfEwoYaS0uWZV5TjZcL0x/c34NVU=,tag:tsFhuHuTWD1gJM4KJSMTvw==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:9C781EHHzl+95i0nOQ==,iv:xSLLmy/jUCeG8IRoFtOllLJEfa+CMd640ffc5SdxvKs=,tag:GRD+pgZ9x1KPgiuNlQ3bow==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:nwU7T14=,iv:hgeIbQ8BNgQE9gnDBIVhcfXkYh1tNcCwoMl8t4lkZWQ=,tag:8/XjFRH+zkXRYEBNcHoz7Q==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:Kpx121w9ikmz3bDRf/HdVBlale0qwdrU6avRRi4DVYdXvX9jbku6BJ0uwes=,iv:Z4ybSCb9yTDQFU4I/uNuuiHnejjHiGo1r/5X8eEUStk=,tag:I0h3jeAAcLpvBa3iUIfoaA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:JncmSXylAFfh7vUaR1SeZqvvuJ6ebJDBGCU4+jXisLqYod/NdLAkDDIbz00=,iv:C+Tt9kc/dmfQxghqBL9lEveC5h9ppc73UH4TJW/mWYo=,tag:fttyrvw3EoOyWzGaiXtBKw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:ILqP1MP3LQ51N21CRhwyhG4eJ59pT5ihxNwaaeAChEo33E+jl2uKoXM2J0M=,iv:W5qnjao/vA6ZYUQ0C/u0oIcpuA6hONRp7AEfQeEZgAk=,tag:Vy9ur6C95DSTjsvnDLi7ZA==,type:str]
sops:
    lastmodified: "2026-03-28T17:18:39Z"
    mac: ENC[AES256_GCM,data:aRyOxd+OeTh9TCAuaZ0b+Jm6/6U11ERxT2Etd3nTpyeBWX7G/mGFQ/TyINwr9enbaxbO94M7kNr/F7yvOHtZAfJtLLz7ekmf6T8JCLl+iqrBYLRphMm8hhuPvdkh3vWY9dT/UJZZJtzcQilVxjp7o5iMu44joC2vmdiMMrpDT58=,iv:MujmSuyL9wBLW8+r9GVImlAfj2lmMAxje6Wq1c2eIY4=,tag:ypexYg3CG3OUtgvncCfFlQ==,type:str]
    pgp:
        - created_at: "2026-03-28T17:18:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//Wfs6T9IhCqvQtv9eBhTcvJRZCasdFxWdqRLBpMrBexVz
            3IitWj4TM2KI0GIegkBAX9LFlYNkuDdUkPXrPm19n+R/UT+aFSnJhepP7eFxGIGt
            eEUIhtzhKpdBlWSZ+/dYh9aGvMOFYws6Bn2g6R7IqcDNbeioeLYFLLuGECi6ndvY
            m1T8JCgi4xdINP6b13DfbUFpl11leGZvm9ef/RXeDuyDuKBS6z0qkaahwKYpRF8r
            BgqlJefhmneEDf5XX8oCjEdjpntlnwLsRaPeU1P6RYdDbQ063a+kguiFAGG5181b
            txHRAB5C8VbDX+ZmFD4waMC4USzSxh7gI/5jOGdEuqU+owjN1PMXw0s9qFpSsTqP
            wrf6AGquEifRWrGi6iMbAgOVu7KYuNt+jc75+yt2KQaBScnqPQzGqZFfYfcnUDtL
            xBv05aavMNMKVLABaNiVccai0nWxBqO27fU7+MTZmbrCaSTxDWtrqWhgF2ZcUSs8
            hreRJGYv/fHszUqq4e8xjMhtbMhOe+u1ThBffQ8kjurqslMBCjpNXzIXrhPBqd1U
            hjW4DbnSE43t0UFDbi/Vela38tPveWkA5VWFJ+TK030pKCcjGKVYlGOfFKTQBVTF
            kVQgnbgMJ8T8vRuHIJSc+Hu3UcjauyCfggHEfPqp9psE7LmWJdI8XnmrtS2WvXTU
            aAEJAhAmvtICS18elxqGK+3ZOQlgFyzh52JZ5WHBiRq8CSu33cn49TzbR2UnQ0q2
            1f3tUDr6TjdJjqThzcRsl+qlWZLJrUX5XcOQO2ru99G/bz99hrlfCIF3lllf2ywi
            LD8EXEV/tm0u
            =hq29
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
