apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monero-operator/config/bases/deployment.yaml
  - monero-operator/config/release.yaml

# images:
#   - name: ghcr.io/supercoolalan/monero-operator/monero-operator-0f25b68d038cd3967cd5a1bc4733cad6:latest
#     newTag: latest

patches:
  - target:
      kind: Deployment
      name: monero-controller
      namespace: monero-system
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-pull-secret
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: ["monero-operator", "run"]
      - op: replace
        path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
        value: false
      - op: remove
        path: /spec/template/spec/containers/0/securityContext/runAsNonRoot
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/supercoolalan/monero-operator/monero-operator-0f25b68d038cd3967cd5a1bc4733cad6:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: ghcr.io/supercoolalan/homelab-manifests@sha256:34b811cf2b75016f2c646b9c353fdacb7d7e754d1eb22a999784fafcecf8f808

