apiVersion: v1
kind: PersistentVolume
metadata:
  name: monero-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - noatime
    - nfsvers=4
  nfs:
    server: truenas.asandov.local
    path: /mnt/ST6000NM0095-pool1/xmr/talos-chain/v
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-full-node-0
  namespace: monero-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: monero-data-pv
---
kind: MoneroNodeSet
apiVersion: utxo.com.br/v1alpha1
metadata:
  name: full-node
  namespace: monero-system
spec:
  replicas: 1
  storageClass: ""
  diskSize: 100Gi
