apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: crypto-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/imagepullsecret.enc.yaml