---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.7.200-10.0.7.210  # LoadBalancer IP range
---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: opnsense-peer
  namespace: metallb-system
spec:
  myASN: 65000
  peerASN: 65000
  peerAddress: 10.0.1.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool