apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helm/k8s-mediaserver-charts/helm-charts

helmCharts:
  - name: k8s-mediaserver
    namespace: media
    releaseName: k8s-medias
    valuesFile: myvalues.yaml

patches:
- patch: |-
    - op: add
      path: /spec/rules/0/http/paths/0/pathType
      value: ImplementationSpecific
  target:
    kind: Ingress
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/3
      value: 
        mountPath: /sabnzbd-downloads
        name: mediaserver-volume
        subPath: media/sabnzbd-downloads
  target:
    kind: Deployment
    name: jellyfin
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/2
      value: 
        mountPath: /sabnzbd-downloads
        name: mediaserver-volume
        subPath: media/sabnzbd-downloads
  target:
    kind: Deployment
    name: sabnzbd
