general:
  ingress_host: mediaserver.talos.asandov.local
  plex_ingress_host: plex.talos.asandov.local
  jellyfin_ingress_host: jellyfin.talos.asandov.local
  storage:
    pvcStorageClass: nfs
    size: 250Gi
  ingress:
    ingressClassName: nginx
  vpn:
    provider: windscribe
    type: openvpn
    user: ~
    password: ~
    region: US Central
    existingSecret: windscribe-openvpn-creds

sonarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

sabnzbd:
  enabled: true
  vpn:
    enabled: true

radarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

transmission:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13
  vpn:
    enabled: true

jackett:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

prowlarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13


plex:
  enabled: false

jellyfin:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

jellyseerr:
  enabled: true 
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13


flaresolverr:
  enabled: false
  container:
    image: ghcr.io/flaresolverr/flaresolverr:latest
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

