general:
  ingress_host: mediaserver.asandov.local
  jellyfin_ingress_host: jellyfin.asandov.com
  storage:
    pvcStorageClass: nfs
    size: 750Gi
  ingress:
    ingressClassName: nginx
  vpn:
    provider: windscribe
    type: openvpn
    user: ~
    password: ~
    region: US Central
    existingSecret: windscribe-openvpn-creds

sonarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com

sabnzbd:
  enabled: true
  vpn:
    enabled: true

radarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com

transmission:
  enabled: false 
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13
  vpn:
    enabled: true

jackett:
  enabled: false 
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

prowlarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com


plex:
  enabled: false

jellyfin:
  enabled: true
  ingress:
    annotations:
#     external-dns.alpha.kubernetes.io/target: 10.0.1.13 #opnsense-managed ip
      #external-dns.alpha.kubernetes.io/hostname: jellyfin.asandov.com
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com


flaresolverr:
  enabled: false
  container:
    image: ghcr.io/flaresolverr/flaresolverr:latest
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

debugger:
  enabled: true
