image:
  tag: latest
  imagePullPolicy: Always
enabled: true 
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
#    external-dns.alpha.kubernetes.io/target: 10.0.1.13 #opnsense-managed ip
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    #external-dns.alpha.kubernetes.io/hostname: jellyseerr.asandov.com
    external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com
  hosts:
  - host: jellyseerr.asandov.com
    paths:
      - path: /
        pathType: ImplementationSpecific
 
