general:
  ingress_host: mediaserver.asandov.local
  jellyfin_ingress_host: jellyfin.asandov.com
  storage:
    pvcStorageClass: nfs
    size: 750Gi
  ingress:
    ingressClassName: nginx
  vpn:
    provider: windscribe
    type: openvpn
    user: ~
    password: ~
    region: US Central
    existingSecret: windscribe-openvpn-creds

sonarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      # external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com


sabnzbd:
  enabled: true
  vpn:
    enabled: true
  ingress:
    enabled: true
    host: sabnzbd.asandov.local
    path: /
    annotations:
      external-dns.alpha.kubernetes.io/hostname: sabnzbd.asandov.local
  extraVolumes:
    - name: sabnzbd-config
      configMap:
        name: sabnzbd-config
  extraVolumeMounts:
    - name: sabnzbd-config
      mountPath: /config/sabnzbd.ini
      subPath: sabnzbd.ini

radarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      # external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com

transmission:
  enabled: true
  vpn:
    enabled: true

jackett:
  enabled: false

prowlarr:
  enabled: false
  container:
    tag: latest

plex:
  enabled: false

jellyfin:
  enabled: false 
  ingress:
    annotations:
#     external-dns.alpha.kubernetes.io/target: 10.0.1.28 #opnsense-managed ip
      #external-dns.alpha.kubernetes.io/hostname: jellyfin.asandov.com
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/target: e800665c-e425-4486-9e8e-25953a5ccad4.cfargotunnel.com


flaresolverr:
  enabled: false
  container:
    image: ghcr.io/flaresolverr/flaresolverr:latest

bazarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

debugger:
  enabled: false
