general:
  ingress_host: mediaserver.talos.asandov.local
  plex_ingress_host: plex.talos.asandov.local
  jellyfin_ingress_host: jellyfin.talos.asandov.local
  storage:
    pvcStorageClass: nfs
  ingress:
    ingressClassName: nginx

sonarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13


radarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

transmission:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13
  vpn:
    enabled: true
    provider: windscribe
    type: wireguard
    region: America
    host: "dfw-86-wg.whiskergalaxy.com"
    port: "65142"
    privKey: ""
    presharedKey: ""
    addresses: "100.66.83.118/32"

jackett:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

prowlarr:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13


plex:
  enabled: false

jellyfin:
  enabled: true
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

jellyseerr:
  enabled: false
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13


flaresolverr:
  enabled: true
  container:
    image: ghcr.io/flaresolverr/flaresolverr:latest
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: 10.0.1.13

