apiVersion: ENC[AES256_GCM,data:e7A=,iv:If3fMU0xiLGTFer9lg+fm0JjU0j6eQplE+ZeVIN7Q6k=,tag:ABgR4SfVRF+ort1C9OA8kQ==,type:str]
kind: ENC[AES256_GCM,data:IWlyyIVZ,iv:xAqnTRkWrJVYCt8E1TNI3RQUgkaD1BWvxeUFehXYcW4=,tag:yJCiDf8kwWl76ycjzzgi+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pI3ilRfhlFmiyHCd6sAdSg==,iv:jvlE6/K8tSlZ7NsDKo4curGMA8WuU0k54cf5VLg1hzQ=,tag:CkkAcUnmHtEygZ3dNHcFJg==,type:str]
    namespace: ENC[AES256_GCM,data:Gjylc7yjQoWy,iv:oAmYagXjXLgmPaY0TINjP5CD1gMnBq1yMbV2KKdWV8s=,tag:IYYR9Ao7X2LJ5XgI494AFg==,type:str]
type: ENC[AES256_GCM,data:WEtJQ15e,iv:LT2LNc7A3w3eOGQ86GwEgrzzNlFPi4OcUrgq0Lv7KSM=,tag:Ee8BCnz38w0nBRhYn0bcdQ==,type:str]
stringData:
    private-key: ENC[AES256_GCM,data:Z5IFVDyarhBiK65MbVXu0513/7JK3bZHzMWtybgfn5oxpDyk+mSpgrm5dBo=,iv:nZ2GK8QcuaVt+lawHIlBj+GEhsmQw8nZ1k7dlfxd6Kc=,tag:ijO0AnE6U87mQlMOEb7y/g==,type:str]
sops:
    lastmodified: "2026-09-14T18:54:20Z"
    mac: ENC[AES256_GCM,data:FcVqyBZIBdVAayjQBW4oIlZ+r3kc5/Iang/4VeTziaRW0mgD341Nt42xrH7ABFOM5d8m0i5kVRexoDUx5tBc59cNeZhAuKL7zvQUPYaAIx5DjFnFlPnmD0SRESohliAi77jGcRNI+TjWk6IZUFEhTlyfw8xv83u1SDEGoT/+pcc=,iv:SHRkTHlPNe0Z4Oj1s+kDQV1xcqdXerTDhLLeW/nuEPg=,tag:elqCkHiqJfeCh5HYJFISlw==,type:str]
    pgp:
        - created_at: "2026-09-14T18:54:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAxovfgu3k0ukPZX93YjXpha0b3x64gKAxwZPnHXvOwlIg
            I3KkDasivCgEjdj20YOL4qW5LSNvheR6Km+alo13IlKY2rTXs27ZVUn42jLNWJlp
            M56n2dcmInwRYRG+5Va5k4yEwnuhkKsiOk/0wC5O/L99aZ0B0kbBaiw44UOzzgE5
            +6e00/Y8N13JGlEXvblqeE+UAf3NmDzFghMI1GfgBihDBqJasrbeSbGX77xZjET9
            wC4QpJWB9+PH9g+ELAoGiyYphi7Ei2t2gGo7yeVNNz2KuuihBbV3v8PTxRtJsrkG
            0MLAznWWi6vZ4xNVphn0ng87hg98DOVbCPnm3VPRkj/KIB5r4Sm2Vq2Sk3iKsEP9
            HMd0XRE856XNQoTVbuorphT4f/VgoShljdt7h8jn7wXXc/EHptQTD2740L9uX0M1
            sW61TPk2wgo251Inj/TlDqcvPswNUyDCK6LtqZXYGU/X3xRHayqGdyZf4lByUOp/
            UGNQXzyynl7emQ4WHTqUN5Idhq+zlEZKNUueVZdUCjK+cgnpW5JP9Kjk4lVvh8Px
            HtCTUHU3pfsFKthbmpgGhedEv2ZJt2nh+hB6BvVx1+CKWKA8a4U6y4UlErwR+pSK
            ryhx7UI3iWOgad+kew4zbo3N5crdgz8YqPQnGof+WDbBEx6WpZW7gUy1kmF/UL7U
            ZgEJAhBx0HU//xrQqP99Wbv3HMSl6DIAvdXuCr3KA0GKspnEdHKbmCvnCrD1szPb
            4HY1UZGLt6hs2lIDqvwCyaLw2hVh+Bfoiko0tSDDNnlkNardEwOvDTiPIhlZXmog
            A3wnJnGF4Q==
            =THk6
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
