apiVersion: ENC[AES256_GCM,data:j3g=,iv:cu4r8drZuO1WiBTsewbNy62X6jeDvEMejO0zu5go/as=,tag:sjvsajOXohYFcg2qsHGkaw==,type:str]
kind: ENC[AES256_GCM,data:Mrb2o+D9,iv:uQ1LDj7cBlJJqvvkoH+BarmjX87BRdUyShL2Js4hkjg=,tag:JLAZPWH2+fPrrZH1i7hRfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DpLuha+iMzKxuiKJcL1btIAF2RNMk901dvMP,iv:hSxk34bu9VP15/vyGXVa3pPcGhOFttVz3Xfxv93dKkk=,tag:KFxLTjtGhXPdLUKcr2MJGQ==,type:str]
    namespace: ENC[AES256_GCM,data:GX6iCzx3PaPK5fY=,iv:G3sFAHjCt0ZzL2PjhIwAUm6DLEw04a6tPrrewD7jeGw=,tag:RNGlfkyu+Xpqk3A3ma26PQ==,type:str]
type: ENC[AES256_GCM,data:ggYWe1ht,iv:mlyezDhxKDOilpIoaa2lD6FZ1SNdlp+9LHO9Y9B5G2Q=,tag:SjAi94sj688KHrGnfz9dGQ==,type:str]
stringData:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:P4PrtR1U5Z5s/OqFFgXC77KZ,iv:8lv7wAkzBOcZKG7qawkEORpQNNSZ/wDmO3jq8a9tp28=,tag:RoUfDiv3OZG1v+lujgvpAg==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:NSSjfLanW9F/h2UP,iv:DmOViJbiGxw/uaXGm4Q3Ujt9gSTf3eQS3Q8MkApr84Y=,tag:tIbiSAzoKJ/n92BcCud9sw==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:Ee1Yok8=,iv:yT+4PtOCEQa5dSAgP72dO0lGzc1Sjjn4MQWdK0naMGI=,tag:QuYsxpavQnF/WnoUPOIcTQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:BOEmZ2qozbegLzzKXhYtF9ZWYc/hIl64lqTxJ+EaLr4QWhaHLjiaOYga2zA=,iv:67hz6M1o+ygwuxMWzwcHwYd78P1xXE9HuoZdFAilBcY=,tag:kchuxgI2+3B6WUHK6siR9Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:1xjHO1uQTVRo/Arpl60rAlKLtf6kT+CNS8tmgvbbLp9KHz6RfhyOpiiIGCc=,iv:Eng4g1NG8Mscg++jvlluTvTO+AH6+jDMDMJHgBwn80Y=,tag:aPZHctl1a2WtF2uQGGfdhQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:AB1KGPum2UDvUmaN8yZJ3slDYtx89ow07DcgBB0sw9lKtJ/kSi0vY28LRe4=,iv:+JIAcMEkGWsGIMtXDTTWjo1RXEHrzu16CoHRnAGr/N8=,tag:HIp05XD9dIzjJLifmrC3SQ==,type:str]
sops:
    lastmodified: "2026-01-07T02:16:39Z"
    mac: ENC[AES256_GCM,data:6tf8qQo70Z/tLfYZxaA2ifpmZZ+ooe+j/uBuIZHeR/M7HnZQECnhOUh+9Iudq8U3gBMqxKBZFkkPkO3SIemg9gMqJgB8DFqa6mTtdi/WGb89T+KFdUcQRbobofVB/TgQUZOUJ9quwWnohNhTtFJQNCRK3DRUfW4wUMQ8jN9pgc8=,iv:0ncQpOiA3r0zwH9eRLp/4f4fesezqxObYZgpjmkNpxY=,tag:zqDRaFWl1yAPpRc99BBWTQ==,type:str]
    pgp:
        - created_at: "2026-01-07T02:16:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAthlxHBKGOThzqCTQAy21xZ7SGfE10eTds9fCEXKCH+D7
            Rmc6QU+kXaccflldNPiNz3I5gOLhnyMt4Q92p6LZzTzOD4XgngJeyhufilP9ykNv
            EDoPea99SAggYIvdhzZelJVLjIO99sJHvBQRERUVziZkDZPevqbrG6r0CGFPvQ/O
            l3fCJlRfsx+yMXHv8tWRNlkRdouy5OjW2NSK9oWCNE3EJPlxLSXg7UlacF5+ot12
            2lG3Y8ATKRJ51N/Ja3QpXCU3Qpc9mNXl13TY1Z4u49I8Q9oD8JYttmBR4mX9L3b+
            5IATE5GnMh/4ce1KBN7pIZfe6mj+qyZNDzPOsXDE+B9XFrkBhwwOZs+KmglnbMu9
            JMiA/1/+25kmAWlv4ofqJ4u0dhT8E3fkrq2FNi28fxGQY9JQgUyoSzGe6WKMo6Oi
            XCCJ9rxCRF5LgOfK/hRT2xaElURgZiPNUIFeIcfNFeG/2deXPnJxIhNbEl3uHpEn
            3O4G6DJqRmDCjE0io7fF8mPmRi4CyUkrmkWEFWSAj25hD9iygr0kMsr4BT0jiQKa
            zsVxmvJ/X8MYY+lk0F0i4jBblb/mkVmIYD3yoKb0KIojcOJTs1S/7d3zDk8IlvTR
            8UzGw6ntoXoRCiMVZ5S6lHv64FEkH8Odl4GfWb44xT41Wh937LNb/pW3HXbdR2nU
            aAEJAhAZjLVFUW7dk5t8q6ESLuGvY+oMJ1iNqtmj4A1erH23QzfavTLrZa8JFJNX
            Km6imbezX8ZtC7ZOekAqY/J0yy+F/CgjNrFA8Z1BllRqPiXKSmLylpW6+gNendfa
            ahPeCqW4n9Uq
            =bqyi
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
