apiVersion: ENC[AES256_GCM,data:Aqw=,iv:zZuTNfcPwkyrMNUPcAbxIoFmI0XIX3rQawbFS5JZG7s=,tag:YX1SFhQ/ZIgOlC+P3+N4xA==,type:str]
kind: ENC[AES256_GCM,data:VZ3ZESMj,iv:b+jwfz1KbnErxKRj7tfcszrlyxGFF9BDJ44xiLTD7Kk=,tag:rU7/WJgh6Dg13/8NLOIufA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6dfs5IyTQfCKxU9Cjp57qTe4WqlQFvpQC727,iv:5aZFcq8dQEYUCbo6rkAiIMKNn3BT2PluIy/MY91EpUk=,tag:OHmatmd8454+6z9XksluzA==,type:str]
    namespace: ENC[AES256_GCM,data:QaPVG0UIXVSdTzI=,iv:xXveV9C8daCmUXzVNkQj62zM6QA7eDdVwt2ufInQnuM=,tag:HW2Z/8b8BwMPrk34GcOTYw==,type:str]
type: ENC[AES256_GCM,data:eiRWpQIp,iv:41w45fxO/WU73I+4ctibb2wOf2lu0GRK1D03u/GLi0g=,tag:1KGsjwGYXkiY2XD9LY48nw==,type:str]
stringData:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:4qKJifqZA9O2UH6tsPCoqIk=,iv:HJrkHbPa34uwPLq57JmjnaTKBf3dUT/RljKr4mDhPds=,tag:tRqSpv3JEHm8/rnMmM68vw==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:UXJr3o3TGBF3ty0YQw==,iv:gLZcY/F4BU+rKrJ40aeesVc5AClWHKpBMPHeTX0uT2I=,tag:7GUA6AjmrphcJ7DwqxSAcA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:U+zFpPI=,iv:A0vt7T3IaIgJWEY8tgShRGfZAb5JD2wsAnSt8MhSGMw=,tag:dAbSZiWUNePS0Yd1KW8p0w==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:3kBu3l0abK630YT9kSnRBfxqhpxEyCBj0L4/Mfya1zse20gF2+grQPP2aHc=,iv:OfpWvnA4NgyHvoRtB6GytTaTdzlyiC5iVrfu+p1xyL4=,tag:CIi0mvNuSoNhZE9jCktupg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:jTw/hkBba0x1BFTR5ytt10RDioOE2/EfEhvkf8l0Fgch+6KL+1++Dt6y8Qo=,iv:hJewxAXg9jE09FsnOlrrezqwwrS1UQVjPuCMsSmGk2s=,tag:4/rC8OCZTzOLyc9V7clz2w==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Cb7nl6ef0c4TKoX/UF9EJg/yo9CjWX290hVARHx5E8I/WA/VRUNz3Aj1a6Q=,iv:tVlBmaGDoTyDJIPGmp2AY/HT0NNCNxg0iP47wAs4QO4=,tag:6ZesMbyvbVnv5ZfQhxoPKA==,type:str]
sops:
    lastmodified: "2026-03-28T15:49:10Z"
    mac: ENC[AES256_GCM,data:e9lH4Vhy1tdnKiKbF0Op5tBsz8+w1Gjk5hWJxGq7L1knU4PyCkN9Ry5NbyeYvk4QEVJQLnZFsQIA9WXjWOqz5pC2yAGW2t0FjuMpR+bnffLZXbxp30MlFbDyhPvP+EGBM2la6Fj99DO8GLemVjiAH+TuaxkqzMp7gxU0agYmc5E=,iv:CY9291/znXKX0Ojqk+knQLXqpmPUxuBQi11GvjFlapg=,tag:C5f+FiGzfH4mhTblRD6epA==,type:str]
    pgp:
        - created_at: "2026-03-28T15:49:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/+Nc3kYCQttQ8fJOWTmtIT2VdjBFsKHVIpiJDMyETDu167
            EQlkyOh42Opup8fWVr8qgg6StJ2bcVA4w2RlqjN1nph7NtHBaPOgfS+9tGnpvs3O
            TqMRySTJRZ/Njba3ic66DbX09Q4sV9II95qcqJtmoT5uch8aSei1K4qf9Bvxh521
            WEkqgian+dvjvgjV2ZjRUNL+LK2OmdxAfeJmFDl964QbSo+ZCG6/S5i98xDlRKMd
            CnYGqoLxfBAPyVFfcP29RWCZY08LJdhKQ5w4iVHrcUm6jl6l/MCJsMct15B2Kn6X
            lzHv+8ItxM+aKgOC7FyNjRQSjOgxb0uKLy8CoEOf75uBAVMWq6lMmi90it1rg+Ed
            3Gz2I5g89HJO4KVz0psl334GVTbDYjHc1wQMt3pjd4NMUUkSM+dWzkpc5SLop8bY
            85csjcT9ubeyT1gkUsg/XQ7abHixoyMorYktTqVG8Va1S+aamXfzIn8ZbhGDKgGK
            rtRsQyp+3y74SSDBOlDxR0GWnD3eCoQ7uhuIEGWwQsN4AoSUDkUIIZJdocH4fLR8
            FDfz/jnoqH3R5XWyDuKchg+phqEqSrneQmBx+cYpaL1nA9lJv+EcoeISJo8oK3Ud
            sYTJG0gvRCAe4TBuEX9MGdzqy4btF6G5rLupwjyw60KP+SYZPgOTz51jXvEhiqPU
            aAEJAhAqcl2jI3vcpVfbTw/E9/2bbtnW0/d2xOB1KSZVeueXYx7WLmqPTPSL8yP8
            O8hW+YQzwmI27sReBPAXL6IL8XkS0mVqPMavy2dom27fAUr0pIIOTjmjbHCuA0Kv
            IoAOz/OZi94+
            =x/a4
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
