apiVersion: ENC[AES256_GCM,data:Yq8=,iv:xkCeOJUI92fVMltUP7naDrlCHJtDjIPE8/cz1E6mWOw=,tag:UD9MfFsFNFaFtWfNIjFcwA==,type:str]
kind: ENC[AES256_GCM,data:7gQCWzcn,iv:c5AR2Y/NYVL5AnLwrDcAvJg0y8egRetThQ+O89XVg/M=,tag:ubT5jR0EWlAMeM3jk2nA3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:24YiGvbYmhYA2ATozAhIyccfdszVXyyMSg==,iv:9b/KCFQF888avBBa2vwH+F/0mLZQ0KYYyybqyYR/GYU=,tag:iWph3YlChcOQg/eUd7/XEw==,type:str]
    namespace: ENC[AES256_GCM,data:AhfNY3cLSbTV298=,iv:gAFeZ4WlXP7qDqTqzrLFxdEM1Ocj3zoIO8VmoxAdZrc=,tag:gIevT7JTu5NQKJxPBhMqrw==,type:str]
type: ENC[AES256_GCM,data:CTEb1J5r,iv:wfX5HeNGWD7HTv3mLzCtmOvSe+0gFr0km8jl0yQfc7A=,tag:yZQckOExiQpOZjghltVDjA==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:2E6oUOPsc2TJN7rFNOqmDaQBmPWXWpYfBdmiHOMj0PL212ipHjmHD60vnDs/WY0JQ48ZCiiTSq5DPuS7Q8VuSWFEYU5sqqCMAQZCTQ==,iv:HkaktZE7SunFq1tsjUfTPYBNpxKCPxJK3iHZTa6PURk=,tag:YxKnQxwLjAbEL8YF8Nt1nw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:rDuK5nibaaDzOg==,iv:p8uqgO5hKcFxSZ8Xa6eRDmxD7mS+cplNM6qrDW5nBcc=,tag:DLmlEbHj8qVrFX4SOLaA6g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ooWqrAn3cbHv5A==,iv:5T1h5EJXjh5zbkpKPKCYzqYfL0+Kgzvmn1QTFtqCVTo=,tag:x7CeO+PW1D7EdmY4C51oKQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:P2/BRBDV95ixig==,iv:K6PtDSJly7kSOYRQG+W9/JMwzb9jJbMkSzA+Wcfpy3k=,tag:RYzGljOxNiTwhmFyH1Cdmw==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:7nVp3XGR1ZKu9TYlXWwkke04Kw3iGFse0RMOreRgRKHh9vauQmkmubTqpby7VObvhyZNjMRQv/aYD5w8VXDWxBahqvO1FivbQCzHf2rHbekzgfCkGCpciHTaKoaE5a050UTk3rdThPegKwVE5eqsuh+gji7CYKiJYjZp3nEneRo=,iv:+RjmpRWuxtfdk4uWgs3tyg+kgAKQ2W54SOJ5zZnqCFA=,tag:RlzI8XQYOkDLkd7Qt5wQOQ==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAhhfP9Ekm8rQAo2Q/kMwJXpis53JyZdghMX6qrFwNplsB
            cdeRdldD9nlX8MrMmL9v07cZmpT6r9DLNzLvYKwtWRPKM6w/QfQ0s/wrXu0QG55X
            TPNKG3GqN85/pkWxmGeKrdQwBqZl8cvWvuXH2GQxOC2IY4q9sx85a4KSE+EIsO2c
            BlHI4dEgw4WGXgIhaAX1N3CISaY1pMCFF2q5ui4wYle+Z2jvnmPljHTR9D5Nrq57
            a+HnTCsqvWeGbdOIgEns/8KBuY/adtzYSzVNUN/3UuXVQBTga6Rmw1sFaYeW0Wt4
            FWFgEyHfb0NE638LVwO0/f8RIG08n0IOCUiZ+aVjrjdVozjD6UFXgmzqYlIz8QQG
            rn02IzS1gtgIB+BDDqw+jh07E31qMHQCX11RyhewfGM+YGcpqkylw5UayN+mWUGc
            Kms4A4oYb+Iuw0ovJUOZponkdBn9YQium4WIbuyZfKn6C/a3EhfFWmv2YGMqXUrC
            DmwH8TVdDf/NV+n5mTm6lE2W98pKZca5FyjzNjE8dYb4le5NiCI3EnoB6YeFXxLD
            W9oLZ2Cdjkt/N+tFrKHQ+B5ZLQLlYYaxoyilFNXkOXob/2pLZjnyTdyqTLt4TZ0F
            0xjWOfc8citOrJXzMhW6tuAEmqCEc3zlLU6avhiYjbmvb+4BQd3Gb9wqt3Rdl9zU
            aAEJAhCiPcDR9h8J55h3UtmMqEWQEjI5cYiiQDkt8yh9piijtHQxJj09En2nXtD0
            WziRHKuD4nOihD7V9lul2EQfbEwAiNQLyaUJB4L8w2QfYIpj2FxiEsk3C0W2TzHT
            Hq+A/kDF5wTw
            =t7pr
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
