apiVersion: ENC[AES256_GCM,data:LJo=,iv:lgrSM13LW1ixEm22eDIawGBrCLgynrX1yXi+jWlPJoI=,tag:pYQA6Esv99xBeNjmLdSapw==,type:str]
kind: ENC[AES256_GCM,data:veju7TyR,iv:VN/sylxQCbzLLibIgc70sLawjivZMlyW5k5WOd+kp+w=,tag:XIFfHFpsfAmzS8d6dQqCCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZfALFGm0c/9w8a1qDEHXGJ+JZpmpLWdFhhMV,iv:IXNYKRytO+Fa5V8EfBNH4mI1foeEk35qeUdZ81n4ln0=,tag:EMvdIrV4P8NunVmxBmvVGQ==,type:str]
    namespace: ENC[AES256_GCM,data:PJgMNZmxWu9Eu3Q=,iv:wOnfP3vsX61yiHrujQCZrAK2z9a3axzeXZdzrmUwHvI=,tag:fcEOTWrif/InJi+j49QCUA==,type:str]
type: ENC[AES256_GCM,data:HoupYUzL,iv:CB677OcBcTFCmNmcVE986M6c50QeaknIrghvZBN9OUQ=,tag:lB37TebwVmiGq5evHKYFUA==,type:str]
stringData:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:dnWtqx03Zy4sltUa7ahOD+Y=,iv:Cr7hjyAPpnw3KhSnr/kVZiVAP1ffqfQm91ZO/tBCNSY=,tag:gDn37L3JYAMjelJn8h1cdg==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:JwaBpszcZFDcax6DgQ==,iv:7Vr/QF68HNCL5zABuKcrGkuOv5xjFy2GIWQL2QoFKaA=,tag:8aTnjIT1lsoS6JqXs5HhyQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:cOZR3X0=,iv:AgAttQJu156KyBZ+3Qlhi4/a+1SLTZwDjqdHSHrhzqc=,tag:jw6kGnZGqgw+Y+77dPzouw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:WrfFeAH/OtDgRbHKkSHJsgQSf+YRjwBdi9cUXljKwWo+89z2WuuSyMj9cOk=,iv:K+FTE/6VPZYL/Awxyg0J58Z6tk3yfxYUPD9t7iXUkj4=,tag:dRQc+h+nmyMINNXKDtjUpg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:lciLcul25myWBn4flI+lAjABAbxshSAw6Mb76HEuMeyrjS+G9umcTQpKzX0=,iv:IjbiyTB6m6m4p7WUkZls4F7o+/LI7VOmFTKJSfES67I=,tag:SBFHmBn2sufTngqIXqktmA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:EIWI0Q8f2EH6mAxGacrrOLWRgUWW5nIkTCz6zYArCcgJENTgfbJChLf4Q0Q=,iv:F9BvNHJEjYC8V9cFu9S6gur5t/qSYyJ3Eqh4YJ6Wxso=,tag:ulTWaumyEDucfY6KRc0+iQ==,type:str]
sops:
    lastmodified: "2026-04-09T02:27:28Z"
    mac: ENC[AES256_GCM,data:XVg0ShuF+CXaQnu4y3D7zC1bj35WE/2wj9sVtkEk8Eep7CsEImj20+errK3rvqEjpK2dqaAAhZ5HD8ldA3LeJFsVlsBfC0VNEZ+jKun48j7K6Eag6GKuOEd7iVkpvBMFRhQhR5+CRkUL9rlrmjyP5JgThoFwLM99ZlfqrFUIOf4=,iv:ZZZh1lWlF7GizTnLdwHzVZvFEBSBt7n7idRb9gna1a0=,tag:6pTwDzoWKbrbGChq/Cvh+g==,type:str]
    pgp:
        - created_at: "2026-04-09T02:27:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//clRKyZOkO8wjfNIltbzldHlZiHiu1sueywoDEddPYOxB
            hqUl+7idTUdvlwnHCGQYT8u5laJ2xkikrA2YC3q/HiqbFLU2CtruPGEaAjF2uhJ6
            32RYYWfHQZ6pxPDCgFTvMG2asPGHvZhljlclmxTk7qqBvCNC85YlNbs89L96gZNk
            YngkIjaP49grK7CdZU1PvGOBeu4XrGk4L1yRFRGY220aN/97hmgH12dZwytKhbTV
            PmisLfAq33/0MtknZLs09mIamhAGcv3wArlSPAwlvnHMKDH2tKUhJWN3+yNbw7N6
            xbaBaxeBNfwXg7Lf5PZjUGsyJD674zq4cfOP742198TpDyNyFC25CCxL5z/l4K/z
            BotvT3bKqsdX6MxBeXv2zurkjmfppz62DhP+cKxCogm5rsdz2QHwwKr87yDxTgtf
            2kxRqoYhX/yKBYUmHu64RvX8vBE2FN3gjga7v4ktzbgdPVeQuyyoXlzcBwHt1oWa
            M52ba56bMycf6vFovr2iafvsvsjTlkZ0ONO8giBeJFjXuhmtrA9nRZwvvEYTTbXC
            dghQvITWuIlfDMpKuRiCHjrjB718u1JX0TOhmHuG/M8SaPrk3q7jyeeSf9j/jHxP
            BM65IyE8CQFWVhtlS2Maju7JcuHG1LxsrI6Iqs7el6Rtw1q84tmxM/otbFR+nj/U
            aAEJAhCu4+LW4rNf//obyWuFXtD7j7evjFWPtiBMKN9W776B+ct6cvO3fD/H8Rnd
            qTZPmVnHU/MWOPxIYGcvkRVM+Tc1E3SzpRY2CPnq38YkKfoa9iD2Ec6r3V3MAjyp
            oATPaUlugOB7
            =xMS9
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
