apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
    name: seedbox-autobrr
    namespace: qbittorrent
spec:
    jobName: ENC[AES256_GCM,data:vJp+coFbI31NXDYX7D8C,iv:oTYpX1TwAW8V3LtLzvDpBWLe++JdTE8B2u9UEejPH6A=,tag:44bZfkBUkKIhIcJ9tt2C8g==,type:str]
    targetEndpoints:
        - targets:
            - ENC[AES256_GCM,data:8xblmRn7I/tzTZIzhl/a8v2MiRk=,iv:9XWBNv49CuexliOUhyqdzoVzB/H/IqscQkdLuQ3Cuzo=,tag:5F3tZFKGLFCl8hzA3ZawwQ==,type:str]
          scheme: ENC[AES256_GCM,data:qKClWyM=,iv:2Vge5UlKFMYr3M6eie8ZkMRK1n/Y1GAvJNN5IApMKxE=,tag:hbJmdeS2S1D9kcIgR9IwaA==,type:str]
          path: ENC[AES256_GCM,data:7PQIrajT/i4rG2HLkVWieI66PAOsvWOS,iv:L9KG+fYRjRSQa0B6VYGDGDZkN+zksgoSefxnGm3MJao=,tag:rQb5dA5bKbAoE4bi2FnX/g==,type:str]
          interval: ENC[AES256_GCM,data:x0Ei,iv:kJ1hY9PXLCnZsXMVZhTZfH4/AybKSGNvnyPB5jYrGlg=,tag:02lZr0K40t3JtgU1zvOlAg==,type:str]
          basicAuth:
            username:
                name: ENC[AES256_GCM,data:N+0UqD4JOxLPNvU8OBri,iv:NbHELuqIC469Vg2OmlnIaJE82s0TkhnDDoJ3GsJL0cc=,tag:HUWUcUhb8SGmGap55m2C3Q==,type:str]
                key: ENC[AES256_GCM,data:j62CFZPHOJb1D+lGqAFHdRVwq/A=,iv:o1ENJsLufsAYOm0NUIJM92841tr5+8Y5IDGwkdnnh+4=,tag:6Z0uH0nbbDM9yVeIEsvPTQ==,type:str]
            password:
                name: ENC[AES256_GCM,data:1A380EEHkJdGyjoH33wx,iv:K3zCs9OPFsT0rDTWitnD89CNULvmBNDJEccI+sNCGPY=,tag:ocCc0+/nNNLDC1bkky/jKQ==,type:str]
                key: ENC[AES256_GCM,data:rJLiSfvr57a0gsUNJWMc4Nfl8nM=,iv:U9OyKI20uNk5crDtTM9Z7EoT7jExh9gWCf/btMGrDr4=,tag:ODZFiMz1hLfErQ7HzVrHMA==,type:str]
sops:
    lastmodified: "2026-10-01T17:32:20Z"
    mac: ENC[AES256_GCM,data:/hFg2L3g08z6tPIz0UudgL2YDHqhfDek/3mdKaUNPrcSplqDQngH/UJIKF72A+J6R9eUR+1aYUT1ucE9bh8X1h4aT6AEeRtcp9q384YlwFiapsIxhVX9bUtEZElzABbaSdwx2X/NSmoA7yzuil/ntS4jqi4Nf+7gCu27Mi3YAo0=,iv:IwM8GHoMYIDKA9DSUSclUBuO8JzQFtwsOlUWci4aL6M=,tag:k9ibb2GKs3xZ1UE3KW9yEw==,type:str]
    pgp:
        - created_at: "2026-10-01T17:32:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAxufNix6Xs0hf7LL0tOSU+OmCVKteBatd3ScsxfuK42Oe
            Ek5e4a+3lxVxz9Gd3yDhf3GYREdrzXEJzLHYFLXl3nVBJWDVTTruEOH8IyAalMTm
            0CUbk2Ndf/wB+DlZeShzeccMpfdD278E7cnvQLiRLLDcHJdM9ER+zq2jkI39D2o5
            YVKK2vqJMUKMoj+CEW4qbmr7gusG0gP+vVB6PXOH/0+NDnt+3zddQxiTWja8NWej
            QwfD6KJxqCSEPgvldKYFgyBPgAnDniryDz/ozPScFd3czF/FW0mV6CQlBqTJin11
            TZEZWsklvRdxAYNdUWo4TkHT0CNlzp23rHnSZwpzsP76V0FYLKmi+YorK3OsN0Ni
            XIezPZts6R28pf5zZubDL1rYcO8c5XlKA2lRgm8Jwgs4FZP/W+Ooq7MpRwqDKS7Y
            Ip1z/LD3U8MIgsUnmC9efY98rjWiHXw3bVoi6Oj9qGXOD0PL4ckJsqTjrkDemSxb
            FspV5RIvJtCvIAKnKOTH6kus514qV7B8uqjlla4JWd5UzTGmh8M7ZhTJ9WI0Wd2b
            Ba6mZLk+Lx9G9++fPewTKoswWEfuVrz1HZDRJnc02d/ym1ZEOkAhINLH/b0VBrZx
            3QgBN5l0HN3BMVBdtCHyu8QTnbkN6urRruh5dnRqdAeffzyP5cIYM0YSh27YN2jU
            aAEJAhAClf1nVo1fxGRgdQctyQYp/P3OytaBuFmlqStuRJWGmdib/2bgQ8sni6VP
            eSY/dBpoNSLQbufL0XtZMMhokYIJmBOCPjfouxf+RLdGtgBHywCo6o7qtgwEnB1T
            uAnsh+21kYcQ
            =/X6A
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^spec$
    version: 3.11.0
