apiVersion: ENC[AES256_GCM,data:gCM=,iv:c2m0jBmwQy8QSeRdmSPcXgQoxd1ZmAcDG0xQ9wOnQAY=,tag:DykxqDFRpGo/8bPYctVVbw==,type:str]
kind: ENC[AES256_GCM,data:BnQkUheC,iv:qyJ8G04/65QDMQMtLCFIOPu/H2No/AE692UD6ybk8SY=,tag:o1I2cdL0viCxX560QH5tDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/RKFrgQF5URRCB0=,iv:ADmAis/WJ57WPqKTI32QXLfv2VdtWhNQJ2sepbRbwNo=,tag:NDs+1b/T85Qjvq5dA4HUUQ==,type:str]
    namespace: ENC[AES256_GCM,data:WiVNDw==,iv:vaX6hsoN5k08Jmlm2uHXGxnXlo9EmtroBb2iiHXrsvc=,tag:v930V/gRhCwChFSFRNhYOw==,type:str]
type: ENC[AES256_GCM,data:MzYcx5QH,iv:AW9moQTByWZi8CEvl8YAe1l2PZZvT/uaelH15rcrjPM=,tag:F0W89+srHZ0QKE23vFYtgA==,type:str]
stringData:
    abuseipdb-key: ENC[AES256_GCM,data:0ziDmg+1aO60GagSUfcBQ6d8nSCHSxprAA0n5NXiqp6ouiAiFs3jLwrIqHsc9iHOa9t3VEP6z8I8z3y1kSV0CTCgIUY6RqoQVhyCzF5JKqA=,iv:7i3bNm1dC1GSY63PduCEov5lFKjC3zhY702BwBG3/wM=,tag:2SiLYlvzdYyv1JqgPzkTfA==,type:str]
    hive-password: ENC[AES256_GCM,data:c2lrsDYUy1XzEGbAvdAXBZCTsQs7+tb71b9xga46S98=,iv:++L3yIsC8NjY9hSg6VHc/+qGb6OwSQG9axW2Y4sjTSo=,tag:eXdwNaVgZ2CmIl/pPTX1MQ==,type:str]
sops:
    lastmodified: "2026-09-17T22:10:57Z"
    mac: ENC[AES256_GCM,data:FXRen5oU0taDrx5RZWBi6h53c7XwkMnvuQWMRC5jkhpBP56ecGHS08PBSVm4FJ4WK22bAWNCmH1kn569BdhINy7q+MA3eN4PVpf1vb5thNRrwCuEoyX4g8+AJcoj/j2lTuw8L/weaLE8xjm+nrMLe7aByCSLJIMbmWq3AiXWDQM=,iv:l4PW5PsBpZSharuLzClk1NFwwdf1nn7Tz/SDeOF+gLY=,tag:IhBKd7jZoSlvAJqjE3NCfg==,type:str]
    pgp:
        - created_at: "2026-09-17T22:10:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//XKARiF4c8gFApnBMfzm2YifoA+8ryWGO2Sjoh8O2lKeR
            jK93GoOOpkN2SkXvkhZZHZ6tlbBXa4DE2SCDAf6JKl/LPp7zG4kiAZqwgk1/GDX0
            GeirSRmk7uyuCXBDITB0bq9QGUMajPrFPiaY28iyHqB1K9Lb36monn+lpAbQAmwF
            qYR4v+5WfoE/QXf5EFe3CGA4Y6yi182FG5e/whHmv7qtCfIMxeeyTKlum6yXEsfs
            7lp/BYo4BMrRjqNaZEMbl7bMDTaXhEU+J7TbbYJv3tudi5CqxEYvqyZb1ks+56ai
            vBKyfjfiMwjt38Vvxazt5A3D8QIOhX9XkemAXuyWUdrt+vKohqT3WS6lcP2YFEW4
            eknWJOt8p3wTubLAc35cd99PiN65rDbH4R1y9BfseEqDf9YRWeDvX9fyf/SH7Yoq
            q8gVdgKIpVTNIY47mxTI7Xl56m1BR2ps2JqJFPzLAdyldwja7K1yoPDkcFS6T2KU
            LnO0u7Ooapf+6Ej7AiQozjJvG9qXVIEQuKJOKIhPxKeT/PJJVMbApIe+I1YzjHt9
            +Ppd7Pno5HJWFh+Gwpw1U1wEV673B4e/f7z9NbU7ZXJpP0i31OhVPQkyVPTwyto8
            WC8mKs30jyamoJf8TVzZtRlt4AxfkLi3Ydf+vZFUU6FXRaUX16rcibrFQ2hX7ePU
            ZgEJAhBKxz9NunFK1Wxo8nbBJqfPkWsahv5Upa/7IJ3RElInix0ZMUGN9q/UlCPW
            dK8c7DOKYPuTVcH3fKstgfAwcvWbm0ZEA6dDO+01IDGWbdlMdR4EpmkVvECLIiM6
            5ipetSnZ4g==
            =RFnS
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
