apiVersion: ENC[AES256_GCM,data:ZlQ=,iv:AUydPC7M3dTmNpR+q9EwRCz0RLiJob24wXPiKeflQGA=,tag:fQe5M/+0klTRMMdnGKMX0w==,type:str]
kind: ENC[AES256_GCM,data:cXsoROI6,iv:e7FXIo7XbizND8o4EZ/9kQn6eeEkE8wGGF9BBf3d8EE=,tag:IMvejc3L20iGl+v7NO2v1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E8eYIWxpU0iV97c=,iv:2p7NmgJhOONKQF29QTsR076QJgbqlCVyDdfQ0/VEoLs=,tag:Ylv+LdT6YMNRUWzN1Ac6nA==,type:str]
    namespace: ENC[AES256_GCM,data:3yH9UQ==,iv:CY/Mpq8GGBeuxySiXjv2c4zuap6cqPw99SvXmAgRUZA=,tag:LGFj00KUOHKPlpTSWD3YQA==,type:str]
type: ENC[AES256_GCM,data:0ar5ivBR,iv:sJG9Ey2IpVPv0VwgbH2/BvvVWM8OdBeFzH07EZO5l7w=,tag:59aP5/5XJANXccJsYR4DFA==,type:str]
stringData:
    abuseipdb-key: ENC[AES256_GCM,data:7FFJ0ZeX45uDEp7Up2JAcuwXizCZhA/VvQrnUszcybC3/1eYiEMro5LynrJGCUvHLfqGOOpbOi9Sa1QCc8jLuv6A1MuUyLbw3kBcnbwhgiw=,iv:LIPXoZmiNCyt7Kbny+hEhzTc53klpsRsfcrKqJ3Q/dc=,tag:uJ/J1PSonglA9d8twRcCkA==,type:str]
    hive-password: ENC[AES256_GCM,data:2CR/7o/m/yVKNKYYdkCH05JCDAxWtdTrmeLFEXFo1kk=,iv:iQTSPqgnlY8VuLWKPVHtGaUlUD0rNCwQQn57QsOUod4=,tag:uRGYOkVb8sLNewbl607mZQ==,type:str]
sops:
    lastmodified: "2026-09-17T22:14:35Z"
    mac: ENC[AES256_GCM,data:0Z8jwr90Hp3nG/ZPx2xRappITa+jhZqByrzA2ck8dNRtTVolfzcIK7RFL+Fgg+o704XgOBse944hNm2r9peHbONf1PksjczVD19Vb0tcNTRKdmyTg6GyIArBcA6ysvNtF0/mUbqmtejsB5tdZ+9Of2R0YKZgHTSgsSOHmy/3tNM=,iv:xCVKVdm9/xQdmJAYzhEhcemIgOOmaEn1bTL6ZpUUsUA=,tag:PGeUmFr5vb+Oed+nRcntIw==,type:str]
    pgp:
        - created_at: "2026-09-17T22:14:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAApi370Ojds57WTnqLndKgd2U3vZEo4VRO9V26UP4fKW9l
            Ascm8MgLEPD8IIeICN6HXx1s0cjA0T/AY4IUsKjgiS38qCXTbf8F/B6yYGfsW1pj
            VBo81FNkfRnvbI6GYNW/rT5I4dbNhX1QnvU3MVq79x5zgviq3Yl+hFdxXr3nHFSC
            ixMT7MAEy44XiJjyAbk00rzu6RCUFuGJI2/ZGgJQ3gCVTJseRevsVrogVEP/0veP
            IgJucgE2jPBjfryqw0nibbgJmB4jh/aPEI+pm65kxvMu2WLYHfclXCZ/adMxBIMW
            vO3QXYoanRA0kNVvty1udRLDJB5qACfYxT5R/zMHHw9rnLbtbCesiEp0fEDKiEud
            5I69lu96BQbBFJO4M1qfxe0M1lhABoBKgIW3CGGEDvERqO/1xdouccgtYh1+XFcr
            m2FFMrqB2XwO1VMuYQAadoC691UJ++9D8pX9yMhLGolnf7K1DrmPToB0lDi9nGWO
            mb45nwa8gxwc4Zsp8ezuPO2PgWnp9iTisj2Kc3oqjPAcJsbZ0TH82CL4ign1GaGN
            TruE/QymOMbUpLcU1KT0ga41B0Qj6S0UI6aPvN5rA8/YhPLi/BUgxybbPmehHKm0
            LCVgbHQ8/W1N2obo/pS6VW705ZIvi+rEsTHa8xiYebHkbvzs84I1EJb7lnLg0FfU
            ZgEJAhA5q99MB5H1wpb7gAD06clfCD+oG7j3KY6dFU9Er2KjyXNVT53MvYkHYoUP
            8vobv0+U26M1fdJS6797vBaNAPK2zpMsnzhInDIxwRQgl0ia6dq8OpVgV75jq4Ch
            Wr4k7F1x9Q==
            =q6a0
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
