version: ENC[AES256_GCM,data:dLuvy1Sf4DE=,iv:F9oMBN5Puy4uXVUyp/9rIDx817ydkH0PV3ejisRy3Bg=,tag:scZkkojR0hfG2O4D8/wWQA==,type:str]
debug: ENC[AES256_GCM,data:hpW56Xg=,iv:PH+5m7Vb9w9t+/nVziOejhEf1ka0E6KT75EundnyCik=,tag:l9dZMsr3ZKowFhJgiFAyZg==,type:bool]
persist: ENC[AES256_GCM,data:eIkf8A==,iv:CQgQc+72/OpeTSB+vw/C0zDYnLLIbCi3OMseuMkfX88=,tag:mk6z0x+3E8+4oX2fi0XhZg==,type:bool]
machine:
    type: ENC[AES256_GCM,data:ApUn8veQ,iv:leaUbotwyz1Y/l1dsG0ypkYJlApvSYE/LV/QLMceX3s=,tag:btnpEe0boBVh2LORXCBCUA==,type:str]
    token: ENC[AES256_GCM,data:hs0IBeRM2bWBs5mv42gY5bbTcOjtQqg=,iv:LF5kda+acpP7wjACnM0jJbqEgJ4Z8wz34L0Arg3Wx38=,tag:RwQY9JYABhdZ1ej8FY9CPg==,type:str]
    ca:
        crt: ENC[AES256_GCM,data:SHz9BNhU5EfJUVyw5pFTlr9izaoa6NLUNn+yiTiv14iHql5kK5l56eaeX/0Zhg/ejdjLb/SOqc8legHAJa5ZCYWagyDCpIsXgUC21jp00L6BPGzaX4bDBu6SPSVoGx3zNNHCElyNd5InB8/MHrb8h/QeCbL1mqoTOYoDI5z9B9lyBTMlaQSfP2x68swdOcC9JJyaHKIdXGjXyeRiQWjU2xaY5dA9+ur6IvaVI9d4l6zK55QXM7UVIoQ+S31hd3c/7LzQck+y5Z/aWa4gchguyrgWVcMudjhCnVfu8v35mZPSRgXWRKzE33xc+rWK+oQ+yDSpx7zKumlE1p1FRC2GSyXc2MF37UCDb/IUY63HMLXlMSkHKmGv8Q+NhcmBHm9unpe6z/JAgWKIaqQXhUGV8XePnkv37UZ34MaB7pmvjupEBqgAPm7nT+xUJiWPMQCy/3zmI5VbmRx93cbqj6+GVgPYZXzE0BgN0SHd9MgaZemFcXb4WZv3sXT7irmGvEWGbnWXaQLyTpE2GUiLSjHEO1cCPTMVDv9IeGO8VqIME33rONahoygbbrlNx1WCZQm5Z7GNKISoYq2wcth9FDsHWhzpo3L5KTjocOBzhmaC36tFe2ARSqrf7VvTDIdBcX2cn+tN/xXr3U5eoJLVkbvRxPQOUvrhVXtfaW2vpUZryw8lb3toMVTSbyOATkp28YEca61LvNCw4lWTSP1xLIfp/tmKodjUd9AR2XCGqP1mnj7aZYNFi7R2lGTPWmAs6giqnejjbcZhXrHTOklh96zJqTdhfNSWNqbuifwfMk/wQsSqYFNGh18+RV64gX2fqHK5SxkJ6MEmZbxefLInx7/cmgmnWEVmcVbwv3kh1DCtl+wiRgTj,iv:HsPcKhUszS1pLWX6Gj+QbeYXaieMaaRnldUQgblRFXc=,tag:Ic5p+1Ri6nivhdJa31GxEQ==,type:str]
    kubelet:
        image: ENC[AES256_GCM,data:VTg/ZnKqlIEuhLExjuAlohX5CY8abvOuuMtAR6gOcIANoQ==,iv:IuHs4In9PhAbCuptl0fpMOtCke39mIHVZAXORtdESOE=,tag:iKmti/CH0OMGAG5BARxufw==,type:str]
        defaultRuntimeSeccompProfileEnabled: ENC[AES256_GCM,data:IFQUzw==,iv:WTkJbOhKM1p5gwvL2Vb/TrMFJgCXb4WTbA7d4XqMMEo=,tag:cBlS964Mr/XXoiZaEvruaQ==,type:bool]
        disableManifestsDirectory: ENC[AES256_GCM,data:movsww==,iv:ZPRz7J7MTlHO+0cWgsnqbLGFSrD2jCXYOrdfcNT6zzk=,tag:vpiFylz1AbP114SoM7Ditw==,type:bool]
        extraMounts:
            - destination: ENC[AES256_GCM,data:aoGv5jOjFLaR6UyEuAJXAYM=,iv:32fbRDLIGmzM1kZ0aoX2kwWDGPqyw/Lm6kJg0F91dDo=,tag:1AjyXJra802KzAuPhZBNOw==,type:str]
              type: ENC[AES256_GCM,data:B/Gwpw==,iv:lQY3FjYMuo6yHENlWjxTJa7NqT1nksm7BRsWbf535LM=,tag:CgV4fMiZcCoFndWS+AX6sQ==,type:str]
              source: ENC[AES256_GCM,data:P1bjbc7//ymqndhKT/J1F4M=,iv:iSQ4/AMGFC39Qy9vukEd711uMloTs3FOJpeOfU75/x0=,tag:PqwOloUUl6FDdfPJ2zYelw==,type:str]
              options:
                - ENC[AES256_GCM,data:dVMbZg==,iv:GMXtSQGcomuahnr8z+bPIvhc76NKkbjHu1N0NDXbgHM=,tag:jcPUhRGCbvahPGi02mRz2A==,type:str]
                - ENC[AES256_GCM,data:G1LJDo7ISA==,iv:Upj4RTkGKKjtwNR7i8oWKEORY4osO8okJ3GqtSEMy4I=,tag:3xkdg/YHppI8Pwqu6oiUwQ==,type:str]
                - ENC[AES256_GCM,data:1v4=,iv:VJyvDFM8VZzghBe2yok7Hblh8NcFfMVHvztiBc0hvc4=,tag:HZzwu5+vwQQdE+UOBmQcHA==,type:str]
            - destination: ENC[AES256_GCM,data:bIGGfQAJ1SkkLVYXxkFPC7maidYXOg==,iv:RuCsYSVZdBJpE8x+D8eV4oSlA9K2IQTrtpZHffC+X+s=,tag:/3vtG7uWszipVv/L2X/p6A==,type:str]
              type: ENC[AES256_GCM,data:khPUCA==,iv:vmmoqV3feIxmiCLIHLF9G3WneqMW0YDPDlLQUAgXlFM=,tag:VAviD5I3Awuev08zr5w1gw==,type:str]
              source: ENC[AES256_GCM,data:NhsFyYNkY7xGsmKiSzsXG/588x06EA==,iv:+Vi86EKKMJqHArUh4KAITkZRGc8zApER6OrBnqDICSE=,tag:yUpQHDWuS9U+9gYcCG7GOA==,type:str]
              options:
                - ENC[AES256_GCM,data:WF/Fbg==,iv:5E8SJaasZjyNd6Nn2YtceA+EoD0F4A1EUe89ferQqsw=,tag:FLho6h3+mzIKWVI6BeElLA==,type:str]
                - ENC[AES256_GCM,data:zKDlwzF3cw==,iv:/s1tBvaPg8Xc6BD6ev7pTpFIPl3bBJBJxcVfNgMBmNc=,tag:noyvMxne7FispuI4hxXa/A==,type:str]
                - ENC[AES256_GCM,data:XlY=,iv:5491XjODVtGhITh0qwBXbwD9Qvj6mH8Jrl0wvevN4OI=,tag:PcMPSDnT7TTlOy9Un36mEw==,type:str]
            - destination: ENC[AES256_GCM,data:eLCTE6BEO064srzvUkQ8BrnHJC3suES3,iv:Duosx7a3+D3b2KDHa/WeT6LU/6FnCHe95WknEfhASiE=,tag:f8/3IHso5oiI8o3YrhCOoA==,type:str]
              type: ENC[AES256_GCM,data:TdioFg==,iv:9yY1sZ+cjfHnRw2hQ9nCyAoS840M8GJ2g2pBUipQS4s=,tag:213JB+zqjG7xbO/OY3CKww==,type:str]
              source: ENC[AES256_GCM,data:iUUzJcTcww9pqdI/I08HzMANo2Lj527k,iv:Yx1Yw7w8m5gY/JIMtiOiXvHUXbp3stDI4YJWw9tFOp8=,tag:xYarbLmCfU67pxsYd7cwBg==,type:str]
              options:
                - ENC[AES256_GCM,data:prORRA==,iv:p9l5JBRxT0J5Va+sTlIfGRxUVSXFgJeJmrnJRgS2yzA=,tag:ydnSPm9WpWxcbLzzbxzFsQ==,type:str]
                - ENC[AES256_GCM,data:VUh/fjIC5w==,iv:5suOwEF3xxZSJARIlWcA/E/bVrE9lnJ62QqUvO1f4Oc=,tag:KYk2BlNKM7GNC/N1KToo3w==,type:str]
                - ENC[AES256_GCM,data:neY=,iv:Tx4XXKpkuKBJWWxszRUiwVySTELjftWBV1VY8HnIYy4=,tag:gGf1/3IA5jC13WqC9ukleQ==,type:str]
    network:
        hostname: ENC[AES256_GCM,data:rnnVCPU9MabdT8BEOA==,iv:E6CXtklm+38e5Bf5D74xprpgfgG4U4K1HHdpmKttNfo=,tag:XxEPn/hUvmuwLSn/bWpL4Q==,type:str]
        interfaces:
            - interface: ENC[AES256_GCM,data:YdesTg==,iv:zg5J1nLp3U1LLZ1CCm2qKCNnCBniqX0Ziebyosz8fH8=,tag:NuPQ+6SeQtJPQ2+1mTkVUA==,type:str]
              dhcp: ENC[AES256_GCM,data:3LHSvA==,iv:TwIO1uX2wRft4XC6BVCk8msPbYjj8puWIZkglEk5CfI=,tag:TlX2HHNQOSoa6hJQbIvzNw==,type:bool]
        nameservers:
            - ENC[AES256_GCM,data:UpRlz1S8cEY=,iv:BWc+JV2MINSS6rahB+H602mI569eXx5rqx/9Zx+joes=,tag:CeJZD904J3S64tfoLIAGqw==,type:str]
    install:
        disk: ENC[AES256_GCM,data:/yddXJ6pT/I0jibY+aqn9LvlKQov65gz+eGzeD588elxx1wRqKD1GB4Bk20Qks0Amz+Yv+6GDg==,iv:/4A/wuGZwqvcaSLiROe0q4WXDT+fDhesv2JvlAx27As=,tag:ycCrjdvsdElF2I0DHU1Csg==,type:str]
        image: ENC[AES256_GCM,data:pHyrILdq1sEkvfR3deXwOmk8DNoVnjtNjjplb6hhZdjEhfp6,iv:T7i5ddhK3w8N42eg1bLvn+gGOVTPwi4glK1j4WhioI4=,tag:C3wyzGGSA6o8dR1adZAvJw==,type:str]
        wipe: ENC[AES256_GCM,data:Akjgdw==,iv:bSOB65w/TC2D0xSs5wFLNCuK8fh8oR4uWcJdWe1rNgI=,tag:fEmOtgSBG7BoaJf5Fbpg2A==,type:bool]
        extraKernelArgs:
            - ENC[AES256_GCM,data:VEKXbMIaq1lLj1rfAVwuaULc5oOek1CWh1Q=,iv:XECbLgGbzwmb8ZN2tWzK+dXMRE01nOK04Xli9zt57I0=,tag:BM6H7dvnt7FUOJh4E0p1rQ==,type:str]
    registries: {}
    features:
        rbac: ENC[AES256_GCM,data:veCUKw==,iv:imVI7k+KCfrHa/z098oiy35oyPEhSr8IIHqP1DAHiP0=,tag:jyzHN8FGcblCHsPQoHjJfQ==,type:bool]
        stableHostname: ENC[AES256_GCM,data:Ilfiug==,iv:M3Xdw8nZSSuji8yyWdEKZnP3yH+0I3WJ7u3EKeaw/94=,tag:1HIp5U/RGlYv1H6yG0DYeg==,type:bool]
        apidCheckExtKeyUsage: ENC[AES256_GCM,data:BrKrhQ==,iv:x62t4g5CzRCkAizZ1dX2xhHRRYQvlfYGV9J/7lv0Aic=,tag:VonOAM7CrL/8uGcs6eLl4A==,type:bool]
        diskQuotaSupport: ENC[AES256_GCM,data:9FtLwA==,iv:AbtlxpxdHhFhB6T3AVa0Rdpzbk9zWTvGT8CLMmbgHWQ=,tag:afmtVjk6YZ9bZQSKDGvs2Q==,type:bool]
        kubePrism:
            enabled: ENC[AES256_GCM,data:Q7ZGlg==,iv:/mI+BjAbudxcyRgZasLSqgGRjv6N9VPOTD5VJkx8RUE=,tag:jPEG/bwcKQL0opdxH9OOxg==,type:bool]
            port: ENC[AES256_GCM,data:B/BYdQ==,iv:6pAf8ivPGhXlaiYS4HSlbBdz7g48ZEMbSTuD8Ivmsj4=,tag:v6YOAeYpXg/T9Jx8d5CQLA==,type:int]
        hostDNS:
            enabled: ENC[AES256_GCM,data:nQ62EA==,iv:Je4KnyUP/okLkehv5vM2R2JB30hhf962TzaLRNGPKVw=,tag:4HI17CMpKwHOb7TmE5AIlg==,type:bool]
            forwardKubeDNSToHost: ENC[AES256_GCM,data:ilhHTg==,iv:jVQnEgKCAvRdpoYJd5pnSWclpjyKKWe7Ipd+k+G1hHA=,tag:o0N1KqoE7p+c0t87xVYfrQ==,type:bool]
    kernel:
        modules:
            - name: ENC[AES256_GCM,data:8kzNIPuRJsw=,iv:t8LH3wiqitguSYBWBXYaT5riAdLdLqvvEr4pHv27vAc=,tag:c8eEEsKon3s1JbxOB6Y6Pw==,type:str]
            - name: ENC[AES256_GCM,data:+Zzand12V1s=,iv:LihSVG1A31jYL9aUlCc9xV3hGAw/hQz9lsu4B6HXjDY=,tag:tWiGJxTo05XTIbIMRnwqPw==,type:str]
    #ENC[AES256_GCM,data:kIR7VORzzTGvdwHnfkjeNEmsRnA98bUxyvYHb8fl9jTCb+RqzofKdeadxUFU3I0=,iv:BD8ie6b7eaSYfqBSkEK0p5YXK7sW7C3avYE6KRBPoGQ=,tag:Dtf2tfwS9CyrkBFLgu1IGw==,type:comment]
    disks:
        - device: ENC[AES256_GCM,data:QRr/3YD6JqsgGO0UBjv5rbH/oSjeEYHmbq9vjL5dc+mFN0XViLFw/R+aS0TRm6I81XU8zlcaFaCPJ1g=,iv:fDABJ0rwZlcy7Cmd0l2gGhJrOsctufJzXJHoc5GHUVA=,tag:5n5ETC/HfFQrsGHp67FYtg==,type:str]
          partitions:
            - mountpoint: ENC[AES256_GCM,data:4I2zDaR9kfop7mBy1ImnvuWvAQYZ4g==,iv:iBoYihl30KxxV1YbufxVnlk/JYHn+9MfEvK0VDUthW0=,tag:wdGA+Mke4pMivSbvv0GNlw==,type:str]
        - ENC[AES256_GCM,data:CzrQbS/j29/uoNbKlhTz1DQojLeyglzX0N4yE08evPd2/tyIs4JtnhT4tLX31gFI7hdN,iv:AQRZVmt8hpNJy/T640yCZMtcQxfRrCsk/axv3pxD+98=,tag:KkmkqcwN7cDcW4oib/MKMg==,type:comment]
        - device: ENC[AES256_GCM,data:eZzCGqyzhmJ3USgmm1jWIepQncGzz4VZmSiK/t0fS/0NsHtv0OjpRDWk01migcKV9DSxes0VgXE5gcq5R+w=,iv:VoNwgpmVZuGxP4COqCe23IKm3evHfkCJAGASGR8us/g=,tag:VDykGescBTfXhPq/N0qEHQ==,type:str]
          partitions:
            - mountpoint: ENC[AES256_GCM,data:2gAENuh1ho7QpIHKakqnywUMbBKgEIyO,iv:+S6o+qZFev/HR4jkOPe6tevU4IbYAMxKrYZS/zOq/lg=,tag:fce2h8Im/KoF2dgxVDEmxg==,type:str]
cluster:
    id: ENC[AES256_GCM,data:D+O0848vSn4KaFTga05xYwjOhODY9yyQN03E+hD09f0XN84iLtBwtgGMqy4=,iv:3cIsmy7+ZXt/Mlj5i1DWFOo/NEX4YMxS/9YFbqrJkKo=,tag:DrV9nVhmtFd2sRLH3LvJPw==,type:str]
    secret: ENC[AES256_GCM,data:IDCPQ+eWJpIf4Ferp0kPCikHRkMgJ51JyHJbO3z7V+glsaSTG8PYjGNIkjg=,iv:vHJikYB4vqmfCG0Wy0DIFr9+OwHQlKqlExujY2Awx6o=,tag:K2eG99oKmU0dmzz4v2gapg==,type:str]
    controlPlane:
        endpoint: ENC[AES256_GCM,data:sB2H9lCIwVVGAi4m8umAv2IdPG0A4A==,iv:/U9Q5oiiqCeUwCct4nEyXdWFpHcTngxboOp/Y0Lp/KI=,tag:sJsbSmp4KmJohsZQG576nA==,type:str]
    clusterName: ENC[AES256_GCM,data:SKVB2SDa,iv:rGLeeGA6u4qx9WHKMbEcW9Je5SqOcgX2GOa6Opj6GbE=,tag:x/7zAkYYHaYEOFmby9HHMQ==,type:str]
    network:
        dnsDomain: ENC[AES256_GCM,data:ypXOvEpjMyegMApxVg==,iv:BHdKLb+LtAmNjyS7JMMw3PchXrW2k17vRjBKJZ0a7+s=,tag:060mU4HhvhEoJDq2N8jp0g==,type:str]
        podSubnets:
            - ENC[AES256_GCM,data:/9JZuS8uWyGXjUEBAw==,iv:Fg7gouPYrgIRXNHIy/p5I+kDMm7wNnYNtdKWFOQrGnA=,tag:8JrJXkjC1bpP4b6bzMbt0w==,type:str]
        serviceSubnets:
            - ENC[AES256_GCM,data:n7EUJ9xkswCrVfLI,iv:/YQwAXO6iGCV/c764YbSMcaxaAhvMUlSjAb56lIJrIw=,tag:RgsmDUGDYwL4XfLrgiqyNg==,type:str]
    token: ENC[AES256_GCM,data:Ji5xkRCmr3BhjcUGk1es5kzIf900EmE=,iv:BnKPQULySJK1aHh7/1b7w+/Xb3ndXYT4mpnBBB4qWU0=,tag:mscHS4k0yotlWotR2J0Rvw==,type:str]
    secretboxEncryptionSecret: ENC[AES256_GCM,data:KEdKxjmiX+52dsYuhYsXgsuBXVpRb8BdhvveqD+Oc8KakH9gWXz+FR1NyX4=,iv:9Z03tNlvf3VL6XcdkHVwsLGBvAAmeIMRvks6TZy4caQ=,tag:FaNiJt6fvjGxKjcjZd9iqQ==,type:str]
    ca:
        crt: ENC[AES256_GCM,data:MzDRMCMFOY3AtUoa13LEKmzU/gkGGwfhZP+qYJiq4NynPfaiNNFK98tCrgfKB0vgS3rrFdCBqr4b3G1xl1+3mZZ1fXUe/vJN1sIayw3VjaSFe2nk3v20D8mhOv/OYkMt/HqH+4QnGXl6zAnFiUfC2xEO8dcgnNYMd6egWVGbcTgiS2fNDNBOxUNlPmaX4vd8SXKAUnum2WIktC4a7JrSIuwLrFC7cUooeoFwYsiYIIpwdKYgHWkBSZBnRRQR6fIOADN2W2QCvKyAXGbQ5FpzZSlEsgJsQiy2Ra11rmYPD6fqpdsSS01aGzyA0Gfz3HBCXpKcFp4G1DKpWvTcRA0bfnTqaQ1Je9imtwvV3a23BzHOpX96dE7uQ+50IuXa2q5IEdIKyepgSJO/pnHRbtnDGf2h7y2KFWky6EAgxOgoVfVB65cnOzfYcJA+wjF0ISISGHppG6rHwVGw+/rOtGOFEDUDEbWx/Fj98CDnSV4mfBfiOqv0froo/hniXwwG4LZnkSQ8tAOl4Ig66QssqQlIRvZ7+w2Brpz8EX37GaczslC9+LedXUzpbCzriqIFdIL913TffMfveXeq8vd4mdSmzIre66W8Z8P7eS6W5pDzRAZOAFmN/PKQeUMAr5p7ypNZY7N4frRZKmKbh4GDOn/4MI7GBgAa9N7I253BDqAOXxr5sSgpF+OJjNl+gMHj/xW1GdFweI59ZxuPSPydjU9Hyb/8eulFK8AhB7CuH+/4g47+TiqN+CeN7aOyTOYL/0E2CP0+jxjuucyD5LNdt6IGprBG+OyJZ6792KoicABQUfl0986NkSuae3xHxQiMXvi/0Jem6uPqaGFKn1kVMOaqJF0V8LNlnHy5hN95OCEmlEs4ibUcXRl9DZS53SjObEN/y8F8Q4fJ8m0MwjVwpE28l5a2igSql/ekgrkQQki53Yhf7WpyL1zP+RPBeG7naeC5ioA0nvJ1sTC38mrEIQc4u8toVbRCov6BcIG7qMI/MSvuM1NCopVwm6KgUfNfXOzV9ws+KoIsm/bFw6d1G/AhWSA45UhJy9VX6ziU5g==,iv:pPwyLmYGcS9Avg0+CCRDWDju/ws3ajwQZSCRIIJDANo=,tag:EN2nqrJlbZwBskra4GpKwQ==,type:str]
    discovery:
        enabled: ENC[AES256_GCM,data:7ZfyyQ==,iv:hNn7peHe7cd+cHxruoEoCzB2JtE1giDZNJBXa5ZX6FI=,tag:rQp7/91WZNw6270+Rbzb2A==,type:bool]
        registries:
            kubernetes:
                disabled: ENC[AES256_GCM,data:vGYEBA==,iv:7Hul0rPeEbXz5tQRPrZjCMMM/Tpyk1c+B7o0m4W9TA8=,tag:5v4YRihTRbS8cdTyHiJzhg==,type:bool]
            service: {}
sops:
    lastmodified: "2026-07-26T18:33:25Z"
    mac: ENC[AES256_GCM,data:wXxRyD9tEQlqRJ/OFkP6y2n7QLCEkdnl7JOihb0h7hJqI59XMiqZ2WMYDlr91I7IQwt/yq0P3zphaYSDPv23VXwZuqQgkCU8LbJVjUSd/rIztFZIWU4z0H4+/SqOVcQIjjHZ9m+k8Z9ws84eMcSgR8qHUTIMOGE9z1WdC5KUUGI=,iv:X0/j/KehFiS+4wY/xuut1Ll5aEQNU4Zem7j1zRtrvuQ=,tag:/lEDVEQ+xSx5c/Q8mgcoVw==,type:str]
    pgp:
        - created_at: "2026-07-26T18:33:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//UrGPa5pyz8SQWNrYKtgqx4p81RIX1vHh/rAn2POvQGEd
            MtKa0IaFRrNohfBEYJQBsmXl6VeftlN7EmRLXsda4yQJqjUwObn3Si6bSHSHymaM
            qVfyUWKdDTca6zh5MkAWH5rKdpT+I92Y6EmJ/iGumFcjrF+FG4pmdaH3BsvSzmKH
            UBVRSx84WnebvvAU7TnFbp+0wWZZtjTsotAXB4Y1LFPjOnGX9aLSsPmtp4uh7c7V
            I4xoF2mrLwoDKNBRXfv1SGm3aDvRvh34sgONMKWrV0FyWYPMvwzFdx/tnBJu9mSX
            8gsDJZhOD2XWcSETKdWx4eMkUBQDEI8JbUeUP6+DCxw1PB4MW/eOreB5FZE9zqPQ
            Z0dJ3UdNYxLhA1t/hb1kIVZCwYVbmJovhIDldo0kmbSeZIVftePFglzU8KE/T6CZ
            8CB142M+CYZPk5fHBEAFTdkhA3197LtVzjLe7eIF5w7emmFf1jI70/fs5he0m2Rl
            cf//OF2FM9MXi12GZdJHpfAL2Y1aoC7wl6la8g8iJdRCVQ6cOLFpYnb+AhMeXKxv
            3YotLCRIIpO6wJ/ax7jX+1+GkDe7r+5NmI5kr9v51noquQla8oHzL7FrsaAUzaCf
            W5NPWaUsp+NmFip1F3uSD6bdRmG4+AE54jUCp9XBABy6OIbeKqKizcrebRChsoHU
            aAEJAhCpwS5mC4IdfaCdi2J3AoAzngonpQe3YatsOY4JwRJ3Q4UcNunlky3Ux4/a
            kSAfgHSpnhfmiL3bzdQDPOA7+PMDFKPSxPU6BiSgmdFfqV7XYTFK8rs8VMnY/B1a
            aUZWRUwfyadd
            =airy
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
