apiVersion: v1
kind: Secret
metadata:
    name: p2pool-wg-key
    namespace: p2pool
type: Opaque
stringData:
    privatekey: ENC[AES256_GCM,data:s4Kgr+YiAVr1aBGnTiKSAffcR4kKcSQre05EuD8A5Ad0IALvBx/FIko/Uqo=,iv:QBdsuX1DkU3b1uTfF5gT+g0+6TYa79IiEKKJyty8w38=,tag:MNw3WDYhhF+hdSQJrnuYSw==,type:str]
sops:
    lastmodified: "2026-09-13T17:21:09Z"
    mac: ENC[AES256_GCM,data:Nyz7Onb+RcsHgGZ4N+ovu4quB5eCLQTCvvzL/NAyrnld4Ywl3idMsXQ34wpLAnbpwEdXNnKxn5jcxzFRODr3ukKCIeLguFctG/9qqD5wVsNeuZSSXQDbF1pbrtT+wTAf0sw4n2hgvwZmM0iDB1WqTnHnh/oBopMyxCA8pl1xEpg=,iv:leNYvk6jU6JGfHWpFGcMIcPNYmdtrChSnbh1fXahfyk=,tag:1fhKN9vBxoDo41G6KZ87Nw==,type:str]
    pgp:
        - created_at: "2026-09-13T17:21:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//c5F49dAz4u8lsaaX27SVhYFzN0Lp8CaXO6NzG18vp/0E
            KdplcdHLaAVpfFXFwMe67FznRIbQ7Z6MdygXT10G5rGJC3yYa2fKlIPLMRoVYNOk
            LMh0zO0sG6X0YU8FJ4hM66Tsa7HBZS95BXZtrIGLuBOjNoiOVE4+ajj0ZFY7dtkU
            JgjTVcsT2B6TcBLlfc1A0SnvvXdiGYRl7KQVFvg9ECU3puycRcQwtrZc4qsxVF7I
            UWIhbMto7j639wlsUYO7eb8mgQtB8nUJqtzs6XrLvHW+imq+MCIRrOY8uqLVbyc8
            h6/pBoV+qjr1K8J+PtEkKNO3rYfNW0YfFRxM+GTqpg2G+OigaYkLwOa2BATvKu/2
            pJpAzs6aSvtu5SQYVrqmu273QHHq5hRIggFewWKGcAHdEOtMAIRR7ttOdHtIGg9r
            af/Og3ZiJ1+nJVjaS7GT2bBsAmye6+5ETZHpwCVq+dikjrXEkx/MRpDAD8sYJTxg
            vnInYeN9eQ1WkiU8qTF1WSDrk3QF9kkUwHoxG2ppa2rGexObLvbDPctnz9PLJ8vh
            JF/W/VjKhxws6jdVyseziD0eccKsr+BuDE2k3txYWsQrA5yM4Ib4M3iuB/bxBKa0
            /ti+1H9054/8PH4LEQZqv9bvOFl+LYUylCsZs1WMOI125BQAmK5CJ0+vIwzlP77U
            aAEJAhA6YZkj93FVDSiKSEOXCuRXUQ3OQZ0jasiA5OxHRzU3OSeB6dwz/haUrw5N
            211jEk6Z094jBDPs4EJRamQharS1qGmfEZkcNWWjxSJnJXFjFigXvfWoQdA7KXOf
            f6asuzi69FGL
            =TozQ
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
