apiVersion: ENC[AES256_GCM,data:JLU=,iv:RaxbLoXrmKV1nzp2TFyEZY70qkJcahlE4+x7EGBHCRs=,tag:h6KMW6Ld/dqZ5qiMwYN3kg==,type:str]
kind: ENC[AES256_GCM,data:m0kcSF3L,iv:7nVy7m69vT3nB997g8fowtiSnkFc6H+iDMXTjHTk1ms=,tag:bV7whEHtRZgqP75y17cXHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:f3gubuaAg+tNmUyBJWQkdfs=,iv:gsgUtjqMnjCuQTFmKgDYNLwVm7nNxJL9jzLnhjAofNE=,tag:Uz+yAWLsz88ypxPvUkPjxQ==,type:str]
    namespace: ENC[AES256_GCM,data:jRmH2elQFz1JAOUg,iv:WJOy/OsHceS77WWyDFK1l9AffYCNSPw6gdPSHeLcmh4=,tag:g8d+wTbsL50OZmkfhC8RUQ==,type:str]
type: ENC[AES256_GCM,data:ahTcWCeB,iv:jKDs2l5GDoLG9yoi5o0QeQ6EEvi81ACHsX/1wkgrTDc=,tag:ou7kiyzi7zB0hpcQhIVfaA==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:NrTiyRlyXrtGBUrXF7Jz+4wbpT+iKv6638KK3UjvWbiVxzQDVDL/wQ==,iv:uOAz43mleQVsNx1U216O3JXKBKVx4urmn8NLRtuLLZ4=,tag:Oy0XD74UHdKZSYXXxr6syw==,type:str]
    client-secret: ENC[AES256_GCM,data:Xn7KB8lo1Dr4en6RJli+PknoknOqO486uIo1p5nTlewVp+ZpY+s46GKo5ng8dBtLyqROFXBXB5mVMly5dltl5VavT73JE/t/QSLHNR5O6corCgWRqwTLE49DvW+pwTq+t7WWKEnUu+lvTasb1yAipHKveocL41WC2bhCxBv5xXI=,iv:FFYysAE7JhxKGO7HYLRfF11ZKHlppo+s03Q6NczV1ic=,tag:ROvhmmZfM+m20pdCEKG9MQ==,type:str]
sops:
    lastmodified: "2026-05-14T19:17:05Z"
    mac: ENC[AES256_GCM,data:KmqvU+jo95culKXRFv1XiE8mWcBfmUQdPQv0C4avWRPx0gmZiH1lXPmL8Sc3fPSzvNBeGHpDkXkHNLE9bahOnWUr06vN9SvR14aKNRkLJjVkkrwGHW1BHabyen+RWSKH/nhY5TTKong7BYFRdY8vBhDDfR/hgFC5Q+I+Qf1OucM=,iv:nJgAMarPZ7lFO2XJSgAFyyaS1MRm/6UDYEEmyMeUwjM=,tag:sVNDwFQVbtfguJSdPLo4jA==,type:str]
    pgp:
        - created_at: "2026-05-14T19:17:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAg2uaC8Ld/fB6KxBQ+rM6xjBiZIbsAFia1ZRZ4aI7WDlQ
            oQpjqWDxlyCvi7/1MY2d4uOsbE/iEn2THzk+aA/mRmHcyPKYGwR0sFPQib4E67k0
            8AjivqCyKGWMh8CBR2gsh/UDUP6bhiybpLzPEHCRQZsvKTnvC7tj7+NteQviRTFa
            Rtg5p8ck0Z7abr4off/pytVXCJ7Lw8sd1TP0lkX9oVTrPnVsLORVH8j3yUFaHNsC
            1sOwSEwDicmrKQLGZaWJoVfuv+HNedTAvsTicKr3IO8gePjvbLbMuQ61uIDeJIWD
            Bz4grDSqDa6IC28w5oUQx5icYaMsqu2w9gHchLTNf2KczAMfZdlmB2OOZoVi0bxj
            R9YqnU+C1Q/qBWQdyGjhoVsb7hr8lnCUhr6J/2f7qx2kC8ufzuIBpj1k05Z72Sih
            NIB9GFyY8mGFjTsZlSdEUWq/BG3/jWX6oxN4A6LUC5m0iGgewmc1sRhJz/6Uscd4
            F4V7MkbVG1w2WR2HyhA5HuMZlR2Lwv/UCDT1HQ5YWtrEOztr2Xh6VMAxFIVbqX1p
            ofaJapqBvwCR4ENa7EM0teOpekDwuVal+xD8yrMBo5j++mrjrIP4LUUKYA6aibVh
            0OXZe4FSQ4lPS0gm5SxiY5HBLsrGZvGK/mpn8VKOV2a7elQLsSFoW+Bv3o/9GEzU
            aAEJAhBin6VSrECU8egzJKJqlFTUSPD2qrWqdbwMGaPIlwYZJ5lwqXP3k+mEHxMI
            /vwE71niZz0qU1abq77exyIcsfPiS3Yql6L27UkVEgh+arceKlPgObpZp4sQIApi
            /LVY2AAmRs5f
            =sGt6
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
