apiVersion: ENC[AES256_GCM,data:+s0=,iv:XfdpfiPa+RTBuhZJy8lRsNLTIlnsSotV3dqb350n/so=,tag:908CFD2UmqX7wGb4vXT27g==,type:str]
kind: ENC[AES256_GCM,data:YT2NfUm3,iv:81w7sgqkF4Ll1p7Ke2gx8I81sK2aeCrVoUtBCaEhscA=,tag:60NFjbzjQY7UvTLsIadv1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:72/ZAJCtImWATQmBNh7clDskvwg6DoD3,iv:MipFJ2EuRJQF78AkLjvCc8doOyKgCPzn0nFHzL5zxyc=,tag:TgyrL9ge5NaK3nuZK49oPA==,type:str]
    namespace: ENC[AES256_GCM,data:6TFlf/egW6eM5eSt,iv:qn7suC3QWEwdY/CFmSo6SChqizSnRNseIVjV7pJkZcg=,tag:aPTN2BpFulxzpNQM3ykLqw==,type:str]
type: ENC[AES256_GCM,data:GrxYrJ+j,iv:NfDPOTQQOQFwgCcxhGHWHoECdCdHfyj++9yVvadO0zU=,tag:/kslLWoCyCLPpDZZlLvHnw==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:XcS8spVqOh/JeLQmCzO/0DZ5hWe6darUFUCy7/MTrP1JMBc0zl06NtUpa/TiGEu1EdFUXm1GfNSU0Ht9x9I+1UwlvVaIw8AxmUr0,iv:5sI0iRLhJ2VhxsYvHsndVjvEf+6u0tmn3RNTQPtcsl4=,tag:C4F2/ifBeOLKo5wweghT0w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:j8qFxJVFc7SmIQ==,iv:ekaCJdCmXnoREkJro2+SjlrQM4CW+1fTOc0M7BzLW98=,tag:wu+1M+RLQ1gMMyfkD28K8A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zVoKmYVuMXxK0Q==,iv:t4dXpdhDFdzDqzrQ62nP68VE4HQklmVXYAtEpiEPg7k=,tag:8JSNdyFfFSdsDUr0L1dHHQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WAnwXhtlyTWWhA==,iv:VvcIkPu6F+zKI8gavfp3PRg2Ypyu+5xqRuFnsfuJYtg=,tag:gl6vl1eVgTv4D6i9fZlgQg==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:QG4aJBv3GFTlVPdZ/jAlaFH8pT+nAP/s4UI5sEZGMFIYr1gOCN1/0kk5m2liA0iOHC0bQAPPb7VJpAucGNp2rO7iYBGU7Z25VXV7yL82RmHb8k0A0ZoltrGW3yuvAi6wnp3/gBVAePoZEopcwzoWg616TZFjDaHUwxYNbGT6dds=,iv:+pswHS2RiPP0cEJ6WQTaqO+87Yrci7squWF1ealC7aI=,tag:bUlmAbppVrKU8yL71Z6SQg==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//YJF8n9QQkNhQoZomIwFFEk4UV7PwlfGNQ0TPZpUlmGXX
            Kp1KWSo/EbLMSOHjK0U4fOvsYOkEkOT2Nac6hnv9LzKL0/3KOEbInO0RwxPjJCo0
            GCQzG/NVGSnoscB/P9/svgQ71tBr+MwV4d9LBgaO8RekIlxRdryVrcxDrcy1huKQ
            fxoICOSwLObeyXrXd26htmClEbNmyA3z8spYmhSQ1X568zCTatBK8aOs4O1+Vtb3
            +SRznjyfZhtjnK6u19oEb1XwH5bHhLG08UboLUjteNonxKWEWTwVNOTYnYSmpGu9
            wuwTfrwZ7MwL2efeQSIb/OPeZL+ZauvIPu1Fz0f3SGYyyXoeFTs7HQgdlkhNqgmr
            iIbp0D3DubG0XoiUxUzj1rQcOI2kUOxJSSXamEvdzOghD3ofd/+syuiVHPNTQl5+
            ZkWzz+gagQ5/RN3Dmquyo2TlY0ePJySJXoRnf7kXfBNup9OXFgEmucznkXQKavlF
            wmyLcuqnURPhJSnFpwjvAqaoM7ZNFt4egMUqJ6bYzY/AsnC7ktehFV3HqaeQ5MM7
            yWNkUOWUyEKQF5PAZyU94KJplRZ0f+dM2MTGav1C2MIQDOzxTSbySI8XvezqKIvL
            8OV54oe3sTka/xAFwNrrpRWe3I3SSLJby6rK7gXS2h53SLNvJt/1z99AREgT99rU
            aAEJAhByZS5IBKI7s2rGFUZ/4nrV07W9XeIx25e25UDfs5znItwMNl+LvQTURC6k
            rIdlQZ229t3uBwPizbS9+ZSnGyEpfaH701mmq3I1alV9uy+CYGkLBDvnd+50q8mx
            MJ3LpHe+tkGd
            =zArx
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
