apiVersion: ENC[AES256_GCM,data:fUI=,iv:4uNaxRCG+hKct5xR7c+7mdT3uiI3Y1POMvrWKVKSUSM=,tag:SeDbXoFIeq9zHnQACg2Ldw==,type:str]
kind: ENC[AES256_GCM,data:uIqFyy+P,iv:cjiNqpe2x4nuxKPSHVZ2/R3/F1LOfxm9fnYFYfXf8R4=,tag:dopiw7ZvUIQnIvGwdhuKOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YbdaSZENrlcKU9o/mUXlYqP719KqHp0=,iv:y8Cm/AfsYTOoQnOtXJcmCHEOIxpQixrU8rDdY/I9r+8=,tag:YQpGWs80ZWY7a0IYUjrb3A==,type:str]
    namespace: ENC[AES256_GCM,data:xQfc2xYQoGA=,iv:CmnzNsvZEylcSzdlWWV0GjDLpL4w2xOWi1S0/kRrZvY=,tag:oyWqFmmWmboYYlf9YZX0tA==,type:str]
type: ENC[AES256_GCM,data:UmL/ZUWV,iv:A/QS6Vzpt6LyxAG8EIKZQU7uTq5QkcOiBhoHKc/duLA=,tag:On5pV+XWdsyN2FW6L74wQg==,type:str]
stringData:
    ENROLL_KEY: ENC[AES256_GCM,data:D7RWxFSCQcvVkGkl2IHJeGoUU2+i97dwAw==,iv:9oMe0ARijcvCCoVQR/ynqXHY8iQtPDVhdJF0QBwGIgU=,tag:fw6zJoDVn+/o8DW3dKrucA==,type:str]
sops:
    lastmodified: "2026-08-31T16:48:26Z"
    mac: ENC[AES256_GCM,data:UB+9s+PQW602TGNNoX4RwWFF2b+4ZbWHJ6QY+dUDH/OLt+EiCtF1CsIvE6IfcfB8rqlHnFI1ZZseKeafaEax6ce2EQVpVhB6uwRjEJn+eCPM84o1l3eDa/vXCSRch3hjxgh1j1FBqcgB+K3KfX2TF0/5rn1N+BJiJlIYO/jAlRc=,iv:uwxDXHJlhVH4pS6TKz8sV6kGqQvk6FTbkDxaqRi522U=,tag:B7IFwUhTKr4o71+EVHs8PQ==,type:str]
    pgp:
        - created_at: "2026-08-31T16:48:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAoUoVh9hIjYmhbch4TdNWVDWIE/qlCHht3KdmvQyZeEEg
            T28oayz833Yx8buGz0wiHliiYx1G10gfSZlCDT1DokYxK6CsjqKYlLEFzVb5b2Zq
            ILkeLTxrtGj+ODisTjJmtrCjJ+2BjrAq0WeQEsh0D3q/qQVnc1pf267H7k5cOOWL
            qKihHAJNoQHZdWUbZVFddWkFV/VfFwtmpkOWTy2Z1yLbI8dLlxLtW1zhJ4QkvUjE
            TIxQYeHRTMh1O1uFTr8IG53k95fBxuBkmCy3Bjo/4DMyWB3UQGiQO3uSO1IsiQsw
            7kqcwq7LoGeU8dYcyv/iD9oNInLPQPPKBL7SBu2UW9aVf4g0NHEIs0Uupr1xW7JU
            VOnflI49TnmRLk8cZGhL71uAnRIwx6jEx1CqhquSFJANMJR1w3OHDsgNs3QW4nXD
            uyZhtOAymen4CzWd4VYwK0tMDDvXO7doPvE0kzcZJyqy5/eCd5bHYu2Cot3RMWEq
            Cawr9FkTWj7OMWTFwmPTeXiFYfQwBMUMFeSj3snU8ttsw6NwkO+fDod4ZAggVwjl
            bPE4duT1ocN+2EAN2Bffs0gfBxHe5xzpaTD6fNpjrY7a08aIeycz016jkHXaqyzc
            tSAUfgtF6FNpeW8iqXaIq6GyZl1KiuUE1FUluxr4SNYoVOIkl2K1+osi4TTdzbnU
            WwEJAhC7VtB0y+T5MfT2LzY/BQ81c1KeFXW+1fDw/9OmlZyPmt79HzY3L+hDd91l
            4A6c1ERLj/11rVMbQYLXpchTCJ0Ik4o+AUu7lChZmQdunnfQqCXSC85wQFg=
            =/IfQ
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
