apiVersion: ENC[AES256_GCM,data:DN4=,iv:AK0zAS0+dKC8LifoessC5SMraAoh+R5nmtx1vovKyds=,tag:8IjGG+HgWd86X5ikudZe7A==,type:str]
kind: ENC[AES256_GCM,data:Smk2ZHui,iv:VbGZecxBDCPhjYJbtvZ9eh3YKqI+k4+hOJNBCX1lX14=,tag:RVwkTyKyYbdUZYqzzwVI0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RLdHZze6yhj8JBmoiIGW,iv:I6Mqsj37w/dGKAmK9+aXT5YzN2D4fS3nOTKHeUVHRis=,tag:dupStTppo5ccFqqwoqvdxw==,type:str]
    namespace: ENC[AES256_GCM,data:G9wta0SRKvk=,iv:CFTA5r6JP/fVNFVOmuatq435D7Hitn0VRxMqJxgElzM=,tag:vFzg3+QB4tvgXxp6MlrXtg==,type:str]
type: ENC[AES256_GCM,data:y2DZlxC8,iv:4wkSCacPW4aNJBs+I5S2KFMD5aKWCKCWKryyvfFqjPQ=,tag:u7ZcoUn8R4CcMJTwn4Zbzw==,type:str]
stringData:
    lapi-password-cluster: ENC[AES256_GCM,data:VTqE0hiuTQ+qJ2vyL9NoKgy6LxfdTT9mMWgQXELtDyGoZIDLS7aoeN3Tlo6cz6kIJvh3DP3ubZjajBC11XC1wg==,iv:5tzCRiEioQkyKxFUI7mBF7DrnJPU8iR+7q5sNkBHpF4=,tag:9TvQbMOG8+mqSjg2dsDgRA==,type:str]
    lapi-password-jelly: ENC[AES256_GCM,data:RhIt90Cw4W7lgGBKvgFl900nlUD4zQI7BbkYlFqxNGjQSXkjyXb1oGVQSEJP4Da7L/p/NZZ/87UIQ+2yAdzO4g==,iv:FA91/IEOnBvig9IbrLiWmB373u1tiyfnMA6nrsRSVy4=,tag:s0JxCOGCIvTYnMUjZwirUw==,type:str]
    lapi-password-monero: ENC[AES256_GCM,data:hwz7AaOSr/kI3GEjJbpTn2YW9Tboud3BSH46BGRTKqWDeBq8mJUq0ypKi1kcHZ+mKSmw1Hn7q+Kpi4qZWimbPw==,iv:k5wDQBK9dPGeAY1NjJ0cuIH11T3gtei0X6oUmU0cnaQ=,tag:nLty5Pc5YZHmo42ZEYA/xw==,type:str]
    session-secret: ENC[AES256_GCM,data:wMR93PvpZ6nU2KrgAlBemIE/+B6CflHrjhiJ1U2imeBkCbmUtwYTpe/cvV8/DvDT7gs0cOkcarmuTnSbMH6XCw==,iv:xh4mgclGa1kra9nij0aTz+6vnMDKPy21cgelEmY5ryU=,tag:wlcgwDNJCJp+TJbmoeIj8Q==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:QP6uRNq2Py6GjgQAGj3Euf+BWY2Cyr9fz4ffxGiA2Ig8tw4IRd7HuA==,iv:R6TzuiNVhOXC138/2HmNUtLXyBiLEBc6IEZVXUP24r4=,tag:MCFc/44DetON3E4XiI4Gnw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:dbSPdD2icnSIJccwgV4iOldJx2vLvB524addCXrG6ISfV9rkN5JfgSu3c9bj6RJX1oVuxYuIhLpX9FccNYkWQQoOgh+IXAEAdIcfuSofY68xf7w60ygtEXOgxB8SIWUb,iv:TW2TVeRYnog9+kyGe98zPoInW53QMwvWpXq9Rcaz6rs=,tag:bQd27zzDqx8k3WB0BaNt5w==,type:str]
sops:
    lastmodified: "2026-09-14T18:12:42Z"
    mac: ENC[AES256_GCM,data:ygKkRKzje+5LUhcXZIbGXYRK4oA1o9IuGWl0YY8Q8aEQPlWy3CagBEXg9ulYSiP18F5LjQ+ml0QexdE4tF8TBmag/ltcguJIZdTK+fl/AByvGKAHZuKBQmulFUvx8ngr2Ob8d2SnsLpD+1ZloMas1x2jabU7MG/HJesZnPlP2iM=,iv:78dorwOp9e/IjErwMV8vy8XikVb1hWGNJIVJB64BPzI=,tag:GlOFk6Bza+UntN0x5nr3Jg==,type:str]
    pgp:
        - created_at: "2026-09-14T18:12:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/8DLZ8P2Dms57EgGZWC6aeqe4KkU7OVHzb3HMC/p+hQSxg
            0AD2UqHtG5Ts/6VtUHgAsC8eOMjARgpLtuX5/JQTm7b4HMgfEJc7hpu+NbQUaHhi
            AWWefMwL70lDjbx4ICVnYL4mx7G/HgPjxi2xaxOYfnyykBuvfaZ1dy72YI15h7kt
            oC0aQjhKh9L0C6i/1YLQFTxN9qTaICXd34UsnYyYRmjcrRkYBtS4NEsT/1lDor7v
            9/kc/9kSyPT8MUjATwGqMXwL+dwMXDqdPiSVMDkUycE1LQ532oGiIUNFzZ3TWHfT
            r3Y1rwvRjja8gqvYpgbhDCXfCVGLKQzKeMaasQWp7QBSmupLtXeCqmHMf9VKwYJS
            Ux7Ut6DRUq6AncLpi0ycf/uLTrH8Si3YPgSlvXLHA21wIbuY//LyYbQ9JDBRN8qH
            kZZmoigBTzP/DK3uEzzO6zK8K5DDnyF6toSoCBDSvstqW+whAuO12kTUOuPVC1pa
            Y+Kpjwa8bVCD4nl5qblCXoB289BywSx0FXw6jPHMo/0eFEBrk1DmV8ns+vJIAplh
            p+O4ikvTqeMZldg1nwamsw1bLpzVsd7b+Vyykcu2nsfYuz0aWtt/W+cUT/1ELKAR
            HLTWXDxMNOBQxVnlhnU5aguwG0Fs0lqcYOzHgkU3OfbldFKv/eJmzE6+HJlPpsTU
            ZgEJAhC4rEqtVhn3shn0dKCInf0g6f6br10+gs5hkB+dFcRzh6vaUskcclU7nsha
            zdk1YTDYIkfiFrnLgZ0h95CzC5Uukv0l2fkYG8VMkCqXjcVsG/NTtvfgcmmF5dlC
            YZ3ooxTn/g==
            =RP4e
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
