apiVersion: ENC[AES256_GCM,data:F84=,iv:+tySRXGFZyWOiRa1T9/rjHn6ZYF6PZK/oiTU43rJ1CY=,tag:G4DpP8e70TUQOJO758qbEQ==,type:str]
kind: ENC[AES256_GCM,data:+M+rCHm1,iv:iHeeKPOgwWAgNAlWu+ykCtK0kn5z2rsDvU9ZCNoAmxk=,tag:X9249ciFIIzBdE+yXCV/Iw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KN+QWD6kuoi1OI8IyIU3Nj7aXSSW,iv:y6PfUXS4F1kJjHDGLYNXVVioJUky5Esm8iLI8Lnfro0=,tag:FLg5SOvk+hAGZdH1jpGLhQ==,type:str]
    namespace: ENC[AES256_GCM,data:VJpgDhqdLQo=,iv:FWP2aqjNCRYpCZUcbTB587fLPPUMjIs7L1TF/nAxEj8=,tag:TO9cZXXoPplkEqlvcN9m0w==,type:str]
type: ENC[AES256_GCM,data:M5HUUM8s,iv:nm6E240z6udMlbaPxfnLlertfvbCowgyDeC9oP2gdmQ=,tag:yK/LWoTdVzfONUfY/MNMzw==,type:str]
stringData:
    csLapiSecret: ENC[AES256_GCM,data:14hQu1RZhT1t3Y74GgFbkXkNJ6jZa9fNVujDiq8nv8U6LwDK6CYATNJGlap1/4aCUM4ztksPdYI/04IOdlpi9uWRfaCuHUZ98djTNzs8pKA=,iv:j0Nf9ZNjuIr0Z74s7vnC+Fj3NamvByc9gYTBXkXa39E=,tag:SnVgF49e45zcEvi6fdHKKQ==,type:str]
    registrationToken: ENC[AES256_GCM,data:oT0DvOxkf8fvcqHGf48SjjjineRsrubxrLKPXA3G6VRPTJ3xx+oZHssG4u/R3zXdpl6KeayRESRCUf/d0MbNnA==,iv:HTMktnq9ZejTBGGj4RrUrj64TE64uVpfR72PPtiNXrk=,tag:Kod38L/4FfJVFEfaW/p8Pw==,type:str]
sops:
    lastmodified: "2026-08-31T16:20:43Z"
    mac: ENC[AES256_GCM,data:S1IM2IiNdxpTNLiXvOVyxh6EWwddoKaAYIBLO7DeVUN4Us8iyz0ALwwrieOewBKxBtMX8xlfehYpiF5jSV/fYtISUgY+ildr55+SAQ/YNTiXkMMRvS3vRsr1n1+BJP04YroMCkypWoLdzfNVjiL3z/xmR4Pfy3sKehWKcUpjtM0=,iv:Xx9l8Z9TZU9IVmC30Hwl/8PHNKA6ax/IJTcIsB5gB2A=,tag:qUXf3jW1mAkmYdqNg9qeIg==,type:str]
    pgp:
        - created_at: "2026-08-31T16:20:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAnW5af6GwlrSHpv6/hjoPLSq5eYuPF2lHf5lyIKLVDT2v
            k18vCvwUpScuBQBiWbkE2T/RwacjJNE1lHccOEwxS06KFA9R2iUfdolJjBwk6BaM
            5rITY2zaQBBb2RwouTwWnrhW0u9nwQJF6zCqj5oIhH8jvvBbIut10z0cFmoJz+Oa
            1JbFlj5Jk7IT34cP16SzJvbQl5CKb7QLBW0T9lv+/T2URTus/LqykOo3EioTWJmR
            W06a/U310NL6JIf7rBZESMG/74lyg95wkF82B8/3OKwWRXEQznIN14T/HOaY5L8g
            /z/85eiFKojCvcXfDOJ7HYQWxbrNRwQ7JWsSxaCqDbJZSCNX2zUYGTxWvYTCxwrH
            hOHGxGzIVPzHpJ8NrqEZbhCNvh0yDAGXtqK/YvzK0lzpul0rdLWSfyPcqojghJHd
            ekh6ISg1qHQhflRZMZu1jEC/bB4Z1I1x1ZdkCV4aBr0AGHxstH/5KG92wLENegvz
            6CcRrse+oclICmRjpbZdMDJq68sXIzOxclSbR0/in8wyW0xl8cQG6aO0rY+tTHk4
            R0tb9iEQE71TQV3pm/vsFFE1K9NDDNiljd0oN67uA8JRaNdbioChub5BMSrTW3EM
            fsUfuX2Q6HFgn+OY3SdTh8vOvEGKRkp/7h5AzthAR9li9zZFqw3cqfi3BOi9YuzU
            aAEJAhByJmcIBEyWhyDTwiDDEAQkL1fL9fJagkpNWWMV3ahcSmhqwtXC4NBGswng
            yt87/HnZmj8WfP3G7uUozgZAbeQs6pMEIKxW1sJTLhmNAE0+XpQeDy0xwyUgM6tB
            9QhujYzWxDtH
            =6z2a
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
