apiVersion: v1
kind: Secret
metadata:
    name: nut-upsd-password
    namespace: monitoring
type: Opaque
stringData:
    nut-upsd-password: ENC[AES256_GCM,data:u8FpzSE+rmIeVsfbyk4pMxYsFWNU82cC3WYQlj8JFpHLjpBLiaxkuzUhvQx5KK4F,iv:rmpCH3ITd+2PCsYRNV4TasPjbNc5lbkjTRz3rrBzktg=,tag:WLqA1k1QO2eGbEJwwEGFnw==,type:str]
sops:
    lastmodified: "2026-09-13T18:16:37Z"
    mac: ENC[AES256_GCM,data:f6Z8twfIubtuGuorxMHjRgZ1RQ5p+gTnlJej0XHAO3EOKpkh7sQ32NPBHL1Zj6KPY07lpoM+PlUC4fMhlMNbGtIxFiVNpx15NNHHxU4LjGInfZ7g5HH3w8Tt+fNf6tcYt4uzXMRGdT97dJytFSaXyRICn8nCS2t+UDV3r5YG6nA=,iv:ztNl2FO4f9rw2LZYsY+RxglWKfRjjE7j+0QaJ6SPl54=,tag:LjNfBSMgGjNL5kznUV76fg==,type:str]
    pgp:
        - created_at: "2026-09-13T18:16:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAApfKlHxVHn4XCp9quTztPaO8y5Q7ztvyW9bWVl8kyQH7h
            eW+lUZCX/EuNCKpDQ8TA8p+jdrCWfM07YdWixMmj69yPAPxmlvWXrz/Tbsej+bjA
            yszt8fqZFU62q7VQmCVs5aQcpLc8lw6+r75LN6Z4kXdgUVomr0vSwoeupFbbY4SI
            2r0+iInq55PvDHg15OaiOgWTKdmjWxJSuxC2fPrTaG07T4y7ADBCF8W0leX+3j2b
            NYA/Y6ebdAsMeTBBZzTpNu/dKdw0OzK+XAbtFtvWrH+NkJKqWMyvxX/TAnh8ezkK
            VxGfppU5Xun4fI26GS4SkJWEomBxK5EVMXUYtR0/i7GiAdJiKcHhZBex5Jxnx7ae
            uG4ckMiU53DWTU43ATvBBydMMTjH98hYxYdHcj2KNV4J/Utmm0fzS0DNl6I1MMQE
            ELLziUzaanHmumGP0DmZvgMnc1wBMFtoJFm8UrmOI34XayzMynSZXpiEL8J8x9/u
            FQRkN9jga1f39uzkFttix6ITdYDEDZbF61MT4A2xe25jXwoSUzwBcdpksrgB7Aux
            9/n178F8IG2HmCuk7+Etlyh8TzIIDk9cnItauqnbMq50M01pslVnFNimEmkibDpG
            it/ESSZ1ciZZPQYO85vUDkyVso0h3zsbwDDlH9btTdtjS39Y1cBReNA0Y2pCTonU
            aAEJAhANdnq09kEGfau5YcqX5M4sLLPkrxAK+BOF5EAvGclZTXPEXV+vhBy29qO3
            ow5R6CxbqKw6WAOH53ooypagbm3nemyKLw3pzCj7lcVnAIWuDqwEV+6K460+Tk8H
            4bg8Bx11Lsyj
            =h2oP
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
