apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: falco-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/discord-webhook.enc.yaml
