apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tpot

resources:
  - cronjob.yaml

configMapGenerator:
  - name: tpot-report-script
    files:
      - report.py

generatorOptions:
  disableNameSuffixHash: false

generators:
  - secrets-generator.yaml
