apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oracle-telemetry

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - tunnels.yaml
  - servicemonitor.yaml
  - vmrule.yaml

configMapGenerator:
  - name: journald-ingest
    files:
      - nginx.conf

generators:
  - secrets-generator.yaml
