apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: fast-array
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ssd-array
  resources:
    requests:
      storage: 50Gi
