{{ if .Values.jellyseerr.enabled }}
---
### CONFIGMAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyseerr-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"  
  TZ: "Europe/Copenhaguen"
  LOG_LEVEL: "debug"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jellyseerr.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: jellyseerr
    spec:
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.jellyseerr.volume }}
        - name: {{ .Values.jellyseerr.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.jellyseerr.volume.name }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: jellyseerr-config
          image: "{{ .Values.jellyseerr.container.image }}:{{ .Values.jellyseerr.container.tag | default .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.jellyseerr.container.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          ports:
            - name: jellyseerr-port
              containerPort: {{ .Values.jellyseerr.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.jellyseerr.volume }}
            - name: {{ .Values.jellyseerr.volume.name }}
              mountPath: /app/config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /app/config
              subPath: "{{ .Values.general.storage.subPaths.config }}/jellyseerr"
          {{- end }}
          {{- with .Values.jellyseerr.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
### SERVICE
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jellyseerr.service.type }}
  ports:
    - port: {{ .Values.jellyseerr.service.port }}
      targetPort: {{ .Values.jellyseerr.container.port }}
      protocol: TCP
      name: jellyseerr-port
{{ if eq .Values.jellyseerr.service.type "NodePort" }}
      nodePort: {{ .Values.jellyseerr.service.nodePort }}
{{ end }}
  selector:
    app: jellyseerr

---
{{ if .Values.jellyseerr.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr-lb
  {{- with .Values.jackett.service.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.jellyseerr.service.port }}
      targetPort: {{ .Values.jellyseerr.container.port }}
      protocol: TCP
      name: jellyseerr-port
  selector:
    app: jellyseerr
{{ end }}
---
### INGRESS
{{ if .Values.jellyseerr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.jellyseerr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.jellyseerr.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.jellyseerr_ingress_host | quote }}
      secretName: {{ .Values.jellyseerr.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.jellyseerr_ingress_host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: {{ .Values.jellyseerr.service.port }}
{{ if .Values.general.ingress.enableSubdomains }}
    - host: {{ printf "%s.%s" "jellyseerr" .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: {{ .Values.jellyseerr.service.port }}
{{ end }}
{{ end }}
{{ end }}
