apiVersion: ENC[AES256_GCM,data:0TU=,iv:OlANJPeSfYgisukTu7X7fcebd9t12lp2AES94tGBJv8=,tag:eOVXizxZN1QXYLMP2/4q5Q==,type:str]
kind: ENC[AES256_GCM,data:JeeZmUv7,iv:+zop+ykwFm2NKW99sQpLbtTRgn2LHO3ocdbtzb8uEp8=,tag:CxN8/vxxgwX0pUH08F+sWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QhqLhjAeTT53mlwYOPHfegtf6GVo8FCmFFOP,iv:B6Kp/CI51A6KbapUKEUEGzqmatyM3bDyetFP1m+viso=,tag:+Rf5WjuyjppQTKMIz5iE5w==,type:str]
    namespace: ENC[AES256_GCM,data:+aRYwrHq,iv:qdu0ASMg1QozNSAK//8oO8BaIEz8Iv6sHOD2ryMiXgY=,tag:aCA5HKeFBnNZLTKO0PyCBw==,type:str]
type: ENC[AES256_GCM,data:CGWZ5By4,iv:TEYUyr5Tv20kaMauzjdUTxYNVbojN9E+mIDu+/rAg8g=,tag:Z63R79/ZqcUMSXIWsNkqxQ==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:LFQO93hU+7X8mKQv9t4CdBQbxMIFyy5M/g==,iv:JgLnggFPFxUtkdhmDOjQwy5PLm+rvqg0C15u0sDZceA=,tag:wqcKcjbUQNSSD/5F/nu5TQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:KpuS1QGegsrxaxX5LA4i+L45j3b3nHn1aMApUiKrqw==,iv:nXNPm4A7P51CkRm1zNJwriNd5RMOs3eBQte6LpxiIfg=,tag:MUhAjlwFBe9QcE9hABJVpA==,type:str]
sops:
    lastmodified: "2026-04-21T18:52:50Z"
    mac: ENC[AES256_GCM,data:KNUJKfgHNq4XHul9wRM6pi7LliUjOQ0+mN0yg81DLIrvU5o/C2h85tM/surz4wJiVr7YI8ou6cdkLok+HtGsbMhpyzVR7nhHMnmhnbM4fCgBwQDVkphssq6p9J7oqj5qJW+HlL5d0FjQFT9XSAQGfWgkb5LhFDrwPFalMkzoIa0=,iv:YfbspLbz0WDLPzrdbYe01+WyhVM2qTAc3HTkgMJUUW4=,tag:roV8T59VWA8ZWplP6/zqwg==,type:str]
    pgp:
        - created_at: "2026-04-21T18:52:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/+LRiDuOxRH1AJMnVpJx5zshBpPof3OrZZDGn7hrFZf63H
            wFGqL5rpjBobmJUKg3bFu/e9KceIixm9pbsjG/8gwkx6+kxTBpUJo2G8bZYfL9gs
            RAKm673ZLRriFx4W9WLA9HkugkvWWpwJ6fbAxNQtjUAx9BovveUCmphW+MH4AjcC
            OQpbMc+TwL2hxjSU2hqjImGDMxaZix5Q/4brjX3PTa3EHz5XbaYYtYXfPbpALxG3
            k1h/SOfQr5bxQgyGKkItobaqXWcGKGOWbAOejwTerNXNKNqYWJQRghEfRPUv1D3S
            ID9x+MCz7+7LTW+4+mgdfaBJ0ET8O7TIyN0Sv7lE2882s78RD7oOOAQpvO4PaoWE
            eUiBWyDCTsWUziEmUaWwbsV/WMNbmZoWnn9gIEyaMoDtUZGi33KYwYgNuLvGo+uy
            k2LIX2axUyW/gA3IT239QA81UIR1dVxDajFQgJ3zakL+n/7G6Dpy3J3K8duPUx4x
            nFiJ6QjBjR7MvHodAel7ynVqgOM1+Tq3yswB6fpqJdBCGYMQai+VDdydSg3ikx1T
            Mbx1LLQSdALghtrzTS71lSOPvNz5Fj4phChdMwfiIj/GBVdG0DOouUV+glyif6za
            s9vL+23f996GXZTu7XVPe0fWCDqxMWZpqbLiNv0uU2zIVZ6UlGCpj9wxCW1np7fU
            aAEJAhBTk+MupRwbqVLuWHuF+C5HjuW1xjh+d0ddOjAKoSqrwg0oBiv8EtgcVN7J
            6SEqwuXiVZPaXFYjAlpk738h7uS956BpmoVLHj5jPNPaR62nCj3XWlbs1yZwjadm
            YHZsgrzC/kjc
            =fqjf
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
