apiVersion: ENC[AES256_GCM,data:GX4=,iv:0ypm9hGHICPkPCP6ixqp6K98K6uLwnXxGptzTUhCkzE=,tag:F7/VanC+yploKkiGFfnBXA==,type:str]
kind: ENC[AES256_GCM,data:9kCBalxN,iv:gmVg37cTIHd5aqR6cnkPpgROqcHRPKnkN9ADfYEE/Ko=,tag:sWo8gpQkG57oeipSeJiWeA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8ZpxyWwZGD+O8/l9KbizewTbkg==,iv:AuF4A/0JeC0qOqOtgv68gJ59CbJwzu5/7/eHtxbNRU4=,tag:mLwSzx1qMKJKLjuzYCECKQ==,type:str]
    namespace: ENC[AES256_GCM,data:ep3VxCEj,iv:R4tbkfGafZgc69GpvD0D0+EAoPjf3KqejXeDLSesX6g=,tag:QJFJBwYy0WI7+uUyWMgdQw==,type:str]
type: ENC[AES256_GCM,data:u7a0j6vT,iv:E8gD3JMCopdw1hqDEK2Os2uP7LzTR5zcuaWPlonBAuc=,tag:ZnTOyGVL+erHIcDZseIsYw==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:X73a59KkKrqFDfZIK3LsCXd8a3MxRGbVHw==,iv:cf3lQRHVduNaBi8ypINN8tfv0E5A6X/a4IeUfz/nOrs=,tag:OUccF55XOZBz0XRV1kBjWQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:GpQ+RMUQVGoJF9CljPhj4eIJkYLa87VFI76+AFRDsw==,iv:1zLWdeLvlwW+uY2Fe1qHYZ0qPXsXIa+t/wPVkwOpHZ4=,tag:nlCfdGF+J1N1kQJyqFmyLg==,type:str]
sops:
    lastmodified: "2026-02-09T03:46:23Z"
    mac: ENC[AES256_GCM,data:uGYGpGbuceAYr6WWhVv3s8xt6BD0DHx4+gLHsGPhTvJFddfZt7IXRNmd7gu8uiPeMwd+Aw5rrVoWbG2L7x4g5HuPFswyZYjHzs3HWQhFTahzUNKdGtiLpJmiPah+89z6r+5V5OKvUFbJRbiFTLY2ktOeaq54IYe98D78h/79hgM=,iv:UsAgfgDf79yMonNMti/tCvmLknmU30l+St9BQVHtXbw=,tag:q1WrAJ2x9qiSxx/t9Reqiw==,type:str]
    pgp:
        - created_at: "2026-02-09T03:46:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAArXbPuZ4wgMJoO4PayLWceh+mmWpiM7/ZgHftSGVcCWx+
            qcKaHJqWwfu/RHmkn6CC+UZXVIV1vwdJmnxUq1cgx0F49TJKUNbj62cVZkyk20Ag
            U7XtMN6HtAPq7vgxxzQMvUaatoy81w32YIsLe/NIXrkydYRiMeczyjZaS/AZsuzl
            gguDQCJSQgTcOabK1EOsrEgIYQmTHAsd9EukljPIlQIzcxK35meY7yE0H1xujoGi
            hIyaUn8NJkPA/kLorL2/bJaIw2gwO0OPgBfJ9mCpDLq0QQiQfP9AgRsm2BaG3wy3
            SQkmyjVI+0gQZefluW9ZZT4PdWaB4OfAffQqhoJ4tND28Jo0xqo4AO/MVVaqcaGr
            xefmtMWwSAOfM3eXQbpGMWxoKy4VBLvp6/XcahmNTs3zL4zJRgwA45eJW1zqDG7j
            e2t1LIiRQ1HA6+tafqvwM/ub4m9orF/2Ol28Vy3wYNpF/l2YOPnuq9P57IecmxmC
            P6NZMzF0I+wMf3M+jONLNElglO2Qh/4xQky0Dgk5ZlTIzXLgfxEMlWWk9DCGkjun
            GKAb8lMxDO9SOI1pNleNLtpu7Eof/6PGNKKK6J8oUqWjcW/XGpZT+SDk4PpGebbw
            IzBrR+CPzARFGImXvwLLdmgeHItlCCxlFHHe/raendXuIZ/CK1WvNDsgvoHnavLU
            aAEJAhAZ2b0MrFQ1FkWpojZLgskP+aIODWgpyGSWjGRFJshZ6VQa9q1FqCezZKr0
            lB/cPUEH87LSO/XQbH6LlISanh+1rkdO9mEaV0q/7VBSXdGFMemwbPEr4XUL0l4N
            cAOQIDSI2+qo
            =9y2L
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
