apiVersion: ENC[AES256_GCM,data:2G0=,iv:KDCBH7CqYiOWZMsRpnEP99Pn1azZp0y4qKsvAkTtC68=,tag:I0qG7DtrGNVJtkhyaI6aCg==,type:str]
kind: ENC[AES256_GCM,data:5hb9Lra+,iv:JxLZLRvE/peydGuBhHnzkMTewDYH5nnj3C/7XfBXR1I=,tag:Kal9eoKIYsz9jcTHZAc0MA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZSb7FsGK2ACStt8P6g==,iv:Oowp+ATRaHTD2D4vj0kabta5ZQ2VvvhCFKpKMH9YpN0=,tag:+0S2EOyeV+KrDj+goetxyA==,type:str]
    namespace: ENC[AES256_GCM,data:1naVqmi+,iv:hOvrja4h9rozennbbdK/QYOThw0bRU7Fkmh0ukLELX0=,tag:y++7Mtul8nRJdasd2NURdA==,type:str]
type: ENC[AES256_GCM,data:n05tjC9Y,iv:NZkaafHtzfJorj8acwoDbePVys8VDd/RBLSGKNU6vOY=,tag:TE4vYE37G6jbTgf31wDFng==,type:str]
stringData:
    immich.json: ENC[AES256_GCM,data:8cbdrCrTfTCV95EyNn6baefUxID166sgxN/n+05xD3YmPjvQOKgKUsiBoJeCZPiUBaDn+FlmpVXHLQtea7itLwKp99tbDEVAW61FyUx1FwIw/moafLnZ3ZJ9y2bPHfVWlFyXJUO5+aYF08uW/M/Tdq2KdZkYk67grthgpp92M4/W/8RwMTEr5CfBC6KB2IWkFo+4Y6ujybTlLBbOcQuroC5BsSB3/V4Uma7xF/VGJkjgqLfEJzSBUzPwlaU4XogoR4DH4GKEEcmQlOPpxAXSqaJgdBpYhrcwOdkcgJV0+Yh68hoe05YLq/Y+UzyjLQzCjIUoeSMka+7SLHNFrWPqUL41eQoWGRcErz+cGvh9NnySGU1VMRQiCPYOPNNxd6sdFvIEmq0ywX/C0rvFEnYQNSZGArUdN1OzcKutfv8IwlbwPQXPFLi7XRJTzLsifqSZfn/B48PARTmUUqp43/M9/QRi4DqqlvdhHjv1h4OIB/TBs1ADQHgIfDND17UHjmdqRrFF8x0HgrOZmcImHdCGVuVQTD/1NsdFQ7DfTsEQW2cU/hyZ56J+tWcayRopoZK5sqNXdxYhu+KYC6Jfjit1IFHg4qpm7LfhkmbaWglaQr17lMyeUjw6vEwi1YLGWs4GyfKgcEq5aDDCcPQ47xcqQttcCDJt2pFpkY2JTANgqS0rvveFZvwM3dg0P8/Psuk+Iat0QAduahF1Vgkfl0HXjD8oA6teujYW0fohsCgp+FgjGE44S22LSKo2wQe9F9uWBUrDK7nrdY61tRJ7TqnActZalUByi/LzbKe3lonak0ELNEqnfuggSdc7VgO4HyRJnKL/9O/ReOy1N3jTQDG7NM0eGbgZnndftwCKOC6nM4AsPHPHmz+5e6wknEMvmruCXg6/kWxkZ4yhCIRoBj0cIxi2vhxhrcFKloali1d6hhYiIYEkqfnM0PxEEvXkIKw5dxNizz5MVgkjj8fbbXWuItY/nd72G5ECboPrCrlam6WRhVtdkCyRW3GN81km+ytUfNRSplTldKXvYZ3oktartCY=,iv:otYs5f1tVz8ERlYeMGoANAyarYVdaVu5MaMdH5U519c=,tag:AtGq0u8PHKNQyqMSccctLQ==,type:str]
sops:
    lastmodified: "2026-05-06T21:21:23Z"
    mac: ENC[AES256_GCM,data:hdSzf08KWnYSe4+9dssmyKtZJQ5ayUVKSYch0FmMZYVAcmXWgT+1+Ze9AXpfXxP6eM3kfOjF8oU1yCY+gJCX2CJouwPOz5X3Wh0jvjFsHMLgCxz9IhbKw7kMfhwR+5eG7RBhG9C2TED19JrgaJjujOyDS2VqPv6hZFaoN29F/vA=,iv:i89XinBq1dhfAcv6FdmnSeYCpr+cZaiqRg6L2QkU9zE=,tag:VjxMs2rBLiv0bU/GSQcjmw==,type:str]
    pgp:
        - created_at: "2026-05-06T21:19:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAo5G2HuF+sEIWbP05CpwWMw+amiMhM7Vniq0ugHmnbfmt
            iTrNrdg72ck2Pddeo1wQQo1Vzbvgl7x5Bgkj/Jpofmh7/RfNPcdyISK/X1FgBlIy
            jMHuiqCwrDw6fEHt512KqSqMswgzfAizpZs18wtby9pyoFK/8cE+4dYSdwIPSB9M
            NZq6B1qzFGecDj3JkXzC7oTBXpOsJuPO9nxEyzQroCkVwmd6U9h0rayQidLXVnDj
            +TmUnn6O6w4Va+XPBE6S3Egtf2WQ0J7WrtV3toTYsqZonBMAf45nZ29+m0WIn9XQ
            JXV1+slb6mdLie95BL3g2uzhlDdfI6PbUQ2bYVgxD49S5c21+FFJschWHQMJwX7b
            dOP3zk6FtU9gdYG5xrw0H7z6+Ci3LtxRGyODtn4354pL+DSKRIwdpquYtiWe43Ou
            lz+jVBePD9AOLA8f5pHn8WvAjH7ULSoXF8dVN6q7Kj4pkhAG4INfAtZ+0ogudtTh
            kERxTkg+QvuBnNrFq7scNboEVBOaFH13jJpoZgR2S6NL7+UbaftRoJpnSxxuovwI
            AVr5IX/TZtbCq/EHeUmypFE9srMKVDXDq+lFPhlQmjyXt6q/0Dx/fak/NlPWX3qv
            cMS3Z1cOhMqp6ulqWVVNGLGx9b829wTh92a823XCq52zPg3X+vDSkP3w+idCsKXU
            aAEJAhDmKXkkpsdFkzYmLs8j8YoVna9A4sKwmThd/jACBOPeGvziZoU/0Z0LxY2P
            DaMdOZD9b/vVTeHS+OEOOS094RtN/7DQqjI1xYsioRzOaLlvSot5XPt1sPlQ7xIN
            M12Y3zp682+h
            =9CGx
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
