apiVersion: ENC[AES256_GCM,data:Cc4=,iv:t2MTR8kA0trRyiSDLCC5PSrvWm0z8uykqhnkg0P8nHE=,tag:LEMeTlI27p/lP6yzRQcleA==,type:str]
kind: ENC[AES256_GCM,data:2TWMW7ED,iv:zrj17eU9tG+aNRKG7tPdNNlpmtf0nzeJVDqCfir7tPk=,tag:H/T6EcHVHQ4xyy21ZPpKVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZS5zjzbO8DjbxnFiV8zxwrul9q4=,iv:vgvu35DZMM4EaWxg2pjWMgRv5UpgcavvTJwoRede3iU=,tag:2UVpSsja1I6VlYqpx9p+7w==,type:str]
    namespace: ENC[AES256_GCM,data:zG+4aqaa,iv:V4UqPd7C6tQ7b01xed6fBjbh5q4oJ1sJJLc2ng1wFRA=,tag:1lz+ncy15LYWQGL9Q2GsNg==,type:str]
type: ENC[AES256_GCM,data:Ez6cthDn,iv:fKqLoZJy0Diakz1b7xlBXeb6YFl2lGWWsqkTt1nwa9E=,tag:BjE9fBRgGRiyC13FHN/vLQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:UlGtkIsJ7LOhlAbMHjNlqayaDofInF+Uky+jfL5ryys5sy9jbQBMexfFb/HuhRbfHrs3RdAH4BQR9OW6nfTtdYrbcWvqPvY=,iv:vnyNvkcIuC5WQ2153dmSf6Lqq+tZq5QlT6BfF35TTY4=,tag:jdrgtBKF8eEYsyX2QH+IJA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PHLTgYTP4XLO1A==,iv:Mq2yIcnvSjViyr7mpL6judKUuS6hGoz3g+5UDsc2d4E=,tag:6xTRnIWBE+v2D6fkDC+VDA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vAXePGRyhv/CiA==,iv:ssvEevWU3/+uTf4ixO8GSP8W3ixXgAcbd1s8OsArgsk=,tag:tHUw4hAZpk/n6Sgt5mIShg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cqrp7Qs9BYk8Ew==,iv:8OsromPSF6x+yAMUgVXrXjomE/dkeNKYOASylQMkG0I=,tag:IH2+oiATo9mwG41HMvA+AQ==,type:str]
sops:
    lastmodified: "2026-08-10T15:50:04Z"
    mac: ENC[AES256_GCM,data:3i4+MmVbX81QNlSTYry406UX4obzUUG84bN3x5bIV37Wh3BvZaxDZ2OxY05x79bd2/FHQZCgd+UhRKqT0gHo0NF0b3DQnrfviEgUwedodsIphZAjm1WRSD26f4RXHNaMY9IP2A6ILM+1xqEF5+mdkvclnbshnb55bXLuYLZGZE0=,iv:BrQAjDp3crTGNV+XZrThxgRv+uy/XxVdzAZLCaoAN4Y=,tag:/O1sTr0cnR1UlLENpCU/Pg==,type:str]
    pgp:
        - created_at: "2026-08-10T15:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAxgI1DSD+e1RoWtv4PF5ke6vhpooSc38lMjY1fp7zzjmj
            Zr85Vb2diERfqzNh62tggi7xEmkpY0VmGSITCzGgqU3slJHB3M06O0wV2MOaP0jH
            f1QjHqs6RgFlUpl4XMXhouqljabby4MKe6HyYX26Hz82xiyvf+t25qtamqSfw/8A
            HCqiOySP7c3lv/gFtKZ58zZHTYM9JMWpEf4lTAOWo+KsFb35DHwLEExoIwl5APtu
            Y/8NZCAA73Z3ZDZeHs10O5otWTDpEmHcZfNK0h2wPngRf5DzXCLxeM54R9o0R2f7
            ni4PDjWvADvLOSGoZnLLUDcImvqkz/3JRA+rmmYuInI+QiF5bJ4jb/rILtJBpdW5
            +G3VmD20MtJl+zC7Wgp/aHbF/CiLRvvikfa4+OhFrZubByWBjIWt9CYUrxFg1jcN
            gBbr75flmNKnILdNMQ4SXOPXu0STi8fuopbTkSvdxCX48UHHkEotUsr905KuHMbO
            EHlyknn3GpaNcP1yRs+Jjm+kY1M3t0aFOV7TfWt7e5fewOY6f8u5fWvJQ6y3lp+a
            LQATKCa5LyZbkg3b/Xlc5GQNqUGHVoJco2w+xUtYkKEFGbXiM8ozvSC/v5LuXBHB
            7cPoe6IGGKSb9oIk6fJuWw7BSsgRuS76teUTqUmJ5Jb+ykcl8Llai/oCH0GnYJvU
            aAEJAhAVTqUktnyHNTEcp5Wvj5sEFHSFGRpFqAOnr5oF+RUQ9E9deFGUZqhlB0zr
            92rHTyMPPcxKKuKvxt7cJGvZPMnc/WztaafVUQBAMvQq52dlJKBNmYOw6QvaYjii
            HmVGlxaeptjO
            =8SAY
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
