apiVersion: ENC[AES256_GCM,data:tRo=,iv:Wbo+ife54Qj4W3b8JU/HuKn3knYoFUe2/tvE9++1ntA=,tag:KziHJC3ldFowexE9AkSXNQ==,type:str]
kind: ENC[AES256_GCM,data:m6whJCCb,iv:1tuVEUTUXEENQKdn6bQvz6GcTVA821RF8fSw5Rd42h4=,tag:pewsVKsMofAphiZ6UngO9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k5kONiVmWDg4rRBBna98wJmkU48=,iv:wMXVEJUikZepo70aeWG97LXIIBdumZaP1MkX/v6iVHQ=,tag:UtXgSd0ak1h+zTCPBVCSwg==,type:str]
    namespace: ENC[AES256_GCM,data:jR7AMZTU,iv:CohRmNdnsnJi8dxBj8oeJN3IXUI7oqU1B7WItR/U5iY=,tag:Dc9RL09gQjFEAcIZ/6miQg==,type:str]
type: ENC[AES256_GCM,data:6Jy+EdYZ,iv:qPauDrFpal0elJpDArHeEY3s9PWwFVcy3wyBnsBnQQs=,tag:mYz0Ui2fz3n/ipLXyeYMag==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sF5KZBOO/MjlOndrHSQtNBeUVitEeKZmNECaiZVFzBppD3KZuPIK+A9ciOHBP2Pcs83wIsaKTzW3JxFmS4IrXDsY+JNySmg=,iv:rg1oHAsktVuBjWAFf4BofFgw9DOhc61bTnL1Y/DO+64=,tag:UUSJHVKKWIKKkItEzsF99Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:V8yH6KHFOKxfFg==,iv:J3g3POMhWY1q5f3DnLxFrsRGqmf3SjOp5duP2xPFhNs=,tag:WL4irWeRnvd72NBa4/sgIQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6op8bYtloaInLQ==,iv:UxseaoqxYtdqyXOsOjfdGfM/uZbOBSQkJ9Qm49jOcrU=,tag:+bkC7QqmWdGCjb/eu4IujQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QCsRvg44+/6xsQ==,iv:uOMeNtB9gX2UYmSbg6sGemzzFGCKv9n7ZIpK4yIx+AY=,tag:81tmEWR9UYuoC6f+k/ENVQ==,type:str]
sops:
    lastmodified: "2026-08-10T15:54:52Z"
    mac: ENC[AES256_GCM,data:OfBOIXkSP7NXVGL/GwgvkR9da4M4FDL40EKfOPFXLpUlRmZ/ZuKg0WaC/ri7NP0iWpTnPtQtImkbQyhRVAzPaJoMj/n5THVj5WNaG//mj2Lmxq3Vynz76hQ3b/7NOf6gky5V8eTdutjLKxjCipL4xAJi3WK5NZ384BDPyfABwDk=,iv:bo9aAUVa5jDUtzW0WZNFq+JaUTaFpjP9ENxF/hMx/Qo=,tag:/FTLJ39xB7W5nvXraOtLDg==,type:str]
    pgp:
        - created_at: "2026-08-10T15:54:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAiQImZfYksUb0PruW/gU6En8KpAxfEsg4O2NiHiE+pD24
            eRoIBIKOEt/K3d0QE2TbvXQ7npVnwhAfZys5SW9U1mI74KZkDMLPlswhoy67GVt7
            UDr+JQAwI5tm6cbnaWiSBXDQWd1cPJ/eznK/+3PcJLcQhdhYwRFpgtyuQoWBHDJm
            fkBNztl9VF/dtiCEDLUEfHqezCgyfXLORstXeBy2pykrEsvTYiEFWla/myYBZEaj
            dQzvXA90GzSBkuu3PWQFQbc6+yf/p8xguwxCDaggeEcv3wIRlS4GdiwR5kLC7RDc
            zr9mBMX9drPkAl8TVe7aC8nUiJ/pDbcAPqg7T1YqqzJ95iL2dos5wQNW0o+/H2FT
            D3wgZlCc0nuah3BTsboItmnC80YIjeooqo8FqG+xGOgBVhcoFAErQEdq43PCk4Dq
            F0mad8rEXCmQbhy6a7YFnFMHcw/17Fw71By0YkHEu3Z55kLVK2YAlUNt3Lx9LmKb
            SpkGJ6rLsidqfvM4X4DfoR6CaH5XB8B39tyI73IOJYt7I2cdMhe/gP7ZLneNNXVN
            sdXaFsMUVceAQSbMlsR/UEZTzwrs31J0K4yXf1GXvMAWOdUbUzjPWRLb3sN+PFtq
            sS1vAGFhxSZszJafF9X2Xx3NhiW1IFUmxbfFRFCWWKvFAC2PeWQq6LC7N9vGN4nU
            aAEJAhB3A/8ocfaTJ5YaON3Jic+ZuYK4uwqqCZtag6luj8fj+eU8vIIPNz92wdhg
            8qohjgFnYn3nQD/Q7YSAQedTzHdUs8cWXheWaIXJ3IIXiVQRY+3veZbIhbWK70K+
            1LL6erYtE3Qu
            =1c6/
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
