apiVersion: ENC[AES256_GCM,data:Cc4=,iv:t2MTR8kA0trRyiSDLCC5PSrvWm0z8uykqhnkg0P8nHE=,tag:LEMeTlI27p/lP6yzRQcleA==,type:str]
kind: ENC[AES256_GCM,data:2TWMW7ED,iv:zrj17eU9tG+aNRKG7tPdNNlpmtf0nzeJVDqCfir7tPk=,tag:H/T6EcHVHQ4xyy21ZPpKVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZS5zjzbO8DjbxnFiV8zxwrul9q4=,iv:vgvu35DZMM4EaWxg2pjWMgRv5UpgcavvTJwoRede3iU=,tag:2UVpSsja1I6VlYqpx9p+7w==,type:str]
    namespace: ENC[AES256_GCM,data:zG+4aqaa,iv:V4UqPd7C6tQ7b01xed6fBjbh5q4oJ1sJJLc2ng1wFRA=,tag:1lz+ncy15LYWQGL9Q2GsNg==,type:str]
type: ENC[AES256_GCM,data:Ez6cthDn,iv:fKqLoZJy0Diakz1b7xlBXeb6YFl2lGWWsqkTt1nwa9E=,tag:BjE9fBRgGRiyC13FHN/vLQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:O1gaDUYPG2f54X51H6DAweErNbeF7JXUf92jV5kv5J4MFKaMyEmM3x063B3C3YWBvU9NbFf+mD47odT9RokxsMxpGRgEc5Y=,iv:LpXInSUKeDs55FsFa/3z1u3Q3E0YKuwkP5Cz0YktN7o=,tag:IXkGRj0XTLvBmw2jiZ+i1Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:5IrkDpOIiRkSHDn2EE10e5MgoCtpzEA1qgYZ/hGeYwPrpKno7CrcIS5MnE0Gv/ynM0XLubXbUxRTIU5zPZOf,iv:YiwdaSj+x+YbufiFwuN0OWJoRQoAdZ5AhVxBxl6zkVY=,tag:bwGvH6i5FS0qeooIdIsTCw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bzgHFFYKHY71XZJ9Z8JxpIOn+hvh9Xez1A==,iv:KghzjCE6vddpFCcIkAcwmEFm/0UqGgWA/V0gCl2yFyA=,tag:Mi+MJyHbv3tv/Zhjicv7+g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iEMfeYtW/ZH+EuHrMJ77MntCNy3RsJDh9v/t/H9X0A==,iv:hEOlNSzLQ9qinnPqhwaf+bzfpG4dQxjTOQRwPL4TDNI=,tag:ZiM12rWCNKbfKDXuqQchcg==,type:str]
sops:
    lastmodified: "2026-08-10T15:56:09Z"
    mac: ENC[AES256_GCM,data:T78zpZtPm9L2l9Fe/zfRZi0pvjyufkkEQr+oXTxCsLiT9sdiZdFUXJYWkKoEwRAnx/rmoRt7r3kGf7ln/CY02r+d6Jcppmj5DtepB8EC1hZhJbY8WlA8fWJ10IdZZ62SxEKMcuevTTtYLatR0NWjfQIbtHwmk6NT27Tfb2FVR4U=,iv:XMyp4VgzfSrg0xGAhAHZm+e2fX+PqwYhgTIh+e30CJc=,tag:JeHOn4NOCTwlbNsgEgZ0PQ==,type:str]
    pgp:
        - created_at: "2026-08-10T15:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAxgI1DSD+e1RoWtv4PF5ke6vhpooSc38lMjY1fp7zzjmj
            Zr85Vb2diERfqzNh62tggi7xEmkpY0VmGSITCzGgqU3slJHB3M06O0wV2MOaP0jH
            f1QjHqs6RgFlUpl4XMXhouqljabby4MKe6HyYX26Hz82xiyvf+t25qtamqSfw/8A
            HCqiOySP7c3lv/gFtKZ58zZHTYM9JMWpEf4lTAOWo+KsFb35DHwLEExoIwl5APtu
            Y/8NZCAA73Z3ZDZeHs10O5otWTDpEmHcZfNK0h2wPngRf5DzXCLxeM54R9o0R2f7
            ni4PDjWvADvLOSGoZnLLUDcImvqkz/3JRA+rmmYuInI+QiF5bJ4jb/rILtJBpdW5
            +G3VmD20MtJl+zC7Wgp/aHbF/CiLRvvikfa4+OhFrZubByWBjIWt9CYUrxFg1jcN
            gBbr75flmNKnILdNMQ4SXOPXu0STi8fuopbTkSvdxCX48UHHkEotUsr905KuHMbO
            EHlyknn3GpaNcP1yRs+Jjm+kY1M3t0aFOV7TfWt7e5fewOY6f8u5fWvJQ6y3lp+a
            LQATKCa5LyZbkg3b/Xlc5GQNqUGHVoJco2w+xUtYkKEFGbXiM8ozvSC/v5LuXBHB
            7cPoe6IGGKSb9oIk6fJuWw7BSsgRuS76teUTqUmJ5Jb+ykcl8Llai/oCH0GnYJvU
            aAEJAhAVTqUktnyHNTEcp5Wvj5sEFHSFGRpFqAOnr5oF+RUQ9E9deFGUZqhlB0zr
            92rHTyMPPcxKKuKvxt7cJGvZPMnc/WztaafVUQBAMvQq52dlJKBNmYOw6QvaYjii
            HmVGlxaeptjO
            =8SAY
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
