apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: helm

helmCharts:
  - name: external-dns
    namespace: cloudflare
    releasename: external-dns
    valuesFile: myvalues.yaml

