apiVersion: ENC[AES256_GCM,data:DbI=,iv:pgIaZlTFHU06MS9wlZjcPpdoAr2iucLYSNgo4qaMmwY=,tag:QjGIjaGek6pQ2hmySHe0HQ==,type:str]
kind: ENC[AES256_GCM,data:XE7bzOXM,iv:dXHpYFbKG3tv0hrKlzGNArv/F8/7nbYCOUIgHnGs6uA=,tag:sJA1DfAd05ZLJZz1Vso5YA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2AxnxDA66d9UHFMf231FR3FycgSjFA91+s1rH5j5aamkiXCw,iv:0l82eeTLsegLCue2jK6u9dJ62mURAXX0m33viEfShzE=,tag:afyoLqj6J/QNwSY4aE1g3g==,type:str]
    namespace: ENC[AES256_GCM,data:GuAImWD8Hw==,iv:CDgRmo1PI4GD5GJmD4psAhy/1STT7s6DZj35RyW2iTU=,tag:G/exGicKKNaag2YxNJNDEQ==,type:str]
    labels:
        app.kubernetes.io/instance: ENC[AES256_GCM,data:1ojFyAhoBA==,iv:RMsYN0wtThwpkA5bKntjISJqIPFiPk/2c44wRBpsFt0=,tag:iaX+kqN+sw1h17aTwMbUtg==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:32sj5w==,iv:M7hmu6AsszFojPXshKInMeqLQsmu6iIQm1rEg1yTQwY=,tag:12vy/RFeg2AMHFlQdAj18A==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:sJlQ/5IHhGpcL186jq4=,iv:0HY9lH99z0ACVZQk7TVarMghmmxPN/GDThaUonRFliI=,tag:VzbpbbmrLuPZGLjPn+46bg==,type:str]
type: ENC[AES256_GCM,data:Oxz6psdI,iv:yKyRisRcTJjrFhOsiC0bbJP89PcP8EhRON/FX9UGrJM=,tag:vInXYzOnL5H9sPDFp1zBTw==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:GWqwHrP5LX9AtonmDkf9WbWJp2yYyqrxAPeLyViI0akzRZSBSX/bBxAo4/WyUijO6ja6rFem97LURmMClBdbevnuXNF6Jum2nRNjLgSY1Ns4zL0X17X2fPQLbdKyzZjk+Dgrw75KFxa0HLBDm+R7ROHKpWci9oJD2XeoNA0EP4gNGJBfDJFAFzRR40wF2aWGQdzCXIpnwgKxTPseGwFaYQOclsDXuSAYpBJROexEHsb/+XDWMwHXymUJs1U6AJwixiiOARg35zvPJBQ5MV+Z1rS8m+b9iAR+vryCnLozr0QeM5YcqzoK6B1biSQEWwnWDmIkGCoS9I18QrVGUIXkCr2x8ush7LU8oQqif8BuaYMkpyAZ2gkEq0LmPn9KSdn1SoBFhbNLOo3SMv0Mwyzw9RD1zMImATpoRHvTG++Grta/CsO+UWweLij6B2n1iFnJNuG3cqySPenkoLgwqLudxKvcUJNB79w6hcLxlkxnvST5zRrPk8kVlE01dGzIrF85obTbCCu17t4toHAJ9kAtjH66oDNo6QhUtbMFOCV0n4qv2Zc33xS6w7RGUP9HoYsv2Jk6RvzrkqTAQXNLv7MCTcTN2B7vp46LmJZvoYEoey50w28g9nvKKH29M1gTrIR2CmXlQglOUoP3IGGSJq34LRIBT8/CsJj2rbWwXTjU/Fe1NEWoTLGNxHKbYO1Zm19wSRGIkLSOOIg+tmO0j9Us6FSgo+pELL4LQaPTXwkS+ZB+pHH2gny6/PgEdlg4hfA4FUPKBfcEv9R8D82ur0LXfSaVt/bEFsAtftr2XdNODjOJuRDsamigsoJhQWK9q76xcKEiNoYOixl86hUM9UhwpcRlwRCxnuNHg+5Hd6LyPHHg6yUAXmpBuBHkK1wM7JSVBAj7HLD4/oedlFNAW6syvPlISkySrVm1A31DBr0UJTZrBRBsWUITPBfHHPEMhOavY+oc/AFbVZYbdw==,iv:d9neA9B4IXP0vN4X6z/4TTaD2LNG+McYMpTTMP7Ul1o=,tag:1phzUrpSaVb8bqfbeG/LLg==,type:str]
sops:
    lastmodified: "2026-07-31T02:32:59Z"
    mac: ENC[AES256_GCM,data:usDVN/6DXmIEyJpnpoLwqAeIX8+DJxHtQT43cuSHIEhLF+w7xdtBJUq/9jBAbdjn/34UbE/7WV5nKCWaqcG1ocsp8+1mYJh1J0jPCO3wy6kzTHGPW2R4sZ9jSpzWhCWcQILDxmPgYuxFrXdgYVDeDLnPspCMsAV+U3zgafnn3BY=,iv:Mb3/Sh6Vi9y/fLp+Z4ELRU+LLer9Uv5PTCgRrrNidmg=,tag:ClEVwPb/jCC2prOErbkZVw==,type:str]
    pgp:
        - created_at: "2026-07-31T02:32:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAArX0pHDiPk00Xwh6BJPAiemSHIWGuIpgbk+FcM2noB4HI
            PWbVJAKRlgx6AmH/aTkX/N7ckxfyt+lIV+mA4GiJDj5YXavuN3CMMLTtVM6vXUen
            H1mDeeDl2R7WiaM/FpRIch0Mav+UdI2eVwtgFQdXwZpB1VCvRVK5J3IoYgS3dLI5
            E3dvce4p9BP4LbXpBXtqwEWCMshbzZpB5H6UIsFjAwWTRkEpV+d1Pw5PSdByUvJa
            NNO/5S7Km7NwN2LLexG+zv4CLBkrFK9RWyxXnX30j+2/YUv7ebNiSbudsvAVXXE+
            Rtye/yo9T3wALgz3HxMcWrZUK6u7AT/jU9JaLRJSvOje0gn29TDJXm2F3BtXHeSf
            OQWmFa2zcBAB5RtE+yULKH4N1vP/6VZfr2rZRYUDfhsJXz4Pq++NtbmDslQohx18
            +Mtj7E399zDggaQ0aPWQkc4t+YgJwsHOHg1bsLiLU+h2BzeGkSluje3u//WYU2gS
            M6vd6LWHzuoD14bqxs+/SbxVL/C83+nQjRzjfjKEWRHru+w/hFcl23T8/ttZYSdd
            BF5plY/24c04E63sxVA2ujpsNUNWOKdIEOadFGlJ/VlYpnINyS6p95rxyOt4+Z4B
            wSNWv1X84hyAG7uGIanawDo5/4xWxqqrB9UpbJ8h/0Wki1cDnMk5obglS2PZGtHU
            aAEJAhA3DO9jhyz87xw7XmhjOY9IKvq3q6xr019m7aUmgqT6ZPzePMKpsJ2Rdlml
            bRJTt8zVFXdWRGBbld6R7IBhfqyE3wR8a5KR7BqhIT4kn6UeGyYpLZTeKgjee/zE
            oxbJQ/pIxwkn
            =f/OQ
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
