apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monerod

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - local-asandov-ingress.yaml
  - servicemonitor.yaml
  - vmrule.yaml

configMapGenerator:
  - name: monerod-torrc
    files:
      - torrc

generators:
  - secrets-generator.yaml
