apiVersion: ENC[AES256_GCM,data:Ghc=,iv:6t/2Gqk7Li0fApcDGO/qno0de+dPO/TFs7QYOU4pTow=,tag:7w/seyL64q5+CfZLG7W3Bw==,type:str]
kind: ENC[AES256_GCM,data:0wpIIhEj,iv:5MEGuk0MNXHQQ8QEbyUd4AjjrH2qZ/R4HCFysq7P028=,tag:Y+kYM+iZykE9lqr/yc9wlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gygl6CUikfBHRESMAVZL,iv:g6h/2QLX51QD+WYdPEBO7n2TAy7XgzTuP3gPQRNbTGI=,tag:rRP+I2PR4vm9P+iZjVntQA==,type:str]
    namespace: ENC[AES256_GCM,data:UgvMQ+o=,iv:KuUjAqg2B1f2QdznQD6x2/C9TictM6uUnDvBvDet1KY=,tag:6hQzmYmhs83Uq1cOUc8Gzg==,type:str]
type: ENC[AES256_GCM,data:5ec4C7Ab,iv:tMROr6IOIZ2u7UNYC5DV3g4RKs6+Olu8moZzWJHyX1w=,tag:3xhtF8OsCD0wQCJ0uOCYOg==,type:str]
stringData:
    NZBGEEK_API_KEY: ENC[AES256_GCM,data:DK3Y1cnPlT9WgMW4neb1dwS/00AM7CAM4q0YdsbW8Gc=,iv:LG359BvIWnxBRRjMkYeUng3jW/UaB7GakqE2ABLYrbI=,tag:WXipYfmwgDpt1ejOt6euqw==,type:str]
    NZBGEEK_API_URL: ENC[AES256_GCM,data:vEDdYh8DJcaNyTjPo2rexim5aw13IvPDZQ==,iv:BIQ7IpSpt+bdvkCQfpdtMrc2pOKBRZHJDfRY3v9TLDM=,tag:HJSw/8pQfy/5ePW2t6FrCQ==,type:str]
    USENET_USERNAME: ENC[AES256_GCM,data:B2sBN1lPFeLgRV4U+Q==,iv:KkpQ5qEI7ZZviJH4g0Ti10RyLKi7TM2IkSSZlUlNau0=,tag:VPzQrBJoNSsF0zDk4pVxCA==,type:str]
    USENET_PASSWORD: ENC[AES256_GCM,data:8qdINrHPii8Lyd4QB4+BqMbn,iv:nkzZsSEj+39f/l1x8LP4BtOjgIqBYqnX/if7/DHNUFg=,tag:LmOZeEdYWsB9GkRK5nelGg==,type:str]
sops:
    lastmodified: "2025-09-04T04:22:21Z"
    mac: ENC[AES256_GCM,data:xklg32dEM8ikMCRB/DOCiXaLTe1iA5PPc8tQ5lEdujx9utb5eJr1fQnQUqQ06q81hMglyG87pP28uypWvrFzA1ym6fMRGpJIy/SLUhx//Uog4WHJ+/I/ipzT+sr5qNrSk8WACxQrlkrHngvgfQWIpeZcYCXvR4NRVTCvbdjHrJo=,iv:AdiaoBekF1c1MFdDRaNkHC1PQLRvdgp/ww+HFDL5eVU=,tag:vsu2YBy9luqFvSNxcZnjjQ==,type:str]
    pgp:
        - created_at: "2025-09-04T04:22:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ//VUiiJXxbsTJHarqxShnFAFrAmqk1Gl3mX4CoB4gutGJm
            xpEGciOza15cjSlvvqxrnUHAx/fXMFrUe05ZhjO6KTXtNT6kP1oL7RbcUA5/IFJp
            m/IdOzS/cexGTmUMO0NWjhw5MtXVGPUfu1i7+/dWIgai4ZOfNK8Df8nNWHl5juAV
            7nlMtQmieT0J11XaM3NTaWr+IjoJ+AASNaPwasCjDHTr1wLqrqL7Sab4hA+Pa9Ct
            KJJ7wsJsfSup89OBxErthxMEpVCsGKzzPdPkM4M5rki0ZmMK3aqK+E6VxVJbN9Bq
            35d4pruRMP9vOfa0GkND/6UcefheVu0djewq2hbL59hK3IcZssvLb1v4S4iREcbm
            Hn+8VuVZVnshOg9oGHnk8NVpG2th6yfZpOv3XG9tyJrljV9ldO9sch7QI05KPCZh
            RuMZ/tKgI+A9Wa8aCXvtPv0n3oljEsl/CZqUVugtz1KzEowYDT2QIqkaVDeswm3x
            lmTul+OjNsGY0RBIe8gLf3RE20KIyV98B/YIyfHGiFWeQpvRhIGZ2PHzXyGLBDk9
            kf3Wr6mZ7ZX3V5O2IXlDAE9QoshXUiTtPFTYXrH7PkBa2NTLG0HFyASMZw6FZLrq
            U9F5DSf75xGFO67ZvpqzoJFlTDVq6iXMxPDjYpQlWz5sDXZ4+6sp69RTvvN+tiHS
            XgFNjNl3bWnrJyY1pPULsT6yIrMLJOUK6uMpJaxfjVvk0Xsvu0VIBfDmiR7+peOd
            sPl3wBh/WldD/8VVRtY+oLvFO1ihOJx64mrUULGaUo8qKefHfQFbhGBeV1dcNA0=
            =4JWY
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
