apiVersion: ENC[AES256_GCM,data:+bU=,iv:cQo73P6DH1jR4PHO/DXKG1RGtfF5Kjb1PTRy9ZjXnIo=,tag:lZOm4pJoTdjIX9liu1DdLg==,type:str]
kind: ENC[AES256_GCM,data:UBXhjbuL,iv:IYx+flmg8MfPfl8cDSnlnycVVLcBnrpURNxlc/9M/xc=,tag:82is8Wqaookd2tnjF9GXtA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9J4XeleX7zahWodhaekWcrC5F2JepV9N,iv:/DrFZCXzjM2g9gZBDY+YDpAmH+vCc/Vq47jSnjvneIQ=,tag:oD38pcKlweD49C8/Z3WVVA==,type:str]
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:NZZQSA/h1wmV/0pKovP/ew==,iv:GPlDVgqv+cNrVC/fo4QoRvbMqxtw0e/ovTCT03ytbx8=,tag:N9vzbOOshvafgZugFgoRFg==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:XpS661u/Xg1eag==,iv:6oyRabM5MzFXWTwfNflR9QVYSlVv1gVetbv8ipytBXU=,tag:5uM7FCUlYS0zZ6oKeiV+Eg==,type:str]
sops:
    lastmodified: "2025-06-19T00:48:29Z"
    mac: ENC[AES256_GCM,data:7J30bmO+j0ao58n1M0QkNd8niAzZukWyO1HfXi2klWr1j6v4sgou9kXANv/pvF/VP4DSEDRcS2Cp3nn8RArEYzkVq/yrU50Lgx0v9KuU+/YmNNujYa1+8jRnIX8SBYZE5WZr0YCTxXu8LRm766JEWlwn0+usIJnKOlET21mKleE=,iv:Lp+jhU/8bJmTP5bdYYas1qZNn/x+O6z7f2wp0RSAdDM=,tag:QZJGqQFQzcbbnCpXYaq3GA==,type:str]
    pgp:
        - created_at: "2025-06-18T20:04:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63ARAAsCqupC89ioAeS/w0QCs8zx+TD+7juQSp+2BiFSLzouVN
            J5kkPqDqm9lSBEICCUrRH/NEZQMLs1BnlvelpMIfR2sCIk4KuWr5QpfvsQmPAYa6
            RzhGfLgxLuS7iqJqTcsq2b1f6ddUsCBKNGE49NRz4oRPq0uoycNvfGBLWueKjvJ7
            Ya6QzKAeQamctTM8b/fgXtoiPgDf+0tG8eBvvm4fTJGgFDdAFc2cZQF6xwCMVoiN
            PzvAlXG8pyulZRx6Cskk7zllnRTt06ZUnTCbYPxYF3xF8GOLlURexnK8Fadi8n3Z
            1Q9b13OUmSbMr2vo8h2eyj7EG26azs+5sPVAOXUHERvQG7lLeBOPrhKMXy9Hdvmp
            wdj1x1RgOQo9Tm3FQB+7tcEucw6C1j9bF6YJ+ihjfvin4NxmnDYFwIcLq2AeMa79
            aILkB+u783vs7vy1G842nhGi5v9AfDs3QFKg3hPdzO1dOsCikQdyWLnOdL5Wh8Zd
            gN4b3713PitLmed3uqjG+mll6CeNOxzDpQngxOk4SFyNr012f49/katwRjWDgSBq
            dGOqgmRTiV8jBgk3f8C8B6YUPcD2VlqQE46e3OPWEjLQOSaQBW/eGb7HnQ0P3LJS
            b2sEnSeHtM7iBllibUieECZp+URSjCUjJja1l5jOln3uTQJyfnUFTFh3lgr1C8bS
            XAECksInqwTa6khYYyVy0hUT8erPhAoQMpbMi4cOiCVoUBFbLNJqNCcwfWX/i2R2
            oXHHMs2QpKoNEeQJe0YcdK+wNkEKZpLBKV9gGftGk5aFZa3WxpW27LiO8UIP
            =pZP8
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.10.2
