apiVersion: ENC[AES256_GCM,data:jJw=,iv:bbMHLn9whtqtJizonOKGuuKAfWGbAOhuNwNxLFRf4w8=,tag:Av2tqm+vMhWmzcfoBnSHCA==,type:str]
kind: ENC[AES256_GCM,data:GF3DOsAj,iv:6o2FGVBzuCr0aofe/UUXJRZ/kvDV5uPTz6WLUM3P9zI=,tag:ljei2EtZkgvAQz/zI6r7+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ysxZdgF5qB1d7y9++y0=,iv:0D7HVsd3cxiQngpGeIfznXCE64KncU9WmLf8VDMRgFw=,tag:Pc0OdWLwytLKv4Y18zrIqA==,type:str]
    namespace: ENC[AES256_GCM,data:TUWgHTtn,iv:kvV1mMX6nTk7+lMo1Z6m8C+eIhJ//XWZ0hFNeo/ZxOQ=,tag:q4kGUq1AXYp3la78MxV8Ow==,type:str]
type: ENC[AES256_GCM,data:SVV480s+,iv:taJZbII9PAtRMFjvGnkQvhG3VGPz6xWeprxUMVJrqzM=,tag:61rwk6tmUH5gPQO516exrA==,type:str]
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:Tq8MmjPD0xeb6POr/NJh6id864cPdCxixqUnQsyQOdTYaNKuoWvQFQ0R7XpF745ypMfEs9Gg2SOsSbCcA+fN1w==,iv:iZ0hCpoYb25N6Q3+uRWNUPno0tNcMf2MfLEtpiiS0+A=,tag:FYU2g+oWdoZ8qbh5ubhFGQ==,type:str]
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:08701KZu6cEru3XH4E4BSFf5NxOzOVO9MNyWm0++ij4P2E1vksABd91KhM4=,iv:btIRWjSA/Eqn16YKnUHE6P/5Nrs/mtAwoGFrjK9U7R0=,tag:g3QE8pbhA9thedOmkyn9/Q==,type:str]
    GARAGE_DEFAULT_ACCESS_KEY: ENC[AES256_GCM,data:HvSVN9eB7I+DQs1/k7Z4K4GHGAMkzzsLm2w=,iv:QPf2S6XD4TXZmyST9F+T8M/nNQuzeAFTX7T4corMvr4=,tag:U/lwmxp8jJgYV2v1G5xsbg==,type:str]
    GARAGE_DEFAULT_SECRET_KEY: ENC[AES256_GCM,data:R9r1JI8aZT7pCiu26gKuIUl4klp1bi8ugMm9S29lVLQqEZwHs4yF88Qlxd+3dMKvpjbbOD8bNyQxuS7n+hZsOg==,iv:OeIP5fkf1mTDHS8RlOTZCqWEBcI2S/82YCvdOq5SDKA=,tag:58si6fmaGFuIs6RM0fVZTg==,type:str]
    GARAGE_DEFAULT_BUCKET: ENC[AES256_GCM,data:J1OYDjOSCoYI2xpT,iv:1wgPSIzzT07yy44/dUwWyGxxHdHJLbSL5KO23nGT4Pw=,tag:zIu6Ad1nSt3WfQTLsF0Dzg==,type:str]
sops:
    lastmodified: "2026-10-07T01:22:23Z"
    mac: ENC[AES256_GCM,data:q7mC5qwhf8wPEG9x2NY/2m4zZ6wfbj6FLmktMbI2wRbENn4wFlnP/LFpL7CBc0+dwC4pkYLWxntGQZr/HN5pQ8nF9cW49FoDma5PolrcfoJbAPsp6xHZp9Ry/GnhGAr8rg6DuBHzVoQ+kslo5hvZ6iEXmDK+JAtvj8Pj7+XE4BM=,iv:akU6r29RjeipojbV9dq34tad5SZ4QAPt/HtVuso6sW8=,tag:F1dOTF7Q6lQtIzLRvWa43Q==,type:str]
    pgp:
        - created_at: "2026-10-07T01:22:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/+O5iuKWVzR/flkOowBvyVJcRRoGadiTgqjibvecfKUl8n
            KJOAYRySQ+W1Zoycj7okda6+WX1Qq/6mgBG9P5uC85hymx695fDRKrU5wmnEMlN1
            /EpliZZaTy+DZxzMgliQAhwok376ONL8YF0QClI0r4b3CJq1e0RidL3IwdBsKRs6
            x70ZeEsXEns2ZrNrUSoCYuK9VVbcRe8R1eTl2XkZ0umG9wxQOxTdWldW3i9N7HhB
            tTbovIzaGeheQLqgjoL+ckqLXIWcqbQNJ9v+sFak7qYdLzDhrQe6aIxt/ymwxpqL
            CqqaPQc70P0x4PfDyYo9jc5ONlaFJEDd2yEcxQ8QGqFJ1496i0+J/otiseVw6YsD
            y+uOStuYWjHec+xiLTQqHG7fZjtDLz7Al7f893wIHzVMg7PdiTT9Ct6k4m9iklam
            iaEhrsKbtn4e3a8k+3QxgyYdS61uXHzA9wElmZOrc5I+TPC5KC0JNUiSz+hWZz46
            Hn09pDPouAeJSNegeyorpKITbDm4O38SvFrEqulHH26S62Drx9va8/xxxDpLz6EB
            bjBPVI0Yj123jYfkIc+OMBqFXDTP3B63mWDS5F4ZtjirVllMmqwT5vsBvsRIeSvK
            d7rOteDufA5NJHSJE6pHT4DkfBpJj534pXdT4C/8hi8f0rxesdoixA82Z7pbAubU
            aAEJAhB3fklsLDeqwL5Coskz9iJ3/+GawOIC5LbITdew5az1Mz8FTZBofTpcnOTY
            1SqZSvRD9Gi2vFG8PlIwZl/TtO0ku9w5SwbQ7aiPL6ZHH5MEs7wEPMIi+SNUGkgE
            6I+yjg6VoUxM
            =6rSX
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
