apiVersion: ENC[AES256_GCM,data:eqk=,iv:PHINeL1tqt7izmx8CndrPdKVaZ3wNrg1mFMSdKpq9xA=,tag:BKFTthxOLH3bIGZIql58iQ==,type:str]
kind: ENC[AES256_GCM,data:+XE6dxZs,iv:9It+fFKFNe1s6q+fr+MwqffYkrJN+rLaPtf2657Zd+g=,tag:gCtlj02QkfaVoPB37czwhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VWSl3KqMxhMaD+J681EhuPb3F0+QjQ==,iv:/tFc766KshI2q6BYFPjvpHCJ5ONAr/ywRmp1X5aei7E=,tag:hLw9kAdiruI6MFFnSEeFtA==,type:str]
    namespace: ENC[AES256_GCM,data:LqL94UDXrz84pn1H7XJhVVMpPe4KLEBgRLgZfJiabUQ71OaR,iv:zywPGcztSCtAcCE9M3BzJ2gdH8GvPF/0lr0qQT5mTNs=,tag:29RNGpyRiYtDf9f/5Xv+Qg==,type:str]
type: ENC[AES256_GCM,data:zZe1/wuk,iv:OWRexkcMTrbXlH/d7q3UZTm9a4/wPuylxal8vtY4P1Y=,tag:8uUYxYyd070X5JPryDYsew==,type:str]
stringData:
    account_id: ENC[AES256_GCM,data:l1AuhuQOi5zk4sQrlHMGjWx9LBAwwS3X1U8Rf9Qvsbo=,iv:6yf6x5nO+K9HyIRP75KuS8hWwalOb221xzWeuCjDspM=,tag:avAKITk1AHRCEz8LnefUaw==,type:str]
    tunnel_name: ENC[AES256_GCM,data:q/g9I9K3HmTOKidWBg==,iv:h/bbVVWYmuOAnUenOPXhkmJs0Vz7ebnm5/9+cPBavwY=,tag:7GCUozUasp5xi/zq5enHmg==,type:str]
    api_token: ENC[AES256_GCM,data:IV4JvA6tPg6SsGH40KBDdXm68WwQS2h/vgTPjyX9xb86yIq0MxBKyQ==,iv:icmWE96UUrRt5zqK+y5M/Z9PNhaE6iIRqPN9vlufeKc=,tag:ZJB8Ql9RoqXhyZutUH/Kgw==,type:str]
sops:
    lastmodified: "2025-10-26T19:30:42Z"
    mac: ENC[AES256_GCM,data:ftZjxeyM9NTla3HuPbF4ohyFFhDwvHBDCwXdLyrMPCpFXcCj23THqiwrGiCdGvg+HShGm9yDYgWiyg3VwdqpUFmaalcFLRv1KHG3Cmunp8Q9ROmLxMMsUSAbsxFHnLQnAKUn3Luqw8wlcN+40/WgPiCTWdwwa1SH1yfvd+6oSsQ=,iv:JkxWP5+gqa55mnEqAf602A+CEkRmF4pDL9ByLEZ6fXw=,tag:/IejD6OcqSrdrb0hKbxWbw==,type:str]
    pgp:
        - created_at: "2025-10-26T19:30:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0H+SpFv9B63AQ//eF08P7ir60OlCPskT2TQwDXH2uVeGDlEryBOCdNj+jA2
            +uMZAM0fU6clKBpO2AN3JBg8aXw7nibhcO/TL5blZNZUmTeHr+/odIjmgXMU4ryp
            MlvwOTJt7//FsMxRKqoLyspxbI9QwxFQeT+TOcAmboZdOUCLg28ajh6Per/oMGcv
            5QD2AuSW3Pmylo0ccg4g3pk1C8d9pmeMh5R1n6OIGb9TpyIfQSIAfTWJ6p5ELPBN
            /j5ckUloUdHg//z4a5+9Y/qVnL9Si6RCw7fEAytb2DSc0XeX2OSugKMJkM/Pm9c6
            qGKn5WjK2uqTcp9sNb+ZFh4epfYndM/RFCshCHNPhd5LVOuygukaEte3SD64E9I/
            S4oJ60Cd2u+XQyA3X9MWfPdobbrrf8p/IVF9kwF/RLDNg7rN0gv+EH3AMMdb9X3C
            oHHudNyUrw5cAauXsK/qaGdRGN8lNe2zAI8HBMc0QythnrJo9QGHhVLJtL9bB7lA
            vOHXO/IR865XCEUg/s/tPfabCZVZCxh/lGLOshqooN7GeCW26dp4EMH6hMcoQfPO
            SoUYA379Se+vRP5nMJ6pz/Wia57Wb9GSvmTAk8i89lrjs/JT2uLOSEI7K3NkInu1
            pigmnVE48g63fT+UOxJq/iOZL1duqXKA3VM95qXEBBWUScau7AqxsfCBq4bb9+bS
            XAHLZDvq5ADFO4WweoXbpVCqxKVAgPYeUYUPk7Wnk2g/Wy8RTWbUpF7wg85TkJFo
            FQmIMnSJutmkHE4Tuc64g71IuvKRq4qNdU9ZMfrT0x3VC7z38R2pe/knW2v2
            =Fw33
            -----END PGP MESSAGE-----
          fp: 29FE211C0F0BF17C10EFEB150ECC79FC3C76B242
    unencrypted_suffix: _unencrypted
    version: 3.11.0
