apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-remote

helmGlobals:
  chartHome: helm

helmCharts:
  - name: cloudflare-tunnel-remote
    releaseName: cloudflare-tunnel-remote
    namespace: cloudflare-tunnel-remote
    valuesFile: myvalues.yaml

resources:
  - namespace.yaml

generators:
  - secrets-generator.yaml
