apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflared-aldo-ssh-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/cloudflared-aldo-ssh.enc.yaml
