apiVersion: v1
kind: Service
metadata:
  name: external-truenas
  namespace: media-v2
spec:
  type: ExternalName
  externalName: truenas.asandov.local
---
# ClusterIP service with explicit endpoints for traefik compatibility
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-truenas
  namespace: media-v2
spec:
  ports:
  - port: 30013
    targetPort: 30013
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin-truenas
  namespace: media-v2
subsets:
- addresses:
  - ip: 10.0.1.14
  ports:
  - port: 30013