apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-v2
spec:
  template:
    spec:
      serviceAccountName: media-apps
      containers:
      - name: api-key-sync
        image: alpine/k8s:1.28.3
        command: ["/bin/sh"]
        args: ["/scripts/sync-api-key.sh"]
        env:
        - name: SERVICE_NAME
          value: "radarr"
        - name: SECRET_KEY
          value: "radarr-api-key"
        - name: CONFIG_PATH
          value: "/mounted-config/config.xml"
        volumeMounts:
        - name: config-map-processed
          mountPath: /mounted-config
          readOnly: true
        - name: config
          mountPath: /config
        - name: api-sync-script
          mountPath: /scripts
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: api-sync-script
        configMap:
          name: api-key-sync-sidecar
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media-v2
spec:
  template:
    spec:
      serviceAccountName: media-apps
      containers:
      - name: api-key-sync
        image: alpine/k8s:1.28.3
        command: ["/bin/sh"]
        args: ["/scripts/sync-api-key.sh"]
        env:
        - name: SERVICE_NAME
          value: "sonarr"
        - name: SECRET_KEY
          value: "sonarr-api-key"
        - name: CONFIG_PATH
          value: "/mounted-config/config.xml"
        volumeMounts:
        - name: config-map-processed
          mountPath: /mounted-config
          readOnly: true
        - name: config
          mountPath: /config
        - name: api-sync-script
          mountPath: /scripts
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: api-sync-script
        configMap:
          name: api-key-sync-sidecar
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-v2
spec:
  template:
    spec:
      serviceAccountName: media-apps
      containers:
      - name: api-key-sync
        image: alpine/k8s:1.28.3
        command: ["/bin/sh"]
        args: ["/scripts/sync-api-key.sh"]
        env:
        - name: SERVICE_NAME
          value: "prowlarr"
        - name: SECRET_KEY
          value: "prowlarr-api-key"
        - name: CONFIG_PATH
          value: "/mounted-config/config.xml"
        volumeMounts:
        - name: config-map-processed
          mountPath: /mounted-config
          readOnly: true
        - name: config
          mountPath: /config
        - name: api-sync-script
          mountPath: /scripts
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: api-sync-script
        configMap:
          name: api-key-sync-sidecar
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-v2
spec:
  template:
    spec:
      serviceAccountName: media-apps
      containers:
      - name: api-key-sync
        image: alpine/k8s:1.28.3
        command: ["/bin/sh"]
        args: ["/scripts/sync-api-key.sh"]
        env:
        - name: SERVICE_NAME
          value: "bazarr"
        - name: SECRET_KEY
          value: "bazarr-api-key"
        - name: CONFIG_PATH
          value: "/config/config.yaml"
        volumeMounts:
        - name: config-map-processed
          mountPath: /mounted-config
          readOnly: true
        - name: config
          mountPath: /config
        - name: api-sync-script
          mountPath: /scripts
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: api-sync-script
        configMap:
          name: api-key-sync-sidecar
          defaultMode: 0755