apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: status-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/gatus-data-restic.enc.yaml
