apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared-aldo-ssh

helmGlobals:
  chartHome: helm

helmCharts:
  - name: cloudflare-tunnel-remote
    releaseName: cloudflared-aldo-ssh
    namespace: cloudflared-aldo-ssh
    valuesFile: myvalues.yaml

resources:
  - namespace.yaml

generators:
  - secrets-generator.yaml
