apiVersion: ENC[AES256_GCM,data:l6o=,iv:0p0V/v5bFv5CKvzS5uRqqtWe/LmIRclok+1vASiBHL8=,tag:Qg4brIOV7usFqYHVcauJcg==,type:str]
kind: ENC[AES256_GCM,data:TtQ5eBI1,iv:klPgyLVYi1PJLUUAzkO1R42mwvTwiwM+xID3W+xXPjg=,tag:CIh2v9ECrgk7AsEgBIuYHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c/9x9X1+5PbEgRBEFdlXxNeASiA=,iv:ea0Ya6aWsd463qae76+60eUfk0tvihx1TnC6bIWypNY=,tag:92nN3JpTMEvHrSi90YnDiQ==,type:str]
    namespace: ENC[AES256_GCM,data:cHVRFw==,iv:8SJkOewgzU+qoPitQMcswcpINX0N3Hdh5O0td8zATr8=,tag:RbD2sFdmjIVyREasfidgQg==,type:str]
type: ENC[AES256_GCM,data:kLytv/rO,iv:WcW/erzxcDhWwmLe8seYUp5S/rgovNpmNj8ec6aSvkI=,tag:6hVKi2tGO3EYbbCtX7YImg==,type:str]
stringData:
    userdata: ENC[AES256_GCM,data:34bKeZhxkaF9fP/MrbTus4oMAS7rzUMlWU2x9StP316p2+5lE92LUasG4MdOXJQ6AjBg32HO04mD2eT9U8NWCQenwy9nKNzZlllPOTuCa1/Jaj8a19iy4CGFJGXgkjCOHmmEfq9mVMU++LLPsjQRTwuo6v+eQzlnx05/Mg4TeCwO1Gqya8IwTWl2w7mptBrBTmaDbkTL6zjSi01ujLTnnEMerfkbpWat2yQ+w3W+onT19IgvgfQ2l79z2L45MocBnOW1FJdQP6ouFRl8LMuhS+9GfmMYgfK48xqmudcCqpG06UNAeffzhdjxw30MISCoReCQIsjtsm76oZOEmOOWqvhR61HQYBuTc/YHbySVi38ZzpfMKhBEj8gbeOJWIf3jP4EGRpyVthi0/Gc6rc6lMB6yteEqTx9s7N85JFrwyEzae6Gacm6j/YPXnQcqpeoC0X+VhGHkO3b1619EJitvdWLB/5x+kSg091DKhfcZF8n6FahQPyuIMe555NHtbiYsK7qN0nJY7Y5zev3YJleGECPywXHjczeQ4CE/jXEE26JoX2k6CmaCHEmeM0++/CW5H8Y19B6IYmK4JCTqSeTN+WekY8Vs7IqfynjkzXdA9L/Qb+nuCgyCBPZhVcu0PA0mNCqp4+nIkiwOGOLmwrw3fCn3SEuNwol4B3MON3uuNi0JLtSB3i5bNZ5U3V7RKOG+V1R1gzF/T2/quHcRhyJLeHwGeRtOrrBn/nPh2TOeHgVmv16BqH0RKFWVwUWaW2DwsPIAipXNbhoW9j3F9RkuCHL6xDxdQoX9pfpxekGwDP4I9Pq4mwl3FJLE670VGaKKUc0gE3via4NeslwlS/DVLKLRubu+pTj8lJu4hOcbow63koMtoQFh0Pc3HRZw+6eafP0XrSZglA+dAx5R+NYWSdAmlSUcbpjJvrEV31bELpTLV4yxukR140F7ubYPN7MaXvx1ROQNQ9uhGJi6r9vsTXjsJ0U8dVfvl8RJE25bmYF7gVn0sQPX0W5uIPqQibzhFi8X/H8SL7J8fD2uMe/zkYq3FqeujtPrW2FHMmfgFL4fnr1u6Svg8VBig+2e2umE183JObf1rimkYD4dSC3yR4dJbYF9xRQUviay1Cft+xRj3jmexi0YKNE8V0/Cu1LYiiZtXLvst8Appq+KRIW8vSD8XoKoyWnS4Sjee7lRacGl,iv:uSkQQZXtXMaANlNSGJPOaLjSFFg5GHfEpL+o7GRKKqk=,tag:uIs1cR2lEOJGZEb8G183ng==,type:str]
sops:
    lastmodified: "2026-09-16T15:00:22Z"
    mac: ENC[AES256_GCM,data:kkA8SpXn0ZOwIiDqGJ37JB0Uk5DuxXnk/G6ddMoRBBnqpeRX0n1XHlGZzoGCQhLDMSOA+hyO6PHidQpbjOqLtpStXgDPbzvF6ChEbVMx0L451eQXOlsGPIykt7yhMFSOooOFpcAgIi3oOnSH+HXsWXk2ir0X+8Gf9LMBmFlaQx8=,iv:Spnn9WoaMJZBR3Ri/n9qqadP7o84mdYKU5OLAaAFoiQ=,tag:Y2MxLO75NNzjkziedDVOYA==,type:str]
    pgp:
        - created_at: "2026-09-16T15:00:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//axL+EspZsFWIQtbFAVOlSMBRe/yXwZ7jbqoxP5PVpNRm
            blQFxlBqrvt3n1ZVnjY+q0bFP8wI9JoMFkTf7HRhLhuQgihTsII1Oc9N5GjfaVWu
            jQozjUG9+SBm1Vp58pRD1mBCydGN9luDgDNRCyt5FcKU3oA56g4cvrKGBDHCw3Dq
            MDEDFZs3aBvIVfq7XZosX+dmt6W8aLEL3YrzgbS2K5aYdcjoqoYytkP4fk8GQUJE
            6QtDl8hFXvRhRnAf3dj+yrEJLcMSxKoRG8TQjmcKloFI8rK4iYvNcO0bs/CAHkPv
            1Kx/vI6WjIqIE/EaqU4Pmzy5ehQo0vagFLwTGtiO1E5hAXOV0ZxlJiiLWafO0qlV
            Ska9N+ZyxUN3jyLlL5Nj6SE75ku+tGhczGEqpULxMXJDVokATnJRGrD0v/V4/aOA
            Fp1acpPMm0CwwdZglSEUqZc/X83GdqIaIW0iJekA46iaJHfPD0GnAfYV19Y8W4/M
            otnnAed7gVaZl/ZOARmaMWdMbOt9uRdaPfXcWXZVB7ZUYKpbZRg8JgVIg7VpdNw4
            Ct/ajdCLQ2Q8veXv1SHfa50QHAkV0h7cgjAyc0aKr6+LSIiU/+g7/v3c41uMyN5E
            TOneQXHSpbzV44Pdd4G12lUDE+yGaHoxp86GNIVdFgnP5pJCm7CU9RTphWsF5ePU
            aAEJAhDW5XjB+O/kGmPdZCz16DMGaEoM2M1GFmf0D6WsMBsyZonXFFCP+LC+1b5L
            SYh96799vKDKjiY8oQ1AtURPuPQcTiI3z+4yPYgRwYIEid0K9ywL2RwsxI4zitz6
            XvwLVj9nLTR9
            =YnOt
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
