apiVersion: ENC[AES256_GCM,data:l6o=,iv:0p0V/v5bFv5CKvzS5uRqqtWe/LmIRclok+1vASiBHL8=,tag:Qg4brIOV7usFqYHVcauJcg==,type:str]
kind: ENC[AES256_GCM,data:TtQ5eBI1,iv:klPgyLVYi1PJLUUAzkO1R42mwvTwiwM+xID3W+xXPjg=,tag:CIh2v9ECrgk7AsEgBIuYHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c/9x9X1+5PbEgRBEFdlXxNeASiA=,iv:ea0Ya6aWsd463qae76+60eUfk0tvihx1TnC6bIWypNY=,tag:92nN3JpTMEvHrSi90YnDiQ==,type:str]
    namespace: ENC[AES256_GCM,data:cHVRFw==,iv:8SJkOewgzU+qoPitQMcswcpINX0N3Hdh5O0td8zATr8=,tag:RbD2sFdmjIVyREasfidgQg==,type:str]
type: ENC[AES256_GCM,data:kLytv/rO,iv:WcW/erzxcDhWwmLe8seYUp5S/rgovNpmNj8ec6aSvkI=,tag:6hVKi2tGO3EYbbCtX7YImg==,type:str]
stringData:
    userdata: ENC[AES256_GCM,data:ZvLXG0mxMd4WHiEbLigK7pqS2E+t3ZpBIwSTxM2xT0JXuDezxlPBXX8syM1xuxRBmJVEfn0XV+bkG3hbbyzvSgnbAVsQzbspYDm/aF3yKWg4JXHSnyeKG65bO72P9rjSMi1n1yteVqUNimx9cebNw4w8O2S6K/RuKGm3yCIKk8vZBWGU4T2HPDe8pz5BndVKCGRV9/FehGy11+C2LPMxP+iI20Et+Eep1J4svZ12DiLTIDm/WlMTpHRCqge1pS3n5TLowd9QHTE/P55gKcW6m/kXxH1kYOwtJcd5PKWrVRoXFOMC6+5aA7Lbkg7vqQ1Ylw0lvmDop3OjTJxcwxb+vmn8ILOA70dbEVCRevZKHcXSEkXcokUVDGM6Cqv7661k2mpLIvH9VQdmYmBnjJuyZoEUPGh7HaGikwChsstiriPT79scJJvZwvq1JOg9pqlGvEk6DQynN8gjNNwbcxzA/TOssV27u4MruCbmSgvik2EbtV3XXrGaAVgr3IYOA5OFAPlCOK6sNHnGNNN7kBjUr6f9Jwhi/9KnP34a5VpzZNWcNSk6Qrh/MtpCyaLg85btLY7FfSZJUk05505nQV1an15WRv/13O8igGtOneWR8rxF3L4EpEXTB3VEItgKi5AFt3ejBFK1chQInJEAH/gqDP3o4md5B4OrI6oaUQVygGN9pzwB3ZiMMp73R8szvsZFa/Pwe/pEvfu7kUvMTBOcOGVTjtTGNMNkzpuaj3241cGrHV1Vb4b9HwtuJ5rhCEpomWLVha8QNgWnovahi+oeLpe7YbClKXFMVwlUkuzifIReUnpOB3CQ1xM3qwox7oYtN9/azu3rhFqpQD/+gWOLcy3Y9iZe0Tf56aTsejuuhArOoWr1/ZrQRGnozRrxzxI06CowtYIpkjskv//GReWF4akn3rB10up5JksuQIMU0ObvS6Aoc4nKijbGkAl+1DCwfmI930iykT6KqDbx4rSp6NSiEeF8Qjb1xSZJE9MjzRdCtK74o4CxFXrGPYL/P7K9odj65gCS/4JHN8GiYulDYQvf7MVx4Uxul981oj/XW2eszO+dNRCJWcUV/gyqCaqY7q8t6VqTg/RganF9ql4FUTLmonQkbr9klV6LOpgCjl5gLTjkoKrEd6PgLN/WozK5iUBouaAnguShK/yF0AcwY/8vMx96Kh+VLqOXOfwU6Hq7,iv:K7wuZS95evcePMuKPNKIFON+7HxEx3SJEG8YBUUpUhU=,tag:97WNVG2vUSlwiek2OuWKHQ==,type:str]
sops:
    lastmodified: "2026-09-17T16:37:47Z"
    mac: ENC[AES256_GCM,data:0fURCPAEKyXTGno9VBcbTF09ey5OKDstKcJv7xJ+o5v3e6t2AGWgOG0NBrSncwnzhudd7ccGkfEXXNKSZUtJy/yKQUe/PfaDKHMt48McvpLchwZtxNsR/Rt0ADDNjiToMLzkvPG1lS3+2Kob2zvHul5plFx8GZfJEJrAIfQRww4=,iv:i2Sbpn6VR6+aHgXOEgexRoHOVFcjdB8ThtNbxQh465k=,tag:i2+9DFZxwl1yBk+Z4cQMdA==,type:str]
    pgp:
        - created_at: "2026-09-16T15:00:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//axL+EspZsFWIQtbFAVOlSMBRe/yXwZ7jbqoxP5PVpNRm
            blQFxlBqrvt3n1ZVnjY+q0bFP8wI9JoMFkTf7HRhLhuQgihTsII1Oc9N5GjfaVWu
            jQozjUG9+SBm1Vp58pRD1mBCydGN9luDgDNRCyt5FcKU3oA56g4cvrKGBDHCw3Dq
            MDEDFZs3aBvIVfq7XZosX+dmt6W8aLEL3YrzgbS2K5aYdcjoqoYytkP4fk8GQUJE
            6QtDl8hFXvRhRnAf3dj+yrEJLcMSxKoRG8TQjmcKloFI8rK4iYvNcO0bs/CAHkPv
            1Kx/vI6WjIqIE/EaqU4Pmzy5ehQo0vagFLwTGtiO1E5hAXOV0ZxlJiiLWafO0qlV
            Ska9N+ZyxUN3jyLlL5Nj6SE75ku+tGhczGEqpULxMXJDVokATnJRGrD0v/V4/aOA
            Fp1acpPMm0CwwdZglSEUqZc/X83GdqIaIW0iJekA46iaJHfPD0GnAfYV19Y8W4/M
            otnnAed7gVaZl/ZOARmaMWdMbOt9uRdaPfXcWXZVB7ZUYKpbZRg8JgVIg7VpdNw4
            Ct/ajdCLQ2Q8veXv1SHfa50QHAkV0h7cgjAyc0aKr6+LSIiU/+g7/v3c41uMyN5E
            TOneQXHSpbzV44Pdd4G12lUDE+yGaHoxp86GNIVdFgnP5pJCm7CU9RTphWsF5ePU
            aAEJAhDW5XjB+O/kGmPdZCz16DMGaEoM2M1GFmf0D6WsMBsyZonXFFCP+LC+1b5L
            SYh96799vKDKjiY8oQ1AtURPuPQcTiI3z+4yPYgRwYIEid0K9ywL2RwsxI4zitz6
            XvwLVj9nLTR9
            =YnOt
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
