apiVersion: ENC[AES256_GCM,data:5WX4LdqEgIZDewHcmGT04+cemA==,iv:0R8zrZgPyLfkrfe3Zc53+o4PHLbRNYA8iQVuEDRknoI=,tag:vZiIyK815d91snnqJS1/eA==,type:str]
kind: ENC[AES256_GCM,data:uzLS5ZOnAeGIfw==,iv:OA3ZYoEtabUjJW3a/t195BmMAbsUHcJOoMOV20VPSZI=,tag:r589l/Rxr43JoGJ4O7nMjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:68kJasD/57PH6sQkPJ7M,iv:xLpwrMj7DrdnBNit1ID7e8xjWvdFCH+ezzmDSsgVA18=,tag:ln5u44NpUhbQ64y9AKm0lQ==,type:str]
    namespace: ENC[AES256_GCM,data:A2wQ8A==,iv:AA1pDK8XR5knTj6ojQz8g6lVk/EenfQvCwKNrI9JIP8=,tag:ixHZYoAcXfSNMYUHpugRhg==,type:str]
spec:
    headers:
        customRequestHeaders:
            #ENC[AES256_GCM,data:FrUPFZbKjvKSeO1tpyjx7WtUxAC0lwi/y+lNoXYD1uOK4sz8xr/orHUU0tswQEX2q4Ndy+GJ+yxSGXoJwvVJ1ljniVzUsTNGfSZtyN27DBpeAkKYkbYO1OOUfDNotSv5jm0fMmeV,iv:3XY8AW0i9mo4y9TBbFC2Umnhx1QPCmg4/jGyM09lpq4=,tag:YO+IwgqPFPWqE0cMqs6Rfg==,type:comment]
            Authorization: ENC[AES256_GCM,data:s7ZLBS+KOIcO54wuN11MU49HP3IaW52T/tmFtsj66HpmYBYS2a5SBfULNUMsRYn3luhU7YMQV4CPrg==,iv:LUvIPyQWIiNrbq5x5J4VrzT1vgWqBwoH2NvwpEQpuPQ=,tag:TkikyesnikZGBf/oBSn8sA==,type:str]
sops:
    lastmodified: "2026-09-17T20:00:58Z"
    mac: ENC[AES256_GCM,data:eQrTfkonnpiAVUC6kHkKxa5BCt5ST1VwW5Z4SF07WcDjABKyccbG98zsScPKbhwOh5k3VTxQhKeiWe2R9ERbO23YdyCdOjUVgMeduwyyefNCzl6JJj4U0MUWkioQbQGhD5zHvnqpUxvqjb733EZCwzhnbw2wunImVfzkoNAFqbY=,iv:uZ/egmw3bPyo7BsC8JxbVgcEnGOxG6BuI/kZbJ1FNn4=,tag:lRbMQVHiIjIq5PV4hdBOUA==,type:str]
    pgp:
        - created_at: "2026-09-17T20:00:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAr9xwcut+FTsbd0Ie0hE+k/553IZVUm5vxdlbfWicOBVT
            CsPsOx1zFArDv+mZdIoSo5VgxTbDW1zUNX9hbaiHEngd/mVOeHntLXzfEYY9cCNj
            fhOxob+YPpHNQusKq4eCFlC9Ts/xMTs3GP6WOV6KHem/lLNg7yALA9GF4zJOrPQJ
            YyNBI6/5HrGOJEnemxXMa3jB0uGld7Xd1xchszbOG3XMpDMzqBKw7p32/dd9BexK
            X4bTnOOMHlQe7t8i6NsL6g2JtVe5pmQNXRznOEZD8tz7J3EYCU7xTwSphWHUzpVN
            fuvqVP+l/S7hA4v9/PR3fwHQbLxuq+JY90G67+C/wzsWPSAMHNk/Ir1JxeTacd7w
            pLWaJmGygQlYmujn0EOkADRRDd0d7QMN8iX3QUjpCVYvXx7YupJWL4K4/nYS9Ijx
            H7fM5C1QNeUFDVmZaGtKbMNnsvfy6z4I2hdDg4w50fU16EeHWxa0VCRMcCoZxsqu
            7Dxz9cDgt/xBBFV+nqToJ0SA38xYfCHCwp5fwsWVRhjysqDsWJmn7ROE4gjE7eVU
            FYsfCIN/u/LJ2nyjJkg6ifWpc1zPOWFDR934UwVBRokVo/46rSLoz4EMbj6exMMz
            pYyJf4SjaQM85tskmI+u/uuyfoYW3V9/NfKsC9AGe835zP1U+AiOz1f05ytybyrU
            aAEJAhAVrqmPndOklJGoPvl+LmNPdMOp7k8+fzoyG6ho8aQT+jrqEGgsLS0cnFv/
            ui0S9UuZHl81VlWkdyhBabvvDe5njVHTfi5Ha6abh/PE5LejiEbyRBezldlroZnL
            aQjiN/+GOA1M
            =s6yf
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
