apiVersion: ENC[AES256_GCM,data:l6o=,iv:0p0V/v5bFv5CKvzS5uRqqtWe/LmIRclok+1vASiBHL8=,tag:Qg4brIOV7usFqYHVcauJcg==,type:str]
kind: ENC[AES256_GCM,data:TtQ5eBI1,iv:klPgyLVYi1PJLUUAzkO1R42mwvTwiwM+xID3W+xXPjg=,tag:CIh2v9ECrgk7AsEgBIuYHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c/9x9X1+5PbEgRBEFdlXxNeASiA=,iv:ea0Ya6aWsd463qae76+60eUfk0tvihx1TnC6bIWypNY=,tag:92nN3JpTMEvHrSi90YnDiQ==,type:str]
    namespace: ENC[AES256_GCM,data:cHVRFw==,iv:8SJkOewgzU+qoPitQMcswcpINX0N3Hdh5O0td8zATr8=,tag:RbD2sFdmjIVyREasfidgQg==,type:str]
type: ENC[AES256_GCM,data:kLytv/rO,iv:WcW/erzxcDhWwmLe8seYUp5S/rgovNpmNj8ec6aSvkI=,tag:6hVKi2tGO3EYbbCtX7YImg==,type:str]
stringData:
    userdata: ENC[AES256_GCM,data:NM1yQABnAKeqsOmrIfskzeZUuXG+8AIGezgoyP/7RqaxwMZe/dimg6wvNO2M2h6FqczBcqZVXmhq+2JO8Yh/7+bS8vKZaNOvJqrSuz8t8CzbG/bcGvIzE9/EN3NUVll0teWlc1wcjE2kql6nUyVUY6JMyGTNXveGNSQE1SSBP8rcPrKf7a5BxQS6sDAUm5VAyNEydNY9Y0OFnBYvWNLyWaiZuDUR2Rmbgj4l6onYedkAJmkVzio5QWb9UigAP8UzfCg6nSYTv16DqLQzNEKWpTfgQ+fa6+B3IHT27PUgiBeGBGlj/L5gs/DhMN4ah130grSLbOhLR2n30ZqSlrYTlQe8dTmBnYLaQ64NLBreX9anD7zbMChc3SO/4nFCLy1xqnnm/kIThvntpznI1ptHUOPtEQyajXOGLQU76qxGPjDXhfzHO94ekXztsfxM87hLxRt9LT4OAdQ9wj8sgWiwHb5qKwTuHBNcViWJwQhuZdzJ8jOoockaqgUeQukjzaYQc99WPynWbFqngTe7Bw1722W9hg6Je4jcmRplsg9AGDVx6e+q+7hXnEv/m3fDvjCTvfG8nghVoV+wfpEvCNv0VTe38ww3kmUZZFPNjSjYqy+cWQjDcjI8rMtraxJTQmfUNaESoAEglEeqp3ZInifgWlvoAuCltMa8RjMxTayOMcUYRC4YLYUYhbuAvl1r6/AvnHemEQ3EgNcTV/qrOMTizMFBres81hjOA2An2sDDwErQ3yJUX2Kegebc4KEJUFrW0Bkr8ivUv3u+F0ODNSjmE/rpYTp9sHvxUB23zQheJEGmRCrrci2UZ4H9eNkPfQFoAZwq04Ktky6BBReCNb20jZO7tB239m/cW3UzqiOO8Vm/ddcftDONIYzTZEPLGywkOVA9VDwXUQS/2CSjUm8ouBEL5FTdk7nhwPjU6HakeOa+GjjlkuD8j7377STnRDtUcUItqKNxKoWgmXMrl23FEQa52NwcIJg04pY7c8ZSi0R6rYqkZxVWpSSy6Ji9flzo2IKgpCm6SwocIgkWxPAW7WgcXHAd9qks82QIQ/AYhN+Lb1rQSk8sz/djhhLc74jlEjyRUblxSHZ8qdO2Rk17QmFhuXA8U+2IM+07UjspDo0WnLr/1e6eO11hEM5VUlJ8aYc9uFp7FaI0S4ub1NQ3osJxehVWiRW9EtNt4KbX7BpHd6w5JorBtgR7cy7e9d0p/7xqatGzd79e1vTNgyPWM8I3y0t++7QmEGugbZsWalfQEsNdIrrp,iv:QXv46avTQrqCygbfiEm0KQP13YoZHeatVhaKHrefNi0=,tag:R3K7fIQvBhN2r70QkUebOA==,type:str]
sops:
    lastmodified: "2026-09-17T17:03:09Z"
    mac: ENC[AES256_GCM,data:32VhAxBbg5MVHRjgb7aCUbmbqf+2Jfhw3ccinz2ZpAHpK15LhMsmbUHVP+zIKWQ2cTaaon27P/w22UU2LN8qPnTCJk8KPoJb7T17QvkwxArteLuHz5qCzW0bVlaKM5uYXv0jOGm947tIhA38A8BPxgI1zNiaBdlo3H3yU9qwDFs=,iv:7yhehaFrihdGqxjlNO0UYnVPUuOIco85Ooa7X3qHmk0=,tag:6PoYtczTphDusEyprDD8LQ==,type:str]
    pgp:
        - created_at: "2026-09-16T15:00:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//axL+EspZsFWIQtbFAVOlSMBRe/yXwZ7jbqoxP5PVpNRm
            blQFxlBqrvt3n1ZVnjY+q0bFP8wI9JoMFkTf7HRhLhuQgihTsII1Oc9N5GjfaVWu
            jQozjUG9+SBm1Vp58pRD1mBCydGN9luDgDNRCyt5FcKU3oA56g4cvrKGBDHCw3Dq
            MDEDFZs3aBvIVfq7XZosX+dmt6W8aLEL3YrzgbS2K5aYdcjoqoYytkP4fk8GQUJE
            6QtDl8hFXvRhRnAf3dj+yrEJLcMSxKoRG8TQjmcKloFI8rK4iYvNcO0bs/CAHkPv
            1Kx/vI6WjIqIE/EaqU4Pmzy5ehQo0vagFLwTGtiO1E5hAXOV0ZxlJiiLWafO0qlV
            Ska9N+ZyxUN3jyLlL5Nj6SE75ku+tGhczGEqpULxMXJDVokATnJRGrD0v/V4/aOA
            Fp1acpPMm0CwwdZglSEUqZc/X83GdqIaIW0iJekA46iaJHfPD0GnAfYV19Y8W4/M
            otnnAed7gVaZl/ZOARmaMWdMbOt9uRdaPfXcWXZVB7ZUYKpbZRg8JgVIg7VpdNw4
            Ct/ajdCLQ2Q8veXv1SHfa50QHAkV0h7cgjAyc0aKr6+LSIiU/+g7/v3c41uMyN5E
            TOneQXHSpbzV44Pdd4G12lUDE+yGaHoxp86GNIVdFgnP5pJCm7CU9RTphWsF5ePU
            aAEJAhDW5XjB+O/kGmPdZCz16DMGaEoM2M1GFmf0D6WsMBsyZonXFFCP+LC+1b5L
            SYh96799vKDKjiY8oQ1AtURPuPQcTiI3z+4yPYgRwYIEid0K9ywL2RwsxI4zitz6
            XvwLVj9nLTR9
            =YnOt
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
