apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  instances: 2

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-credentials

  storage:
    size: 11Gi
    storageClass: authentik-cnpg

  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore:
      destinationPath: s3://authentik-cnpg-backup/
      s3Credentials:
        accessKeyId:
          name: aws-s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-s3-creds
          key: SECRET_ACCESS_KEY
    retentionPolicy: "30d"
