apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  instances: 1

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-credentials

  storage:
    size: 11Gi
    storageClass: authentik-cnpg

  monitoring:
    enablePodMonitor: true
