{
 "title": "UPS Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UPS Load ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "ups_load", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_battery_capacity" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_in_voltage", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Estimated Remaining Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "expr": "ups_remaining_runtime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_out_voltage", "legendFormat": "{{device}}" }
   ]
  }
 ]
}