apiVersion: ENC[AES256_GCM,data:KgA=,iv:9Ko5YlwnfYOietiVFZchNlbk/IHPR3DgM9CXBL2UWqQ=,tag:iAV3xLy/o+IW3GnAS2rK8w==,type:str]
kind: ENC[AES256_GCM,data:Y1uoljZe,iv:XW1FmRRMHmdtmm9hi8UyGE4CRrQOO1j6bPPn4K/2Yew=,tag:M2vjwfl6NsBi/17quRgE5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3BwW/vbqOvmOCjuBVWzNkZIFFfY=,iv:Ox7QVxCjl3ysBtTp9ggPNPUFo+/U48JTJkXM4Nc2Ziw=,tag:khnMS6IqKZXD72pODUHeTw==,type:str]
    namespace: ENC[AES256_GCM,data:rUmvcqYLzXYwZAqHJEA6PaY=,iv:7IHKEIZYunxrgG0MdsY/5vqs7L/7KzT0/tF2tieeRk0=,tag:8AYPcX24kI7CbjuYk12z7w==,type:str]
type: ENC[AES256_GCM,data:23/7k9qp,iv:1rQgbe2cg8Qfv6BFQ866b+ngLXI0Vg7ihFz6fnD73Ig=,tag:iBuy705zxwQ2pmeZU8LRPA==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NpBOaXHVuCDdJfdlLD6HSAzLirUJmGlkS9Q=,iv:+Dh1DjCReQdn7AV1G/gO+4Y8ik5mB3FtM4lClHnv6w4=,tag:rt8NmF9r/qOjpBVOpoQ1uQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gzxch9JPZXNxsAeC0Kfx58N5RSLtbE3BDOKZ2RCg7ABIaH55jPCPf6Ye0aruk8eAprBFBOvoCZW/9i/9BVsnxg==,iv:h2o5KfnqASEeWPK5Va2JiQWeV2yycfFEYLaBUp/VYFo=,tag:VTFhy8T63kdElyIL2IG3AQ==,type:str]
sops:
    lastmodified: "2026-10-07T01:22:23Z"
    mac: ENC[AES256_GCM,data:mxK/Yuq4DgVLSuFSTF4QanNyG6cfnRgNxGawoLOEplhMrkVLEMQ6pnzggX+d8RgWqZE1mZGiY4XypkRYk6M3eVP3BMhMqiMlKwzBCosiLndDQqyVSOZS0MxkVCs5+PAvs2A38pQNagVb4DSyiqVVbdd7dcSFXUluhelMzDdz7Pg=,iv:DF04dJavI8aazRaF5QJrNKBdteOwybKItG06K3fdAcw=,tag:/cDiMOhEhg6/aQsqF+Uhdg==,type:str]
    pgp:
        - created_at: "2026-10-07T01:22:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//UwZzIrS7HKi9ih3QqKCh9aTtdagKlvXxDMMlu9772UJH
            zzliaeog6HZluVgLWmpuvUuaYh+ERarix0nHxy+Njpr9L4HcHaiK8VKhptE9bR6L
            czdbBiDCaSgc/Jr3T+LSkxeQHLAftZIYv3rJlTZccCr+rsvyR9Nx8U5kdmx8QD1y
            U9XnaNjoAZuiRh6VVTUOakyR6cq2TL51oFpVfuQ9EdNvxTS7LcJ0MgHf0iDrGG4/
            t2+FZi2WFOMZLV5Dc0wPy+Lsyi0yRqdhWCbQmsIYXksbRjMr0B+57B/vivNirqsB
            5vEB57gVhqB7a+vZlZK6TrEcvdd5hC0fiLpgmaW7b1fF79rTGPURXtUR7ex4opP3
            cRbsRt+tn5tlMuho8+4RYQJma2m01mpcMKT86BAIVR2KBHd6B1sgn9PlFrLojZPX
            bSLT1gra7Dz5z+iPm8MBBSLmTA+Be43cngd2FbxmILLVeCe678GJZWkfjsD5I+3P
            g+eenkEz2HHY83X3UoM+T9bEZ/6KkUwYo63x+cHbsPu4/Zj+3leo6K7GekMjF2wi
            XzvMEguAq0bhmghrypujZfuGYKcYNebSniom771amz9tyy6rciOqC1gUIGXH5xtw
            h6mV9G0dU7vuxt6joMjfiAzZS34AUQrSHO/NvO6njBWCLICwjM6jVLN0ATv+oRXU
            aAEJAhDs6BRgly54MuFAO6+yBbgaV/q4QNFfzMlIVnP73Ul0ngFE0V5QCbxwr4m5
            CCPq75kGBgsOtVYbmLVx/rl3tsT/9brpstpoXcGyb2OLnd1H7i+yHMZL+frJfGON
            52dvMHLeztk/
            =b9lY
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
