apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tpot-hive-secrets-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secrets/tpot-hive-cloud-init.enc.yaml
