apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: windscribe-vpn
spec:
  selector:
    app: gluetun
  ports:
  - name: http-proxy
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: control
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: windscribe-vpn
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        imagePullPolicy: Always
        env:
        - name: DNS_ADDRESS
          value: "10.255.255.1"
        - name: TZ
          value: America/Chicago
        - name: VPN_SERVICE_PROVIDER
          value: custom
        - name: VPN_TYPE
          value: wireguard
        - name: WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL
          value: "25s"
        - name: WIREGUARD_MTU
          value: "1420"
        - name: HEALTH_VPN_DURATION_INITIAL
          value: "10s"
        - name: HEALTH_VPN_DURATION_ADDITION
          value: "5s"
        envFrom:
        - secretRef:
            name: windscribe-wireguard-creds
        ports:
        - containerPort: 8888
          name: http-proxy
          protocol: TCP
        - containerPort: 8000
          name: control
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
