apiVersion: ENC[AES256_GCM,data:UR0=,iv:l1Zjn8L2jJ0o0Pt2bnxoqYK9M0ih1VV8OGat+nbBzXU=,tag:frrdjHF0dR4VAHPaMif3PA==,type:str]
kind: ENC[AES256_GCM,data:aHeaI3Bt,iv:EgTGdMW1ajecfxrIwmY7y3paBPYO5gYv9mO6sHmvTB0=,tag:6dCD8lE5We6QWkf1qVqgSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J0hDnbeKr+WBwQtD5eRY2Zg=,iv:P/dI5FZgIvoddpq3IcwdagRh9o6SrG8uQ7ywE77Z+Fs=,tag:wp0UQZx/z5pdx70uqw5RhA==,type:str]
    namespace: ENC[AES256_GCM,data:6wF3YcLF,iv:OcCpaayhH9Ng4WKFHUg8IkS0KeNttcbNEENjcpMdJ9I=,tag:EibZQJUf+5/PD2VPyV6uxw==,type:str]
type: ENC[AES256_GCM,data:vZdAvlpi,iv:U6shSqQFn8o//NkthkL6zqofieiTgLSqnp92kkBQL64=,tag:Q6Kh6OUnuIv4lkS9KEwhdg==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Sj9XJZX9+Cae3cp5rGWSMbOn0iseuL5ReH+RgbUC09qMRyqZduLAKDrPNzEnZZN3vKJ2UzWAvfFM1/pBRpPpNQedRRM=,iv:wIfpCKy0wStBUtm+U1rz0W5O7UjZOq1yB5vH/7gxrAM=,tag:aEOfL6zEmRQWAGrtA4vdeg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:9TllzTt9/WckRw==,iv:Cv5dbjo8JQFv+rPiZdacJKyxbuCkcz9kjfmxAGrxugU=,tag:xtwBpPh/SaIKqZo5veXxlQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:W5l0WknAM2mfCw==,iv:S+zwfhu9qKP5ueA11fe9RJF8d2dciHqNRyOyTZGy9gg=,tag:ZJzcgDX7u7k5riZxjT581Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IrumZqh/5B4vYw==,iv:b/uE9cuwzbLeH9gp7b5RZipePsZ8utGTH/rKjEorAAA=,tag:HfDzFhq5AwwPhBn7K323YA==,type:str]
sops:
    lastmodified: "2026-08-10T17:39:59Z"
    mac: ENC[AES256_GCM,data:li0nBnIQ+R7a3Qu/VtmArkKw2PsDavitJqJjBtyOWddA7QSPcFcq7wtNbMvYPWgsTUtaQ22f1TRAgIn3p1LqKCxKgXlzLR6/giRr35aJ+fiCAG+HZRFcLVoAjz1ZvehQUYE58atmX2ZUYIWeqncw3wJGiN61cWbdUUIynJfCxtE=,iv:PpDoNWZLLzs7vKh7B7x4c+o6/FF2IzIns1lrmeKj9Bo=,tag:EBHFcrd1+GRroVCLkTzssw==,type:str]
    pgp:
        - created_at: "2026-08-10T17:39:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0ARAAmMaDhH6ld3oQEtb9SZ0ETANprzWIB8d9X2Nm1todvQq9
            vgdMlpfetcHUU86SrELWDyKKnj7WB2yQioDmo+gS//DxZAS0dtIAFJx9RmNt7i3+
            kRL1QdimyGKgz/zXwupATptTTSaBPrEz69TIZg7RnUDFPeQU9xyJchc7qzI5XkKh
            SxbeYC9wH83R0d0y61BeFjAJ5oFAPsvVGjV15c8YekZEuwQ+ZhAP5DiA0EM1Th/j
            fYwysmSbnhmc9ipUEqQgsG5UIjHZ6M9sFH6Mro+MRgGNUX6ipQI1OKhDXdXYjoHT
            IF8mvex8oeGqFDAly+kVYbfc8xVJLasCDEnZlB9n/dVgdXbDTLiQgPYaKJ0sa6+H
            wk2kEWn137ed55NNpaQgZMs4rPn3BME8iz6+ggbv8hLF1SP7pj/EIdp+p6x4eBIb
            BecjSRD08/SJqU4J2cpnJmOpm+IwdclmIAoT7hG00KoGrysGAGd7y/h09wNa4zL2
            m9X1m/Kxlv3G9jvQL4jO2NnBw9R4yKuBcn+7o3m77Ewq96WtDYsJCTz8QOOegoz4
            O240ouXCP0XDNbh+wvAhzy3tJK1emZ3u/1y1+OfgrLqzuDCM7zJLimgR05E0ZHbO
            5OcHnG3tHJKRvbSco1SzpswIMGoh87GJdZWp8jCpVpdMh0OT3V3opfyaLzsVbsrU
            aAEJAhCZDYOVQ0bLOMnrfzJy6xb/8fiA3iKQh8GBCHQjwL+PKVcLVLdToefpF4l0
            W+qoDurq8ng4pCd+HDiyZkyr47WIzhgXvw/+pJMY2NkB85sO7lu/sJquEgwe5XTP
            0pLbivcq659n
            =lBnG
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
