apiVersion: v1
kind: Secret
metadata:
    name: monerod-wg-key
    namespace: monerod
type: Opaque
stringData:
    privatekey: ENC[AES256_GCM,data:hIS30FOjZ+TbzF3j6g2cYEJKtiV/cdpLhfBxVzIiBQ6971y1iN7RbgfbJHY=,iv:XfpUMsvNnRb6eUKSOW5UC/5Hzz16m7D2bb1dsVdWEKo=,tag:NLalhaGsnAIV9bS5dXBWFg==,type:str]
sops:
    lastmodified: "2026-09-11T00:45:42Z"
    mac: ENC[AES256_GCM,data:ZVD14TJgI6o+oJISfGtBasPX5GZqT5teFWc3UMaBc5IBtOdI3EitG8VVjqU8lMSg4s5L5A8oJzfiEALiuNZpDO4UsMdC3gAYlUdawM7eAExQ+Bft3zboqBc8rLauU3VeN4cmS5bkAkjNXCP7Z9bAtgcvbtu73WuMBwiwHiAMNO4=,iv:Dicsx+50yyUhOerM4W0r8zNYdmbZM61lGlapklJpkfk=,tag:CXcB/nUUnjO4QS3i0cfOQQ==,type:str]
    pgp:
        - created_at: "2026-09-11T00:45:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//XnouUjjrgaHygNlLREQ7o61darVbQS0hry/6r3cXJoUp
            YiZvH7n3yWXzRJDv+2q2uKPWQHiuYJ4gS6kC4FT1LSuC3kKLgZSg+0V/auNHgTdI
            LXipGgwKQDgry3JWywoKj8sesFKJAWf1Vh/jjqJ1nksm2k0uDerSHOviOO9eof1t
            9t8gkaF9BPP8pVklrjWOZB6lTS3KRA7/Kahy1xvlveu3xB8sXES0+5YXE9xGepWi
            0fgG8N+y1DZYgkE5al4zjhdQLehQfhlIHXtKvGrEqPmPP49Stb2TLz+LdhQYxXfa
            X/bAawKVB0w7OmHSCbmQgNbl0TOV/sickFgc9h4qJ2XA84o56BVKksk5coQhTbV/
            DnoolvqJO6nERoxmexMkbtyN/OIQ6/ODE0G/EM6ajCG8qCmmzMzVBAYVo6KYf8vb
            1wb6dUd7jQ4s3MACSDzUNXe2r06RyXXpvz1FxaW5AXvM7sB3oNEvbHEBbDiJ7Ec8
            bdqQzNvmjhvH4yAEMWQHltoB97ltHP6toK7cNWbiGhl4WaEo8/YHDYuBZJBnSxVT
            TzZOVBrOFLXyVUB10WhIIUeq91/2wthAGCKa0/DgIswwQJ8LDxyyxgr07ejezJyy
            +VjzgeSwiVcRLv+2morDcG7h3rb2mpsH0BW7vvAXcWw/SvA+GIojAG5ztBHb9UvU
            aAEJAhCXHp30hb5GeOAA7d0tEK/Dd7xWgbkWSLzkI7ZrKPyEAI9UEWXwovSL3W/r
            PQiOUmnRtODUEJwnb64hYZlhbDhQFZGf8Unu/DEvTr2uWgvoKzWpMq6aSUJbv9x/
            33Evwvj8jP7R
            =pC7b
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
